### ISSUE TITLE
Text for Empress Band mentions another server...

### ISSUE THREAD

**Issue by LegendaryCerberus** [HomepointXI/Issues#10]
**Date & Time**: 

March 15, 2018; 9:45pm PST

**Client Version (use `/ver` in game):**

version 30170329_0

**Character Name:**

Cerberus

**Nation:**

Bastok

**Job(level)/Sub Job(level):**

NIN(1)/THF(1)

**NPC or Monster or item Name:**

Empress Band

**Zone name:** 

South Gustaberg

**Coordinates (use `!where`):**

X:541 Y:0 Z:-332 (96)

**Item tool link (for items issues only):**

![img_20180315_213821](https://user-images.githubusercontent.com/37431296/37504281-8f4e5f34-289a-11e8-9c41-374c3dc10452.png)

**Multi-boxing? (multiple clients on same connection):**

No

**Steps to reproduce:**

Hover over item in equipment screen.

**Any additional information:**

**Comment by Jessland86** [comment]
Do you use custom .dat files, or a Nasomi install to play here? I just added it to my inventory and it shows as below.
![band](https://user-images.githubusercontent.com/28382433/37504527-4a4d9934-28b5-11e8-83b7-c9e41734d5ba.png)

**Comment by LegendaryCerberus** [comment]
I shouldn't be. I had FFXI installed to two different directories, and I used Ashita for Nasomi and Windower for Homepoint, and Homepoint is using my primary install directory. My Nasomi files are in C:\, and Homepoint is in C:\Program Files. I mean, I can try uninstalling the other copy of the game, but I don't see why its installation would have affected Homepoint.

**Comment by Willthefluteboy** [comment]
I have two seperate install files for FFXI as well with Nasomi having it's own launcher of Ashita that came with it. If you download the Ashita launcher from the makers website and use it to play on Homepoint I have personally had no issues. Just putting this in because I have both installed on my machine as well in two seperate locations and there are no conflicts similar to this.

**Comment by LegendaryCerberus** [comment]
Disregard this. Unbeknownst to myself, Nasomi hijacked my install directories for FFXI and pointed them to itself. Doing a completely fresh reinstall of FFXI.
