### ISSUE TITLE
the Eminem Flute is (again) in the shields section

### ISSUE THREAD

**Issue by ediww** [HomepointXI/Issues#106]
**Date & Time**: 
1st july 2018 0:30 eastern European time

**Client Version (use `/ver` in game):**
30180604_0

**Character Name:**
Tate

**Discord Name (if different from in game):**

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
thf99/whm49

**NPC or Monster or item Name:**
Eminent Flute

**Zone name:** 
AH(Auction house)

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
both yes and no

**Steps to reproduce:**
!ah then Armor then Shields
the first item

**Any additional information:**
the Eminem Flute is (again) in the shields section

**Comment by nfaletra** [comment]
Classic M&M Flute.

**Comment by Jessland86** [comment]
Fixed in today's maint.
