### ISSUE TITLE
Ready skill not accumulating charges after recent update.

### ISSUE THREAD

**Issue by evenger** [HomepointXI/Issues#107]
**Date & Time**: 
Noticed it soon after the recent update

**Client Version (use `/ver` in game):**
30180604_0

**Character Name:**
Evenger

**Discord Name (if different from in game):**

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
BST\multi

**NPC or Monster or item Name:**
Jug pets

**Zone name:** 
All

**Coordinates (use `!where`):**
All

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes, the issue is present with single box and multibox

**Steps to reproduce:**
retried ready on 5 characters

**Any additional information:**
More of a request; would it be possible to add Ruszor Meat to the Ruszor's drop list in aby xarcabard?
they are needed to craft Burning broth (the Lv 96 tiger jug pet). This would make bst much more enjoyable.

**Comment by nfaletra** [comment]
Trying to understand what behavior you are observing. Ready isn’t accumulating 3 charges? 1 charge every 30 seconds?

**Comment by evenger** [comment]
yes

**Comment by nfaletra** [comment]
Confirmed fixed.
