### ISSUE TITLE
Avatar Idol required for boss fight did not spawn.

### ISSUE THREAD

**Issue by T3RT1UM** [HomepointXI/Issues#108]
**Date & Time**: 7/21/2018 9:40 pm cst

**Client Version (use `/ver` in game):** version 30180604_0

**Character Name:** Rushana

**Discord Name (if different from in game):** Kura

**Nation:** Bastok

**Job(level)/Sub Job(level):** Blu99/Rdm49

**NPC or Monster or item Name:** Avatar Idol

**Zone name:** Dynamis - Windhurst

**Coordinates (use `!where`):** X: 0, Y: -16, Z: 131 (202)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** No

**Steps to reproduce:** Enter Dynamis - Windurst and when you reach Heaven's Tower, the Avatar Idol that spawns the NM Loo Hepe the Eyepiercer does not spawn.  

**Any additional information:**

**Comment by Heepster03** [comment]
Hi Kura!

**Comment by T3RT1UM** [comment]
get on it! lol

**Comment by nfaletra** [comment]
![thisstatue](https://user-images.githubusercontent.com/11480851/42192642-5e90f50e-7e27-11e8-8557-469f6f13b513.JPG)

You mean this statue?
