### ISSUE TITLE
Can acquire more than one Divine Might earring with a transferred character

### ISSUE THREAD

**Issue by nfaletra** [HomepointXI/Issues#11]
**Date & Time**: 

**Client Version (use `/ver` in game):**

**Character Name:** Autkastx

**Discord Name (if different from in game):** Autkast

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:** Suppanomimi, etc.

**Zone name:** The Shrine of Ru'Avitau

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** No

**Steps to reproduce:** Complete Divine Might on a character that completed it in retail (do not drop earring). Pick a second earring (different from the one that was transferred).

**Any additional information:** Check _NUMBER_OF_DM_EARRINGS_ in scripts/globals/settings.lua. I suspect it is set to 2 or higher. Default should be 1.

**Comment by Heepster03** [comment]
They set it like that on purpose. Working as intended.
