### ISSUE TITLE
Enemy aggravation range far too large above normal.

### ISSUE THREAD

**Issue by LadyLux** [HomepointXI/Issues#110]
**Date & Time**: 07/02/2018 16:48 P.M.

**Client Version (use `/ver` in game):** 30180604_0

**Character Name:** Mist

**Discord Name (if different from in game):** LadyLux

**Nation:** Bastok

**Job(level)/Sub Job(level):** 15PLD/7WAR

**NPC or Monster or item Name:** Quadav family (Ruby and Sapphire used in test) / Undead family (Tomb mage used in test) / Goblin Family (Goblin Gambler used in test) 

**Zone name:** Batallia Downs / Pashhow Marshlands (S) / Eldieme Necropolis

**Coordinates (use `!where`):** 

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** Yes, for distance testing.

**Steps to reproduce:** Simply place a character not above level of aggravation in zone within 70 Yalms of enemy to reproduce alert and attack.

**Any additional information:** Barriers did not seem to affect field of detection in any zone, walls did not obstruct sight on goblins.

**Comment by EpicTaru** [comment]
Couldn't find any information regarding aggressive behavior on bg-wiki, lol, Found this article on ffxiclopedia (https://ffxiclopedia.wikia.com/wiki/Aggro) which states that the farthest away that any form of aggro has is 20 yalms, but seeing as it's an article on ffxiclopedia, no idea if it's an official article

**Comment by nfaletra** [comment]
Are you sure you're testing this on Homepoint and not your own test server or a different server? I have not been able to repro this at all. With the mobs you listed or other mobs.

**Comment by LadyLux** [comment]
Closing due to being unable to replicate it now, unsure but perhaps it was a fluke, will keep an eye and alert if it happens again.
