### ISSUE TITLE
Shattering Stars (BST) - can't hp after a loss or exit after relog

### ISSUE THREAD

**Issue by Finalferrin** [HomepointXI/Issues#111]
**Date & Time**: 

July 2nd, 5 PM MST

**Client Version (use `/ver` in game):**

30180604_0

**Character Name:**

Terry

**Discord Name (if different from in game):**

NA

**Nation:**

Sandy

**Job(level)/Sub Job(level):**

BST 68/ THF 30

**NPC or Monster or item Name:**

Maat

**Zone name:** 

Waughroom Shrine

**Coordinates (use `!where`):**

x: -190 Y: 59 Z: -136

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

Yes

**Steps to reproduce:**

Fight Maat on BST, When his hp is 20% or very close to 20% as he asuran fists and he kills you.  Reraise doesn't appear from the signet thing, and homepoint doesnt appear. Forcing you to log off.  Logging off and back on, brings you to full health in the bcnm with Maat gone.  Clicking the on exit does not give an option to exit. It says Which Battlefield will you enter. With only None as the option. Have to warp out. 

**Any additional information:**

I get the impression that it's not giving the homepoint option because it's confused on who won.  This happened on two seperate fights. I killed him as I was dying the first time. The second time, I died but my pet did not despawn and killed him.

**Comment by Heepster03** [comment]
I can say that the second time shouldn't have even continued because the instant you die, your pet should be gone. But we have an issue about that already put in.

**Comment by EpicTaru** [comment]
@Finalferrin are you still experiencing this issue?

**Comment by Jessland86** [comment]
This is a longstanding issue in DSP and might be fixed with their upcoming BCNM re-write.

**Comment by Jessland86** [comment]
https://github.com/DarkstarProject/darkstar/issues/4020

**Comment by Heepster03** [comment]
This was resolved in 2019 on dsp. They fixed it so that dead people can get credit still.

> can close this issue all is resolved now, magic/abilities lists scale, and dead people get credit now
