### ISSUE TITLE
RDM Inundation 

### ISSUE THREAD

**Issue by SqueeksAlaster** [HomepointXI/Issues#112]
**Date & Time**: 7/2/2018 6:14 p.m.

**Client Version (use `/ver` in game):**30180604_0

**Character Name:**Squeeks

**Discord Name (if different from in game):**Squeeks

**Nation:**Windurst

**Job(level)/Sub Job(level):**RDM84/WHM47

**NPC or Monster or item Name:**Scroll of Inundation

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**http://ffxiclopedia.wikia.com/wiki/Inundation

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**When using this item, the client says "You cannot attack this target."

**Comment by nfaletra** [comment]
The spell has not been implemented at all.

**Comment by SqueeksAlaster** [comment]
Thank you for letting me know :)

**Comment by Heepster03** [comment]
This spell is not implemented anywhere. I made the scroll learnable but it's useless as the spell has no script. Gonna close this ticket. Long story short, don't buy it , unless you're wanting to add a spell to your list for completion but won't have a use for lol
