### ISSUE TITLE
BST Reward randomly isn't working. 

### ISSUE THREAD

**Issue by Finalferrin** [HomepointXI/Issues#113]
**Date & Time**: 

July 2nd, 2018 6:15 Pm 

**Client Version (use `/ver` in game):**

30180604_0

**Character Name:**

Terry

**Discord Name (if different from in game):**

NA

**Nation:**

Sandy

**Job(level)/Sub Job(level):**

BST 68/ THF 30

**NPC or Monster or item Name:**

Maat

**Zone name:** 

Waughroom Shrine

**Coordinates (use `!where`):**

Unknown

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

Yes

**Steps to reproduce:**

I really don't know what steps to reproduce this issue, it occurs randomly. But, sometimes, when using Reward either through the macro or the menu, it says Cannot Attack. Your Target is already claimed. It has happened on two different characters using BST. While multiboxing, and while not multiboxing. While fighting Goblins, and while fighting Maat. But then it works again having made no changes. 

**Any additional information:**

Have a Screenshot of the message saved from the maat fight.

**Comment by nfaletra** [comment]
Attach the screenshot and can I get the macro you’re using?

**Comment by nfaletra** [comment]
Sorry. I also need the pet food you were using and the jug pet you had out.

**Comment by nfaletra** [comment]
Sorry, I also need what big pet you had out and the food type you were trying to use. Thanks!

**Comment by nfaletra** [comment]
@Finalferrin Still need info on this. I can't go through every pet and food type. I just don't have time.
