### ISSUE TITLE
"Enhance Chakra" from artifact body i119 and relic hands i119 does not work

### ISSUE THREAD

**Issue by kyokofu** [HomepointXI/Issues#115]
**Date & Time**: 
7/3/18 4:23 pdt

**Client Version (use `/ver` in game):**
30180604_0

**Character Name:**
Kyokofukada

**Discord Name (if different from in game):**
N/A

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
MNK99/BLM49

**NPC or Monster or item Name:**
Anchorite's cyclas +1 
Hesychast's gloves +1 

**Zone name:** 
Upper Jeuno

**Coordinates (use `!where`):**
X:4 Y:1 Z:-52 (102)

**Item tool link (for items issues only):**
https://www.ffxiah.com/item/26979/hes-gloves-1
https://www.ffxiah.com/item/27829/anch-cyclas-1

**Multi-boxing? (multiple clients on same connection):**
Yes, but not during testing

**Steps to reproduce:**
Used Chakra with and without the items in question and the amount healed is around the same. I assume the little difference is from a difference of VIT from gears (Chakra's MOD).

**Any additional information:**
Tested with the normal af body and relic hand and the amount healed is noticeable so those works, but the i119s does not. I'll assume the i109s equivalent does not work as well.

**Comment by nfaletra** [comment]
Mod does not exist in DSP Core yet.

**Comment by nfaletra** [comment]
https://github.com/DarkstarProject/darkstar/pull/5185

**Comment by EpicTaru** [comment]
Translation: it'll be fixed in next version update

**Comment by EpicTaru** [comment]
Correction in the translation: It'll be fixed whenever DSP merges @nfaletra's commit, and then once we do an update of the server to pull whatever the latest commit of DSP master is, we will then finally get this. :-)

**Comment by nfaletra** [comment]
#MadeChakraGreatAgain
