### ISSUE TITLE
The Death of Castle Zvahl (S) Quadavs

### ISSUE THREAD

**Issue by nxnslite** [HomepointXI/Issues#117]
**Date & Time**: 
2018-07-05 but its from 2018-07-04 and still a problem today

**Client Version (use `/ver` in game):**
30180604_0

**Character Name:**
NxNSlite

**Discord Name (if different from in game):**

**Nation:**
Windy

**Job(level)/Sub Job(level):**
Thf99/dnc45

**NPC or Monster or item Name:**
any quadav but only tested with them

**Zone name:** 
Castle Zvahl Baileys(S)

**Coordinates (use `!where`):**
around quadav so -134,-24,102 (83)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes but did happen even solo

**Steps to reproduce:**
Kill a monster

**Any additional information:**
They are dead 4 ever... Shantoto would be proud but.. other player might not :)

**Comment by Heepster03** [comment]
This was fixed in a prior update, Orcs spawn 15min after being killed.
