### ISSUE TITLE
THF TP Glitch

### ISSUE THREAD

**Issue by SqueeksAlaster** [HomepointXI/Issues#119]
**Date & Time**:  around 4:45-5:00 pm MST (GMT - 6)

**Client Version (use `/ver` in game):**

**Character Name:**Topatoe

**Discord Name (if different from in game):**Squeeks

**Nation:**Windurst

**Job(level)/Sub Job(level):**THF10

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):** East Ronfaure Pugils at river

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** tested with both. happened with / without multibox

**Steps to reproduce:**

**Any additional information:** *Sometimes* able to WS twice before game would register that I already used a weapon skill. Depletion of TP isn't instant. I have no subjob or advanced job unlocked.

**Comment by EpicTaru** [comment]
Are you using ``!regen``?

**Comment by nfaletra** [comment]
Does the damage happen twice in the log? Can you get a screenshot next tine it happens?

**Comment by SqueeksAlaster** [comment]
it doesn't happen twice in log, but it does twice on the screen and to the mob. Yes, I will SS next time it happens and no i wasn't using !regen

**Comment by nfaletra** [comment]
If damage doesn’t actually proc twice, this isn’t an issue.

**Comment by SqueeksAlaster** [comment]
it is. by the time i snap a SS the TP is gone but it is happening twice and is damaging the mob twice.

**Comment by nfaletra** [comment]
So you DO see the damage twice in the log?

**Comment by nfaletra** [comment]
Is it any weaponskill or a specific one?

**Comment by SqueeksAlaster** [comment]
WS is Wasp Sting. just the specific one. i do see the damage twice on the screen, the mob takes the damage twice, it's not seen twice in the log.

**Comment by EpicTaru** [comment]
If it isn't appearing twice in the log, most likely it's just lag making it seem like the tp isn't disappearing until after the 2nd ws
