### ISSUE TITLE
Yoshikiri not swinging in off hand/ stats not working

### ISSUE THREAD

**Issue by Stealthsoft** [HomepointXI/Issues#120]
**Date & Time**: 
Friday, July 6, 2018
11:38AM

**Client Version (use `/ver` in game):**
30180604_0
(ecv: 30180604_0)

**Character Name:**
Graice

**Discord Name (if different from in game):**
stealthsoft

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
NIN99/WAR49

**NPC or Monster or item Name:**
Yoshikiri

**Zone name:** 
Abyssea - Misareaux

**Coordinates (use `!where`):**
X:267 Y:-15 Z:232 (162)

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/21909/yoshikiri

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Equip Yoshikiri

**Any additional information:**
Weapons stat bonuses do not add to char stats, weapon does not attack when in off hand. other weapons functioning normally. Attacks normally in main hand, other weapons attack in offhand while Yoshikiri is equipped in main hand.

**Comment by EpicTaru** [comment]
Weapon stats shouldn't add to the character stats as the weapon stats are specific to that weapon.

**Comment by nfaletra** [comment]
Weapon has no mods and isn't coded in the DB correctly.

**Comment by nfaletra** [comment]
Added mods and damage type to Yoshikiri and Yoshikiri +1.
Also added Ashijiro No Tachi/+1.

**Comment by Stealthsoft** [comment]
Thanks for the quick response! You guys are the best.

**Comment by Jessland86** [comment]
Should have been fixed in last nights maintenance.
