### ISSUE TITLE
Cogtooth Skagnogg Drop Table Issues.

### ISSUE THREAD

**Issue by Jessland86** [HomepointXI/Issues#121]
**Date & Time**: 
1551 EDT 7/8/2018

**Client Version (use `/ver` in game):**
Current retail

**Character Name:**
Immo

**Discord Name (if different from in game):**

**Nation:**
n/a

**Job(level)/Sub Job(level):**
n/a

**NPC or Monster or item Name:**
n/a

**Zone name:** 
LA Value [S]

**Coordinates (use `!where`):**
@pos 142.595 -0.377 -176.132 85

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
Mob is not check as a NM, respawn time is not correct (2-4 hours) and has no drops.

**Any additional information:**

**Comment by EpicTaru** [comment]
Mob checks as an NM now, but drops still need to be added:
http://www.ffxidb.com/items/2682 - Holly Strongbox @ 100% drop rate
http://ffxidb.com/items/11390 - Llwyd's Clogs @ 11.2% drop rate
http://ffxidb.com/items/19218 - Murderer @ 16.3% drop rate

All items have mods/gear sets coded already.

**Comment by Heepster03** [comment]
Fixed. Next update.

**Comment by Heepster03** [comment]
yay, had to redo the fix due to unfucking the first september update. it'll be pulled in when I do it again.

**Comment by Heepster03** [comment]
Was resolved way back.
