### ISSUE TITLE
Kegpaunch Doshgnosh not implemented.

### ISSUE THREAD

**Issue by Jessland86** [HomepointXI/Issues#122]
**Date & Time**: 
1551 EDT 7/8/2018

**Client Version (use `/ver` in game):**
Current retail

**Character Name:**
Immo

**Discord Name (if different from in game):**

**Nation:**
n/a

**Job(level)/Sub Job(level):**
n/a

**NPC or Monster or item Name:**
n/a

**Zone name:** 
Fort Ghelsba

**Coordinates (use `!where`):**
(H-9)/(H-10) on retail

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
Mob is not implemented at all.

**Any additional information:**

**Comment by nfaletra** [comment]
Someone else added this to DSP recently.
