### ISSUE TITLE
Boll Weevil incorrect drops and respawn time

### ISSUE THREAD

**Issue by Jessland86** [HomepointXI/Issues#123]
**Date & Time**: 
1551 EDT 7/8/2018

**Client Version (use `/ver` in game):**
Current retail

**Character Name:**
Immo

**Discord Name (if different from in game):**
n/a

**Nation:**
n/a

**Job(level)/Sub Job(level):**
n/a

**NPC or Monster or item Name:**
n/a

**Zone name:** 
Jugner Forest [S]

**Coordinates (use `!where`):**
@pos 444.051 -0.373 -154.413 82

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
Wrong drop pool, Supposed to be 90-120 minute respawn time. Does not have a NM flag either.

**Any additional information:**

**Comment by nfaletra** [comment]
https://github.com/DarkstarProject/darkstar/pull/5212
