### ISSUE TITLE
Cerberus dropping wrong item

### ISSUE THREAD

**Issue by T3RT1UM** [HomepointXI/Issues#124]
**Date & Time**: 7/9/2018 5:02 pm cst

**Client Version (use `/ver` in game):** version 30180604_0

**Character Name:** Kurare

**Discord Name (if different from in game):** Kura

**Nation:** Bastok

**Job(level)/Sub Job(level):** Thf99/War49

**NPC or Monster or item Name:** Cerberus

**Zone name:** Mount Zhalyom

**Coordinates (use `!where`):** 

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:**

**Any additional information:**
![image](https://user-images.githubusercontent.com/22230953/42479438-7ee6c438-839e-11e8-9733-cfee93a35beb.png)

**Comment by T3RT1UM** [comment]
Forgot to mention that the item that was not suppose to be on his drop table is the Tajabit.

**Comment by nfaletra** [comment]
Cerberus should be dropping Falubeza like the item tool says. Fix incoming.

**Comment by EpicTaru** [comment]
Bless you, @nfaletra, here's a Kleenex.

**Comment by Jessland86** [comment]
Fixed.
