### ISSUE TITLE
Missing Mythic Weapon (Nagi)

### ISSUE THREAD

**Issue by Stealthsoft** [HomepointXI/Issues#125]
**Date & Time**: 
Monday, July 9, 2018
~5:30PM 

**Client Version (use `/ver` in game):**
30180604_0
(ecv: 30180604_0)

**Character Name:**
Graice

**Discord Name (if different from in game):**
stealthsoft

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
NIN99/WAR49

**NPC or Monster or item Name:**
Nagi (95)

**Zone name:** 
Arrapago Reef

**Coordinates (use `!where`):**
X: 19 Y: -7 Z: 624 (21)

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/19722/nagi

**Multi-boxing? (multiple clients on same connection):**
Yes (Graice & Johnhenry)

**Steps to reproduce:**
N/A

**Any additional information:**
Logged on this afternoon and immediately took hall of transferance to Arrapago Reef for King credit was unable to locate Nagi in inv, 
![graice_2018 07 09_175202](https://user-images.githubusercontent.com/13657496/42480280-397d1e02-83a2-11e8-9bce-1088c50ca0bc.png)
any of my mog house boxes, or using /find.

Used it for sure yesterday, typing !trial still shows its trial progress at Stage 3 with 5/9 kings defeated. Screenshot as requested.

**Comment by Stealthsoft** [comment]
Yes, please. Sorry for the ticket. How stupid.

**Comment by Jessland86** [comment]
You're fine. Please log Gracie in and I can restore the item.

**Comment by Stealthsoft** [comment]
She's in Arrapago Reef.

**Comment by Jessland86** [comment]
Item restored to player.
