### ISSUE TITLE
Fistule No Longer Spawning

### ISSUE THREAD

**Issue by pyroleo451** [HomepointXI/Issues#126]
**Date & Time**: 7/11/2018

**Client Version (use `/ver` in game):** 30180604_0

**Character Name:** Artimusie

**Discord Name (if different from in game):** PyroLeo (Nicknamed Artimusie)

**Nation:** San d'Oria

**Job(level)/Sub Job(level):** 99smn/49rdm

**NPC or Monster or item Name:** Fistule

**Zone name:** Abyssea

**Coordinates (use `!where`):** X:-207 Y:63 Z:795 (34)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** 

**Any additional information:** Supposed to respawn every 15 to 20 minutes.

**Comment by nfaletra** [comment]
Need more info than this, bud. When did it last die, how long have you actually been waiting, etc?

**Comment by pyroleo451** [comment]
Last Known Spawn was last night about 12am. Is there a command to find out how long you have been online?

**Comment by nfaletra** [comment]
Spawned under the map. Let us know if it happens again.

**Comment by pyroleo451** [comment]
Yes sir. And thank you very much for your help. 2 discharges away from my Empy boot upgrades ^_^

**Comment by Jessland86** [comment]
Repopped in normal location after a kill.
