### ISSUE TITLE
Animator Z not allowing maneuvers

### ISSUE THREAD

**Issue by Devolnu** [HomepointXI/Issues#128]
**Date & Time**: 4:17 pm  7/11/2018

**Client Version (use `/ver` in game):** 30180604_0

**Character Name:** Devolnu

**Discord Name (if different from in game):** Devolnu-Ace

**Nation:** Bastok

**Job(level)/Sub Job(level):** Pup99

**NPC or Monster or item Name:**N/A

**Zone name:** N/A

**Coordinates (use `!where`):** N/A

**Item tool link (for items issues only):** http://www.homepointxi.com/db/items/21392/animator_z

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:** try to use ability and keeps saying unable

**Any additional information:**

**Comment by nfaletra** [comment]
Missing subskill in item_weapon table. Fixed 3 others while I was in there.

**Comment by Devolnu** [comment]
thank you
