### ISSUE TITLE
Herb Pastoral has no timer on icon

### ISSUE THREAD

**Issue by TrezThorne** [HomepointXI/Issues#129]
**Date & Time**:  July 11th, 2018 @ 18:24

**Client Version (use `/ver` in game):** 30180629_2

**Character Name:** Trez

**Discord Name (if different from in game):** Trez Thorne

**Nation:** San d'Oria

**Job(level)/Sub Job(level):** 25 Brd / 12 RDM

**NPC or Monster or item Name:** N/A

**Zone name:** Northern San d'Oria

**Coordinates (use `!where`):** X: 72 / Y: 0 / Z: 24 (158)

**Item tool link (for items issues only):** N/A

**Multi-boxing? (multiple clients on same connection):** No

**Steps to reproduce:** Cast Herb Pastoral
![herbnotimer](https://user-images.githubusercontent.com/38732209/42607518-36d3b4bc-8538-11e8-95d5-0e72bd3dc40d.PNG)

![herbstillactive](https://user-images.githubusercontent.com/38732209/42607592-9178fd0a-8538-11e8-9c44-e204f1aa8c9d.PNG)

**Any additional information:** Confirmed that the effect just doesn't expire, sung another song (Sheepfoe Mambo) and it wore off after a minute, but Herb Pastoral is still active.

**Comment by nfaletra** [comment]
Duration math was stupid. Made it less stupid. Effect was also not applying the poison res mods. Now it does.

**Comment by EpicTaru** [comment]
O.o?

**Comment by TrezThorne** [comment]
Like thanks, but spanks lolol

**Comment by nfaletra** [comment]
Has a valid duration now. Also actually increases poison resistance.
