### ISSUE TITLE
Zilart Mission 5

### ISSUE THREAD

**Issue by zainheart** [HomepointXI/Issues#13]
**Date & Time**: 
13h30 26/03/2018

**Client Version (use `/ver` in game):**
30180203_1

**Character Name:**
zainheart

**Discord Name (if different from in game):**
homepointXI

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
Pld99/Whm99

**NPC or Monster or item Name:**
Fire fragment
Light fragment

**Zone name:** 
Sanctuary of zitah
Yhuntunga Jungle

**Coordinates (use `!where`):**
Cermet stone

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
Check the cermet stone for pop a nm , after defeat it , check stone again for get the fragment.

**Any additional information:**
When you start zm5 you need to check 8 cermet stone for get a fragment of each color of the light , when you tried to get the one for fire (in yhuntunga jungle) or the one for light (in sanctuary of zita) you suposed to be able to get the fragment after deafeating the nm who has poped when you check the stone for the 1st time. I try several time to redo the fight but each time i got nothing and some second later he ask me if i want the stone again and the event repop the nm each time , without success to grab the stone anyway.

**Comment by EpicTaru** [comment]
This ticket doesn't explain the issue you are encountering. Please explain such, in as much detail possible. Thanks.

**Comment by zainheart** [comment]
Edit  Thx E.T.

**Comment by Heepster03** [comment]
You have to wait for the mob to completely despawn and the name disappear before you click the stone.

**Comment by zainheart** [comment]
just tryed and that didnt work he ask me if i want to remove the fragment again and the nm pop again too

**Comment by Heepster03** [comment]
Try it now, just did maintenance yesterday and it's seems to have fixed issues with NPCs.
