### ISSUE TITLE
BRD songs only lasting 1 minute instead of 2

### ISSUE THREAD

**Issue by TrezThorne** [HomepointXI/Issues#130]
**Date & Time**:  July 11th, 2018 @ 18:45

**Client Version (use `/ver` in game):** 30180629_2

**Character Name:** Trez

**Discord Name (if different from in game):** Trez Thorne

**Nation:** San d'Oria

**Job(level)/Sub Job(level):** 25 Brd / 12 Rdm

**NPC or Monster or item Name:** N/A

**Zone name:** Northern San d'Oria

**Coordinates (use `!where`):** X: 72 / Y: 0 / Z: 24 (158)

**Item tool link (for items issues only):** N/A

**Multi-boxing? (multiple clients on same connection):** No

**Steps to reproduce:** Cast any BRD song
![songtimerborked](https://user-images.githubusercontent.com/38732209/42608077-f839eb1a-853a-11e8-955f-5b63f127630a.PNG)

**Any additional information:** I wasn't aware BRD songs are supposed to last 2 minutes until talking w/ LS members about the Herb Pastoral issue.

**Comment by Jessland86** [comment]
1 minute 59 seconds on the built in status timers will only show up as 1 min. I'll verify. But this is probably just the fault of how the in game timer displays things.

**Comment by TrezThorne** [comment]
Gotcha, I will do an actual check instead of just going by the timer display.

**Comment by Jessland86** [comment]
If you use a plugin for Ashita like StatusTimers the buffs will show the actual times in minutes and seconds. SE's built in one rounds down until it gets to sub 1 minute, then it shows seconds. Just tested this with StatusTimers addon and they show 2 min buffs. If you look very quickly at SE's as soon as you cast it with 0 lag it'll blip "2m" for just a hot second then show 1 minute.
