### ISSUE TITLE
Automaton not taking damage

### ISSUE THREAD

**Issue by SqueeksAlaster** [HomepointXI/Issues#131]
**Date & Time**: July 11, 2018     around 12:30 MST 

**Client Version (use `/ver` in game):**

**Character Name:**  Squeeks

**Discord Name (if different from in game):**

**Nation:** Windurst

**Job(level)/Sub Job(level):**  35PUP/17DNC  (level sync'd to Dakkonalaster(hubby))

**NPC or Monster or item Name:**

**Zone name:** Crawler's Nest

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** No multi-box

**Steps to reproduce:**  

**Any additional information:**  there were times that my automaton did not take any damage. my automaton was hit by Final Sting from bees and instead of death, it went to full health. I did not level at this time. No I didn't use Repair. This also happened from the crawlers. Some times there was no damage taken and others 2-hit KO

**Comment by nfaletra** [comment]
What do you have equipped on the PUP, etc?

**Comment by SqueeksAlaster** [comment]
Tension Spring, Stealth Screen, Accelerator, Armor Plate, Stabilizer, Volt Gun, Mana Jammer, Inhibitor, Mana booster, loud speaker all tier I's

**Comment by nfaletra** [comment]
Siiiiick. Thanks. I’ll look into it. Might be a weirdly coded item. Some of the PUP stuff is still pretty bugtastic.

**Comment by nfaletra** [comment]
The attachment stats look fine. I suspect some kind of damage overflow happening. Were you level synced below your actual level?

**Comment by SqueeksAlaster** [comment]
everyone was sync'd to me. if you need further info and a response, plz mention me in Discord as i don't get emails from this very often
