### ISSUE TITLE
Dawn Muslum

### ISSUE THREAD

**Issue by SqueeksAlaster** [HomepointXI/Issues#132]
**Date & Time**:  7-11-18 22:10-22:18

**Client Version (use `/ver` in game):**

**Character Name:** Squeeks

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**  64PUP/32DNC

**NPC or Monster or item Name:**

**Zone name:** The Boyahda Tree

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**  http://ffxiclopedia.wikia.com/wiki/Dawn_Mulsum

**Multi-boxing? (multiple clients on same connection):**
Not multi-boxing, same connection as Dakkonalaster

**Steps to reproduce:**  while using Dawn Muslim, if two Automatons are at low health, both automatons heal to full when not in same party but in same vicinity
![squeeks_2018 07 11_222131](https://user-images.githubusercontent.com/20497620/42612500-f2be5176-8558-11e8-960b-1446f29756e9.png)

**Any additional information:**  this is a picture of the coordinates ... have scrolling screen :D

**Comment by nfaletra** [comment]
Tested in a multibox environment. Could not get it to happen with the PUPs in the same party or not in the same party. Are you certain both of you weren't using Dawn Mulsum at the same time? You can expand your game log and scroll up on it so it stops scrolling automatically to get better screenshots, too.
