### ISSUE TITLE
Sandoria Mission 3-1 issue

### ISSUE THREAD

**Issue by Dakkonalaster** [HomepointXI/Issues#135]
<!
Please do not remove or change any of the template data below. Instead, simply fill out the following information like you are taking a survey or test. When filling out this information, please DO NOT use the `@` symbol. This will trigger unwanted mentions to users that may not be part of this project.
-->

**Date & Time**: 

7/13/2018

**Client Version (use `/ver` in game):**

Ashita v3

**Character Name:**

Dakkonalaster

**Discord Name (if different from in game):**

Looksupskirts

**Nation:**

Sandoria

**Job(level)/Sub Job(level):**

NIN66 dnc33

**NPC or Monster or item Name:**

**Zone name:** 

Sandoria

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

went to do sandoria 3-1 infiltrate Davoi, went to go get my Cutscene with prince Trion, and I cannot receive the C/S. tried to see if I could continue it w.o the C/S and the person to give me the report denied me in short he just rambled on about what he would usualy say as if the quest was inactive, I had orginally tried to do the quest, and went and talked to trion, moved on to davoi and took the KI to trion. trion said my mission was complete but the mission was never actually completed, it kinda just stopped. tried to turn in crystals and the gate guard said I had to complete a mission on my list to continue looked at my list to see nothing had changed . tried to repeat the mission to verify that I had completed it and was denied as stated in the top

**Any additional information:**

**Comment by Dakkonalaster** [comment]
30180604_0

**Comment by EpicTaru** [comment]
Nope, please be patient. I'll DM you when home. 😊

**Comment by Dakkonalaster** [comment]
I think the game glitched and is making me do it again, ill try the 2nd time approach to see if I can clear it

**Comment by nfaletra** [comment]
You need to stop trying stuff and let ET check your variables when he can. Instead of potentially making the situation worse.

**Comment by Dakkonalaster** [comment]
Ace lead me through it, we were able to get it off my list, it activated the 2nd part instead of the 1st. the 3 points with zat

**Comment by Dakkonalaster** [comment]
however with the mission off my list, the game still refuses to allow me to donate to get magicite.
sory I just read that ace talked me through how to get it fixed, now the issue comes in where I cannot receive my magicite quest,
![dakkonalaster_2018 07 13_144937](https://user-images.githubusercontent.com/41209665/42713262-12a658c2-86ac-11e8-9449-70bb92355ccb.png)

**Comment by nfaletra** [comment]
Screenshot Status->Profiles menu, pls

**Comment by Dakkonalaster** [comment]
it was a restart that fixed this sorry to bug u guys, I have to head out to work.... but im back on track
