### ISSUE TITLE
Diabolos BCNM fight, Diabolos can fall and become erratic.

### ISSUE THREAD

**Issue by LadyLux** [HomepointXI/Issues#136]
**Date & Time**:  07/11/18

**Client Version (use `/ver` in game):** 30180604_0

**Character Name:** Mist

**Discord Name (if different from in game):** LadyLux

**Nation:** Bastok

**Job(level)/Sub Job(level):** PLD 40/WAR 20

**NPC or Monster or item Name:** Diabolos during Darkness Named BCNM CoP fight

**Zone name:** The Shrouded Maw

**Coordinates (use `!where`):** BCNM platform

**Item tool link (for items issues only):** N/A

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** Fight Diabolos in his capped BCNM CoP fight, have him on a tile that vanishes, once the tile vanishes Diabolos will fall to the pit below and fly around aimlessly making the battle much more complicated to complete.

**Any additional information:** I have noticed that he will not pursue you in any manner, it's as if the game does not know how to react to such a height difference.

**Comment by nfaletra** [comment]
This should be fixed now. Can anyone confirm?
