### ISSUE TITLE
Make LadyLux go bye bye!!!

### ISSUE THREAD

**Issue by EpicTaru** [HomepointXI/Issues#137]
**Date & Time**: 
Today @ now

**Client Version (use `/ver` in game):**

**Character Name:**
LadyLux

**Discord Name (if different from in game):**
Not sure, it changes frequently, multiple times a day

**Nation:**
European Union

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**
!goto LadyLux

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
Requested, by Autkast, to make a ticket to give LadyLux the #banhammer.  Autkast will "ban them good" once home.

**Any additional information:**

**Comment by LadyLux** [comment]
You can't do this! I got rights!

**Comment by EpicTaru** [comment]
I present, to the jury, proof of admittance of abuse!

![image](https://user-images.githubusercontent.com/26195580/42716745-c1950110-86c2-11e8-8c0b-b82d788cb869.png)
