### ISSUE TITLE
Dual lock door in Sacrarium will not take sealion crest key

### ISSUE THREAD

**Issue by LadyLux** [HomepointXI/Issues#138]
**Date & Time**: 7/13/2018 18:00 CST

**Client Version (use `/ver` in game):** 30180604_0

**Character Name:** Ladylux

**Discord Name (if different from in game):**Ladylux

**Nation:**Bastok

**Job(level)/Sub Job(level):** WHM99/BLM49

**NPC or Monster or item Name:** Sealion Crest Key

**Zone name:** Sacrarium

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** Having one character use the Coral crest key to hold the lock in order to use the Sealion crest key causes the Coral crest key to break right away and the Sealion key does not respond to the lock for it upon the door rendering entry to the door impossible as it stands.

**Any additional information:** Grabbed two keys for each person to try it both ways, coral crest key broke right away with each try.

**Comment by nfaletra** [comment]
Just did this today and it worked fine. Used Coral Crest Key with one character, then used Sealion Crest Key with second character directly after and the door opened. Not sure what issue you were running into, but it does need to be separate characters that trade the keys. If doing it solo, there is a quest to get a key item to open the door by yourself. http://ffxiclopedia.wikia.com/wiki/A_Hard_Day%27s_Knight

I have done the quest on the server before and can confirm that it is implemented and does function.
