### ISSUE TITLE
Learning BLU spells while in another zone

### ISSUE THREAD

**Issue by CaptSparklez** [HomepointXI/Issues#139]
**Date & Time**: 14.07.2018, 17:00 GMT+2

**Client Version (use `/ver` in game):** 30180604_0

**Character Name:** Hakubai

**Discord Name (if different from in game):** Haku

**Nation:** San D'Oria

**Job(level)/Sub Job(level):** BLU99/RDM49

**NPC or Monster or item Name:** Stroper Chyme, but my guess is it is an issue with any monster

**Zone name:** Aby Altepa/Ordelles

**Coordinates (use `!where`):** - 

**Item tool link (for items issues only):** - 

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** Had Haku in Aby Altepa while I killed Stroper Chimes with Joe in Ordelles. Learned Digest as soon as he had killed the slime.

**Any additional information:** Gonna guess this is the same issue as with the shared treasure pool as it happened as soon as I invited another pt to alliance.

**Comment by Heepster03** [comment]
Closing. Any future issues can be in a new ticket
