### ISSUE TITLE
Orichalcumshells are incorrect in level

### ISSUE THREAD

**Issue by nfaletra** [HomepointXI/Issues#14]
**Date & Time**: March 25th, 2018 1:00 am EDT

**Client Version (use `/ver` in game):** N/A

**Character Name:** Autkastx

**Discord Name (if different from in game):** Autkast

**Nation:** N/A

**Job(level)/Sub Job(level):** BLM87/WHM43

**NPC or Monster or item Name:** Oricalchumshell

**Zone name:** Mount Zhayolm

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** No

**Steps to reproduce:** /check the Orichalcumshells south of the Homepoint in Mount Zhayolm

**Any additional information:**
Some /check as Too Weak while others are Decent Challenge as a BLM87. BG Wiki lists these mobs as being level 88-89. https://www.bg-wiki.com/bg/Orichalcumshell. Despite the /check difference, HP and other stats appear to be the same across the mobs. They hit me for the same amount of damage and took the same amount of damage. Only difference was gil/exp awarded upon killing (which is based on mob level).

**Comment by Heepster03** [comment]
Fixed with reboot.
