### ISSUE TITLE
Sexchange addon bug

### ISSUE THREAD

**Issue by Bloodshotnine** [HomepointXI/Issues#140]
**Date & Time**:  7/15/2018 11:40 AM

**Client Version (use `/ver` in game):**30180604_0

**Character Name:**Tornado

**Discord Name (if different from in game):**Bloodshotnine

**Nation:** Bastok

**Job(level)/Sub Job(level):** THF46/WAR23

**NPC or Monster or item Name:**  Sexchange addon

**Zone name:**  any

**Coordinates (use `!where`):** any

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:** using Sexchange addon to change to a different race allows user to equip items not intended for them to be able to equip ie..    galka equipping a tarutaru only item.

**Any additional information:**

**Comment by Jessland86** [comment]
This is a DSP right now.
https://github.com/DarkstarProject/darkstar/issues/3950
