### ISSUE TITLE
Incorrect mob check

### ISSUE THREAD

**Issue by nuno-pires-cruz** [HomepointXI/Issues#141]
**Date & Time**: 1:13am CET

**Client Version (use `/ver` in game):** 30180604_0

**Character Name:** Furies

**Discord Name (if different from in game):** Furies

**Nation:** San d'Oria

**Job(level)/Sub Job(level):** Thf/nin 78/39

**NPC or Monster or item Name:** Skimmer

**Zone name:** The Boyada Tree

**Coordinates (use `!where`):** 31 -21 -64

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:** check monster

**Any additional information:** checking with a lvl  78, skimmer in the area, only 2 came up as decent, rest was too weak, which isn't correct as this is a 72-74 mob. same thing happened with gobs in cape terigan.

**Comment by nuno-pires-cruz** [comment]
I'm currently lvl 81, in Zeruhn Mines, some Burrower Worm are checking Too weak. This is really weird

**Comment by nfaletra** [comment]
exp tables in DSP have not been updated for level 75+. I'm actively working on it.

**Comment by nuno-pires-cruz** [comment]
Glad there's a logic reason. Thank you.

**Comment by nfaletra** [comment]
Exp tables have been updated, but item level is not being factored into checks, yet. Mobs will still /check as Tough or above when they should really be Even Match or Decent Challenge. But that's okay because it does not affect exp rewards.
