### ISSUE TITLE
Atonment damage

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#143]
**Date & Time**: 7/16/2018

**Client Version (use `/ver` in game):** 30180427_2

**Character Name:**Spectre

**Discord Name (if different from in game):** Spectre

**Nation:** Windurst

**Job(level)/Sub Job(level):** pld99/dnc49

**NPC or Monster or item Name:**na

**Zone name:** na

**Coordinates (use `!where`):**na

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**no

**Steps to reproduce:** Atonment seems to do a fix damage of 1287 whether it is a level 1 ws or a level 3.  I'm not entirely sure if the custom hate gain for pld is also affected or not but damage for the ws seems to be capped.  Also tested out a few other weaponskills they seem unaffected. 

**Any additional information:**

**Comment by stevomatic** [comment]
I just noticed this, exact same thing on Agnes

**Comment by kyokofu** [comment]
atonement was way too overpowered anyways.

**Comment by Oderson** [comment]
yup, same

**Comment by nfaletra** [comment]
How ‘bout now???

**Comment by spectre99** [comment]
Seems to cap out at about 9.7k damage whether it's a level 1 atonement or level 3 atonement, which is fine by me.
