### ISSUE TITLE
Enlight bugged damage

### ISSUE THREAD

**Issue by LadyLux** [HomepointXI/Issues#144]
**Date & Time**: 7/18/2018 19:42 CST

**Client Version (use `/ver` in game):** 30180604_0

**Character Name:** Mist

**Discord Name (if different from in game):** LadyLux

**Nation:** Bastok

**Job(level)/Sub Job(level):** PLD99/WAR49

**NPC or Monster or item Name:**

**Zone name:** Any

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** Cast Enlight and attack any target, damage will start at 24 and degrade -1 damage per hit and wear off after 24 swings regardless of time remaining. Example: 24, 23, 22 until all the way to 1 extra damage.

**Any additional information:** The damage is the same regardless of mob defense/level/type

**Comment by EpicTaru** [comment]
Confirmed with player via Discord DM conversation that this is no longer an issue.
