### ISSUE TITLE
Running at retail speed

### ISSUE THREAD

**Issue by Devolnu** [HomepointXI/Issues#145]
**Date & Time**:  12:15am 7/21/2018

**Client Version (use `/ver` in game):**

**Character Name:**Devolnu

**Discord Name (if different from in game):**

**Nation:**Bastok

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** All

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:** my speed at which i run is retail speed

**Any additional information:**

**Comment by EpicTaru** [comment]
Please provide a screenshot of your game window.

Also, try pressing the Z key on your keyboard

**Comment by Devolnu** [comment]
after 3 crashes now its back lawl. that was weird
