### ISSUE TITLE
Jail

### ISSUE THREAD

**Issue by Vygun** [HomepointXI/Issues#147]
**Date & Time**: 
Tuesday, July 24 at 0820 (8:20AM) (CDT)

**Client Version (use `/ver` in game):**
30180629_2

**Character Name:**
Vygun

**Discord Name (if different from in game):**
Vygun

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
60RDM30BLM

**NPC or Monster or item Name:**
N/A

**Zone name:** 
Kuftal Tunnel

**Coordinates (use `!where`):**
H-9

**Item tool link (for items issues only):**
N/A

**Multi-boxing? (multiple clients on same connection):**
N/A

**Steps to reproduce:**
Executable Command for addon

**Any additional information:**
Since starting FFXI 2 days ago, 3 days now, I have been leveling up trying to figure out Ashita and it's multitude of cool features. I have downloaded many of the offered plugins and addons under the assumption that since they were offered, they were acceptable, because why would there be addons and plug-ins offered through the client they use to connect to the server that are not permitted? After playing with multiple addons and plug-ins, trying to see how they work, and what they do using the Ashita Documentation webpage, I entered the execute command for the addon "Debuff" which sent me to Mordion Gaul. The execute command was performed in Kuftal Tunnel, out of combat, without any debuffs inflicted on my character. If I had known that this addon was not permitted not only would I have not used it, I would not have installed it. If the chance happens that I am allowed to play still, I will remove all addons and plug-ins to remove the confusion of what is or is not allowed as the line is very thin and I am too old to worry about treading lines. Feel free to contact me if anything else is needed.

Respectfully,
Vygun

**Comment by nfaletra** [comment]
There are links to the New Player Guide and Server Rules on our Discord and in a System Message whenever you login to the game. Please review what addons/tools are not permitted on this server. A GM will be with you shortly.

http://wiki.homepointxi.com/New_Player_Guide
http://wiki.homepointxi.com/Server_Rules

**Comment by EpicTaru** [comment]
After reading the Server Rules, please ensure that any addons/plugins (that aren't allowed on the server) are unloaded from your game. This will help prevent you from getting automatically thrown back in jail.

**Comment by EpicTaru** [comment]
Released 1230 CST 07/24/18
