### ISSUE TITLE
Ebers Mitts +1 not giving extended Regen duration

### ISSUE THREAD

**Issue by LadyLux** [HomepointXI/Issues#149]
**Date & Time**: 12:38 AM CST 7/25/18

**Client Version (use `/ver` in game):** 30180604_0

**Character Name:** Ladylux

**Discord Name (if different from in game):**

**Nation:** Bastok

**Job(level)/Sub Job(level):** 99WHM/49RDM

**NPC or Monster or item Name:** Ebers Mitts +1  (Item number 27057 in database)

**Zone name:** Anywhere

**Coordinates (use `!where`):**

**Item tool link (for items issues only):** https://www.ffxiah.com/item/27057/ebers-mitts-1

**Multi-boxing? (multiple clients on same connection):** No

**Steps to reproduce:** Equip Ebers Mitts +1, Regen timer should extend +22 seconds for duration but does not, when casting any Regen tier spell. 

**Any additional information:** Effect seems to work with Ebers Mitts 109 version. Effect is also programmed into Theophany Pantaloons +1 as +18 which does work, it could easily be pulled from those and thrown on the mitts.

**Comment by EpicTaru** [comment]
The effect has not been implemented at all.

**Comment by nfaletra** [comment]
Added regen duration mods to the gear. We'll see it in the next update.

**Comment by Jessland86** [comment]
Fixed in today's maintenance.
