### ISSUE TITLE
Tin Ores Not selling on AH

### ISSUE THREAD

**Issue by neonracer** [HomepointXI/Issues#150]
**Date & Time**:  Friday July 27, 2018

**Client Version (use `/ver` in game):** 31080629_9

**Character Name:** Neonracer

**Discord Name (if different from in game):** Neonracer

**Nation:** Basty

**Job(level)/Sub Job(level):**DNC99/NIN49

**NPC or Monster or item Name:** TIN ORES

**Zone name:** Gustav Tunnel 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**  Just please repair the Ah as the AH bot isn't buying them @ 5K.. not even buying them back at all. Period.  PLease fix ah bot. Thank you!

**Comment by Heepster03** [comment]
This would have to wait until later. But an easy fix.

**Comment by neonracer** [comment]
Understandable..im watching the ah on several thi gs that are ah able that
are not moving..i will keep a list going bc its minute...but agsin easy fix.

**Comment by neonracer** [comment]
Thanks Jess & Heep. Sorry i took a while to reply. Its coo!

**Comment by nfaletra** [comment]
Not adding these back to the AHBot
