### ISSUE TITLE
Tegmine ((╬ಠิ﹏ಠิ)) 

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#152]
**Date & Time**: 
7/31/2018

**Client Version (use `/ver` in game):**

**Character Name:**
Agnes

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**
Tegmine 

**Zone name:** 
Terrigan

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
Found Tegmine standing on top of a rock on the west/outpost side of the zone instead of over on Twilight Beach. He wouldn't come down and would quickly de-aggro
![gurgitator_2018 07 31_175400](https://user-images.githubusercontent.com/26309049/43490119-5075294a-94ed-11e8-8d0e-d42f481fbf80.png)

**Comment by spectre99** [comment]
I waited till he repoped and engaged, pulled him from his spawn point a little and let him kill me.  He walked his way back to his normal spot so he is definitely acting normally now.

**Comment by spectre99** [comment]
I've killed him a few times since the ticket was made, seems to be respawning and acting normally.
