### ISSUE TITLE
Metal Shears NM not being found in DB

### ISSUE THREAD

**Issue by EpicTaru** [HomepointXI/Issues#153]
**Date & Time**: 
07/31/2018 at 1800 CST

**Client Version (use `/ver` in game):**
30180604_0

**Character Name:**
EpicTaru

**Discord Name (if different from in game):**

**Nation:**
Sandoria

**Job(level)/Sub Job(level):**
99BLU/49RDM

**NPC or Monster or item Name:**
Metal Shears (MobID 17199161), lvl26 NM (via Checker addon)

**Zone name:** 
Valkurm Dunes

**Coordinates (use `!where`):**
X:547 Y:-15 Z:314

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**
Get tipped by a player about an NM that you ain't never heard of before, try to look it up on the Monster Tool (with no luck), grab Mob ID via GM command, then try and look it up on the Monster Tool (still with no luck), then watch a player fail at soloing it (no one's having any luck lately), kill it with one club hit on 99BLU, come here and write this ticket.

**Any additional information:**
![image](https://user-images.githubusercontent.com/26195580/43492396-53c28592-94ee-11e8-8ab2-93d389c20883.png)

![image](https://user-images.githubusercontent.com/26195580/43492644-8adacf8e-94ef-11e8-8a18-bb0eccd3bc46.png)

**Comment by nfaletra** [comment]
![metalshears](https://user-images.githubusercontent.com/11480851/43532788-8cccaffc-9570-11e8-88d8-d9d7e10f0cbf.JPG)

Looks like it was just cause the DB Tools were down.
