### ISSUE TITLE
Item use interruption

### ISSUE THREAD

**Issue by xendral** [HomepointXI/Issues#154]
**Date & Time**: 
9:10 am PST 8/1/18

**Client Version (use `/ver` in game):**
30180427_

**Character Name:**
Bozidar

**Discord Name (if different from in game):**
xenthraldious / bozidar

**Nation:**
bastok

**Job(level)/Sub Job(level):**
pld/dnc

**NPC or Monster or item Name:**
black drop
holy water

**Zone name:** 
abys - vunk

**Coordinates (use `!where`):**

-194 -40 -287

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/4265/black_drop
http://homepointxi.com/db/items/4154/flask_of_holy_water

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**
Use black drop, cancel use by moving.
Was fighting Buhkis and was petrified while using holy water. Was unable to use holy water after petrified was removed. Simply says unable to use item

**Any additional information:**

**Comment by xendral** [comment]
I think the holy water may stop working when you are using the item while doom kills you. Was not able to reproduce the same effect while just trying to walk around to stop the use of the item.

**Comment by nfaletra** [comment]
Fix merged from DSP
