### ISSUE TITLE
Wivre not using Demoralizing Roar in Bhaflau Thickets

### ISSUE THREAD

**Issue by Falendria** [HomepointXI/Issues#155]
**Date & Time**: 8/5/2018 6:41 pm

**Client Version (use `/ver` in game):** 30180629_2

**Character Name:** Falendria

**Discord Name (if different from in game):** Falendria

**Nation:** Windurst

**Job(level)/Sub Job(level):** 99BLU/49DNC

**NPC or Monster or item Name:** Wivre

**Zone name:** Bhaflau Thickets

**Coordinates (use `!where`):** X:-543 Y:-11 Z:-70 (12)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** Tried using one and two characters attacking.

**Any additional information:** Only uses Granite Skin, will not use Demoralizing Roar.

**Comment by spectre99** [comment]
The blue mage spell tool on the site lists all the mobs I tested one as ones that can do Demoralizing Roar (http://homepointxi.com/db/bluespells/659/demoralizing_roar)  I tp fed Mesa Wivre in aby konsch and Wivre in grauberg S.  The only move these mobs spam is Granite skin which gives them stoneskin.  Kept dispelling and feeding tp with low dmg weapons.  Even fought the aby ones for a good 15 mins tp feeding, and only that one move.  Also popped Stachysaurus with Spectre a few times which is a VW mob in La Thein.  It only seemed to do two tp moves granite skin like the others and crippling slam, but no Demoralizing Roar.  Wiki says that you can get the mob to cast the move if you attack from the side, so I've also fought these with multiple characters, one feeding TP from the front the other from the side, still nothing.

**Comment by nfaletra** [comment]
Many of the Wivre abilities were named wrong in the DB and didn't match up with the script names. This caused it to fail to use those abilities and try the next one in the list until it found one that was correct which happened to always be Granite Skin. I fixed the DB names,cleaned up the ability scripts, and added a script for Boiling Blood.

**Comment by Jessland86** [comment]
Fixed in today's maintenance.
