### ISSUE TITLE
Revealer's Mitts +1 has no stats

### ISSUE THREAD

**Issue by kyokofu** [HomepointXI/Issues#157]
**Date & Time**: 
11:34am pdt, 8/9/18

**Client Version (use `/ver` in game):**
30180604_0

**Character Name:**
Kyokofukada

**Discord Name (if different from in game):**
N/A

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
99WHM/49BLM

**NPC or Monster or item Name:**
Revealer's Mitts +1

**Zone name:** 
N. Sandy

**Coordinates (use `!where`):**
in Mog house

**Item tool link (for items issues only):**
https://www.ffxiah.com/item/27992/reveal-mitts-1

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**
NQ revealer's mitts has stats but when switched to the +1, all the stats goes away.

**Any additional information:**

**Comment by EpicTaru** [comment]
This isn't coded in DSP at all.

**Comment by nfaletra** [comment]
Fixed for HP. Will be in the next update. Still needs a submission to DSP.

**Comment by Jessland86** [comment]
Fixed in today's maintenance.
