### ISSUE TITLE
Jenglot is either spawning, or wandering into the wall

### ISSUE THREAD

**Issue by BrenMcM** [HomepointXI/Issues#159]
**Date & Time**: 

12/08/2018 09:49

**Client Version (use `/ver` in game):**

30180629_2

**Character Name:**
Tleaf

**Discord Name (if different from in game):**
Tleaf

**Nation:**
Sandoria

**Job(level)/Sub Job(level):**
PLD 99

**NPC or Monster or item Name:**

Jenglot

**Zone name:** 
Fei'Yin Map 2

**Coordinates (use `!where`):**

X:-59 Y:-12 Z:-17

**Item tool link (for items issues only):**

NA

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**

Unknown

**Any additional information:**
Jenglot is either spawning, or wandering into the wall at the position provided above. I've been away for a bit now, but is this even the correct map for him?

**Comment by EpicTaru** [comment]
Jenglot spawns on the FIRST map. This is per Ffxiclopedia.wikia.com.

http://ffxiclopedia.wikia.com/wiki/Jenglot
