### ISSUE TITLE
Quest "A Goldstruck Gigas"

### ISSUE THREAD

**Issue by nuno-pires-cruz** [HomepointXI/Issues#160]
**Date & Time**: 
2018-08-15 19:50 gmt

**Client Version (use `/ver` in game):**
30180604_0

**Character Name:**
Furies

**Discord Name (if different from in game):**

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
99 nin/49 war

**NPC or Monster or item Name:**
Briareus

**Zone name:** 
Abyssea - La Theine

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
quest "A Goldstruck Gigas" active
kill briareus
re-enter zone

**Any additional information:**
should clear quest and get a reward, based on number of abyssea quests.

**Comment by nfaletra** [comment]
Abyssea quests aren't implemented. You get the title when defeating the zone bosses and that's what is checked for Abyssea progress.

**Comment by nuno-pires-cruz** [comment]
thank you
