### ISSUE TITLE
Recovering Past Accounts

### ISSUE THREAD

**Issue by Garvaunt** [HomepointXI/Issues#161]
**Date & Time**: August 12, 2018 ! 11:28PM

**Client Version (use `/ver` in game):**30180629_2

**Character Name:** Garvaunt

**Discord Name (if different from in game):** Garvaunt

**Nation:** Sandoria

**Job(level)/Sub Job(level):**PLD99/war49

**NPC or Monster or item Name:**N/A

**Zone name:** N/A

**Coordinates (use `!where`):** N/A

**Item tool link (for items issues only):** N/A

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** Looking to Recover my BLM lving Alts, all named Garvleech1,2,3,4,5, or 6.
When LD shutdown i basically stopped playing after a week on Jova. i recently rejoined LD and cannot remember my Account ID or Passwords. if you can message me on Discord i can give you any info you may need. Thank you for your time.

**Any additional information:**

**Comment by Heepster03** [comment]
Issue has been resolved :)
