### ISSUE TITLE
Not Learning BLU spells

### ISSUE THREAD

**Issue by Aurelcassy** [HomepointXI/Issues#162]
**Date & Time**: 13-06-18

**Client Version (use `/ver` in game):**30180629_2

**Character Name:**Aurel  , and Cassy

**Discord Name (if different from in game):**Aurel   

**Nation:**Sandy

**Job(level)/Sub Job(level):**
Blu/nin
Blu/nin

**NPC or Monster or item Name:**

**Zone name:** 
Mamook , Abyssea-La Theine

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**yes and no

**Steps to reproduce:**

**Any additional information:**
I can not learn Water Bomb or Magic Hammer and killed more than 200 frogs, I think I have bad luck

**Comment by EpicTaru** [comment]
I can confirm that the frogs in mamook do use that tp move and that it is learnable, that's where Epictaru learned it.

**Comment by EpicTaru** [comment]
Bad luck doesn't mean that the spell isn't learnable but we'll see if something changed recently.

**Comment by Aurelcassy** [comment]
I got bored of killing in Mamook and I changed to Abyssea-La Theine, but I went back to Mamook thanks

**Comment by Aurelcassy** [comment]
after the maintenance I still do not learn any kind of magic in my Char Aurel and Char Cassy

**Comment by Aurelcassy** [comment]
Blue Magic skill =25 , I will upload my skill and I will try ,thanks

**Comment by Aurelcassy** [comment]
thank , now i get pollen
