### ISSUE TITLE
Target out of range

### ISSUE THREAD

**Issue by LuckySleven** [HomepointXI/Issues#163]
**Date & Time**: 08/14/18 2:20

**Client Version (use `/ver` in game):** Version 30180801_2

**Character Name:** Luckysleven

**Discord Name (if different from in game):** Luckysleven

**Nation:** Bastok

**Job(level)/Sub Job(level):** 70whm/35rdm

**NPC or Monster or item Name:**

**Zone name:** Labyrinth of Onzozo

**Coordinates (use `!where`):** <H-8>

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:** in the little cubby hole next to where Lord of Onzozo spawns if you are by the wall, everything becomes out of range, so if you have agro and you ride that cubby hole wall everything will deagro.

**Any additional information:**
I am trying to stay in that cubby hole skilling up and camping to avoid extra agro without abusing the deagro, but sometimes I run too far back by mistake.

**Comment by nfaletra** [comment]
Recent navmesh fixes might address this issue in tonight's maintenance.

**Comment by LuckySleven** [comment]
![image](https://user-images.githubusercontent.com/42387848/44112274-a7350c42-9fd2-11e8-9751-a51498444eaf.png)

**Comment by nfaletra** [comment]
Pretty sure that Goblin will take the extra 2 steps and start biting you after tonight's maint.

**Comment by Jessland86** [comment]
Fixed in today's maintenance.
