### ISSUE TITLE
Abyssea Grauberg Mob Check Incorrect

### ISSUE THREAD

**Issue by nuno-pires-cruz** [HomepointXI/Issues#164]
**Date & Time**: 
2018-05-15 11:00am GMT

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**
Furies

**Discord Name (if different from in game):**

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
nin 99/war 49

**NPC or Monster or item Name:**
Goblins, Wyverns, Peapuks, Wivres, pots all checked as too weak, i assume all mobs in zone will the same. which gives no exp, cruor and low gil

**Zone name:** 
Abyssea Grauberg

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**

**Any additional information:**

**Comment by nuno-pires-cruz** [comment]
Abyssea Vunkerl, Jasconius, bats near lord varney, spiders near iktomi, also check too weak

**Comment by nfaletra** [comment]
Should be fixed in the emergency maintenance tonight. They will still reward appropriate exp and items.
