### ISSUE TITLE
SKill up issue

### ISSUE THREAD

**Issue by apatrickm** [HomepointXI/Issues#165]
**Date & Time**: Aug 15, 2018 8:00AM

**Client Version (use `/ver` in game):** version 30180801_2

**Character Name:**Aliron

**Discord Name (if different from in game):**

**Nation:**Bastok

**Job(level)/Sub Job(level):**NIN36/DNC18

**NPC or Monster or item Name:**various

**Zone name:** various

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**No

**Steps to reproduce:**Fight tough monsters or higher

**Any additional information:**Skill cap for Katana keeps showing as capped early (ie 102 at lvl 35 when it should be 108) Unequip weapon and re-equip removes the blue text to show its not capped for the level, however skill-ups do not happen even when fighting Tough monsters. Has been happening since latest update from levels 30 - 35 (As if the in game calculation is reading the monster level as lower than it should be for skill ups)

**Comment by nfaletra** [comment]
What mobs are you fighting?

**Comment by nfaletra** [comment]
Found the bug. Emergency maintenance tonight to fix the issue. The mobs you are checking aren't actually "Tough".
