### ISSUE TITLE
Cruor Prospectors items

### ISSUE THREAD

**Issue by nuno-pires-cruz** [HomepointXI/Issues#166]
**Date & Time**: 
2018-08-15 20:37 GMT

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**
Furies

**Discord Name (if different from in game):**

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
nin 99/war49

**NPC or Monster or item Name:**
Cruor Prospector

**Zone name:** 
Abyssea Vunkerl

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
when buying Iga zukin, the item received was perle hauberk

**Any additional information:**
http://ffxiclopedia.wikia.com/wiki/Cruor_Prospector

![furies_2018 08 16_005148](https://user-images.githubusercontent.com/40919379/44179437-c4402980-a0ee-11e8-939e-6174293c3e48.png)

**Comment by EpicTaru** [comment]
Pasted from conversation earlier today on Discord regarding this (omitting other responses by myself):

<code>
[4:04 PM] Halkuras: To me it sounded like you wanted the Iga gear. That is what we were saying that should not be obtainable unless by Gil. The Perle, Aurore, and Teal sets are sold for Cruor.

[4:05 PM] Halkuras: You obtained the right item, just the wrong item was listed as what was being bought. That is a typo.
</code>

This typo will be looked into, Thanks for the ticket!

**Comment by nuno-pires-cruz** [comment]
The Cruor_Prospector.lua file was copied from one of the other zones, and the itemID of items where not changed to reflect that different zones sell different stuff.

**Comment by EpicTaru** [comment]
The cruor prospectors here only sell the items that Halkuras stated. Please see this wiki article for information on how to obtain the base Empyrean armor items.

http://wiki.homepointxi.com/Category:Empyrean_Armor

**Comment by nfaletra** [comment]
Fixed in the next update. Woo!
