### ISSUE TITLE
Sweepstox coffer not working

### ISSUE THREAD

**Issue by o0Persefone0o** [HomepointXI/Issues#168]
**Date & Time**: 08/16/18

**Client Version (use `/ver` in game):** 30180801_2

**Character Name:** Persefone

**Discord Name (if different from in game):** Persefone

**Nation:** Bastok

**Job(level)/Sub Job(level):** THF99/DNC49

**NPC or Monster or item Name:** Lower Jeuno Treasure Coffer

**Zone name:**  Lower Jeuno

**Coordinates (use `!where`):** X:11 Y:0 z:6 (242)

**Item tool link (for items issues only):** Nexus cape https://www.bg-wiki.com/bg/Nexus_Cape

**Multi-boxing? (multiple clients on same connection):** YES

**Steps to reproduce:**

ok, i told yesterday Devolnu about this, the Treasure coffer who give Nexus Cape its not giving any option except cancel, and Sweeepstox its not talking. Devolnu go there and told me the box and the gobbie its not talking to him either
![img_20180816_160145](https://user-images.githubusercontent.com/30010790/44235252-7d921400-a16e-11e8-840d-f927515f806d.png)

**Any additional information:**

**Comment by Jessland86** [comment]
Hotfixed.

**Comment by o0Persefone0o** [comment]
thank you :) i get crystal line prophecy initial quest again when i get into lower jeuno but the treasure coffer was fixed! thank you so much
