### ISSUE TITLE
COP 6-4 Issue: Omega and Ultima not spawning

### ISSUE THREAD

**Issue by neoffxi** [HomepointXI/Issues#169]
**Date & Time**: 
08/16/2018

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**
Neofive

**Discord Name (if different from in game):**
Neo

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
WHM 99 / BLM 49

**NPC or Monster or item Name:**
Omega and Ultima

**Zone name:** 
Sealion's Den

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
Yes (Neomorpheus and Neofour)

**Steps to reproduce:**
1. Enter the COP 6-4 (One to be Feared) BC
2. Proceed to the next fight
3. Kill Mammet X5
4. Proceed to the next fight
5. Kill Omega IF it spawns (warp out or time out if it doesn't)
6. Proceed to the next fight
7. Ultima doesn't spawn

**Any additional information:**
The issue is that Omega and Ultima doesn't both spawn. I tried to do this BC 5 times for my mule, and the issue persists.

**Comment by EpicTaru** [comment]
Multiboxing the airship fights is notorious for causing issues.  Can you attempt to do them with only one character online and see if the same issue occurs?

**Comment by neoffxi** [comment]
I will try

**Comment by neoffxi** [comment]
I tried 2 different machines with different ISPs, but the issue still persists.

**Comment by spectre99** [comment]
I've had this happen to me as well as various people I've helped.  I've found the easiest solution is to do one character at a time and have someone else help you so you're not dual boxing.  It's annoying but it's what has worked the best in my experience.

**Comment by EpicTaru** [comment]
Had Neo log out all other characters and I did the airship battles with his character needing thru the mission.  Mammets spawned like normal but Omega did not spawn.

**Comment by neoffxi** [comment]
![neofive_2018 08 16_205431](https://user-images.githubusercontent.com/34224364/44242309-f016ea00-a196-11e8-8e1a-a566383bc6f3.png)

**Comment by Vygun** [comment]
Same situation as Neo. Ran with Spectre and then Solo, no spawn. ;-;

**Comment by nfaletra** [comment]
I'll have to repro it on a test server and see what's dying. Should have time this weekend.

**Comment by Devolnu** [comment]
It spawns but not where it is supposed to be... for some reason it spawns off the airship

**Comment by nfaletra** [comment]
You're clicking on the Airship Door after each fight, right?

**Comment by nfaletra** [comment]
I ask cause he's right here.

![image](https://user-images.githubusercontent.com/11480851/44295534-ef9a5400-a267-11e8-81d1-3ec0ccbcaeb0.png)

**Comment by Vygun** [comment]
I can try again, but he was not there. Once was with the company of Spectre, and a few other times by myself. The mammets were defeated, then clicked on the door to move the airship, received another CS showing Ultima, upon exiting the CS, there was no Ultima or any object that could be targeted,. Warping was the only way out.

**Comment by nfaletra** [comment]
Let me try it with multiple party members, first.

**Comment by nfaletra** [comment]
Did it with 2. Had second party member (helper) wait for me to get to Omega phase before clicking on Airship Door. Omega spawned no problem. Second party member clicked Airship Door at the same time as me to get to Ultima. Ultima spawned no problem.

Give it another try. If you see issues, don't leave the bcnm. Hit me up on Discord @Autkast so I can come look.

**Comment by Vygun** [comment]
Will do, thank you for looking into it, hopefully the others with the issue will have luck as well.

**Comment by neoffxi** [comment]
There were times when Omega spawned and I was able to kill it. However, Ultima doesn't spawn after killing Omega, and clicking the airship door to proceed to the next fight.

**Comment by neoffxi** [comment]
![neomorpheus_2018 08 18_132440](https://user-images.githubusercontent.com/34224364/44301725-1d27e180-a2ea-11e8-9ede-7a1635df122b.png)

I am using 2 different machines with separate ISPs so for all intents and purposes, it's "not dual boxing". The Mammet fight and Omega were spawning just fine, but Ultima still won't load. I tried both characters click the airship door at the same time, Neofive first (waiting for the CS to finish), and Neomorpheus first (waiting for the CS to finish). In all three cases, Ultima still did not pop.

**Comment by nfaletra** [comment]
Depending on which instance you end up in, Omega and Ultimately “might” spawn. Haven’t been able to track down the cause.

**Comment by nfaletra** [comment]
So the mobs are spawning. They just potentially wander off like assholes. Fix incoming.

**Comment by nfaletra** [comment]
I don't think this is actually fixed. Need to test after tonight's maintenance. In the meantime, please message me on discord @Autkast if you're on this mission. A GM needs to drag the mobs back to the ship after they wander off like idiots.

**Comment by nfaletra** [comment]
Had to help someone through last night. Still busted.

**Comment by nfaletra** [comment]
Putting the AI into an inactive state for a few seconds after spawning. This _should_ keep them from aggroing players that haven't teleported away yet.

**Comment by nfaletra** [comment]
. . .anyone on this mission yet? @Autkast on discord if you're about to attempt it so I can come watch creepily from the corner.
