### ISSUE TITLE
Bastok Rank Mission 7 The Final Image

### ISSUE THREAD

**Issue by zainheart** [HomepointXI/Issues#17]
**Date & Time**: 

28/03/2018

**Client Version (use `/ver` in game):**

30180203_1

**Character Name:**

zainheart

**Discord Name (if different from in game):**

zainheart

**Nation:**

Bastok

**Job(level)/Sub Job(level):**

Pld99/Whm49

**NPC or Monster or item Name:**

Reinforced Cermet.

**Zone name:** 

Ro'Maeve

**Coordinates (use `!where`):**

X:197 Y:-8 Z:-28 (193)

**Item tool link (for items issues only):**

http://ffxiclopedia.wikia.com/wiki/Reinforced_Cermet

**Multi-boxing? (multiple clients on same connection):**

No

**Steps to reproduce:**

Fight with 2NM's called Mokkurkalfi

**Any additional information:**

Zone in Ro'Maeve and track down the ??? , check it for pop 2 nm's , defeat them , thack again the ??? , but when i check again that didnt give the Key item Reinforced Cermet, i zone out and come again for try on an other ??? but now the nm's wont pop at all.

**Comment by EpicTaru** [comment]
Checked player's variables, did not see any missing or incorrect.  Player checked the ??? in Ro'Maeve again and received the needed KI.

**Comment by EpicTaru** [comment]
Player verified that he was able to then complete the remainder of the mission.  Ticket closed at player request.
