### ISSUE TITLE
Tu'Lia Outpost warp not working

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#173]
**Date & Time**: 10.20pm 8/19/2018

**Client Version (use `/ver` in game):**30180604_0

**Character Name:**Spectre

**Discord Name (if different from in game):**

**Nation:**Windurst

**Job(level)/Sub Job(level):**pld99/dncr49

**NPC or Monster or item Name:**Any of the 3 city npcs that oupost warp 

**Zone name:** port windy, bastok mines, northern sandy

**Coordinates (use `!where`):** x:192 y:-12 z:216 (66)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**For some reason the outpost warp to Sky Tu'Lia isnt working.  I had LadyLux and Garvant and Lonely hero also try.  It does the white teleport animation and leaves your character invisible, similar to the black drop not working a few days ago.  Also we tried from people from all 3 nations, the same issue.  All the other outpost warps seem to be working, only the sky OP warp seems to be the issue.

**Any additional information:**

**Comment by stevomatic** [comment]
This same thing happens to my characters ~50% of the time I try to use Horst in Port Jeuno to warp to pretty much any abyssea

**Comment by nfaletra** [comment]
This OP warp isn't actually obtainable on Retail. Some custom code had to be modified to get it working again.
