### ISSUE TITLE
Wrong toughness of a mob

### ISSUE THREAD

**Issue by ediww** [HomepointXI/Issues#175]
**Date & Time**: 
20.08.2018 (monday) 22:20 Eastern European

**Client Version (use `/ver` in game):**
30180801_2
mathching the !ecv

**Character Name:**
Tate

**Discord Name (if different from in game):**

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
WAR33/BLM16

**NPC or Monster or item Name:**
Cactuar near the entrance of Rabao

**Zone name:** 
Western Al Desert

**Coordinates (use `!where`):**
x:433 y:-2 z:333 (128)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes (also confirmed by non-mb)

**Steps to reproduce:**
go to rabao exit and check the cactuar level near the entrance

**Any additional information:**
we were 33th level and it was like:
 
The Cactuar seems too weak to be worthwhile.
It seems to have high evasion and defence.
ibar addon shows MNK / 48-53 / NA,L 
looong fight with PL to heal, 0 (no) exp
at the same time spiders are shown ok and give exp.

hunch: was not able to check if it is related but about 20 mins earlier we've killed 3 anticans (well above us) but was credited for just two of them. i was not able to check if it reproduces etc.

**Comment by nfaletra** [comment]
Exp table was being loaded from sql with a hardcoded limit. Anything 11+ levels weren't loading their exp values.
