### ISSUE TITLE
Missing Mods List #1

### ISSUE THREAD

**Issue by tb1** [HomepointXI/Issues#178]
**Date & Time**: 
Aug 24, 2018
6:13AM (Canada Time)

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**
Tbone

**Discord Name (if different from in game):**
Jewbaka (varies)

**Nation:**
Windy

**Job(level)/Sub Job(level):**
RDM99/PUP49

**NPC or Monster or item Name:**
Various

**Zone name:** 
All of them

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
See below in additional information.

**Multi-boxing? (multiple clients on same connection):**
Rarely

**Steps to reproduce:**
Create character.
Level RDM to 99.
Get abby access.
Get sea access.
Make RDM empy reforge.
Make RDM relic reforge.
Make RDM artifact reforge.
Get a life...

**Any additional information:**

My list of items I've noticed with missing mods.  Some mods are unimplemented, but listing them anyway since it'd be nice to have the mods implemented at some point.

http://homepointxi.com/db/items/27968/atrophy_gloves_+1
Atrophy Gloves
**Enhancing Magic Effect Duration +16%** Not implemented

http://homepointxi.com/db/items/27420/lethargy_houseaux_+1
Lethargy Houseaux
**Enhancing magic duration +30%** Not Implemented

http://homepointxi.com/db/items/26907/lethargy_sayon_+1
Lethargy Sayon
**Enfeebling Magic Effect +14** implemented as Enfeebling Skill +14

http://homepointxi.com/db/items/28331/ukuxkaj_boots
https://www.bg-wiki.com/bg/Uk%27uxkaj_Boots
Uk'uxkaj Boots
**Enhances enfeebling magic effect** Not Implemented (~6%)

http://homepointxi.com/db/items/27061/lethargy_gantherots_+1
Lethargy Gantherots
**Saboteur +12** Not implemented

http://homepointxi.com/db/items/26749/lethargy_chappel_+1
Lethargy Chappel
**Enfeebling magic spellcasting time -15%** Not implemented
This would be easy to implement, but make the fast cast code even messier.

http://homepointxi.com/db/items/27063/skulkers_armlets_+1
https://www.bg-wiki.com/bg/Skulk._Armlets_%2B1
Skulker's Armlets
**Sneak Attack+25** Not Implemented
Could be implemented as a lazy hack to mimic Vajra's SA damage boost.

http://homepointxi.com/db/items/26715/adorned_helm_+1
Adorned Helm +1
**Unity Ranking: Attack+5~15** Missing Mod
Although not strictly implemented, it's inconsistent with other Unity Ranking mods.

**Comment by tb1** [comment]
I'll add more as I notice them.

**Comment by tb1** [comment]
http://homepointxi.com/db/items/16204/estoqueurs_cape
https://www.bg-wiki.com/bg/Estoqueur%27s_Cape
**Increases enhancing magic effect duration** Not Implemented (10%)

**Comment by nfaletra** [comment]
In the future, break this stuff up into separate tickets.
Either by mod (like stuff that isn't implemented)
Or by individual pieces of gear.

Makes the tracking cleaner.

Thanks!

**Comment by nfaletra** [comment]
https://github.com/DarkstarProject/darkstar/pull/5216
Covers the enhancing magic duration mods.

**Comment by nfaletra** [comment]
Enhancing Magic Duration mods will be in the next update.

**Comment by nfaletra** [comment]
Added Attack+15 to Adorned Helm +1. Will be in the next update.

**Comment by nfaletra** [comment]
Sneak Attack mods across THF Empyrean hands have all been fixed. The Mod already existed, it was just set to the wrong values. Fuck you and your hacky suggestions. Will be in the next update.

**Comment by tb1** [comment]
Fuck you and your hacky fixes!

**Comment by nfaletra** [comment]
Enfeebling Magic Potency has been added

**Comment by Heepster03** [comment]
@tb1 from what I can see, this is a long overdue update for your list and what mods are completed and attached to each weapon thusfar. everything except 27061 and 26749 has been already fixed.

27968 - Unknown Mod (890) 16 || ENH_MAGIC_DURATION = 890
27420 - Unknown Mod (890) 30 || ENH_MAGIC_DURATION = 890
26907 - Unknown Mod (290) 14 || ENF_MAG_POTENCY = 290
28331 - Unknown Mod (290) 6 || ENF_MAG_POTENCY = 290
27061 - not done yet (but ENHANCES_SABOTEUR = 297 exists)
26749 - not done yet
27063 - Unknown Mod (874) 25 || SNEAK_ATK_DEX = 874
26715 - (23): Attack +15
16204 - Unknown Mod (890) 10 || ENH_MAGIC_DURATION = 890

**Comment by Heepster03** [comment]
Just need to create the mods for modifiers.h, already submitted a ticket to LSB about it.

**Comment by Heepster03** [comment]
Moved to #559
