### ISSUE TITLE
Baramnesra not working AOE

### ISSUE THREAD

**Issue by Roamin64** [HomepointXI/Issues#179]
**Date & Time**: 

August 25th 2018

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**
Roamin

**Discord Name (if different from in game):**

**Nation:**

Windy

**Job(level)/Sub Job(level):**

99 whm/rdm

**NPC or Monster or item Name:**

n/a

**Zone name:** 

everywhere

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

yes

**Steps to reproduce:**
Cast Baramnesera in a party and only the whm gets the buff but this is a AoE spell.

**Any additional information:**

**Comment by EpicTaru** [comment]
Spell should be working correctly with the next server version update maintenance.
