### ISSUE TITLE
Bastok Mission 8 The Chains That Bind Us: Unable to open weighted doors (even when sufficient weight is applied to weight plate)

### ISSUE THREAD

**Issue by zainheart** [HomepointXI/Issues#18]
**Date & Time**: 

29/03/2018

**Client Version (use `/ver` in game):**

30180203_1

**Character Name:**

zainheart

**Discord Name (if different from in game):**

zainheart

**Nation:**

Bastok

**Job(level)/Sub Job(level):**

Pld99/Whm49

**NPC or Monster or item Name:**

n/a

**Zone name:** 

Quicksands Cave

**Coordinates (use `!where`):**

X:-400 Y:0 Z:672 (174)

**Item tool link (for items issues only):**

n/a

**Multi-boxing? (multiple clients on same connection):**

yes

**Steps to reproduce:**

Walk on the weight detector in I-10

**Any additional information:**

During the mission Rank 8 , we need to kill some nm behin a door in quicksand cave , the door dont move at all , i try with 1 galka + 1 hume + 2 mithra , and nothing happen.

**Comment by EpicTaru** [comment]
@zainheart Let me know when you are online and I'll come and open it for you.

**Comment by EpicTaru** [comment]
@zainheart Try it now, the maintenance yesterday seems to have fixed a good majority of issues, this may be one of them.
