### ISSUE TITLE
ZNM T4 Sarameya doesn't give Bright Blue Seal

### ISSUE THREAD

**Issue by tb1** [HomepointXI/Issues#180]
**Date & Time**: 
Aug 25, 9:08 PM

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**
Tbone

**Discord Name (if different from in game):**
Jewbaka

**Nation:**
Windy

**Job(level)/Sub Job(level):**
RDM99

**NPC or Monster or item Name:**
Sarameya Hide

**Zone name:** 
Whitegate

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
After climbing the ZNM chain to T4, fighting Sarameya and getting his hide, trading it to Sanraku (in whitegate).

**Any additional information:**

I traded the hide, didn't notice any errors, not sure if it gave me the message that I got the key item of "Bright Blue Seal", I don't recall.

Its the last seal required for me to be able to pop PW.

Sarama's Hide (9205)
Bright Blue Seal (1009)

**Comment by Heepster03** [comment]
![halkuras_2018 08 26_203652](https://user-images.githubusercontent.com/8421725/44636191-eb5ced80-a96f-11e8-91ef-8375b6516467.png)

**Comment by Heepster03** [comment]
Seems to work for me.

**Comment by Heepster03** [comment]
![halkuras_2018 08 26_203858](https://user-images.githubusercontent.com/8421725/44636213-134c5100-a970-11e8-82f5-cf6054630e2c.png)

**Comment by tb1** [comment]
Hmm, I guess I'll do the ZNM climb again and try again.  I'll record it this time :-P

**Comment by tb1** [comment]
It worked this time, so I either fucked up the first time or it was some one-off error.
