### ISSUE TITLE
Missing Mods: Kenkonken (PUP Mythic)

### ISSUE THREAD

**Issue by tb1** [HomepointXI/Issues#181]
**Date & Time**: 
Aug 26, 12:19 AM

**Client Version (use `/ver` in game):**

**Character Name:**
Tbone

**Discord Name (if different from in game):**
Jewbaka

**Nation:**
Windy

**Job(level)/Sub Job(level):**
PUP99

**NPC or Monster or item Name:**
Kenkonken

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/20484/kenkonken

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**

**Any additional information:**

Enhances Martial Arts V : If not implemented, could be simulated with an updated delay.
Suppresses Overload: This might actually be implemented in the overload code, I didn't actually look.

**Comment by nfaletra** [comment]
Don’t tell me how to live my life!

**Comment by tb1** [comment]
Just noticed Shaolin belt has a hand-to-hand mod on it, which could be used for this, assuming it's implemented right on Shaolin

http://homepointxi.com/db/items/11734/shaolin_belt

**Comment by nfaletra** [comment]
https://github.com/DarkstarProject/darkstar/pull/5210

**Comment by nfaletra** [comment]
Fixed.
