### ISSUE TITLE
Voidwatch Notorious Monster, Windurst Tier 2; Ogbunabali Keeps crashing Clients

### ISSUE THREAD

**Issue by Garvaunt** [HomepointXI/Issues#182]
**Date & Time**: 08/26/2018

**Client Version (use `/ver` in game):** 30180801_2

**Character Name:** Garvaunt

**Discord Name (if different from in game):** Garvaunt

**Nation:** San'doria, Rank 6

**Job(level)/Sub Job(level):** PLD99/WAR49

**NPC or Monster or item Name:** Ogbunabali

**Zone name:** Maze of Shakhrami

**Coordinates (use `!where`):** -284 0 -114

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** Yes, Minervah WHM99/RDM49, Dastan THF99/DNC49, Saturn RDM99/BLM49

**Steps to reproduce:** Spawn NM and continue to fight

**Any additional information:** Said NM above, causes Clients to Crash Several Times. During it's Abilities and just fighting it. 

First time, the NM used a TP move called Gravitic Horn and Crash my Main; Garvaunt. It seem to have crashed the Zone but cannot Confirm as all my other characters viewed everything as frozen. No movement from any mobs and my characters could run around but once i zoned it went Black. I'm assuming this was a Full Client Crash, but i do not know. Eventually all my characters clients had to be restarted.

Second Time, NM spawned and fought me while it was underground on my Screen, But on Ground level on my other characters, Anyways, Proceeded to Fight and did Gravitic Horn again, no DC this time. But as i fought, my Alt Dastan DC'd during no TP move, just physical attacks. As i fought it kept DCing characters without the use of a Special Ability, After managing to kill it, i DCed again, even after it was dead moments after the corpse Disapated.

**Comment by Heepster03** [comment]
I'd say that you should probably avoid it for now until this can be tested. Just curious if you were trying to stun anything with that RDM.

**Comment by Garvaunt** [comment]
Negative, Between crashes it was hard to keep my party members in. Unless Atonement has a hidden Stun effect. lol

But i DID manage too kill it even with all the crashes.

**Comment by nfaletra** [comment]
Wrong anim subs being used for ambushy antlions. Updated the mixin and pit ambush mobskill to set it properly. Hopefully this avoids any kind of animation errors the clients are getting and crashing them.

**Comment by nfaletra** [comment]
Didn't have anymore issues in my testing. Antlions that pop out of the ground should all look correct now.
