### ISSUE TITLE
Canal Moocher (aptant nm) not spawning

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#183]
**Date & Time**: 8/26/2018

**Client Version (use `/ver` in game):**30180604_0

**Character Name:**Spectre

**Discord Name (if different from in game):**

**Nation:**Windurst

**Job(level)/Sub Job(level):**pld99/dnc49

**NPC or Monster or item Name:**Canal Moocher

**Zone name:** Toraimarai Canal

**Coordinates (use `!where`):**X: 164, Y: 11, Z: -103 

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**Canal Moocher is an aptant nm (aptant of pera) You can see it listed here.  http://homepointxi.com/db/items/2817/aptant_of_pera   But.. WHen you try to load the page for Canal Moocher you get this Message on it's page 'Sorry, but the requested monster could not be loaded.' http://homepointxi.com/db/monsters/17469578/Canal%20Moocher  

**Any additional information:**

**Comment by spectre99** [comment]
Also forgot to add that Lonehero was out there for a good our trying to get the mob to pop.

**Comment by Jessland86** [comment]
Heep touched it last.

**Comment by Heepster03** [comment]
It's some SQL bs. I'll fix it here in a bit.

**Comment by canalmoocher** [comment]
**Heep touched me on my left tentacle.**

**#metoo #timesup**

**Comment by spectre99** [comment]
Seems to be popping on his own, but he does repop.
