### ISSUE TITLE
Animator Z and incorrect automaton skills

### ISSUE THREAD

**Issue by kyokofu** [HomepointXI/Issues#184]
**Date & Time**: 
11:35 am pdt 8/27/2018

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**
Kyokofukada

**Discord Name (if different from in game):**
N/A

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
99pup/49blm

**NPC or Monster or item Name:**
Animator Z

**Zone name:** 
Batallia Downs

**Coordinates (use `!where`):**
X: 486 Y: 8 Z:-159 (126)

**Item tool link (for items issues only):**
https://www.ffxiah.com/item/21392/animator-z

**Multi-boxing? (multiple clients on same connection):**
Not at the moment

**Steps to reproduce:**
Equip animator Z and use activate or deus ex automata. Instead of the 400 or so skills for melee/ranged/magic, the automaton skills is only 10.

**Any additional information:**

**Comment by nfaletra** [comment]
https://github.com/DarkstarProject/darkstar/pull/5211

A few animators were missing the correct sub skill (including Animator Z). Animator P/II were also missing from the item_weapons table, so I added those.
