### ISSUE TITLE
~ Character jailed for repeated login attempts ~

### ISSUE THREAD

**Issue by simthra** [HomepointXI/Issues#185]
**Date & Time**: 30 aug 18

**Client Version (use `/ver` in game):** 30180801_2

**Character Name:** Synafey

**Discord Name (if different from in game):**
thranduil

**Nation:**
windy

**Job(level)/Sub Job(level):** thf 99/dnc 49

**NPC or Monster or item Name:** none

**Zone name:** mordion gaol

**Coordinates (use `!where`):** n/a

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** yes

**Steps to reproduce:** got jailed for logging in while maint was starting

**Any additional information:**

**Comment by EpicTaru** [comment]
I'll release you when I get home if you haven't already been. ETA is about 2hrsish, maybe less, maybe more.

**Comment by nfaletra** [comment]
@simthra Login now and I can release you.

**Comment by nfaletra** [comment]
Released. In the future, please keep an eye on the Discord channel for maintenance announcements and wait for the all-clear before logging back in.
