### ISSUE TITLE
Shinryu fight not working.

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#186]
**Date & Time**: 8/30/2018

**Client Version (use `/ver` in game):**30180801_2

**Character Name:**Spectre

**Discord Name (if different from in game):**

**Nation:**Windurst

**Job(level)/Sub Job(level):** Pld99/dnc49

**NPC or Monster or item Name:**Shinryu

**Zone name:** Abyssea-Empyreal Paradox

**Coordinates (use `!where`):** -477.491 -0.5 515.33 255

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**Seth and I tried this and we both got the same message.  When you try to trade the scholar stone you get the message 'The Transcendental Radiance is full.' Even disbanded and tried to go in on my own for good measure and I got the same message.  Seth was multi boxing but I only had Spectre logged on.  Took a screenshot as well.   https://imgur.com/a/8NdlUpc

**Any additional information:**

**Comment by nfaletra** [comment]
Fixed in the next maintenance. Sorry for the inconvenience.

**Comment by nfaletra** [comment]
Fixed awhile ago.
