### ISSUE TITLE
error Start VWNM pre-quest

### ISSUE THREAD

**Issue by carlosx41** [HomepointXI/Issues#187]
**Date & Time**: 
9/1/2018 3pm Pasific

**Client Version (use `/ver` in game):**

30180801_2

**Character Name:**

carlosx,alma,olan,ramza, and Narik

**Discord Name (if different from in game):**

carlosx taka

**Nation:**

bastok

**Job(level)/Sub Job(level):**

thf99/dnc49  Sam99/dnc49

**NPC or Monster or item Name:**

 Adelbrecht 

**Zone name:** 

bastok market S

**Coordinates (use `!where`):**

E-8

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

yes, but my friend Narik its no on my connection and got the same error

**Steps to reproduce:**

quest do not progress into VoidWatch

**Any additional information:**

we all do the pre-quest to join bastok on the pass and when we diliver the rations. and back to the npc, he only give back rations again  and the NPC voidwatcher of the city says we dont joined any city

**Comment by EpicTaru** [comment]
Please follow the walkthrough on FFXIclopedia? https://ffxiclopedia.wikia.com/wiki/The_Fighting_Fourth

**Comment by EpicTaru** [comment]
Player didn't have the pre-requisite KI item Blue Recommendation Letter in order to start the necessary quest "The Fighting Fourth".

@carlosx41 If, after completing the above quest, you are still unable to start obtaining voidstones, please open a separate Server Issues ticket.
