### ISSUE TITLE
cop 5-3 bug 

### ISSUE THREAD

**Issue by carlosx41** [HomepointXI/Issues#189]
**Date & Time**: 

4:30 pm pacific

**Client Version (use `/ver` in game):**
30180801_2

**Character name**

Narik

**Discord Name (if different from in game):**

EduardoMS

**Nation:**

bastok
**Job(level)/Sub Job(level):**

nin99/dnc49

**NPC or Monster or item Name:**

Cid ending Cop 5-3

**Zone name:** 
metalworks bastok

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

no

**Steps to reproduce:**

has to open the CS for rank6 Cop, he saw CS on mines witht he gold key yesterday, but today when he logs cid no talk to him....

also the has "the Three paths" current and complete at the same time, we try to repoduce passed steps like trade the key on the mines back again and no work, also we try to move on to next quest and next npc also dont says anything

**Any additional information:**

**Comment by EpicTaru** [comment]
Player's COP_Tenzen_s_Path variable was showing a value of 9.  It had not updated to the value of 10 so had player re-do the CS in Pso'Xja to have the value then update to 10 and the Three Paths mission successfully complete.  

Player now shows COP mission value of 60 (for COP mission For Whom The Verse Is Sung).  Player's PromathiaStatus variable also correctly updated to value of 0 for the next events to correctly commence.
