### ISSUE TITLE
Rescue Drill Mission Bug: Key item(Rescue Training Certificate) Broken

### ISSUE THREAD

**Issue by KrissyKat** [HomepointXI/Issues#19]
**Date & Time**: 
03/31/2018

**Client Version (use `/ver` in game):**
30180203_1

**Character Name:**
Tsuki

**Discord Name (if different from in game):**

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
Blackmage(18), Whitemage(9)

**NPC or Monster or item Name:**
Vicorpasse

**Zone name:** 
La Thiene Plateau

**Coordinates (use `!where`):**
x:-256 y:23 z:116 (198)

**Item tool link (for items issues only):**
http://ffxiclopedia.wikia.com/wiki/Rescue_Training_Certificate

**Multi-boxing? (multiple clients on same connection):**

no

**Steps to reproduce:**
Talk to NPC to try and complete quest.

**Any additional information:**
Quest: Rescue Drill can't be completed as npc won't hand over the key item: Rescue Training Certificate.

**Comment by EpicTaru** [comment]
@KrissyKat you didn't answer the question regarding you multiboxing or not. Please complete the ticket in entirety.

**Comment by KrissyKat** [comment]
i fixed it, now hopefully can get the problem solved :P

**Comment by EpicTaru** [comment]
@KrissyKat apologies for my delay, I've been a little under the weather the past few days.  Please DM me or /tell me in game when you are next online so we can continue investigating your issue.

**Comment by EpicTaru** [comment]
Verified that KrissyKat's client version was causing a textid mismatch for the Vicorpasse NPC in La Thiene.  Thankfully, Krissy was still able to complete the mission by talking to the Vicorpasse NPC (named Telepoint in player's game client's version).  Advised Krissy of issues that version mismatches may cause but to go ahead and submit tickets still for any issues that may occur, version mismatch-related or not.
