### ISSUE TITLE
Tristitia VNM did not spawn after KI was consumed

### ISSUE THREAD

**Issue by LuckySleven** [HomepointXI/Issues#190]
**Date & Time**: 9/3/18 21:42:06 est

**Client Version (use `/ver` in game):** ver: 30180801_2

**Character Name:** Luckycharm

**Discord Name (if different from in game):** LuckySleven 

**Nation:** Bastok

**Job(level)/Sub Job(level):** 99thf/49dnc

**NPC or Monster or item Name:** Tristitia

**Zone name:** Abyssea Misareaux

**Coordinates (use `!where`):** forget the spot but where it spawns near conflicts 6

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** yes

**Steps to reproduce:** I ended up using hide to get away from agro. While still in hide I rested and got prompt that the nvm spawned and my KI broke

**Any additional information:**

**Comment by nfaletra** [comment]
Hide is actually causing aggro to be lost and the mob disengages and goes back to idle. Added true detection to VWNMs should fix this.

**Comment by nfaletra** [comment]
It works. Will be fixed in the next update. In the meantime, don't pop with Hide up. :F

**Comment by LuckySleven** [comment]
Is it strange that it didn’t even appear on the screen?

**Comment by nfaletra** [comment]
Not really. I saw it flicker for a split second and I was testing on a local server.

**Comment by nfaletra** [comment]
VwNMs aggro through Hide now.
