### ISSUE TITLE
Cannot complete Windurst Mission 9-2

### ISSUE THREAD

**Issue by Midgardsormr** [HomepointXI/Issues#191]
**Date & Time**: 
Any

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**
Buttons

**Discord Name (if different from in game):**

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
99BLU/49RDM

**NPC or Monster or item Name:**
Door: Vestal Chamber

**Zone name:** 
Windurst / Heaven's Tower

**Coordinates (use `!where`):**
X:0 Y:-49 Z:39 (187)

**Item tool link (for items issues only):**
N/A

**Multi-boxing? (multiple clients on same connection):**
N/A

**Steps to reproduce:**
I completed Mission 9-1 (Doll of the Dead) and got Mission 9-2 (Moon Reading) from a gate guard. I went to speak with Star Sybil in Heaven's Tower, but activating the Door: Vestal Chamber does not give the expected cutscene to advance the mission. It just displays. "The door to the Vestal Chambers is locked shut."

**Any additional information:**

I'd reported this under a... um... "prior iteration" of the server, but didn't see the report carried over. I found [this DSP note](https://github.com/DarkstarProject/darkstar/pull/5158) about the issue, so I thought (hoped?) it might have been fixed.

Thanks.

**Comment by spectre99** [comment]
Not implemented on the server yet so Windy folk are still stuck at rank 9 for now.  I believe it's getting added in the next update?

**Comment by Midgardsormr** [comment]
Joy!! Thanks for the info.

**Comment by nfaletra** [comment]
The submission to DSP wasn't complete. The problem with the mission has been fixed on DSP and will be in our next update.

**Comment by nfaletra** [comment]
Fixed.
