### ISSUE TITLE
Cruor Prospector committed fraud and false advertisement.

### ISSUE THREAD

**Issue by tb1** [HomepointXI/Issues#192]
**Date & Time**: 
Sep 5, 2018

**Client Version (use `/ver` in game):**
The correct one

**Character Name:**
Tbone

**Discord Name (if different from in game):**
Jewbaka

**Nation:**
Windy

**Job(level)/Sub Job(level):**
RNG99

**NPC or Monster or item Name:**
Cruor Prospector

**Zone name:** 
Abby - Vunkerl

**Coordinates (use `!where`):**
-320, -40, 683

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/6410/shadow_throne
http://homepointxi.com/db/items/13778/teal_saio

**Multi-boxing? (multiple clients on same connection):**
Newp

**Steps to reproduce:**
Talk to cruor prospector, he offers to sell you a shadow throne for 2 million cruor.  You hand over the cruor awaiting your new spiffy chair and he hands you a god damn shirt (teal saio).

I asked to speak to management, but he said nobody was available and was very rude about it.  I asked to speak to the complaints department and he handed me this form to fill out.  I doubt anyone will see it, he's the kind of asshole who'll just toss out the complaint. 

**Any additional information:**
- It didn't actually take my 2 million cruor, looks like it only took the normal teal saio amount.

**Comment by tb1** [comment]
![tbone_2018 09 05_114204](https://user-images.githubusercontent.com/3310503/45111738-f0a20100-b102-11e8-8410-07948c8996aa.png)

**Comment by nfaletra** [comment]
Duplicate ticket. Known issues with Cruor Prospectors outside of the initial 3 Abyssea Zones (La Theine, Tahrongi, Konschat)
https://github.com/HomepointXI/Issues/issues/166
