### ISSUE TITLE
BLU Quest missing hint parameters

### ISSUE THREAD

**Issue by LuckySleven** [HomepointXI/Issues#193]
**Date & Time**:  9/5/18 1:56:56 est

**Client Version (use `/ver` in game):**

**Character Name:** LuckySleven 

**Discord Name (if different from in game):**

**Nation:** Bastok

**Job(level)/Sub Job(level):** 99WHM/49BLM

**NPC or Monster or item Name:** Waoud

**Zone name:** Whitegate 

**Coordinates (use `!where`):**j-10

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** yes

**Steps to reproduce:** talked to him, answered all the questions correctly.

**Any additional information:**

Screenshot of text provided by Waoud:

![image0](https://user-images.githubusercontent.com/26195580/45115998-1df8aa00-b117-11e8-8e6f-243dbb430401.png)

**Comment by EpicTaru** [comment]
@LuckySleven please provide a screenshot of the text wamoud gives you

**Comment by wapozzi** [comment]
My friend Jargon is having the same issue with the same text that's provided with screen shot above.   I have yet to try to unlock it

**Comment by Heepster03** [comment]
![image](https://user-images.githubusercontent.com/8421725/129137774-5534e5ad-3d10-4827-8cbd-8e02d7287687.png)

Working as intended.
