### ISSUE TITLE
Cannot purchase Magicked Astrolabe from Churano-Shurano in Windy Waters

### ISSUE THREAD

**Issue by Midgardsormr** [HomepointXI/Issues#194]
**Date & Time**: 
Any

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**
Buttons (and Kaiju)

**Discord Name (if different from in game):**

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
99BLU/49RDM 

**NPC or Monster or item Name:**
Churano-Shurano

**Zone name:** 
Windurst Waters

**Coordinates (use `!where`):**
X:-59, Y:-10, Z:100 (175)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
N/A

**Steps to reproduce:**
Churano-Shurano is supposed to sell a Magicked Astrolabe (for solo access to Eldieme Necropolis gates) for 10,000 gil. He doesn't sell it. When you talk to him, he only gives you a line of dialogue. I also tried just trading 10,000 gil to him.

I searched the Darkstar GitHub, and [it seemed to indicate that this had been addressed](https://github.com/DarkstarProject/darkstar/pull/3840).

Thanks. 

**Any additional information:**
https://www.bg-wiki.com/bg/Churano-Shurano

https://www.bg-wiki.com/bg/Magicked_astrolabe

**Comment by EpicTaru** [comment]
https://github.com/DarkstarProject/darkstar/commit/784a531de495f6920584e6a32d3a9c0ea6efe77d

**Comment by nfaletra** [comment]
@Midgardsormr Do me a favor and check your KIs. I got dialogue and no indication that I received the KI, but it's in my Permanent Key Items list.

**Comment by Midgardsormr** [comment]
I just checked and it's there, labelled as a new item. Churano must have slipped it in my pocket without telling me when I wasn't looking or something.

Thanks much.

**Comment by EpicTaru** [comment]
No idea why this was never closed, doing so now.
