### ISSUE TITLE
Voidwalker dialogue

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#195]
**Date & Time**: 
9/7/2018

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**

Agnes

**Discord Name (if different from in game):**

**Nation:**

Windurst

**Job(level)/Sub Job(level):**

blm/rdm

**NPC or Monster or item Name:**

**Zone name:** 

Abyssea Altep

**Coordinates (use `!where`):**
entire zone

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

no

**Steps to reproduce:**
resting with abyssite gives wonky text, resting in a small area in the vicinity of the hunted NM will produce all sorts of different directions
![agnes_2018 09 07_173504](https://user-images.githubusercontent.com/26309049/45245106-e3cf0a00-b2c8-11e8-8f02-d82839cc294a.png)
![agnes_2018 09 07_173825](https://user-images.githubusercontent.com/26309049/45245180-4b855500-b2c9-11e8-9262-545d21eebb44.png)

**Any additional information:**

**Comment by nfaletra** [comment]
The mob roams around.
