### ISSUE TITLE
Outpost warping (Port Windy to Kuzotz) not working as expected

### ISSUE THREAD

**Issue by Midgardsormr** [HomepointXI/Issues#196]
**Date & Time**: 
09/07/2018 - 3.30p

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**
Pesto (and Marinara)

**Discord Name (if different from in game):**
Buttons

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
29WHM (and 29THF)

**NPC or Monster or item Name:**
Rottata

**Zone name:** 
Port Windurst

**Coordinates (use `!where`):**
(193.569, 217.149, -12.000)  344 (N)

**Item tool link (for items issues only):**
N/A

**Multi-boxing? (multiple clients on same connection):**
N/A

**Steps to reproduce:**
Ask NPC Rottata in Port Windurst for an outpost warp to Kuzotz. The animation displays and PC disappears on the screen, but doesn't actually go anywhere.

**Any additional information:**
PC can move, cast spells, etc. -- and can be seen by other PCs -- while in this invisible state. PC becomes visible in game window again upon zoning. 

Outpost warps to other areas (some of them, at least; I didn't try *all* of them) from Rottata work properly. 

(Not a big deal, but figured I'd mention it)

**Comment by spectre99** [comment]
I just checked, Spectre is windurstian, the npc warped him the OP warp without any trouble for me.

**Comment by Midgardsormr** [comment]
Weird. I tried it with two different toons... more than once... and the same thing happened. Both while multi-boxing and solo. (Just tried again after reading you did it successfully, too)

¯\_(ツ)_/¯

**Comment by neoffxi** [comment]
The level requirement has been implemented for outpost warps.

Check this link on what the minimum level to be able to outpost warp to certain regions.
http://ffxiclopedia.wikia.com/wiki/Outpost_Teleportation

**Comment by EpicTaru** [comment]
local outposts = {
..... 
    [dsp.region.KUZOTZ]          = {ki = dsp.ki.KUZOTZ_SUPPLIES,                cp = 70, **lvl = 30**, fee = 300},

Yep, @neoffxi beat me to it, lol, just needed to find it in the dsp scripts. Odd how it checks your level and if it meets the requirement, but it doesn't spit back the message telling you that you don't meet the requirements for that action to be completed. 

What do you think, @nfaletra?

**Comment by Midgardsormr** [comment]
Ah, that explains why I didn't go anywhere despite the animations. Thanks.

**Comment by nfaletra** [comment]
Hmm. I'll have to add the message about not meeting level requirement.

**Comment by EpicTaru** [comment]
Closing this issue as it should have been fixed a while ago.  Please open a new issue if it presents itself again.
