### ISSUE TITLE
Sirens tear issue with inventory 

### ISSUE THREAD

**Issue by wapozzi** [HomepointXI/Issues#197]
**Date & Time**:  9/7/18 @ 9:06PM PST

**Client Version (use `/ver` in game): 30180801_2

**Character Name: Bigbadbill

**Discord Name (if different from in game): BigBadBill

**Nation: Bastock

**Job(level)/Sub Job(level):69BST/34DNC

**NPC or Monster or item Name: Siren's Tear from ??? in north gustaberg

**Zone name: north gustaberg

**Coordinates (use `!where`): x:312 y:0 z:324 (136

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection): Yes, bthreepio

**Steps to reproduce:** compete quest for the sirens tear in bastock mines.  

**Any additional information:**   When trying to pick up another stone, says to sort inventory.  I do not have anther, seems to be invisible still in my inventory some how.  Jargon is having the same issue and preventing him from completing  BLU quest
![untitled](https://user-images.githubusercontent.com/3839262/45250200-14bc3880-b2e3-11e8-9b51-b05199e0598f.png)

**Comment by wapozzi** [comment]
I was able to have my other character pick it up and trade and it worked to get back into inventory.

**Comment by spectre99** [comment]
Same issue happened with Jargon.  Both Bill and Jargon were on the part of the blu quest that asks for the tear.  Both seemed to get that message.  Bill was multi boxing but Jargon wasn't.  His alt that isn't on the mission was able to pick up the tear fine.  I tried with two characters who aren't on the mission and they were also able to pick up the tear without a problem.  Seems like the people who are actually on the the blu mission/quest are the ones that get the message that their inventory is full.

**Comment by wapozzi** [comment]
It seems to do it after completing bastok quest "Siren's Tear"

**Comment by EpicTaru** [comment]
Yeah, interesting piece of code for the "npc" in North Gustaberg, probably needs to have another section added to it to check if the stone chosen for the blu mage job quest was the stone equaling the siren's tear.

<code>
if (mainweapon == 0 and subweapon == 0) then
            local freeslots = player:getFreeSlotsCount();
            local alreadyHasItem = player:hasItem(576);
            local SirensTear = player:getQuestStatus(BASTOK,THE_SIREN_S_TEAR);
            local SirensTearProgress = player:getVar("SirensTear");

            if (SirensTear == QUEST_COMPLETED and SirensTearProgress < 2) then
                player:messageSpecial(ITEM_CANNOT_BE_OBTAINED,576);
</code>

The script for npc Wahid sets the value for the SirensTear var to == 0 at the end of the script for that quest.

<code>

function onEventFinish(player,csid,option)

    if (csid == 81) then
        player:addQuest(BASTOK,THE_SIREN_S_TEAR);
    elseif (csid == 82) then
        player:tradeComplete();
        player:completeQuest(BASTOK,THE_SIREN_S_TEAR);
        player:addFame(BASTOK,120);
        player:addGil(150*GIL_RATE);
        player:messageSpecial(GIL_OBTAINED,150*GIL_RATE);
        player:addTitle(dsp.title.TEARJERKER);
        player:setVar("SirensTear",0);
    end
end;
</code>

I'll work on this more later when I'm back home next week, looking at code on the screen of a phone is hard, lol.

**Comment by nfaletra** [comment]
If you've previously completed the quest, you have to talk to Carmelo in Port Bastok before you can obtain another Siren's Tear.
