### ISSUE TITLE
The (Almost) Immortal Goblin Butcher in Meriph Mountains

### ISSUE THREAD

**Issue by Midgardsormr** [HomepointXI/Issues#199]
**Date & Time**: 
9/8/2018 - 2:55p

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**
Alfredo

**Discord Name (if different from in game):**
Buttons

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
23BLM

**NPC or Monster or item Name:**
Goblin Butcher

**Zone name:** 
Meriphataud Mountains

**Coordinates (use `!where`):**
X:-172, Y:7, Z-107 (77) 

**Item tool link (for items issues only):**
N/A

**Multi-boxing? (multiple clients on same connection):**
N/A

**Steps to reproduce:**
Flight Goblin Butcher. Doesn't die unless he messes up a Bomb Toss weapon skill and kills himself.

**Any additional information:**
I'm guessing this guy's HP has a mistakenly-added digit (or ten). It did go down a small amount in the 20ish minutes I was fighting him. 

![immortal-butcher](https://user-images.githubusercontent.com/17556762/45258787-57c5ec80-b373-11e8-886e-402b171b7764.png)

(screwed up with the first report, so re-submitting)

**Comment by Jessland86** [comment]
Fixed in next maintenance.

**Comment by Jessland86** [comment]
This was fixed in one of the previous restarts.
