### ISSUE TITLE
Ah Bot

### ISSUE THREAD

**Issue by Uzi904** [HomepointXI/Issues#2]
**Date & Time**: 
3/12/18 2:22pm

**Client Version (use `/ver` in game):** 30171223_0

**Character Name:** Uzi

**Nation:** Bastok

**Job(level)/Sub Job(level):**
Pld99/War49

**NPC or Monster or item Name:**
AhBot

**Zone name:** N/A

**Coordinates (use `!where`):** N/A

**Item tool link (for items issues only):** N/A

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** Ah Bot Is Sending Back Even Crystals Posted At Respectable Price For AhBot to Buy Back.

**Any additional information:** Been Inquired About By Quite A Few HP Shell Members, Their Items/Crystals Are Being Returned.

**Comment by Heepster03** [comment]
AH bot wasn't running as intended since it resetted. atom0s fixed that for us. Should be up and running now.
