### ISSUE TITLE
sushi

### ISSUE THREAD

**Issue by atts2002** [HomepointXI/Issues#20]
**Date & Time**: 
thurs 5th april

**Client Version (use `/ver` in game):**
30180203_1

**Character Name:**
Piggy
Salmonsushi

**Discord Name (if different from in game):**
doradosushi

**Nation:**
sandy

**Job(level)/Sub Job(level):**
piggy 99whm/49rdm
salmonsushi 99brd/49whm

**NPC or Monster or item Name:**
monster name Omega
CoP 6-4 "one to be feared"

**Zone name:** 
sealions den

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**

**Any additional information:**
done it about 3 times both toons with and without milti boxing same problem and the problem is
after the 1st fight with mammet u the click on the door to move to the next fight i get the cutscence with omega after cutscence its just an empty floor with no omega
was wondering if your able to boost the 2 toons to 7-5 completion for sea access that would be great thankyou

**Comment by Jessland86** [comment]
It's just a buggy fight. Dualboxing sets it off the most. Its not a bug with our side though. Unfortunately you'll just have to keep trying it till you get past it.
