### ISSUE TITLE
Lost item on server crash

### ISSUE THREAD

**Issue by nuno-pires-cruz** [HomepointXI/Issues#200]
**Date & Time**: 
2018-09-09 20:19 GMT

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**
Sirlancelot

**Discord Name (if different from in game):**
Furies

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
PLD/WAR 99/49

**NPC or Monster or item Name:**
Burtgang

**Zone name:** 
Mount Zhayolm

**Coordinates (use `!where`):**
X:93 Y:-22 Z:95 (30)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**

**Any additional information:**
server crashed, while item was on pool list
![sirlancelot_2018 09 09_201941](https://user-images.githubusercontent.com/40919379/45268784-1835f800-b47a-11e8-95a3-3a6d02d2e657.png)

**Comment by spectre99** [comment]
Farmed him another one a little earlier.
