### ISSUE TITLE
Page Exp Issue: Easy prey to decent challenge mobs not giving exp

### ISSUE THREAD

**Issue by neoffxi** [HomepointXI/Issues#201]
**Date & Time**: 
09/11/2018

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**
Neothree

**Discord Name (if different from in game):**
Neo

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
RDM 55 / BLM 27

**NPC or Monster or item Name:**
Worker Crawler

**Zone name:** 
Crawler's Nest

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
1. Solo as 55 rdm in Crawler's Nest where target mobs check as easy prey.
2. Get page 1 (3 crawlers and 3 bees).
3. Killing mobs yield exp, but not getting credit for the page.

**Any additional information:**
Before the maintenance, you can get credit from these mobs up to level 56. Also, Aliron tested mobs in Boyahda Tree with similar results where easy prey and decent challenge mobs do not give page credits.

**Comment by neoffxi** [comment]
![neothree_2018 09 11_023652](https://user-images.githubusercontent.com/34224364/45342969-75f73c80-b56d-11e8-816e-725e643b6b41.png)

**Comment by spectre99** [comment]
Sync'd in crawlers nest, despite getting 1k exp (with exp ring), certain mobs that scan as IT for me aren't giving page exp, while others are.

**Comment by spectre99** [comment]
Also tried level 53 sync in crawlers, mobs scanned as easy prey, gave exp, but no book credit.

**Comment by spectre99** [comment]
Another update.  In Kuftal tunnel.  Sync'd to spec who is 53, rydia is the other member in the party, 99 smn but currently sync'd to 53 with spec, the crabs scan as IT, killing doesn't give exp or page credit.  This is post emergency maintenance.
