### ISSUE TITLE
Request for 119 Ammo Recipes

### ISSUE THREAD

**Issue by tb1** [HomepointXI/Issues#202]
**Date & Time**: 
Sept 11, 2018

**Client Version (use `/ver` in game):**

**Character Name:**
Tbone

**Discord Name (if different from in game):**
Jewbaka

**Nation:**
Windy

**Job(level)/Sub Job(level):**
ANY99/ANY49

**NPC or Monster or item Name:**
Divine Arrow, Bolt and Bullets

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

https://www.bg-wiki.com/bg/Divine_Arrow
http://homepointxi.com/db/items/21300/divine_arrow
  - Needs Mods
  - Request synergy to crafting custom recipe
  - Exalted Lumber already obtainable.
  - Ra'Kaznar Arrowheads *should* be already obtainable.
  - Need source for Porxie Wing (for Porxie Fletchings)

https://www.bg-wiki.com/bg/Divine_Bolt
http://homepointxi.com/db/items/21312/divine_bolt
  - Needs Mods
  - Request synergy to crafting custom recipe
  - Materials should already be obtainable

https://www.bg-wiki.com/bg/Divine_Bullet
http://homepointxi.com/db/items/21328/divine_bullet
  - Needs Mods
  - Request synergy to crafting custom recipe
  - Materials should already be obtainable

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
- Level RNG or COR.
- Try to find anything better than 113 ammo
- Bitch at GMs and admins for over a year to add 119 ammo.
- Bitch in LS for over a year about the lack of 119 ammo.
- Do some research on what is available.
- Open a ticket and suggest some ammo that should be added without making it sound bitchy.
- Profit

**Any additional information:**

All items are high level crafting with pain in the ass to farm materials.  Should be reasonably balanced, and might bring some more life to RNG and COR until 119-3 get implemented.

**Comment by nfaletra** [comment]
REQUEST DENIED

jk I'll look into it.

**Comment by nfaletra** [comment]
Added mods for the ammo. They will be in !shop 4 with other ammo. Enjoy your new gil sink.

**Comment by tb1** [comment]
![i-love-you-meme](https://user-images.githubusercontent.com/3310503/45457236-3cc4e680-b6ab-11e8-91d9-12575ecd0ae4.jpg)

**Comment by nfaletra** [comment]
!shop 4
