### ISSUE TITLE
Marine StewpoT recipe missing

### ISSUE THREAD

**Issue by ediww** [HomepointXI/Issues#203]
**Date & Time**: 

12 September 2018 23:57 (Sofia/Bulgaria TZ)

**Client Version (use `/ver` in game):**

30180801_2

**Character Name:**

Tate

**Discord Name (if different from in game):**

**Nation:**

Windurst

**Job(level)/Sub Job(level):**

THF99/WHM49

**NPC or Monster or item Name:**

Marine Stewpot
Prm. Mn. Stewpot

**Zone name:** 

n/a

**Coordinates (use `!where`):**

n/a

**Item tool link (for items issues only):**

https://www.bg-wiki.com/bg/Marine_Stewpot
http://homepointxi.com/db/items/5893/marine_stewpot
HQ version
http://homepointxi.com/db/items/5894/prime_marine_stewpot
**Multi-boxing? (multiple clients on same connection):**

n/a

**Steps to reproduce:**

n/a

**Any additional information:**

The "Marine Stewpot" crafting recipe seems to be missing. The item itself is present.
Same goes for the HQ version "Prime Marine Stewpot",

**Comment by nfaletra** [comment]
It's being added to DSP but currently there is no way to acquire the Key Item required for the recipe.

**Comment by EpicTaru** [comment]
No, my ticket, not yours!

**Comment by EpicTaru** [comment]
Recipe doesn't exist in DSP at all, I'll do a PR to have it added to DSP.  As Aut said, until the KI needed to craft that recipe is added to DSP, there is currently no way for the item to be crafted.

**Comment by EpicTaru** [comment]
https://github.com/DarkstarProject/darkstar/pull/5226

**Comment by nfaletra** [comment]
Fixed.
