### ISSUE TITLE
NPC Amalasanda is disabled/Need for Shirataki

### ISSUE THREAD

**Issue by ediww** [HomepointXI/Issues#204]
**Date & Time**: 

12 September 2018 23:58

**Client Version (use `/ver` in game):**

30180801_2

**Character Name:**

Tate

**Discord Name (if different from in game):**

**Nation:**

Windurst

**Job(level)/Sub Job(level):**

THF99/WHM49

**NPC or Monster or item Name:**

Amalasanda

**Zone name:** 

Lower Jeuno (J-8) /Tenshodo in Neptune's Spire

**Coordinates (use `!where`):**

X:29 Y:3 Z:-42 (94)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

n/a

**Steps to reproduce:**

Talk to her and you get  system message that the NPC is broken by someone.
But it seems to be the only source for at least one item (Shirataki).

**Any additional information:**
Need an ingredient "Shirataki"
https://www.bg-wiki.com/bg/Shirataki
which seems to be available only at this NPC shop.

**Comment by nfaletra** [comment]
Customized shop items. Includes Shirataki.

**Comment by BrosephJ** [comment]
This NPC is missing a lot of their inventory..

https://www.bg-wiki.com/bg/Amalasanda

**Comment by Heepster03** [comment]
@brosephj

Working as intended. Hence why it's a custom shop, therefore not retail.
