### ISSUE TITLE
[YACR] Yet Another Customization Request : Legion Rings & Earrings

### ISSUE THREAD

**Issue by tb1** [HomepointXI/Issues#205]
**Date & Time**: 
Stardate: -304281.7091

**Client Version (use `/ver` in game):**
0x1CC85C12

**Character Name:**
Tbone the Cornholio

**Discord Name (if different from in game):**
Cornholio the Tbone

**Nation:**
Canada

**Job(level)/Sub Job(level):**
ANY99/ANY49

**NPC or Monster or item Name:**
Saarlan
Mediator's Ring
Provocare Ring
Dhanurveda Ring
Corybant Pearl
Belatz Pearl
Ouesk Pearl
Puissant Pearl
Myrddin Pearl
Cytherea Pearl
Saviesa Pearl

**Zone name:** 
Rolanberry Fields

**Coordinates (use `!where`):**
J-5, I'm sure you can find him

**Item tool link (for items issues only):**
https://www.bg-wiki.com/bg/Saarlan
https://www.bg-wiki.com/bg/Corybant_Pearl
https://www.bg-wiki.com/bg/Belatz_Pearl
https://www.bg-wiki.com/bg/Ouesk_Pearl
https://www.bg-wiki.com/bg/Myrddin_Pearl
https://www.bg-wiki.com/bg/Cytherea_Pearl
https://www.bg-wiki.com/bg/Saviesa_Pearl
https://www.bg-wiki.com/bg/Veneficium_Ring
https://www.bg-wiki.com/bg/Ambuscade_Ring

**Multi-boxing? (multiple clients on same connection):**
Nope

**Steps to reproduce:**
- Find a good looking (or ugly) person of the opposite gender.
- Woo them with your amazing charm, charisma gear may be required.
- Take off your cloths and their cloths.
- If the potential mate doesn't run away, insert tab A into slot A (can use slot B or C, but will not result in reproduction)
- If the moon phase is correct, and you are point in the right direction, wait 9 months.
- Profit.

**Any additional information:**

Since the Unity Ranking: gear has hax mods, would it be possible to add similar mods to the Legion: rings and earrings.  There are a few nice pieces, on par with maat augment rings, some slightly better.

Might get more people grouping up for legion, other than tanz farming, and might get more people introduced into legion.

# DO IT, OR THE MITHRA CHILD GETS A BULLET!

![kitty-and-a-gun1](https://user-images.githubusercontent.com/3310503/45812497-2d3a3480-bc8d-11e8-8920-a2f18f0fce46.jpg)

**Comment by Heepster03** [comment]
gonna close this, might be something we do in the future. no reason to have the ticket open anymore
