### ISSUE TITLE
??? for Ninja Quest not responding

### ISSUE THREAD

**Issue by sidaious** [HomepointXI/Issues#206]
**Date & Time**:
 9/20/18  12:14pm est

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**
Azures

**Discord Name (if different from in game):**
Asuna

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
Thf32/Dnc 16

**NPC or Monster or item Name:**

??? for Ninja Quest  "Strangely shaped coral" 

**Zone name:** 
Korroloka tunnel

**Coordinates (use `!where`):**
X  -414
Y   0
Z  121 (206)

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**

**Any additional information:**
my sister (Elisani) and i both have flagged the quest... NPC is asking for the [Strangely Shaped Coral] from this location. Made it to the location and clicked the ??? Nothing happens. All three accounts have tried clicking the location. all three get the same response. Elisani is on the same IP but on a seperate computer.  Have attempted to trigger even with only one account on and still same response.

**Comment by nfaletra** [comment]
Went to the position listed. That is the wrong ??? for NIN quest.

**Comment by nfaletra** [comment]
![image](https://user-images.githubusercontent.com/11480851/45839250-1289af00-bcd1-11e8-9c1b-595dc3773c4a.png)

**Comment by EpicTaru** [comment]
@sidaious Please verify your location in relation to the location that Aut indicated above.
