### ISSUE TITLE
Unable to use item

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#207]
**Date & Time**: 
9/20/18

**Client Version (use `/ver` in game):**

30180801_2

**Character Name:**
Agnes

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

99blm

**NPC or Monster or item Name:**

Ambrosia

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
unable to use item Ambrosia

**Any additional information:**
must be somewhat recent because I frequently make and use it

**Comment by EpicTaru** [comment]
Screenshot please of you attempting to use it.

**Comment by stevomatic** [comment]
![agnes_2018 09 20_184620](https://user-images.githubusercontent.com/26309049/45850839-bf7e1f00-bd05-11e8-9889-e69635bd09a4.png)

tried relogging, doing it with and without level sync and with just me logged in etc.

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/45850898-a96c6080-bcfd-11e8-85d9-2bf01558b3d2.png)
 You already have an existing Food effect.  Buy the Antacid from the !shop and use that so that the food effect is removed and you are able to consume other food.
