### ISSUE TITLE
Unable to use item

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#208]
**Date & Time**: 
9/20/2018

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**
Langridge

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**
99thf

**NPC or Monster or item Name:**

Ambrosia
**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**

unable to use item ambrosia

**Any additional information:**
![langridge_2018 09 20_185705](https://user-images.githubusercontent.com/26309049/45851150-54cde300-bd07-11e8-8284-97ee465cdb8e.png)

**Comment by EpicTaru** [comment]
OK, this is different, it'll be looked into

**Comment by nfaletra** [comment]
Script got busted in a merge. Cleaned it up. Will work again after the next update.

**Comment by nfaletra** [comment]
Fix't
