### ISSUE TITLE
Battlefield "When Angels Fall" not showing up for me

### ISSUE THREAD

**Issue by Dauthus88** [HomepointXI/Issues#209]
**Date & Time**: 

9:54 PM SMT

**Client Version (use `/ver` in game):**

30180801_2

**Character Name:**

Kaiba

**Discord Name (if different from in game):**

Kaiba
**Nation:**
Bastok

**Job(level)/Sub Job(level):**
PLD99/DNC49

**NPC or Monster or item Name:**

**Zone name:** 
 The Garden of Ru'Hmet

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Finished killing all mobs, went to exit door instead of other side, when i went to other side it said "Another event was called while current event was running.", went back to exit door and it popped up "Which Battlefield will you enter?" and all that was listed was "None.", so warped out and came back, and its still listed "None." when i click back on the door

**Any additional information:**

**Comment by nfaletra** [comment]
Unless I misunderstood the issue. After re-reading, was the player able to enter the bcnm initially?

**Comment by EpicTaru** [comment]
You and I resolved this ticket, @nfaletra. I'll update you in the admin channel. Do you want it kept open until the bcnm rewrite is merged?
