### ISSUE TITLE
Sandy mission 2-1

### ISSUE THREAD

**Issue by Willthefluteboy** [HomepointXI/Issues#21]
**Date & Time**:  April 6th, 2018

**Client Version (use `/ver` in game):** 30180203_1 

**Character Name:** Reon

**Discord Name (if different from in game):** Will/Reon

**Nation:** Sandy

**Job(level)/Sub Job(level):** THF 99/ DNC 49

**NPC or Monster or item Name:** Yaucevouchat

**Zone name:** La Theine Plateau

**Coordinates (use `!where`):** X:-305 Y:28 Z:338 (176)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** Single client

**Steps to reproduce:** Speaking with him during mission 2-1 for Sandy.

**Any additional information:** While working on doing Sandy mission 2-1 so I can progress and get rank 6 to start working on pushing content none of the NPC's are giving me the Bronze Sword to continue the mission. In addition to this Yaucevouchat crashes my client every time I speak with him.

**Comment by Willthefluteboy** [comment]
After multiple crashes and doing a cutsceen where you talk to an NPC that informs you about monsters in Abysee La Thuane the NPC in question is no longer crashing me and has given the sword needed to continue the quest line. Unsure if this is related however it is the only thing that has been done differently on my part.

**Comment by EpicTaru** [comment]
@Willthefluteboy is this issue still an issue? If it is, please update the ticket with where on the missing you are now stuck at.  If not, please close it. Thanks.

**Comment by Willthefluteboy** [comment]
Mine has been solved thanks. I did hear that there was another player having the same issue though. Not sure if you want them to have the chance to post on here or not. Discord Name: mimi
