### ISSUE TITLE
Rank 2 Final Mission cutscene hangs

### ISSUE THREAD

**Issue by BrosephJ** [HomepointXI/Issues#210]
**Date & Time**: 

Sep 21st 2018, 4:27pm PST

**Client Version (use `/ver` in game):**

30180904_0

**Character Name:**

Hippopottymouth

**Discord Name (if different from in game):**

Hippopottymouth#2754

**Nation:**

Bastok

**Job(level)/Sub Job(level):**

Black Mage 38/Red Mage 19

**NPC or Monster or item Name:**

**Zone name:** 

Balga's Dais

**Coordinates (use `!where`):**

X:-139 Y:55 Z:-140 (67)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

No

**Steps to reproduce:**

Enter Rank 2 Final Mission

**Any additional information:**
![hippopottymouth_2018 09 21_161316](https://user-images.githubusercontent.com/5185864/45910248-6ae9ab00-bdbc-11e8-9f1b-83e0baae9b0a.png)

Hangs with or without FPS/Enternity addon loaded.

**Comment by EpicTaru** [comment]
I reset player's POS and had player attempt mission again, was stuck again at same part of the CS.

**Comment by BrosephJ** [comment]
Cause was "Jova Compatibility Dats". Oops.
