### ISSUE TITLE
Jailed for misunderstanding

### ISSUE THREAD

**Issue by xurpn1986** [HomepointXI/Issues#212]
**Date & Time**: 
09/25/2018 1:11am

**Client Version (use `/ver` in game):**
cant get in

**Character Name:**
Xuron

**Discord Name (if different from in game):**
Xuron

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
THF99

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

**Comment by nfaletra** [comment]
Login and I gotchu

**Comment by xurpn1986** [comment]
logged in
