### ISSUE TITLE
Malfeasance missing all mods

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#213]
**Date & Time**: 9/25/2018

**Client Version (use `/ver` in game):**30180904_0

**Character Name:**Spectre

**Discord Name (if different from in game):**

**Nation:**Windurst

**Job(level)/Sub Job(level):**pld99/dnc49

**NPC or Monster or item Name:** Malfeasance

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:** The weapon Malfeasance is missing all it's mods.  These are the mods that the weapon should have.  https://www.bg-wiki.com/bg/Malfeasance

**Comment by Heepster03** [comment]
fixed for next patch.

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/136277155-10bab9d0-077b-4fa2-92cb-1765e71654b6.png)
This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.
