### ISSUE TITLE
RNG quest, tiger won't spawn

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#214]
**Date & Time**: 7.00pm 9/27/2018

**Client Version (use `/ver` in game):**30180904_0

**Character Name:**Spectre

**Discord Name (if different from in game):**

**Nation:**Windurst

**Job(level)/Sub Job(level):**Rdm99/Dnc49

**NPC or Monster or item Name:**Old Sabertooth

**Zone name:** Sauromugue Champaign

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**Activated this quest closer to when I started on this server, which is a while ago.  All you have to do is activate the quest by talking to the npc, going to Campaign and clicking Old Bones to get npc to spawn.  When I click it says nothing happens.  I even talked to the optional npc characters for the quest.  Also checked temp and perm key items and I don't have Old Tiger's Fang KI.  My quest log does show The Fanged One quest as active.

**Any additional information:**

**Comment by nfaletra** [comment]
vars were not correct. the quest progression most likely changed after he originally accepted the quest.
