### ISSUE TITLE
Request to remove character from Jail

### ISSUE THREAD

**Issue by Scarier** [HomepointXI/Issues#216]
**Date & Time**: 

9/29/2018

**Client Version (use `/ver` in game):**

3080904_0

**Character Name:**

Scary
Taro
Taru
Tyrese
Tyrone
Trevon

**Discord Name (if different from in game):**

Scary

**Nation:**

San'Doria

**Job(level)/Sub Job(level):**

WAR
BLU
BLUE
THF
WHM
BRD

**NPC or Monster or item Name:**

N/A

**Zone name:** 

Mordion

**Coordinates (use `!where`):**

!where doesn't work

**Item tool link (for items issues only):**

N/a

**Multi-boxing? (multiple clients on same connection):**

Yes/yes

**Steps to reproduce:**

No sure

**Any additional information:**

Request to have characters get out of jail, last login was March 2017 under LegionDark, according to game data base.

**Comment by Scarier** [comment]
What's up homies any GMs around to move my chars out of jail?

**Comment by Jessland86** [comment]
Chars were released.
