### ISSUE TITLE
mob exp wacked

### ISSUE THREAD

**Issue by salazer** [HomepointXI/Issues#217]
**Date & Time**: 9/29/18   10:30 pm Est

**Client Version (use `/ver` in game):**30180904_0

**Character Name:** Soap

**Discord Name (if different from in game):**

**Nation:** bastok

**Job(level)/Sub Job(level):** 14 smn/rdm

**NPC or Monster or item Name:** land crab

**Zone name:** south Gustaberg 

**Coordinates (use `!where`):** Around E-8

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** yes

**Steps to reproduce:** nuked a few more

**Any additional information:** the land crabs and other mobs,  are giving 400+almost 600 Exps to me at lv 14 and checking at (seems to be easy prey)

**Comment by spectre99** [comment]
Exp in general was upped to make exping easier, so I'm pretty sure that's normal now.
