### ISSUE TITLE
Blurred Axe Model ID

### ISSUE THREAD

**Issue by Uzi904** [HomepointXI/Issues#218]
**Date & Time**: 9/30/18
10:45am

**Client Version (use `/ver` in game):**30180904_0

**Character Name:** Uzi

**Discord Name (if different from in game):**

**Nation:**
Bastok

**Job(level)/Sub Job(level):** 99war/dnc

**NPC or Monster or item Name:**
N/a

**Zone name:** n/a

**Coordinates (use `!where`):** n/a

**Item tool link (for items issues only):** 
(Item Id: 20802)

**Multi-boxing? (multiple clients on same connection):**
N/a

**Steps to reproduce:**
N/a

**Any additional information:**
Blurred axe image is shown as basically lvl 1 bronze axe if you will, seems to have wrong item image id.

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/46261179-7708f300-c4b5-11e8-9d32-e4135e93daf5.png)

**Comment by Heepster03** [comment]
Confirmed.
