### ISSUE TITLE
Broken Food

### ISSUE THREAD

**Issue by Willthefluteboy** [HomepointXI/Issues#22]
**Date & Time**: April 6, 2018

**Client Version (use `/ver` in game):** 30180203_1

**Character Name:** Reon

**Discord Name (if different from in game):** Will/Reon

**Nation:** Sandy

**Job(level)/Sub Job(level):** THF 99 / DNC 49

**NPC or Monster or item Name:** Fried Popoto

**Zone name:** Any zone where you can eat food

**Coordinates (use `!where`):** Any location you can eat food

**Item tool link (for items issues only):** http://homepointxi.com/db/items/6272/fried_popoto

**Multi-boxing? (multiple clients on same connection):** Single Client

**Steps to reproduce:** Move to a location that you may eat buff food and eat Fried popoto

**Any additional information:** While leveling my cooking I found this food that seemed to be really good for grouping as a Melee character. When I went to sell the food to the vendor the sell value was "0". In addition the food is unable to be eaten. I have traded stacks to other players with the same result. I have 10 stacks of this food if you need to try as well.

**Comment by Willthefluteboy** [comment]
In addition I am able to eat other buff foods. Just not this specific food.

**Comment by EpicTaru** [comment]
A sell price of 0 usually denotes it's an item that dsp hasn't completed scripts for (or isn't in the custom code for this server) . This would also explain being unable to eat it. Just interesting that you could still make it, but that could just have been the work of a dsp dev that did the script for the craft but then never finished doing the other scripts for it. Not much can be done until dsp codes
