### ISSUE TITLE
Cavaros Mantle has wrong mod

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#221]
**Date & Time**: 10/2/2018

**Client Version (use `/ver` in game):**30180904_0

**Character Name:** Spectre

**Discord Name (if different from in game):**

**Nation:**Windurst

**Job(level)/Sub Job(level):**pld99/dnc49

**NPC or Monster or item Name:**Cavaros Mantle

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:** The item is supposed to increase crit hit damage by 3% which is mod 421, but the item itself has the mod 165 which is crit hit rate.  Needs to be switched to 421.  

http://homepointxi.com/db/items/11553/cavaros_mantle

**Any additional information:**

**Comment by EpicTaru** [comment]
https://github.com/DarkstarProject/darkstar/pull/5265
