### ISSUE TITLE
Tiamat

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#223]
**Date & Time**: 

10/2

**Client Version (use `/ver` in game):**

30180909_0

**Character Name:**
Agnes

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

Tiamat

**Zone name:** 

Attohwa

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
Found Tiamat  east of his usual location  flying over the top of the rocks
![map 1](https://user-images.githubusercontent.com/26309049/46383759-12e65a80-c680-11e8-9e12-4591eb1e64af.png)

After aggroing him he spammed tp abilities and draw-in moving around until we ended up stuck inside of a mountain. I warped out and assume he's still there.
![tia](https://user-images.githubusercontent.com/26309049/46383816-6193f480-c680-11e8-9df4-f99eab8f4706.png)

**Any additional information:**

**Comment by EpicTaru** [comment]
Why for you go and interrupt Tiamat's daily constitutional?!?!? Please take a screenshot if he's still up there and post it here please

**Comment by stevomatic** [comment]
I found him here
![map](https://user-images.githubusercontent.com/26309049/46501515-bf951900-c7f3-11e8-8afd-37cc822ca3c2.png)
According to distance plugin he's 15 feet away, although you can't see him
![grow](https://user-images.githubusercontent.com/26309049/46501555-dc315100-c7f3-11e8-8ce0-db4c65b367a0.png)

**Comment by Jessland86** [comment]
Despawned/respawned. Draw in issues are already known and reported to DSP.
