### ISSUE TITLE
Hyacinth Stratum

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#224]
**Date & Time**: 

10/4

**Client Version (use `/ver` in game):**

30180904_0
**Character Name:**
Kommissar

**Discord Name (if different from in game):**

**Nation:**

windurst

**Job(level)/Sub Job(level):**

war/mnk

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
Playing through VW on a new character and hyacinth/tavnazia didn't upgrade to tier 2. It was late and thinking perhaps I'd missed a cs or something I just  went through the steps again and it still hasn't upgraded. The !voidwatch command doesn't do anything.

**Any additional information:**

**Comment by Jessland86** [comment]
Underlying issue should be fixed in tonight's maintenance.
