### ISSUE TITLE
Chains and Bonds COP mission 7-1 CS won't engage

### ISSUE THREAD

**Issue by lumbergsbaby** [HomepointXI/Issues#225]
**Date & Time**: 

8:50 PM EST 10/4/2018

**Client Version (use `/ver` in game):**

30180904_0

**Character Name:**

Lump

**Discord Name (if different from in game):**

Lumbergsbaby

**Nation:**

Bastok

**Job(level)/Sub Job(level):**

99 Blu/49whm

**NPC or Monster or item Name:**

**Zone name:** 

Tavnazia

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

Yes, Lumbthird/Lumberg/Lumb all receved CS on zone. Use Servo and Ashita. 

**Steps to reproduce:**
Zone into Tavnazia multiple times. Updated version to current. Still doesn't trigger CS.

**Any additional information:**

**Comment by Heepster03** [comment]
Lump only had to rezone to Lufaise Meadows, all good now :)
