### ISSUE TITLE
Sancus Sachet missing blood pact damage mod

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#226]
**Date & Time**: 10/5/2018

**Client Version (use `/ver` in game):**30180904_0

**Character Name:**Spectre

**Discord Name (if different from in game):**

**Nation:**windurst

**Job(level)/Sub Job(level):** pld99/dnc49

**NPC or Monster or item Name:** Sancus Sachet

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:** The item is supposed to have blood pact damage +10.  I believe the mod is 126

**Comment by nfaletra** [comment]
Fixed in the next update

**Comment by Heepster03** [comment]
Confirmed working.
