### ISSUE TITLE
Cronus Drain HP additional effect doesn't work

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#235]
**Date & Time**: 10/5/2018

**Client Version (use `/ver` in game):**30180904_0

**Character Name:**Spectre

**Discord Name (if different from in game):**

**Nation:**windurst

**Job(level)/Sub Job(level):** pld99/dnc49

**NPC or Monster or item Name:** Cronus

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:** Apparently on retail it has the ability to drain between 200-300hp, though the proc rate is said to be between 5-10% (only source I could find https://www.ffxiah.com/item/20904/cronus )

**Comment by nfaletra** [comment]
Added. May need adjustments in the future.
