### ISSUE TITLE
SMN Issue

### ISSUE THREAD

**Issue by akahrimirai** [HomepointXI/Issues#238]
**Date & Time**: 
10/5/18
6:30pm

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**
Akahri

**Discord Name (if different from in game):**
miraikari

**Nation:**
sandoria

**Job(level)/Sub Job(level):**
SMN 37 / WHM 18

**NPC or Monster or item Name:**
n/a

**Zone name:** 
n/a

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
I believe i have a glitch on SMN. I played before the server switches and had SMN to Lv 37 prior using carbuncle, shiva, ifrit, ect.. I came back and i don't even have carbuncle as a summon and im still level 37 SMN, so i should have him by default having the job unlocked and leveled. At this current state i can't even play correctly with no summons. 

**Any additional information:**
I also went back to the quest spot on smn to see if i would get a cutscene but no luck.

**Comment by nfaletra** [comment]
Can you screenshot your completed quests for Windurst?

**Comment by akahrimirai** [comment]
http://prntscr.com/l2qtjh

**Comment by nfaletra** [comment]
You need to complete the SMN unlock quest. I’m guessing your smn level was transferred from retail. Even though you have it unlocked, you need to do the quest to get carbuncle. I had to do the same thing.

**Comment by akahrimirai** [comment]
Thank you very much, will start it now.
