### ISSUE TITLE
Request character to remove from jail

### ISSUE THREAD

**Issue by Watashi428** [HomepointXI/Issues#239]
**Date & Time**: 
10/6/2018

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**
Watashi
Watashii
Bokurawa
Bokurai

**Discord Name (if different from in game):**
Watashi

**Nation:**
Bastok

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

**Comment by Jessland86** [comment]
You can be let out in 72 hours from now. All the items you were botting will be removed from your inventory as well before you are released.

**Comment by Watashi428** [comment]
Hello. It's been 72 hours. Can you please release my characters from jail?
Watashi, Watashii, Watashiwa, Bokura, Bokurai, Bokurawa. Thanks.

**Comment by Watashi428** [comment]
=( can someone please unjail me? Pretty please.

**Comment by Jessland86** [comment]
Chars are released.
