### ISSUE TITLE
Do Not Pass Go (Currently in Mordion Gaol)

### ISSUE THREAD

**Issue by honeycubbinz** [HomepointXI/Issues#24]
**Date & Time**: 
4/14/2018

**Client Version (use `/ver` in game):**

30180329_1

**Character Name:**
Brandoh
Brandoo
Brando
Kattannah

**Discord Name (if different from in game):**

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
Thf(99)/Dnc(49)

**NPC or Monster or item Name:**

**Zone name:** 
Mordion Gaol

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**

**Any additional information:**

Brandoh and 3 toons listed above all got imprisoned about a year ago for afk farming crystals in Al'Taieu about a year ago. This Trickster has been rehabilitated!! 
Hoping to be able to play on the new HomePoint server!

**Comment by Heepster03** [comment]
After some deliberation and discussion, it has been decided that you'll get your redeeming chance. Should you be found afk botting anything, it's over. Don't waste it, and welcome to HomepointXI. You can be freed by the next available GM.

**Comment by EpicTaru** [comment]
All 4 character released at 2056 CST 04/14/18
