### ISSUE TITLE
Eminent Gun Won't Equip

### ISSUE THREAD

**Issue by BrenMcM** [HomepointXI/Issues#240]
**Date & Time**: 

1`3:34 GMT

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**

Brendokusai

**Discord Name (if different from in game):**

!3ren

**Nation:**

Sandoria

**Job(level)/Sub Job(level):**

COR 99

**NPC or Monster or item Name:**

Eminent Gun

**Zone name:** 

Northern Sandoria

**Coordinates (use `!where`):**

X:126 Y:0 Z:-3

**Item tool link (for items issues only):**

https://www.ffxiah.com/item/21281/eminent-gun

**Multi-boxing? (multiple clients on same connection):**

YES

**Steps to reproduce:**

Try to equip gun on applicable job

**Any additional information:**
Gun wont equip. No Error Message

**Comment by Heepster03** [comment]
This will be fixed when the server reboots again.

**Comment by Heepster03** [comment]
Confirmed working.
