### ISSUE TITLE
Using Ranged Attack with Darts plays wrong animation

### ISSUE THREAD

**Issue by Koppajin** [HomepointXI/Issues#241]
**Date & Time**: 

10/6/2018 11:28AM

**Client Version (use `/ver` in game):**

30180904_0

**Character Name:**

Yuugen

**Discord Name (if different from in game):**

Hippopottymouth#2754 (Yuugen)

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

Dart

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

http://homepointxi.com/db/items/17307/dart

**Multi-boxing? (multiple clients on same connection):**

No

**Steps to reproduce:**

Use /ra on an unsuspecting monster

**Any additional information:**

Animation is Bard Singing, even plays the audio for it

**Comment by Jessland86** [comment]
This is a long standing DSP issue. It has to do with /lockstyle

**Comment by Heepster03** [comment]
I ticketed this on DSP almost 2 years ago.... referenced here.

https://github.com/DarkstarProject/darkstar/issues/3630

**Comment by EpicTaru** [comment]
This issue was fixed sometime in the past, is currently displaying correct animation for throwing.
