### ISSUE TITLE
Abby Attoawh chigoe issues.

### ISSUE THREAD

**Issue by Jessland86** [HomepointXI/Issues#243]
**Date & Time**: 
10/7/18 1534 EDT

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**
n/a

**Discord Name (if different from in game):**
n/a

**Nation:**
n/a

**Job(level)/Sub Job(level):**
n/a

**NPC or Monster or item Name:**
Tunga
Murrian Chigoe

**Zone name:** 
Abby Attowah

**Coordinates (use `!where`):**
511.266 19.337 -162.986

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
Murrian chigoe and tunga are target-able on retail with names visible while idle. 
Currently after agro murrian chigoe are not target-able with no names visible.
Tunga also does not have true detection like he does on retail.
**Any additional information:**

**Comment by nfaletra** [comment]
Fixed in next update.

**Comment by Heepster03** [comment]
Confirmed working.
