### ISSUE TITLE
Wicce Gloves missing Magic Crit mods

### ISSUE THREAD

**Issue by tb1** [HomepointXI/Issues#245]
**Date & Time**: 

**Client Version (use `/ver` in game):**

**Character Name:**
Tbone

**Discord Name (if different from in game):**
Cornholio

**Nation:**
Windy

**Job(level)/Sub Job(level):**
BLM99

**NPC or Monster or item Name:**
Wicce Gloves +1
http://homepointxi.com/db/items/27059/wicce_gloves_+1

**Zone name:** 
All the zones!

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/27059/wicce_gloves_+1
https://www.bg-wiki.com/bg/Wicce_Attire_Set

**Multi-boxing? (multiple clients on same connection):**
Sometimes

**Steps to reproduce:**

**Any additional information:**

Missing Magic Crit Rate mod and Magic Crit Damage mod.

Possibly other pieces missing mod too.

**Comment by tb1** [comment]
Ohh, in modifiers.h


MAGIC_CRITHITRATE         = 562, // Raises chance to magic crit
MAGIC_CRIT_DMG_INCREASE   = 563, // Raises damage done when criting with magic

Not clue if they are implemented.

**Comment by nfaletra** [comment]
Fixed in the next update.

**Comment by Heepster03** [comment]
Confirmed.
