### ISSUE TITLE
char log into server dont let him log in....

### ISSUE THREAD

**Issue by carlosx41** [HomepointXI/Issues#247]
**Date & Time**: 
17:26 pacf

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**
Narik

**Discord Name (if different from in game):**

EduardoMS

**Nation:**

bastok

**Job(level)/Sub Job(level):**

13drk/06dnc

**NPC or Monster or item Name:**

**Zone name:** 

South Gustabert

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

no

**Steps to reproduce:**

pass the selection screen..... select char and got error 3001
 also on /sea all Narik  char apear online...

**Any additional information:**

**Comment by EpicTaru** [comment]
The session is in a "stuck" status. That will be resolved later when the emergency maintenance occurs unless heep is able to resolve the stuck session prior to the maintenance. Attempts to log in prior to the resolution of the stuck status will not aid in removal of the status. Please be patient and wait for word from an admin or when the maintenance ends, whichever occurs first.

**Comment by Jessland86** [comment]
Server was restarted, they should be unstuck.
