### ISSUE TITLE
Scroll Of Reprisal

### ISSUE THREAD

**Issue by apatrickm** [HomepointXI/Issues#248]
**Date & Time**: 10/10/18

**Client Version (use `/ver` in game):**30180904_0

**Character Name:**Aliron, Wefa, Duirmhuid

**Discord Name (if different from in game):** Aliron

**Nation:**Bastok

**Job(level)/Sub Job(level):**BLU75/DNC37, RDM98/WHM49, PLD75/RDM73

**NPC or Monster or item Name:**Zalif, Scroll Of Reprisal

**Zone name:** Al Zabhi

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**http://homepointxi.com/db/items/4715/scroll_of_reprisal

**Multi-boxing? (multiple clients on same connection):**Yes

**Steps to reproduce:**Go to Zalif to buy the scroll, its not there

**Any additional information:**

**Comment by nfaletra** [comment]
Item was disabled on the vendor because the AHBot sells/buys for a higher price. Removing from the AHBot and adding back to the vendor.
