### ISSUE TITLE
Missing Gil

### ISSUE THREAD

**Issue by Watashi428** [HomepointXI/Issues#249]
**Date & Time**:
10/10/2018

**Client Version (use `/ver` in game):**
30180904_4

**Character Name:**
Watashi
Watashii
Watashiwa
Bokura
Bokurai
Bokurawa

**Discord Name (if different from in game):**
Watashi428

**Nation:**
Bastok

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
Logged into my characters and i am missing all my gil. I know i just got released from jail for attempting to bot for the first time. The gils i had on my account was from legit farming. Also i had 2 char that were not botting and they are also missing gil.

**Comment by nfaletra** [comment]
A consequence of bot farming.
