### ISSUE TITLE
Carpenters gloves drop-_-

### ISSUE THREAD

**Issue by Uzi904** [HomepointXI/Issues#25]
**Date & Time**: 
4/15/18 
2:22pm est

**Client Version (use `/ver` in game):**
30171223_0

**Character Name:** Uzi 

**Discord Name (if different from in game):**Uzi

**Nation:**bastok

**Job(level)/Sub Job(level):**thf99/dnc49

**NPC or Monster or item Name:**
Carpenters Gloves

**Zone name:** Valkrum Dunes

**Coordinates (use `!where`):**
VE spawn area

**Item tool link (for items issues only):** http://homepointxi.com/db/items/14830/carpenters_gloves

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Was clearing dubs run junk items, somehow managed to drop ww gloves instead. Usually kept in mog sack, was my fault, and accidental 

**Any additional information:**

**Comment by Uzi904** [comment]
Dyna run* have screen shot but can’t figure out how to add it on phone.. thanks in advanced

**Comment by Uzi904** [comment]
https://cdn.discordapp.com/attachments/406631963840086019/435143741754441738/image.jpg

**Comment by Heepster03** [comment]
Dropped item was restored.
