### ISSUE TITLE
 Buremte Hat incorrect stats

### ISSUE THREAD

**Issue by kyokofu** [HomepointXI/Issues#250]
**Date & Time**: 
1:36am pdt 10/12/18

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**
Kyokofukada

**Discord Name (if different from in game):**
N/A

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
RDM99/BLM99

**NPC or Monster or item Name:**
Buremte Hat

**Zone name:** 
Northern Sandy

**Coordinates (use `!where`):**
Mog House

**Item tool link (for items issues only):**
https://www.ffxiah.com/item/27767/buremte-hat

**Multi-boxing? (multiple clients on same connection):**
Not at the moment

**Steps to reproduce:**
Magic dmg was less than that of other head pieces with less MAB+ or Magic dmg+. Checked the mods of the item and saw that it was set at Magic dmg+8 instead of +35. It is also missing the +28 EVA and the +4 should go to MDB and not MP Recovered While Healing.

**Any additional information:**

**Comment by nfaletra** [comment]
https://github.com/DarkstarProject/darkstar/pull/5308
