### ISSUE TITLE
Smok acting glitchy

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#252]
**Date & Time**: 10/13/2018

**Client Version (use `/ver` in game):**30180904_0

**Character Name:**Spectre

**Discord Name (if different from in game):**

**Nation:**Windurst

**Job(level)/Sub Job(level):**pld99/dnc49

**NPC or Monster or item Name:**Smok

**Zone name:** Aby attowa

**Coordinates (use `!where`):**@pos -539 -12 -75 215

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**once he starts flying he can still melee attack. Each time he melee attacks he insta warps to the ground, swings, then warps back up in the air.  Also I believe once he is up in the air he stays up.  I had a rdm with me and I THINK if you nuke him enough he comes down, but once he was up in the air he stayed there for pretty much the rest of the fight.

**Comment by EpicTaru** [comment]
Mob doesn't appear to still be exhibiting behaviors stated in this ticket.  Closing.
