### ISSUE TITLE
NM Abyssea Abillity bugged

### ISSUE THREAD

**Issue by tifya** [HomepointXI/Issues#253]
**Date & Time**: 
14:37 EAST 2018-10-13

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**
Nashirok

**Discord Name (if different from in game):**
Tifya

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
99WAR/DNC

**NPC or Monster or item Name:**
Fear Gorta

**Zone name:** 
Abyssea Konschtat

**Coordinates (use `!where`):**
X630 y31 z396 (122)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
NM Using Perdition as only Skill he used but it do death always on each time w/e the damage it does.

**Comment by nfaletra** [comment]
http://ffxiclopedia.wikia.com/wiki/Perdition

Working as intended.

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/46908898-1636dd00-ceef-11e8-8f89-780f034d701a.png)
