### ISSUE TITLE
Gravitic Horn crashes clients

### ISSUE THREAD

**Issue by nfaletra** [HomepointXI/Issues#254]
**Date & Time**: 

**Client Version (use `/ver` in game):**

**Character Name:**

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
Used by Antlion NMs

**Comment by Heepster03** [comment]
Tested with some random mobs doing Gravitic Horn and my client didn't crash. Thus, closing the ticket... should it happen again. Open a new ticket.
