### ISSUE TITLE
Chasseurs Bottes +1 Missing quick draw damage mod

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#256]
**Date & Time**: 10/15/2018

**Client Version (use `/ver` in game):**30180904_0

**Character Name:**Spectre

**Discord Name (if different from in game):**

**Nation:**Windurst

**Job(level)/Sub Job(level):**cor99/dnc49

**NPC or Monster or item Name:**Chasseurs Bottes +1

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**Chasseurs Bottes +1 Is supposed to have +25 quick draw.  The af1 hat has quick draw 10, the mod is 411 which shows up on the mod when you look up the item. ( http://homepointxi.com/db/items/27700/laksamanas_hat_+1 )  But it doesn't show up when you look up Chasseurs Bottles +1 ( http://homepointxi.com/db/items/27444/chasseurs_bottes_+1 )

**Comment by EpicTaru** [comment]
https://github.com/DarkstarProject/darkstar/pull/5326

**Comment by EpicTaru** [comment]
@Heepster03 @Jessland86 This line needs added into item_mods.sql to resolve this issue:

<pre>INSERT INTO `item_mods` VALUES (27444,411,25); -- Quick Draw damage + 25</pre>

**Comment by Heepster03** [comment]
Fixed for next update!

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/136276869-64bbcaa2-6954-4ecf-8fff-c951aaa50d87.png)
This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.
