### ISSUE TITLE
Death Penalty missing mods

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#259]
**Date & Time**: 10/17/2018

**Client Version (use `/ver` in game):**30180904_0

**Character Name:**Spectre

**Discord Name (if different from in game):**

**Nation:**Windurst

**Job(level)/Sub Job(level):**Cor99/dnc49

**NPC or Monster or item Name:**Death Penalty

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:** The 119 weapon is supposed to have     
Quick Draw damage +60%.
Magic Accuracy +60.
Leaden Salute damage +30%.

I know the quick draw mod exists which is 411, not sure about the others.

**Comment by nfaletra** [comment]
It has the weaponskill damage. Quick Draw damage percent can be added. Quick Draw magic accuracy needs to be coded.

411 is Quick Draw base damage, btw. Not the correct mod to use here.

**Comment by nfaletra** [comment]
Added the mods that we have so far. Various versions of Death Penalty were missing mods. Fixed them all.

**Comment by nfaletra** [comment]
Added the last mod with the aftermath rewrite. All fixed now.

**Comment by nfaletra** [comment]
Not no more!
