### ISSUE TITLE
Guild NPC wont take GuildPoint item but still gives the GP(GuildPoint).

### ISSUE THREAD

**Issue by akoocheemoya** [HomepointXI/Issues#26]
**Date & Time**: 2018/4/18

**Client Version (use `/ver` in game):30171205_0

**Character Name:arkoo

**Discord Name (if different from in game):akoocheemoya

**Nation:bastok

**Job(level)/Sub Job(level):

**NPC or Monster or item Name:**

**Zone name:bastok mine alchemists' guild and metalworks' black smith guild ,others dont know,maybe they all have the same problem

**Coordinates (use `!where`):X:117 Y:2 Z:-10(100)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):yes

**Steps to reproduce:**

**Any additional information: its been afew days now, or its a server benifits i dont know b4?

**Comment by akoocheemoya** [comment]
wondering what info was missing?

**Comment by EpicTaru** [comment]
Known DSP issue.

https://github.com/DarkstarProject/darkstar/issues/4559

**Comment by EpicTaru** [comment]
@akoocheemoya The information that was missing was that there wasn't a description about what item(s) was causing your issue.  You've played here long enough and have submitted sufficient issue tickets to know what is required when you submit them.

**Comment by akoocheemoya** [comment]
that didnt come into my mind at all, well i should been look into ...hey ...i have no method to check the similar thing ,how could  youguys find the article about this ? just search, nvm, now i know its a dsp thing , well ,big releave .
