### ISSUE TITLE
Cannot get Ark Pentisphere

### ISSUE THREAD

**Issue by apatrickm** [HomepointXI/Issues#260]
**Date & Time**: October 17, 2018

**Client Version (use `/ver` in game):** 30180904_0

**Character Name:** Aliron, Duirmhuid, Wefa

**Discord Name (if different from in game):**Aliron

**Nation:**Bastok

**Job(level)/Sub Job(level):** THF99/DNC45, PLD99/RDM49, RDM99/WHM49

**NPC or Monster or item Name:**Qu'Hau Spring

**Zone name:** Ro'Meave

**Coordinates (use `!where`):**X 0 Y-29 Z 64(168)

**Item tool link (for items issues only):** 

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** Attempting to trade Parchment and Illuminink to spring durring 100% moon while spring was full, but not getting the ark pentisphere

**Any additional information:** Attempted rezoning, mission log does say ark angels

**Comment by EpicTaru** [comment]
Does Divine Might appear in your Current Outlands quests?
 
`Enter the Shrine of Ru'Avitau from the south entrance.
After arriving in Ru'Aun Gardens, take the center portal to the main island. Travel straight to the center of the island. Straying too far to either side aggros the Groundskeepers.
Examine the unmarked target on the wall directly in front of you.
"Divine Might" now appears in the "Outlands" section of your current quests.`

**Comment by apatrickm** [comment]
The mission is active, but the quest wasn't, had to check the wall a second time to get quest. Going to try trade again

**Comment by apatrickm** [comment]
Trade worked thank you for the help :)
