### ISSUE TITLE
Weapon missing stats

### ISSUE THREAD

**Issue by tifya** [HomepointXI/Issues#264]
**Date & Time**: 
2018-10-19

**Client Version (use `/ver` in game):**
3018904_0

**Character Name:**
Nashirok

**Discord Name (if different from in game):**
Tifya

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
WAR99/DNC49

**NPC or Monster or item Name:**
Craft AXE

**Zone name:** 
North Sandy

**Coordinates (use `!where`):**
 X72-Y0-Z-8 (38)

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/21708/beryllium_pick
http://ffxidb.com/items/21708

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
Its have no stats and isnt have a weapon skin cant be equip in 1 hand .
I have been able to get the weapon crafted just wanted to use it if possible : )
Berylium is a good set of weaponry maybe coding them all would be nice for everyone for a new kind of weapon craftable need farming item NM for get mats :) was good game !

**Comment by Heepster03** [comment]
I don't forsee this being actually implemented for awhile. It's better than Blurred Axe/+1 and Afterglow 119 Gutler. I'm afraid that you're going to have to wait until it can be properly added.

**Comment by tifya** [comment]
hmm ic maybe just input the axe usable w/o the stats i could have not done all this work for nothing -.-

**Comment by Heepster03** [comment]
For the time being, these recipes have been disabled due to the weapons being better than REM for us at the current time. Going to close the issue.
