### ISSUE TITLE
Krousis Ring +1 isnt working into Maat augment

### ISSUE THREAD

**Issue by tifya** [HomepointXI/Issues#266]
**Date & Time**: 
23:21 PM Est

**Client Version (use `/ver` in game):**

**Character Name:**
Nashirok

**Discord Name (if different from in game):**
Nashirok-tiyfa

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
I wanna know if we could input the Krousis ring + 1 into the maat augment too plz I got one and I cant update it.

**Comment by nfaletra** [comment]
No. That’s not how it works.
