### ISSUE TITLE
Item switch from character

### ISSUE THREAD

**Issue by tifya** [HomepointXI/Issues#267]
**Date & Time**: 
23:23

**Client Version (use `/ver` in game):**

**Character Name:**
Nashirok and Tifya

**Discord Name (if different from in game):**
nashirok-tifya

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/20762/ukudyoni

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
http://homepointxi.com/db/items/20762/ukudyoni
I got this drop on my Tifya I can give picture of my player name and the item on me just wanna know if you could get it on my main character nashirok. Ty

**Comment by Heepster03** [comment]
We don't transfer gear between characters. You'd have to obtain the drop again.
