### ISSUE TITLE
Bugged: Crafting Guild Test 98-100

### ISSUE THREAD

**Issue by neoffxi** [HomepointXI/Issues#268]
**Date & Time**: 
10/20/2018

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**
Neomorpheus

**Discord Name (if different from in game):**
Neo

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
99 PLD / 49 WAR

**NPC or Monster or item Name:**
Faulpie (Leathercrafting) - South Sandy (D-8) 
Reinberta (Goldsmithing) - Bastok Market (H-8)
Cheupirudaux (Woodworking) - North Sandy (F-3)

**Zone name:** 
Faulpie (Leathercrafting) - South Sandy (D-8) 
Reinberta (Goldsmithing) - Bastok Market (H-8)
Cheupirudaux (Woodworking) - North Sandy (F-3)

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
Urja Trousers (Leathercrafting)
Evader Earring (Goldsmithing)
Vejovis Wand (Woodworking)

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
1. The three (3) crafts listed above are stuck at 100 (Veteran).
2. I tried repeatedly to talk and trade the guild test items to the corresponding NPCs.
3. All instances the NPCs mention a [blank] item to make instead of the actual guild test items.
4. Trading the guild test items doesn't do anything.
5. I was able to go over 100 (Expert) with Clothcrafting since the NPC didn't bugged and allowed me to trade a Swith Cape.
6. See screenshots.

**Any additional information:**
I know in retail you need to have a guild KI in addition to the guild test item, but I was told you don't need it here at HomePoint (also I was able to advance clothcrafting without the KI). 

Is there something I am missing?

**Comment by neoffxi** [comment]
![neomorpheus_2018 10 20_230949](https://user-images.githubusercontent.com/34224364/47262926-14f34a80-d4c3-11e8-9425-73a8476fee06.png)
![neomorpheus_2018 10 20_231012](https://user-images.githubusercontent.com/34224364/47262927-14f34a80-d4c3-11e8-8d0b-a6ff39196e75.png)
![neomorpheus_2018 10 20_233322](https://user-images.githubusercontent.com/34224364/47262928-14f34a80-d4c3-11e8-87a1-de5408286925.png)
![neomorpheus_2018 10 20_233716](https://user-images.githubusercontent.com/34224364/47262929-14f34a80-d4c3-11e8-8d16-33f45c50fa09.png)
![neomorpheus_2018 10 20_235155](https://user-images.githubusercontent.com/34224364/47262931-2c323800-d4c3-11e8-91b0-106d953cfb9c.png)

**Comment by Jessland86** [comment]
Hotfixed.
