### ISSUE TITLE
Savas Jawshan, armor drop from PW has missing/messed up mods

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#269]
**Date & Time**: 10/20/2018

**Client Version (use `/ver` in game):**30180904_0

**Character Name:**Spectre

**Discord Name (if different from in game):**

**Nation:**Windurst

**Job(level)/Sub Job(level):**war99/dnc49

**NPC or Monster or item Name:**Savas Jawshan
http://homepointxi.com/db/items/27862/savas_jawshan

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**Savas Jawshan is missing the -5 magic damage mod, also randomly has ranged attack -13 which it shouldn't have.  Everything else seems to be fine.

**Comment by spectre99** [comment]
http://homepointxi.com/db/items/27862/savas_jawshan

**Comment by nfaletra** [comment]
Mods fixed
