### ISSUE TITLE
Password Reset Request: friend of mine forgot his password ,please help him reset them .

### ISSUE THREAD

**Issue by akoocheemoya** [HomepointXI/Issues#27]
**Date & Time**: 2018\4\18

**Client Version (use `/ver` in game):**30171205_0

**Character Name: Free    Espritoice   Miaomiao     Xiaolaodi    Kulang 

**Discord Name (if different from in game): akoocheemoya (he dont speak english i have to do it for him.)

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):yes

**Steps to reproduce:**

**Any additional information:   mailaddress of char is 136320151@qq.com, please help, many thx!

**Comment by EpicTaru** [comment]
@akoocheemoya Your friend needs to submit the ticket themselves.
