### ISSUE TITLE
HELM Issue: Logging points not respawning

### ISSUE THREAD

**Issue by neoffxi** [HomepointXI/Issues#271]
**Date & Time**: 
10/22/2018

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**
Neofour and Neotwo

**Discord Name (if different from in game):**
Neo

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
99 RDM / 49 BLM

**NPC or Monster or item Name:**
Kapor Log

**Zone name:** 
Yhoatar and Yuhtunga Jungle

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
1. Visit all logging points in each zone, and log them.
2. After the logging point disappears, it can respawn to a new location.
3. At most, it moved to a new location thrice.
4. After this initial cycle, no more logging points respawn (waited hours and checked again the next day).
5.  Logging points only respawn after a server crash.

**Any additional information:**

**Comment by nfaletra** [comment]
DSP recently rewrote/refactored the HELM systems. Merge is complete. Should be fixed in the next update.
