### ISSUE TITLE
ammo: crossbow bolt

### ISSUE THREAD

**Issue by Fiddler-Cerberus** [HomepointXI/Issues#273]
**Date & Time**: 
10/24/18 

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**
Rynn

**Discord Name (if different from in game):**
Fiddler

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
Thief 12

**NPC or Monster or item Name:**
Crossbow bolt

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/17336/crossbow_bolt

**Multi-boxing? (multiple clients on same connection):**
Yes.

**Steps to reproduce:**

**Any additional information:**
Listed through item tool as WAR/DRK/RNG - in-game as available to all jobs

**Comment by nfaletra** [comment]
https://github.com/DarkstarProject/darkstar/pull/5527

**Comment by Jessland86** [comment]
Fixed in today's maintenance.
