### ISSUE TITLE
Unable to continue past ZM 4 

### ISSUE THREAD

**Issue by Kazatar** [HomepointXI/Issues#274]
**Date & Time**: 
oct 25 2018 651 est

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**
Kazatar

**Discord Name (if different from in game):**

**Nation:**
Windurst rank 6

**Job(level)/Sub Job(level):**
99thf/49dnc

**NPC or Monster or item Name:**
Jakih wahcondalo

**Zone name:** 
Kazham

**Coordinates (use `!where`):**
x:99 y:-15 z:-112

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
Started ws trial for dagger not knowing that evisceration didnt work on hp server 

**Any additional information:**
cant do Zm's till it gets removed from my quest log or ws gets put into hp

**Comment by Kazatar** [comment]
sorry misspelling on npc name Jakoh Wahcondalo

**Comment by Kazatar** [comment]
And another mistake found sorry guys its zm 3

**Comment by Heepster03** [comment]
Sounds like you'll need to finish the dagger trial quest to obtain Evisceration before you can continue.

**Comment by Kazatar** [comment]
Good thing you know that it broken on this server if your not a gm dont comment

**Comment by Heepster03** [comment]
The trial quests actually do work and rofl... I'm one if the two main Admin. Good try tho.

**Comment by Kazatar** [comment]
Lol I just seen that but the ??? Arnt at the spot ive looked 5 times

**Comment by Kazatar** [comment]
I will look again but if not you can cone in game and show me where they are cause they not atcthe spot ok?
