### ISSUE TITLE
Missing Mods: Assiduity Pants +1

### ISSUE THREAD

**Issue by neoffxi** [HomepointXI/Issues#276]
**Date & Time**: 
10/29/2018

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**
Neotwo

**Discord Name (if different from in game):**
Neo

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
SMN 99 / RDM 49

**NPC or Monster or item Name:**
Assiduity Pants +1

**Zone name:** 
n/a

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**
http://www.homepointxi.com/db/items/28135/assiduity_pants_+1

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
The mod for perpetuation cost needs to be added.
(346): (SMN) Perpetuation Reduction (Gear) 3

**Any additional information:**

**Comment by nfaletra** [comment]
Added
