### ISSUE TITLE
Jail

### ISSUE THREAD

**Issue by Mandefresh** [HomepointXI/Issues#277]
**Date & Time**: 
10/29/18

**Client Version (use `/ver` in game):**
Version 30180801_2

**Character Name:**
Xcaliber

**Discord Name (if different from in game):**
Xcaliber

**Nation:**
Sandoria

**Job(level)/Sub Job(level):**
99mnk/49dnc

**NPC or Monster or item Name:**
N/A

**Zone name:** 
N/A

**Coordinates (use `!where`):**
N/A

**Item tool link (for items issues only):**
N/A

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
N/A

**Any additional information:**
Jailed, friend used account. PW and Info has been changed, won't happen again.

**Comment by nfaletra** [comment]
@Mandefresh Can you login?

**Comment by Mandefresh** [comment]
Yes, i can. I just logged on.
