### ISSUE TITLE
Tyrfing missing addionnal effect 

### ISSUE THREAD

**Issue by tifya** [HomepointXI/Issues#279]
**Date & Time**: 
2018-10-30

**Client Version (use `/ver` in game):**

**Character Name:**
Nashirok

**Discord Name (if different from in game):**
Nashirok

**Nation:**
Sandy

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/16540/tyrfing

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
Weapon is Tyrfing sword lv 78 its missing -- Additional effect: Damage varies with MP

**Comment by nfaletra** [comment]
Added
