### ISSUE TITLE
My LS friend lost PASSWORD

### ISSUE THREAD

**Issue by qiganggang** [HomepointXI/Issues#28]
**Date & Time**: 30171205_0

**Client Version (use `/ver` in game):**Free

**Character Name:**Free

**Discord Name (if different from in game):**
Qigang

**Nation:**
bastok

**Job(level)/Sub Job(level):**BLU99/RDM49

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**  lost all password  
ID
a1230456
aa1230456
jlhejingyao0
jlhejingyao1
jlhejingyao2
jlhejingyao

**Comment by qiganggang** [comment]
yes me is  china LS Boss

**Comment by qiganggang** [comment]
LS friend tell me find GM help

**Comment by jlhejingyao0** [comment]
please help me recover my chars      136320151@qq.com

**Comment by jlhejingyao0** [comment]
please help me reset my acc's password.   136320151@qq.com

**Comment by EpicTaru** [comment]
This ticket is being closed because the issue is not related to the person that submitted the ticket. 

@jlhejingyao0 Please submit an issue yourself for this password reset request.
