### ISSUE TITLE
Toreadors Cape (Item Id: 15465) - Item quantity on AH does not match on Item DB

### ISSUE THREAD

**Issue by munkee128** [HomepointXI/Issues#280]
**Date & Time**: 

10/31/2018 8:33 am PST

**Client Version (use `/ver` in game):**

30180904_0

**Character Name:**

Munkee

**Discord Name (if different from in game):**

Munkee128

**Nation:**

Any

**Job(level)/Sub Job(level):**

Any

**NPC or Monster or item Name:**

Toreadors Cape (Item Id: 15465)

**Zone name:** 

Any

**Coordinates (use `!where`):**

Any

**Item tool link (for items issues only):**

http://www.homepointxi.com/db/items/15465/toreadors_cape

**Multi-boxing? (multiple clients on same connection):**

Yes

**Steps to reproduce:**

AH (!AH => Bid => Armor => Back) shows 0, so you can't Bid on anything
Item DB shows Current stock: 1

**Any additional information:**

Same issue as #258

**Comment by EpicTaru** [comment]
Fixed, In game AH and Item Tool displays correctly.
