### ISSUE TITLE
Andreas - WW Guild Point NPC - not taking item for trade

### ISSUE THREAD

**Issue by munkee128** [HomepointXI/Issues#281]
**Date & Time**: 11/1/2018 - 8:22 AM

**Client Version (use `/ver` in game):**   30180904_0

**Character Name:**   Munkee

**Discord Name (if different from in game):**  Munkee128

**Nation:** Windy

**Job(level)/Sub Job(level):**   THF99/DNC49

**NPC or Monster or item Name:**  
NPC:  Andreas
ID: 17723628
Index: 236

**Zone name:**  Northern San D'Oria

**Coordinates (use `!where`):**  Andreas is at -189,282, 11,000, 262.626

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** 

Currently trade-in item is "Flute". Tried to trade him a "Flute +1" but I get no dialogue and no points given. Trade fast enough I get a command error (picture below)

**Any additional information:**
![image](https://user-images.githubusercontent.com/10692407/47861415-0274ed00-ddb0-11e8-8ee4-0e68f091c586.png)

**Comment by munkee128** [comment]
Addendum:
After a light bulb came on in my head... I decided to craft a NQ Flute (managed to get a couple Flute +2 when trying for NQ) and that worked.
In summary:
Flute - works
Flute +1 AND Flute +2 - does not work

**Comment by Heepster03** [comment]
![image](https://user-images.githubusercontent.com/8421725/129252491-2c506678-8e92-4f3e-8da7-aaf72bee6363.png)

These are the only two flutes that are available to be traded in for GP. Flute, Flute+1, and Flute+2 are not in the list. Which makes sense as Flute is just buyable from the NPC for cheap.

Closing ticket.
