### ISSUE TITLE
Enhances "Quick Draw" Effect on Death Penalty Weapons (COR Mythic Weapon) doesn't work

### ISSUE THREAD

**Issue by kyokofu** [HomepointXI/Issues#282]
**Date & Time**: 
11/2/2018 3:06pm pdt

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**
Kyokofukada

**Discord Name (if different from in game):**
N/A

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
99COR/49BLM

**NPC or Monster or item Name:**
Death Penalty

**Zone name:** 
Any Combat Zones

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
https://www.ffxiah.com/item/21263/death-penalty

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**
Used quick draw with weapon and without weapon and dmg was not significantly different. Only tried on the i119 but I assumed the others aren't working as well.

**Any additional information:**
On BGwiki, it states that the effect is +60% dmg and +60 magic acc.

**Comment by EpicTaru** [comment]
https://github.com/HomepointXI/Issues/issues/259
