### ISSUE TITLE
Ranged Items/ Varying Glitches

### ISSUE THREAD

**Issue by akahrimirai** [HomepointXI/Issues#283]
**Date & Time**: 
11/03/2018 at 4:30PM

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**
Akahri

**Discord Name (if different from in game):**
miraikari

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
99 THF / 49 DNC

**NPC or Monster or item Name:**
n/a

**Zone name:** 
n/a

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
Currently on THF, was going to skill up marksmanship, so i equipped "Staurobow"(xbow) with "Crossbow Bolts" but the bolts did not want to equip(they are for all jobs level 1). Then i tried to equip "Culverin"(gun) with "Bullet" and you can equip gun but when you equip bullets, it takes gun off, vice versa. I have not tried other bolts on THF, only available from AH. I have not tested other jobs, but this is glitched for THF as of now. (Unless i'm just having a 'duh' moment ;_; )

Straurobow (Lv. 74 war/thf/drk/rng )
Crossbow Bolts (Lv. 1 all)
Culverin (Lv. 73 thf/rng)
Bullet (Lv. 22 thf/rng/nin/cor)

**Any additional information:**
None at this time. I have skilled up to 102 on RNG, was just trying on THF and had this result. Thank you for your time.

**Comment by Jessland86** [comment]
https://github.com/HomepointXI/Issues/issues/273

**Comment by nfaletra** [comment]
Crossbow Bolts were recently updated on retail to be equippable for all jobs. They were not previously equippable by THF. The equip flags haven’t been updated yet.

**Comment by Jessland86** [comment]
Culverin is a cannon type gun, as such you can only use Cannon shells or Heavy shells with it.

**Comment by Jessland86** [comment]
https://ffxiclopedia.fandom.com/wiki/Cannon_Shell
https://ffxiclopedia.fandom.com/wiki/Heavy_Shell
