### ISSUE TITLE
Mob: Dirtyhanded Gochakzuk - too high of a level, Windy 8-1 NM

### ISSUE THREAD

**Issue by munkee128** [HomepointXI/Issues#285]
**Date & Time**:  11/4/2018 at 01:45 AM

**Client Version (use `/ver` in game):**    30181003_1

**Character Name:**   Munkee

**Discord Name (if different from in game):**  Munkee128

**Nation:**   Windy

**Job(level)/Sub Job(level):**   THF99/DNC49

**NPC or Monster or item Name:**  Dirtyhanded Gochakzuk
http://www.homepointxi.com/db/monsters/17387945/Dirtyhanded%20Gochakzuk

**Zone name:**   Davoi

**Coordinates (use `!where`):**  not in-game atm, will update tomorrow (sleepy)

**Item tool link (for items issues only):**    N/A

**Multi-boxing? (multiple clients on same connection):**   Yes

**Steps to reproduce:**   Engaged NM, found out it was harder than expected

**Any additional information:**   Immortality asked me to open a ticket.

**Comment by nfaletra** [comment]
Dropped his level back to retail 71.

**Comment by nfaletra** [comment]
Try punching him now.
