### ISSUE TITLE
Blurred Harp Image ID

### ISSUE THREAD

**Issue by Uzi904** [HomepointXI/Issues#286]
**Date & Time**: 6:04pm est 10/4/18

**Client Version (use `/ver` in game):**

**Character Name:** Hendrix

**Discord Name (if different from in game):**N/A

**Nation:** Windurst

**Job(level)/Sub Job(level):**
BRD99/Whm49

**NPC or Monster or item Name:**
Blurred Harp

**Zone name:** 
N/A

**Coordinates (use `!where`):**
N/A

**Item tool link (for items issues only):** 
http://homepointxi.com/db/items/21400/blurred_harp

**Multi-boxing? (multiple clients on same connection):** N/A

**Steps to reproduce:**
Wrong Image ID

**Any additional information:**

**Comment by Heepster03** [comment]
Fixed in next update!

**Comment by EpicTaru** [comment]
This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.
