### ISSUE TITLE
kukulkan failed to drop any fangs

### ISSUE THREAD

**Issue by lonleyhero** [HomepointXI/Issues#287]
**Date & Time**: 

11/5/18 11:39:46 AM EST

**Client Version (use `/ver` in game):**

30180904_0

**Character Name:**

lonehero

**Discord Name (if different from in game):**

lonelyhero

**Nation:**

bastok

**Job(level)/Sub Job(level):**

thf99/dnc49

**NPC or Monster or item Name:**

Kukulkans Fang

**Zone name:** 

abyssea konschtat

**Coordinates (use `!where`):**

X-23 Y67 Z562 (108)

**Item tool link (for items issues only):**

http://homepointxi.com/db/items/2932/kukulkans_fang

**Multi-boxing? (multiple clients on same connection):**

yes

**Steps to reproduce:**
farming kukulkan fangs for ochain had one just now that didn't drop a fang at all even tho it should drop one 100% of the time

**Any additional information:**

**Comment by nfaletra** [comment]
Drops aren't setup in groups for a lot of abyssea mobs. If a bunch of shit drops before it gets to the fangs, and the drop limit is hit, nothing else will drop. Fixing these mobs has been an ongoing process. A bunch will be fixed with today's maintenance.

**Comment by lonleyhero** [comment]
ah ok so just shit luck on drop order then lol good to know its a known issue thats being worked on thanks aut

**Comment by nfaletra** [comment]
Grouped drops for all NMs in Abyssea - La Theine and Abyssea - Konschtat

**Comment by nfaletra** [comment]
Grouped drops fix this issue. He can't drop more than 10 things at once now.
