### ISSUE TITLE
Azdaja not spawning

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#288]
**Date & Time**: 
11/5

**Client Version (use `/ver` in game):**

30181003_1

**Character Name:**

agnes

**Discord Name (if different from in game):**

**Nation:**

windy

**Job(level)/Sub Job(level):**

blm

**NPC or Monster or item Name:**

azdaja
**Zone name:** 

abyssea grauberg

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

yes

**Steps to reproduce:**

azdaja won't spawn at any of his 3 ??? after popping him 3 times, once at each ???
The message upon attempting to pops says I don't have KI, I have the KI and can't pop with any character
**Any additional information:**

**Comment by stevomatic** [comment]
yeah sorry i was distracted, in case you're still wondering,
popped it in normal spot
2nd time my normal spot didn't work so I tried a second ??? and that worked
3rd time neither of the first 2 ??? worked so I popped at the 3rd
after that none of them worked

**Comment by Oderson** [comment]
Sedna is behaving the same way.

**Comment by nfaletra** [comment]
It’s all Abyssea NMs. Looking into it.

**Comment by stevomatic** [comment]
yeah he popped that time
