### ISSUE TITLE
QUICK_DRAW_DMG_PERCENT Borked

### ISSUE THREAD

**Issue by tb1** [HomepointXI/Issues#289]
**Date & Time**: 
Today

**Client Version (use `/ver` in game):**
Not in game

**Character Name:**
Tbone

**Discord Name (if different from in game):**
Cornholio

**Nation:**
Canada

**Job(level)/Sub Job(level):**
Unemployed

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/21263/death_penalty

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

Unknown Mod (834) 60
QUICK_DRAW_DMG_PERCENT mod incorrectly implemented.

I'd tell you how to fix it aut, but you'll get mad at me.  (assuming HP is running the DSP code)

hint #1: https://github.com/DarkstarProject/darkstar/blob/08f7115f028376eb4db577c465fc9cfc89abdeb7/scripts/globals/abilities/fire_shot.lua#L29

hint #2: https://www.lua.org/pil/3.5.html

Please don't hit me.

**Comment by nfaletra** [comment]
You're going to have to be more specific. Are you implying that the math is wrong? Just saying it's borked doesn't tell me shit, man.

**Comment by nfaletra** [comment]
If the math is wrong, that's fine. If you know what the math should be, say so and cite a source like bg-wiki or something so I can verify. Otherwise I have to over-explain a fix to DSP.

**Comment by tb1** [comment]
You always get mad when I tell you what to do.

    local dmg = (2 * player:getRangedDmg() + player:getAmmoDmg() + player:getMod(dsp.mod.QUICK_DRAW_DMG)) * 1 + player:getMod(dsp.mod.QUICK_DRAW_DMG_PERCENT)/100


should be

    local dmg = (2 * player:getRangedDmg() + player:getAmmoDmg() + player:getMod(dsp.mod.QUICK_DRAW_DMG)) * (1 + player:getMod(dsp.mod.QUICK_DRAW_DMG_PERCENT)/100)


(notice the extra parenthesis)

**Comment by nfaletra** [comment]
thanks. The base damage is calculate wrong, too. You missed that part. It only multiples the weapon damage by 2. Should be (weapon + ammo) * 2. The whole thing is wrong.

**Comment by tb1** [comment]
I didn't know it was suppose to be (weapon+ammo)*2, I just noticed the percentage was almost right, if you don't know correct order-of-operations.

Its like that for all of the QD shots too.

**Comment by tb1** [comment]
I also opened it here instead of DSP incase you already fixed it and the issue was something different, and that you can bring up shit to DSP easier and faster, and not have to wait 4 months and an arguments of order of operations to get it fixed :-P

**Comment by nfaletra** [comment]
https://github.com/DarkstarProject/darkstar/pull/5409

* Fixed the damage calc
* Properly ignores shadows
* Doesn't feed target TP
* Also added quick draw magic accuracy mod to death penalty

**Comment by nfaletra** [comment]
DO THE MATH!
