### ISSUE TITLE
Nyzul 99 Armor npc not taking items

### ISSUE THREAD

**Issue by salazer** [HomepointXI/Issues#290]
**Date & Time**: 
11/5
6:45 pm est

**Client Version (use `/ver` in game):**
30191003_1

**Character Name:**
Emel

**Discord Name (if different from in game):**

**Nation:**
Bastok

**Job(level)/Sub Job(level):**

Blue99/Rdm49

**NPC or Monster or item Name:**

Mrohk Sahjuuli
Item: Denali Jacket

**Zone name:** 
Aht Urhgan Whitegate 

**Coordinates (use `!where`):**

 I-11
**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

yes

**Steps to reproduce:**

I traded all item together, 1 by 1, and other combo's Npc wont take items
Items: Denali Jacket, 5 Imp. Gold Coins, 8 Snowsteel Ores

**Any additional information:**

**Comment by nfaletra** [comment]
Don't see anything obviously wrong with the script. I'll test it out soon.
