### ISSUE TITLE
ironclad smiter/abyssea

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#291]
**Date & Time**: 

11/5

**Client Version (use `/ver` in game):**

30181003_1

**Character Name:**
agnes

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**
blm

**NPC or Monster or item Name:**

ironclad smiter

**Zone name:** 

abyssea altep

**Coordinates (use `!where`):**
-744 -16 -696 207

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

yes
**Steps to reproduce:**
trading tablilla mercury and smoldering arm won't pop the mob, it popped once and second pop it broke

**Any additional information:**

**Comment by nfaletra** [comment]
Got a fix in. Just need to get it pulled and the file reloaded. Should be able to do it without a server restart. We'll close the ticket when it's in.

To avoid breaking other trades, don't examine the ???. That's the part that breaks it.

**Comment by Jessland86** [comment]
Hotfixed.
