### ISSUE TITLE
Voidwatch access

### ISSUE THREAD

**Issue by Watashi428** [HomepointXI/Issues#292]
**Date & Time**:
11/6/2018

**Client Version (use `/ver` in game):**
30181003_1

**Character Name:**
Watashi
Watashii
Watashiwa
Bokura
Bokurai
Bokurawa

**Discord Name (if different from in game):**
Watashi

**Nation:**
Bastok
Bastok (s)

**Job(level)/Sub Job(level):**
99 thf/49 dnc

**NPC or Monster or item Name:**
Voidwatch Officer

**Zone name:** 
Bastok Market (S)

**Coordinates (use `!where`):**
X:-248 Y:0 Z:72 (181)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Tried with Muli-boxing and tried Solo.

**Steps to reproduce:**

**Any additional information:**
I completed the requirements on the Homepointxi:
In order to participate in Voidwatch, you must satisfy the following conditions:

Be level 75 or higher.
Possess an Adventurer's Certificate (You Must be Rank 3 or higher.)
Join a city in the past by completing one of these quests:
The Fighting Fourth (start NPC is Adelbrecht in Bastok Markets (S) at (E-8))

I have completed "The Fighting Fourth" and the next two quest. I am on Mission Cait Sith. When i speak with the Voidwatch Officer nothing happens. I cannot get the Indigo stratum abyssite.

**Comment by spectre99** [comment]
Are you talking to them in the past or present? Because you get the stratum abyssites from the guys in the present.

**Comment by Watashi428** [comment]
oh.. sorry. Thanks!
