### ISSUE TITLE
IxDrk Issue: ??? not spawning

### ISSUE THREAD

**Issue by neoffxi** [HomepointXI/Issues#293]
**Date & Time**: 
11/06/2018

**Client Version (use `/ver` in game):**
30181003_1

**Character Name:**
Neommule

**Discord Name (if different from in game):**
Neo

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
PLD 99 / THF 49

**NPC or Monster or item Name:**
IxDrk

**Zone name:** 
The Garden of Ru'Hmet

**Coordinates (use `!where`):**
!pos -600 5.00 440 35
!pos -240 5.00 440 35
!pos -280 5.00 240 35
!pos -561 5.00 237 35

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
1. Check all quadrants for the ??? related to IxDrk.
2. Repeatedly check for 30 minutes all 4 possible spawn locations,

**Any additional information:**
The ??? for IxDrk is not spawning.
You can also verify with /watchdog track 452.

**Comment by nfaletra** [comment]
Should be working now.
