### ISSUE TITLE
Prishe not reforging

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#294]
**Date & Time**: 

11/6

**Client Version (use `/ver` in game):**

30181003_1

**Character Name:**

Sonic

**Discord Name (if different from in game):**

**Nation:**

windy

**Job(level)/Sub Job(level):**

sch

**NPC or Monster or item Name:**

prishe

**Zone name:** 

abyssea empyreal paradox

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
trading savant's bonnet +2 and 30 cirein lanterns not returning the arbatel head piece

**Any additional information:**

**Comment by Heepster03** [comment]
When you talk to her, does she tell you that any titles are missing?

**Comment by stevomatic** [comment]
nope, also I've already turned in other scholar pieces and upgraded

**Comment by nfaletra** [comment]
Inventory isn’t full and you don’t already have the item?

**Comment by stevomatic** [comment]
no

**Comment by nfaletra** [comment]
Fix incoming.

**Comment by stevomatic** [comment]
![tc2](https://user-images.githubusercontent.com/26309049/48110996-53a43700-e21d-11e8-9604-62e54465f725.jpg)

**Comment by Heepster03** [comment]
Try it now.

**Comment by nfaletra** [comment]
Confirmed fixed.
