### ISSUE TITLE
wrong text while recieving items from maat and renik

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#295]
**Date & Time**: 11/7/2018

**Client Version (use `/ver` in game):**30180904_0

**Character Name:**Spectre

**Discord Name (if different from in game):**

**Nation:**Windurst

**Job(level)/Sub Job(level):**pld99/dnc49

**NPC or Monster or item Name:**Renik and Maat

**Zone name:** upper jeuno and rulude gardens

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**When I turned in the items to get taeon gloves instead of a text showing me receiving the item instead it showed a text line saying 'tallying conquests results' same thing happened for the first 2 level cap quests with maat, got the item but received message saying tallying conquest results.

**Comment by nfaletra** [comment]
Hotfixed
