### ISSUE TITLE
Promyvion - Vazhl broken

### ISSUE THREAD

**Issue by Wildella** [HomepointXI/Issues#296]
**Date & Time**: 
11/9/2018 4:00am est

**Client Version (use `/ver` in game):**
30181003_1

**Character Name:**
Wildella

**Discord Name (if different from in game):**

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
Blm 99/rdm 49

**NPC or Monster or item Name:**

**Zone name:** 
Promyvion-Vazhl 

**Coordinates (use `!where`):**
First island

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Kill memory receptacles and spawn adds

**Any additional information:**
I killed the memory receptacles and the adds that spawned and on the last one the teleporter did not work to go to the next island.

**Comment by spectre99** [comment]
I've had this happen from time to time, not on Vahzal but on the mea/holla/dem ones.  Also I just wanted to add in case you didn't try this already, but each floor can have up to multiple memory receptacles, only one is actually the teleporter, if you kill one of the fake ones then the telepoter won't appear until you kill the right one.

**Comment by nfaletra** [comment]
onRegionEnter is looking for memory stream IDs in the wrong table and crashing the script. Fix incoming.
