### ISSUE TITLE
wrong text for certain ??? and NPCs

### ISSUE THREAD

**Issue by Fiddler-Cerberus** [HomepointXI/Issues#297]
**Date & Time**: 
11/9/18 

**Client Version (use `/ver` in game):**
30181003_1

**Character Name:**
Fiddler

**Discord Name (if different from in game):**

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
PLD/DNC

**NPC or Monster or item Name:**
Cletae, Visala, possibly other guild merchants

**Zone name:** 
Southern San d'Oria
Bastok Markets
Dynamis - Bastok

**Coordinates (use `!where`):**
X:-189 Y:-8 Z:14 (6)
X:-202 Y:-6  Z:-59 (232)
??? after defeating Dynamis - Bastok boss (KI still received)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No.

**Steps to reproduce:**
- talk to NPC

**Any additional information:**
Certain ???s and NPC give wrong text when spoken to:
Cletae : "The San d'Oria residential area is ahead. You'll find your Mog House within."
Visala : "A mog tablet has been found in West Ronfaure !" 
Dynamis - Bastok ??? : "A mog tablet has been discovered in  !"

**Comment by spectre99** [comment]
Meriri - Store npc in windy woods, message given "tallying conquest results" when you try to buy something.

**Comment by nfaletra** [comment]
Fixed 40+ custom shop npcs.

Not sure about that dynamis bastok one. That script looks fine.

**Comment by nfaletra** [comment]
Talked to a few of the NPCs. All fixed.
