### ISSUE TITLE
Bloodpact in bc60 seems to crash server

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#299]
**Date & Time**: 
11/10

**Client Version (use `/ver` in game):**
30181003_1

**Character Name:**
agnes

**Discord Name (if different from in game):**

**Nation:**

windy

**Job(level)/Sub Job(level):**

99smn/blm

**NPC or Monster or item Name:**

Jungle Boogeymen bc60

**Zone name:** 
sacrificial chamber

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**
server crashed 2 for 2 when I used thunderspark bloodpact in jungle boogeymen

**Any additional information:**

**Comment by EpicTaru** [comment]
Copy, thanks.  Please don't use that again until informed.

**Comment by nfaletra** [comment]
Killing any tonberries with SMN AoE can crash the server. Please avoid this for the time being.

**Comment by nfaletra** [comment]
I'll be your null.
