### ISSUE TITLE
NPC issue

### ISSUE THREAD

**Issue by Willthefluteboy** [HomepointXI/Issues#3]
**Date & Time**: 03/12/2018 2:38 ET

**Client Version (use `/ver` in game):** 30180203_1

**Character Name:** Reon

**Nation:** Sandy

**Job(level)/Sub Job(level):** BLM 33 / WHM 16

**NPC or Monster or item Name:** Tahmasp

**Zone name:** Pashhow Marshlands

**Coordinates (use `!where`):** X:536 Y:24  Z:694 (127)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:** Go to location.

**Any additional information:** NPC Spawned two character models but only one target

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/37499047-c9a67276-288f-11e8-9263-065f0423d36a.png)

Personal server version: 30170707_0

FFXI Client version: 30171223_0

NPC displays correctly.  Don't be hating my server version, lol, I haven't gotten around to updating it yet!

**Comment by Heepster03** [comment]
![halkuras_2018 04 17_095549](https://user-images.githubusercontent.com/8421725/38878027-a3f2f73e-4225-11e8-882a-dab0cc3a7154.png)

After the maintenance, all appears to be working as intended.
