### ISSUE TITLE
WW Guild NPC broken - wrong text, wrong guild points

### ISSUE THREAD

**Issue by munkee128** [HomepointXI/Issues#300]
**Date & Time**: 
11/13/2018 ; 5:51 PM PST

**Client Version (use `/ver` in game):**
30181103_0

**Character Name:**
Munkee

**Discord Name (if different from in game):**
Munkee128

**Nation:**
Windy

**Job(level)/Sub Job(level):**
THF99/DNC49

**NPC or Monster or item Name:**
Andreas

**Zone name:** 
Northern San D'oria

**Coordinates (use `!where`):**
X:-188 Y:11 Z:263 (105)

**Item tool link (for items issues only):**
N/A

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**
Today's item was Willow Wand. Bought 4 off AH, tried to trade 1, got 0 points. Tried to trade multiple times with the same text of 0 points (images attached).
Saw that my GP jumped from 35000 to 99000.

**Any additional information:**
![image](https://user-images.githubusercontent.com/10692407/48454732-52b75c00-e76d-11e8-8464-3f7a88e24f84.png)

![image](https://user-images.githubusercontent.com/10692407/48454799-9f9b3280-e76d-11e8-89a3-624fd1ae1a15.png)

**Comment by munkee128** [comment]
Addendum:
So, NPC did NOT take my Willow Wand but still awarded me 64,096 GP.
I did ended up getting the gloves even though it never said I did. 
I also got the Boltmaker keyitem even though it never said I did either.

**Comment by nfaletra** [comment]
You are a version ahead of the server. IDs have shifted so what you are seeing is just off. 14830 is the item id for carpenter's gloves. So you did obtain them, but your client is receiving a text id it's not expecting. Same with the KI. 1987 is the key item ID.
