### ISSUE TITLE
Emet Harness +1 wrong mod

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#301]
**Date & Time**: 10/16/2018

**Client Version (use `/ver` in game):**30180904_0

**Character Name:**Spectre

**Discord Name (if different from in game):**

**Nation:**windurst

**Job(level)/Sub Job(level):**thf99/dnc49

**NPC or Monster or item Name:** Emet Harness +1

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**The item Emet Harness +1 is supposed to have -6 physical damage taken (mod 161), but it actually has the mod damage taken (160)

**Comment by nfaletra** [comment]
Confirmed fixed.
