### ISSUE TITLE
Hahava T4 Sandy VWNM won't spawn

### ISSUE THREAD

**Issue by kenshin9022** [HomepointXI/Issues#302]
**Date & Time**: 
11/18/2018 1:15 EST

**Client Version (use `/ver` in game):**
30181003_1

**Character Name:**
Yahikoe

**Discord Name (if different from in game):**

**Nation:**
Sandoria

**Job(level)/Sub Job(level):**
99thf/49nin

**NPC or Monster or item Name:**
Hahava VW

**Zone name:** 
King Ranparre's tomb H-7

**Coordinates (use `!where`):**
x:-59 Y:8 Z:159 (193)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes 4 instances Yahikoe Yahikoex Yahi Yahiko

**Steps to reproduce:**
Attempt to spawn hahava in possesion of crimson stratum abyssite IV

**Any additional information:**
Hahava won't spawn.  Used !voidwatch command as suggested prior with no luck.  
Will ask me if I want to use a voidstone I select YES and says I may commence at any time.  
Hahava does not spawn and upon rechecking planar rift it sells me my presence does not seem to eleicit a reaction.  Will let me attempt to spawn every few mins with no luck.  Don't want to waste my voidstones.  
![capture](https://user-images.githubusercontent.com/45149641/48676433-f2da0000-eb34-11e8-8e77-aac8e4cbe3ef.PNG)

**Comment by neoffxi** [comment]
You trying to pop using the rift at (H-7) which is the wrong one.  Refer to the wiki page.

http://wiki.homepointxi.com/Hahava

The correct planar rift is at (G-8).

**Comment by kenshin9022** [comment]
That was it!  Thank you
