### ISSUE TITLE
AF3 Feet Brd 

### ISSUE THREAD

**Issue by Holysword87** [HomepointXI/Issues#303]
**Date & Time**: 

11/21/2018 12:08:19

**Client Version (use `/ver` in game):**

30181003_1

**Character Name:**
Miniholy

**Discord Name (if different from in game):**

Holysword

**Nation:**

Sandy

**Job(level)/Sub Job(level):**

Brd99/49whm

**NPC or Monster or item Name:**

Aoidos' cothurnes +1

**Zone name:** 

Port Jeuno

**Coordinates (use `!where`):**

X:-49 Y:0 Z:-9 (95)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

Yes

**Steps to reproduce:**

Trade to npc to upgrade from NQ to +1

**Any additional information:**

**Comment by nfaletra** [comment]
Corrected Miniholy's inventory.
Fixed the incorrect item id in the npc script.

**Comment by nfaletra** [comment]
Confirmed fixed.
