### ISSUE TITLE
Weaver's Stall Recipe

### ISSUE THREAD

**Issue by neoffxi** [HomepointXI/Issues#304]
**Date & Time**: 
11/22/2018

**Client Version (use `/ver` in game):**
30181003_1

**Character Name:**
Neomorpheus

**Discord Name (if different from in game):**
Neo 

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
PLD 99 / WAR 49

**NPC or Monster or item Name:**
Weaver's Stall

**Zone name:** 
n/a

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**
http://www.homepointxi.com/db/items/3628/weavers_stall

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
1. Look up the recipe for weaver's stall.
2. **Unknown item: 254** is part of the recipe
3. Refer to other sources like FFXIAH for the retail recipe.
4. Also, item 254 is not in the item_basic table 

**Any additional information:**
Recipe for the stall - https://www.ffxiah.com/item/3628/weavers-stall
SQL file for items - https://raw.githubusercontent.com/DarkstarProject/darkstar/master/sql/item_basic.sql

**Comment by Jessland86** [comment]
Fixed next time server restarts.
