### ISSUE TITLE
~ Supplies package ~ ToAU mission 2

### ISSUE THREAD

**Issue by simthra** [HomepointXI/Issues#305]
**Date & Time**: 11/25/18 12.12

**Client Version (use `/ver` in game):** 30181103_0

**Character Name:** Squaller

**Discord Name (if different from in game):**

**Nation:** bastok 10

**Job(level)/Sub Job(level):** war99/dnc49

**NPC or Monster or item Name:** Naja Salaheem

**Zone name:** Aht Urgan

**Coordinates (use `!where`):** 26 -7 -46

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:** NPC won't give the temporary key item "Supplies Package" needed to progress through ToAU missions.

**Any additional information:**

**Comment by EpicTaru** [comment]
@simthra I confirm that you do not have that key item (the Supplies Package KI).  I am also showing you being on Aht Urhgan Mission 1 still.  Please double-check the steps for Mission 1 to ensure you completed everything needed to progress to Mission 2.  Respond back here if you have and still aren't progressing to Mission 2.

**Comment by simthra** [comment]
I can confirm ToAU mission 1 is flagged as completed, currently on mission 2.

**Comment by EpicTaru** [comment]
I'll be on later today to verify.  If you wish, please just leave your character online like you did yesterday.

**Comment by EpicTaru** [comment]
Real-life activities of the day lasted longer than expected.  Just now arrived back home and too late in the day for me to research this.  I will be online tomorrow to work with you on this. @simthra

**Comment by EpicTaru** [comment]
OK, let's start over.  Which mission are you attempting to complete, @simthra? ToAU Mission 1 (Land of Sacred Serpents) or ToAU Mission 2 (Immortal Sentries).

**Comment by simthra** [comment]
I'm trying to complete mission 2

**Comment by EpicTaru** [comment]
What happens when you approach Naja's office? Do you receive a cutscene? If not, what happens when you instead interact with Naja herself directly?

**Comment by simthra** [comment]
She tells me to deliver a package of supplies to any immortal guarding the
staging points

Il giorno Lun 3 Dic 2018, 22:14 EpicTaru <notifications@github.com> ha
scritto:

**Comment by EpicTaru** [comment]
@simthra this issue is now escalated above my ability to resolve it. Please respond here when your character is next online and the issue will be resolved at that time.

**Comment by simthra** [comment]
Squaller's online

**Comment by nfaletra** [comment]
Gave him the KI so he can continue with the mission.
