### ISSUE TITLE
ninja job unlock quest

### ISSUE THREAD

**Issue by morgangothica** [HomepointXI/Issues#306]
**Date & Time**: 11-26-2018 2:18am

**Client Version (use `/ver` in game):**
version 30181003_1

**Character Name:**
MissKitty and Lita

**Discord Name (if different from in game):**
lita

**Nation:**
san d'oria

**Job(level)/Sub Job(level):**
76war/38mnk

**NPC or Monster or item Name:**
Strangely Shaped Coral

**Zone name:** 
Korroloka Tunnel

**Coordinates (use `!where`):**
x:-207 Y:-9 Z:175 (237)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**
I accepted the quest to unlock the ninja job. I followed the guides till the point of going to Korroloka tunnel. the quest log tells me to go there too get the "Strangely Shaped Coral"
I'm at that point now and have gone here 3 different times to see if it will do anything other then when i click the ??? it says " There is nothing out of the ordinary here". ive killed things around it and everything. please help

**Any additional information:**

**Comment by EpicTaru** [comment]
@morgangothica I'll be online in about 2hrs to help you with your issue

**Comment by morgangothica** [comment]
i'm sorry i missed you if you will be available again soon i'll be here for a while.

**Comment by EpicTaru** [comment]
@morgangothica I'll be online for another couple hours if you are able to be online.

**Comment by morgangothica** [comment]
I only get on past 9pm most nights. I'm busy till then almost always.

Sent from my MetroPCS 4G LTE Android device

----- Reply message -----

**Comment by morgangothica** [comment]
i'm gonna be on for a few if you will have time today to help me.

**Comment by EpicTaru** [comment]
https://ffxiclopedia.fandom.com/wiki/Ayame_and_Kaede - There's the link to the walkthru on FFXIclopedia.  Double-check the steps to make sure you didn't skip something.  I'll check your variables when I return if you are still unable to spawn the leeches. @morgangothica

**Comment by nfaletra** [comment]
Possible multibox issues and player vars didn't update. Retrying steps in the quest fixed the progression.
