### ISSUE TITLE
Zilart mission 8 not working

### ISSUE THREAD

**Issue by Wildella** [HomepointXI/Issues#307]
**Date & Time**: 
11/27/18 10:45pm EST

**Client Version (use `/ver` in game):**
30181003_1

**Character Name:**
Wildella 

**Discord Name (if different from in game):**

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
Blm 99/Rdm 49

**NPC or Monster or item Name:**

**Zone name:** 
Stellar Fulcrum in Delkfutt's Tower

**Coordinates (use `!where`):**
X:-519 Y:1 Z:-28 (66)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Previous mission ZM mission rank 7 The Chamber of Oracles

**Any additional information:**
I finished zm rank 7 mission and i got the key item and the title. It said that it was optional to go talk to Aldo so i skipped that part but went back and did it after i didn't get the cut scene and it still didn't work. I have the hp so i just had to use that to get to the portal to zone into the Stellar Fulcrum.

**Comment by Wildella** [comment]
The ffxiclopedia guide did not mention that I had to enter lower delkfutt's tower for a cut scene first.

**Comment by nfaletra** [comment]
Yep. Happens every time. People go straight to the HP at the top, but there's a cutscene upon entering Lower Delkfutt's.

**Comment by EpicTaru** [comment]
I'll add a comment to the FFXIclopedia article!

**Comment by Wildella** [comment]
Lol yeah I figured I would make a comment so if anyone was having issues and reading these before putting in a ticket it would save them some time.

**Comment by Wildella** [comment]
Oh ok kewl Epictaru thanks ☺

**Comment by EpicTaru** [comment]
Disregard my last comment, it's not a retail issue.

**Comment by Heepster03** [comment]
Yeah because the homepoint system wasn't always around. If you just ignore that portion of the instructions, it implies that you must climb the tower. Which starts in LDT. Homepoints are not always the answer :)

**Comment by Wildella** [comment]
Lol OK I will remember that for future issues  when it mentions just skip to the hp if you have it lol thank you
