### ISSUE TITLE
Re: Accounts Neonracer & Neonracer2

### ISSUE THREAD

**Issue by neonracer** [HomepointXI/Issues#308]
**Date & Time**: Thursday November 29, 2018 @ 00:05 A.M

**Client Version (use `/ver` in game):**30181003_1

**Character Name:** Neonracer & Dhiana

**Discord Name (if different from in game):**Neonracer

**Nation:**Bastok

**Job(level)/Sub Job(level):** Neonracer : Thf 99/Dnc49
                                            Dhiana: Rdm 99/Whm49

**NPC or Monster or item Name:**

**Zone name:** Mordion (both)

**Coordinates (use `!where`):**Can't use it there

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**was using Dhiana as my curebot.

**Steps to reproduce:**

**Any additional information:** 
        Please and thank you, may these 2 characters be released, as told it has been over 72 hours, and I understand why it was done, and do not disagree with the decision that was made. I have understood the consequence, and will not repeat the offense. thank you very much and  I apologise if I have inconvenienced anyone, in the process.  Thank you.  ( was not sure to do it as 1 ticket for 2 accounts)

~Neonracer~

**Comment by EpicTaru** [comment]
@neonracer report to Mordion Gaol asap to be released. Please respond here once you are ready.

**Comment by neonracer** [comment]
Im here...ok.

**Comment by EpicTaru** [comment]
Released 11/29/2018 at 1240 EST.
