### ISSUE TITLE
Uleguerand Range VWNM Planar Rift doesn't respond

### ISSUE THREAD

**Issue by malakai80** [HomepointXI/Issues#309]
**Date & Time**: 
11/28/2018 9:44PM PST

**Client Version (use `/ver` in game):**
30181003_1

**Character Name:**
Malakai

**Discord Name (if different from in game):**
malakai80

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
99PLD/49NIN

**NPC or Monster or item Name:**
Planar Rift (G-10)

**Zone name:** 
Uleguerand Range

**Coordinates (use `!where`):**
X:-140 Y:-19 Z:-325 (117)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes.
Also logged everything out and tried again with only 1 character.

**Steps to reproduce:**
Tried all planar rifts in zone.  Clicked on them but did not receive a prompt.  Zoned and tried again.  Logged out and tried again.  Did it while multi-boxing and as a single character.  Tried on multiple characters.

Verified all characters in question have Hyacinth stratum Abyssite.
Was able to spawn and fight all other VWNM along same quest line in other zones.

**Any additional information:**

**Comment by Jessland86** [comment]
Hotfixed.
