### ISSUE TITLE
Water Ore not listed for Water Elementals in Ru'Aun Gardens

### ISSUE THREAD

**Issue by munkee128** [HomepointXI/Issues#310]
**Date & Time**: 
11/29/2018 9:09 AM PST

**Client Version (use `/ver` in game):**
30181003_1

**Character Name:**
Munkee

**Discord Name (if different from in game):**
Munkee128

**Nation:**
Windy

**Job(level)/Sub Job(level):**
THF99/DNC49

**NPC or Monster or item Name:**
Water Ore
Water Elemental

**Zone name:** 
Ru'Aun Gardens

**Coordinates (use `!where`):**
Unfortunately, not near it atm. But it's the water elementals near Seiryu island in Sky.

**Item tool link (for items issues only):**
http://www.homepointxi.com/db/items/1260/chunk_of_water_ore

**Multi-boxing? (multiple clients on same connection):**
Not atm

**Steps to reproduce:**
N/A, was speaking to Autkast on Discord about it.

**Any additional information:**
All other elementals in Ru'Aun Gardens are listed in their respective elemental ore drop on the DB. Only this one was not.

**Comment by nfaletra** [comment]
Added water ore to the droplist for the elementals in Sky

**Comment by munkee128** [comment]
Confirm, it's dropping now. Thank you.
