### ISSUE TITLE
some jugs not working... 

### ISSUE THREAD

**Issue by danz409** [HomepointXI/Issues#311]
**Date & Time**: 
11/30/2018 2:29 EST

**Client Version (use `/ver` in game):**
30181103_0

**Character Name:**
Danz

**Discord Name (if different from in game):**
danz409#0595

**Nation:**
United states of windurst

**Job(level)/Sub Job(level):**
99 BST/ 49DNC

**NPC or Monster or item Name:**
Meaty Broth

**Zone name:** 
Abyss la theine

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/17920/meaty_broth

**Multi-boxing? (multiple clients on same connection):**
yes. 

**Steps to reproduce:**
try to call beast. 
recive error.
 "you do not have the necessary item equipped to call a beast.

**Any additional information:**

**Comment by danz409** [comment]
just bought ALL the lv 99 jugs in upper juno NONE of them work. these are
Meaty
Muddy
Blackwater
Livid
Lyrical
Airy
Crumbly
Pale
Dire
Rapid
crackling
Creepy

all tested and not working.

**Comment by danz409** [comment]
in other words BST is supergimp WAR. and unplayable as an actual beast master. not happy i spent a week getting it to 99...

**Comment by Heepster03** [comment]
made a new ticket, will keep it updated as things come to light.
