### ISSUE TITLE
Voidwatch Stone Errors..

### ISSUE THREAD

**Issue by Uzi904** [HomepointXI/Issues#312]
**Date & Time**: 
11/30/18

**Client Version (use `/ver` in game):**30181003_1

**Character Name:**
Uzi 

**Discord Name (if different from in game):**

**Nation:**bastok 

**Job(level)/Sub Job(level):**
99pld/war

**NPC or Monster or item Name:**
Voidwatch Officer Bastos Makets Entry

**Zone name:** 
Bastok Markets

**Coordinates (use `!where`):**
E-10

**Item tool link (for items issues only):** n/a

**Multi-boxing? (multiple clients on same connection):**n/a

**Steps to reproduce:**
11/20 - 6 stones to make 30total
11/21- 1 stone, had 19 total
11/26 5 stones. 25 total
11/30 4 stones to make 22 total...
I have popped absolutely 0  voidwatch mobs during alll these encounters..

**Any additional information:**

**Comment by EpicTaru** [comment]
@Uzi904 please provide screenshots if you are able to.

**Comment by Uzi904** [comment]
Doesn’t let me post them on here for some reason. Only happen to have the one from today i can take. Just made notes on it and also dm Immo on it when  I first noticed

**Comment by Heepster03** [comment]
You can just drag and drop the screenshots

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/49310860-1f7f0780-f4a5-11e8-9cc5-f9c911a636a7.jpg)

Uploaded on @Uzi904's behalf.

**Comment by nfaletra** [comment]
I did some Voidwatch yesterday and used a few stones. I'll talk to the NPC again in a couple days and see what happens.

**Comment by nfaletra** [comment]
I had 240 Voidstones before the holidays (checked via Status->Currencies menu). Talked to Voidwatch Officer. Received 28 Voidstones. Total is now 268. Working as intended. There's no way you should be losing voidstones unless you are participating in voidwatch.
