### ISSUE TITLE
Jailer of Temperance attacks healing me

### ISSUE THREAD

**Issue by Oderson** [HomepointXI/Issues#313]
**Date & Time**: 
12/6/18 17:32 CST

**Client Version (use `/ver` in game):**

30181103

**Character Name:**
Oderson

**Discord Name (if different from in game):**
Nevion

**Nation:**

Sandy

**Job(level)/Sub Job(level):**
pld/war

**NPC or Monster or item Name:**
Jailer of Temperance

**Zone name:** 
Grand Palace

**Coordinates (use `!where`):**

x-793 y0 z461 (107)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

no

**Steps to reproduce:**
none yet

**Any additional information:** 

attacks are healing me, spikes still do dmg though

**Comment by nfaletra** [comment]
Pretty sure it's an issue with Burtgang's PDT II. Seeing it on other mobs, as well.

**Comment by nfaletra** [comment]
Fixed all the damage taken math and submitted to DSP. We’ll pull the changes soon.
