### ISSUE TITLE
~ ToAU mission 30 ~ stuck

### ISSUE THREAD

**Issue by simthra** [HomepointXI/Issues#315]
**Date & Time**:  08/12/2018 21.13 gmt+1

**Client Version (use `/ver` in game):** 30181103_0

**Character Name:** Thranduil

**Discord Name (if different from in game):** thranduil

**Nation:** bastok 10

**Job(level)/Sub Job(level):** blu99/rdm49

**NPC or Monster or item Name:**

**Zone name:** caedarva mire/arrapago reef

**Coordinates (use `!where`):** -719, 16, -20

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:** 
As reference: https://ffxiclopedia.fandom.com/wiki/Aht_Urhgan_Mission_30:_Prevalence_of_Pirates
I can't get any of the 2 cutscenes to play.

**Any additional information:**

**Comment by alannor** [comment]
Experincing same issue, game version correct as of time posting

**Comment by Blingswinger** [comment]
Im having the same issue. Bling

**Comment by EpicTaru** [comment]
Checked @Blingswinger variables related to this mission, all are what they should be in order for the CS to trigger on zone in. Then had Bling approach the Cutter, that CS also did not trigger.

**Comment by EpicTaru** [comment]
Also checked @simthra variables related to this mission earlier today. Simthra's variables were the same as Bling's. Still can't determine a cause for the CS not triggering.

**Comment by EpicTaru** [comment]
https://github.com/DarkstarProject/darkstar/pull/5772

**Comment by EpicTaru** [comment]
Resolved in server version update to 30191204_1 version.
