### ISSUE TITLE
Jorgumund Spam Spike Flail

### ISSUE THREAD

**Issue by neonracer** [HomepointXI/Issues#316]
**Date & Time**: 3:16 a.m EST Monday Dec, 10, 2018

**Client Version (use `/ver` in game):**  30181103_0 ver

**Character Name:**  Neonracer, Dhiana, Fiddler, Ixtly, Rynn, Aliron, Frankentaru, Yuhe, Oltor, Wefa,Duirmhuid.( all of us tried it)

**Discord Name (if different from in game):**Neonracer (main person reporting this)

**Nation:** Bastok

**Job(level)/Sub Job(level):**99 Thief

**NPC or Monster or item Name:** Jorgumund

**Zone name:** Ulegrand Range

**Coordinates (use `!where`):** X-250, Y-126 Z 8 (204)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:**  ???

**Any additional information:**  Uzi said it may be broken. Last person killed, someone may have pulled it and died. He mentioneded something about maybe manually resetting the mob???  Pls look into this.

**Comment by Jessland86** [comment]
Tested mob, could not reproduce.
