### ISSUE TITLE
Karakul Leather recipes are broken. Please send 3 pieces ASAP

### ISSUE THREAD

**Issue by BrenMcM** [HomepointXI/Issues#317]
**Date & Time**: 

22:39 10/12/18

**Client Version (use `/ver` in game):**
30181103_3

**Character Name:**
Nemu

**Discord Name (if different from in game):**

!3, Tleaf

**Nation:**
Sandorian

**Job(level)/Sub Job(level):**

WHM/RDM 99

**NPC or Monster or item Name:**

Karakul Leather

**Zone name:** 

Northern Sandoria

**Coordinates (use `!where`):**

K-9

**Item tool link (for items issues only):**

https://www.ffxiah.com/item/879/karakul-leather

**Multi-boxing? (multiple clients on same connection):**

YES

**Steps to reproduce:**

Try to make Karakul Leather
both recipes
Dark Crystal
Karakul skin + Distilled water + windy tea leaves
Karakul skin x3 + Distilled water x1 + windy tea leaves x3

**Any additional information:**

**Comment by nfaletra** [comment]
How about you fill out the client version like you’re supposed to?

**Comment by nfaletra** [comment]
You didn’t even describe what is broken. You need to actually fill out the ticket with real information.

**Comment by BrenMcM** [comment]
It clearly says recipes in the title: 30181103_3.
gonna have to cancel the Christmas puppet show. the children will be so disappointed now.....

**Comment by EpicTaru** [comment]
Fill in all the parts of the form correctly or this issue is gonna be closed.

**Comment by nfaletra** [comment]
Which recipe are you using? What’s your leatherworking at? What character SPECIFICALLY? All of these variables can have an impact. Be thorough. Or continue being an ass and I’ll just close it.

**Comment by BrenMcM** [comment]
yeah no bother keep your hair on, working on it

**Comment by BrenMcM** [comment]
Should be all there now. Cheers guys :)

**Comment by EpicTaru** [comment]
What level is your leather crafting at?

**Comment by nfaletra** [comment]
The recipe is imperial tea leaves. Not windy tea leaves. She why I ask for info?

**Comment by BrenMcM** [comment]
105

**Comment by BrenMcM** [comment]
Imperial ? fuck.. my bad....... sorry for the time waste ; ;
