### ISSUE TITLE
Lost Username and Password

### ISSUE THREAD

**Issue by caimartin** [HomepointXI/Issues#318]
**Date & Time**: 
12/10/2018

**Client Version (use `/ver` in game):**
latest

**Character Name:**
AvaZhella

**Discord Name (if different from in game):**

KingCairo

**Nation:**

**Job(level)/Sub Job(level):**

summoner idk havent gotton on in a few months

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

trying to get lost credentials

**Comment by Heepster03** [comment]
Taken care of.
