### ISSUE TITLE
Missing Key item for Immortal Sentries progression

### ISSUE THREAD

**Issue by Gn3x0n** [HomepointXI/Issues#319]
**Date & Time**:  12/11/18 at 8:49am EST

**Client Version (use `/ver` in game):** 30181103_0

**Character Name:** Raistlin

**Discord Name (if different from in game):** Caramon

**Nation:** San d'Oria

**Job(level)/Sub Job(level):** Red Mage 99, White Mage 49

**NPC or Monster or item Name:** Nareema

**Zone name:** Caedarva Mire

**Coordinates (use `!where`):** X: 518, Y: -23, Z:-471 (170)

**Item tool link (for items issues only):** 

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** None

**Any additional information:**
Key item Supplies package is missing, unable to obtain a replacement. Without it, cannot continue with Aht-Urhgan mission "Immortal Sentries"

**Comment by Jessland86** [comment]
You're the second person to have this issue in a week, is there any more detail you can go into with what happened before you should have gotten the KI? How did you get to Whitegate etc? I need to see if we can replicate this so it can get fixed for people moving forward. Any insight would be appreciated.

**Comment by Gn3x0n** [comment]
I wish I could offer you more information, I started the mission quite some time ago but never got around to completing it until today. None of the immortals will respond to Raistlin and the item is nowhere in my KI's

**Comment by Heepster03** [comment]
![image](https://user-images.githubusercontent.com/8421725/129259425-c37c0f67-1f41-4956-a75f-d678284e6f30.png)

Seems to be working as intended... should this issue occur, just open a new ticket.
