### ISSUE TITLE
Relic weapon upgrade time issue Relic 2 to Relic 3

### ISSUE THREAD

**Issue by Willthefluteboy** [HomepointXI/Issues#32]
**Date & Time**: 04/21/2018

**Client Version (use `/ver` in game):** 30180203_1

**Character Name:** Reon

**Discord Name (if different from in game):** Will/Reon

**Nation:** Sandy

**Job(level)/Sub Job(level):** ANY/ANY

**NPC or Monster or item Name:** Switchstix

**Zone name:** Castle Zvahl Baileys

**Coordinates (use `!where`):** X:387 Y:-12 Z:-18 (214)

**Item tool link (for items issues only):** 

**Multi-boxing? (multiple clients on same connection):** No

**Steps to reproduce:** Turn in relic sword v2 to upgrade to v3 and wait 24 hours to pickup

**Any additional information:** On the wiki it states 24 hours wait time from when you turn in the weapon to when you can retrieve the next teir. After 27 hours I am still unable to obtain the sword. NPC responds back with the standard response of coming back too early. 

Switchstix: You really are impatient, ain't you!
This is gonna take a hell of a lot longer than last time-- that's how amazing the outcome is gonna be. Better find something else to occupy yourself with for a while.
Switchstix: This is gonna take so long, you'll forget you even asked me to do it in the first place. A really, really, really long time. Really long. But don't worry, I'm a true craftsgoblin, I won't go back on a deal. Just don't forget to come back, huh?

**Comment by Jessland86** [comment]
Check the goblin.

**Comment by Willthefluteboy** [comment]
What the goblin says when I talk with him is stated at the end of the ticket.

**Comment by Jessland86** [comment]
I know. I checked your variable and changed it based on the recent time issue.

**Comment by Willthefluteboy** [comment]
Switchstix: I don't have the skill to reforge the glyptic sword you gave me, so I'm gonna take it to a blacksmith friend of mine. It'll be expensive, but the work is topnotch.
Switchstix: The fee, including my cut for the referral, comes out to 14 one hundered byne bills. It's gonna be a fun time getting your grubby little adventurer hands on the loot, but the result will be worth it.

I have already paid this 28 hours ago now.

**Comment by Jessland86** [comment]
Gonna wait on the restart on this one to see if that fixes it. I'll do some more digging as well in the meantime to see if I can sort things out.
