### ISSUE TITLE
Weapon Skill not working in Dynamis

### ISSUE THREAD

**Issue by Sethhp** [HomepointXI/Issues#321]
**Date & Time**: Dec 12, 2018

**Client Version (use `/ver` in game):**30181103_0 

**Character Name:**Gendo

**Discord Name (if different from in game):**Seth

**Nation:**Bastok

**Job(level)/Sub Job(level):**99THF/49DNC

**NPC or Monster or item Name:**Dreamworld Dynamis

**Zone name:** Dyna Buburimu, Qufim, Valkurm and Tav

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**no

**Steps to reproduce:**None

**Any additional information:**
Trying to farm some Forgotten items, notice weapon skill is not doing any damage, It has the text message (example) "******* readies Mercy Stroke." plays the animation for that weapon skill, but no damage output or nor any weapon skill damage text.

**Comment by nfaletra** [comment]
What weapon you got on?

**Comment by Sethhp** [comment]
Mandau

**Comment by nfaletra** [comment]
which Mandau? Also, there's no way that client version is correct. You wouldn't be able to login if it was.

**Comment by Sethhp** [comment]
mb on the client, my client is 30181103_0
Mandau is 119 afterglow, also tryed on rdm last night with 119 Murgleis with no damage output too.

**Comment by nfaletra** [comment]
only happening in dynamis?

**Comment by Sethhp** [comment]
yeah seem only in dyanmis. just tested out at the tree it work outside of dyna

**Comment by Fiddler-Cerberus** [comment]
I've had the same problem, only AOE weapon skills seem to work.

**Comment by nuno-pires-cruz** [comment]
Just to add, same problem in limbus.

**Comment by Jessland86** [comment]
Hotfixed.
