### ISSUE TITLE
arasy satchet not increasing avatar level. makes it weaker

### ISSUE THREAD

**Issue by rocko0o** [HomepointXI/Issues#323]
**Date & Time**: 
12/13
1:30

**Client Version (use `/ver` in game):**
30181103_0

**Character Name:**
Rockoo

**Discord Name (if different from in game):**

**Nation:**
Sandoria

**Job(level)/Sub Job(level):**

summoner99

**NPC or Monster or item Name:**

Arasy satchet

**Zone name:** 

problem persistent in all zones tested

**Coordinates (use `!where`):**

problem persistent in all zones tested

**Item tool link (for items issues only):**

http://homepointxi.com/db/items/21393/arasy_sachet

**Multi-boxing? (multiple clients on same connection):**

no

**Steps to reproduce:**
summon avatar with satchet

**Any additional information:**

**Comment by EpicTaru** [comment]
Arasy Sachet has no mods assigned to it, causing it to make the avatar weaker, it is only used as an ingredient here, as detailed in the wiki page for the item:
http://wiki.homepointxi.com/Arasy_Sachet
![image](https://user-images.githubusercontent.com/26195580/126913479-bccea1a3-0c99-4a36-96ac-5fa6bcc8b6dd.png)
