### ISSUE TITLE
PUP: Animator Z, P and P II doesn't appear to make Automation 119

### ISSUE THREAD

**Issue by BrenMcM** [HomepointXI/Issues#325]
**Date & Time**: 

16:30 15/12/2018

**Client Version (use `/ver` in game):**

30181103_0

**Character Name:**

NotEqual

**Discord Name (if different from in game):**

!3ren

**Nation:**

Sandoria

**Job(level)/Sub Job(level):**

PUP99

**NPC or Monster or item Name:**

Animpator P
Animator P Ii

**Zone name:** 

Abyssea-La-Theine

**Coordinates (use `!where`):**

C-4

**Item tool link (for items issues only):**

https://www.ffxiah.com/item/21456/animator-p
https://www.ffxiah.com/item/21458/animator-p-ii

**Multi-boxing? (multiple clients on same connection):**

YES

**Steps to reproduce:**

General fighting.

**Any additional information:**
I have tried Animator's Z, P and P II on 3 separate chars and different Combinations of frames.
It seems like the Animators don't bring the Automation stats to 119 as even the PLD setup is like butter.

I have tried Giant mobs in Aby La-Thiene and the Automation's lasted 3-6 hits each time. That can't be right at all.

The attachment setups I'm using can be found here:
https://www.bg-wiki.com/bg/String_Theory

**Comment by Heepster03** [comment]
moved to #558
