### ISSUE TITLE
PUP: Animator II. Automation moving into melee range

### ISSUE THREAD

**Issue by BrenMcM** [HomepointXI/Issues#327]
Date & Time:

17:27 15/12/2018

Client Version (use /ver in game):

30181103_0

Character Name:

NotEqual

Discord Name (if different from in game):

!3ren

Nation:

Sandoria

Job(level)/Sub Job(level):

PUP99

NPC or Monster or item Name:

NA

Zone name:

Abyssea-La-Theine

Coordinates (use !where):

C-4

Item tool link (for items issues only):
NA

Multi-boxing? (multiple clients on same connection):

YES

Steps to reproduce:
Move mob away from pet. Pet moves back into melee range

General fighting.

Any additional information:
 Ranged pet keeps moving into melee range when using II Animators which are supposed to prevent this.

**Comment by Heepster03** [comment]
moved to #558
