### ISSUE TITLE
Player cant stop walking

### ISSUE THREAD

**Issue by tifya** [HomepointXI/Issues#328]
**Date & Time**:
2018 12 16

**Client Version (use `/ver` in game):**

**Character Name:**
Tif

**Discord Name (if different from in game):**
Tifya nashirok

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
hello my player cant stop walking forward i did everything possible reboot comp and game 3 time remove auto run and control too delete in windows the keyboard and redo it change language update my graphic card try another keyboard completely nothing work i can still run while it still auto walk. 
It does this on all char i using ashita

**Comment by Jessland86** [comment]
Reading backlog of the LS chat apparently you fixed this.

**Comment by Jessland86** [comment]
![image](https://user-images.githubusercontent.com/28382433/50055631-526d0080-011f-11e9-9951-faa1492283be.png)
