### ISSUE TITLE
Rename Request: Autkast

### ISSUE THREAD

**Issue by nfaletra** [HomepointXI/Issues#33]
**Date & Time**: N/A

**Client Version (use `/ver` in game):**N/A

**Character Name:**Autkastx

**Discord Name (if different from in game):**Autkast

**Nation:**N/A

**Job(level)/Sub Job(level):**N/A

**NPC or Monster or item Name:**N/A

**Zone name:** N/A

**Coordinates (use `!where`):**N/A

**Item tool link (for items issues only):**N/A

**Multi-boxing? (multiple clients on same connection):**N/A

**Steps to reproduce:**N/A

**Any additional information:**
My original character on LD was named Autkast. After that, I had my character from retail imported under Autkastx. I have since cleaned out my inventory on Autkast and deleted him. I'm requesting that Autkastx be renamed to Autkast (get rid of the 'x').

Please and thank you!

**Comment by Heepster03** [comment]
Got it!
