### ISSUE TITLE
Tara (account recovery)

### ISSUE THREAD

**Issue by Tatako** [HomepointXI/Issues#330]
**Date & Time**: 
12/19/1018 Time= 5:12pm ET
Last login = 4/9/2016 10:30pm ET

**Client Version (use `/ver` in game):**
30181103_0

**Character Name:**
Tara (Enigma Linkshell holder)

**Discord Name (if different from in game):**
Satara (will be changed to match in game name soon)

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
WHM=89
WAR, MNK, BLM, RDM, THF, SAM, DNC, NIN at 75

**NPC or Monster or item Name:**

**Zone name:** 
Unknown probably Southern San d'Oria

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
Would like to recover/reset password for account.  I have 2 accounts on server when the server was LegionDark.  Returning player, and can remember one account just not the other.

**Comment by DeianYM** [comment]
@Tatako I wonder if you are the same Tara I played with :)! Two years ago, (Unisei not sure if you remember lol) Can contact me on Discord Chakrazee#3094, I believe.

**Comment by Tatako** [comment]
It is!  I'm trying to recover the account.

**Comment by DeianYM** [comment]
AAAAH I am super happy haha, well I've been waiting to do the same, but I not sure when they will have time to recover the accounts, looks like people that have access to these kind of things is very limited now. Don't forget to send me a friend request on discord if you still have it @Tatako. Have been trying to play for like the past month, hopefully we will see each other again!

**Comment by Heepster03** [comment]
@Tatako , Reach out to me on Discord. I'll get it done either tonight (depending if you're up) or tomorrow. Terribly sorry about the delay.

**Comment by Heepster03** [comment]
Resolved!
