### ISSUE TITLE
AF3_Trade_Mog will not accept certain upgrades

### ISSUE THREAD

**Issue by Fiddler-Cerberus** [HomepointXI/Issues#332]
**Date & Time**: 
9 PM EST

**Client Version (use `/ver` in game):**
30181103_0

**Character Name:**
Fiddler

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**
SAM/DNC & PLD/DNC

**NPC or Monster or item Name:**
AF3_Trade_Mog

**Zone name:** 
Port Jeuno

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/3201/unkai_seal_feet
http://homepointxi.com/db/items/12099/unkai_sune-ate

**Multi-boxing? (multiple clients on same connection):**
N/A

**Steps to reproduce:**
Trade seals with equipment to moogle as usual.

**Any additional information:** 
Tried zoning,  changing jobs, upgrading different pieces, logging in and out.

P.S.: Spuk (http://homepointxi.com/db/monsters/17657893/Spuk) does not drop Wailing Rags, so neither Drekavac nor Titlacauan cannot be fought, and I had to buy the Unkai Sune-ate from the AF3_Shop_Mog. The ??? pop also seems to redirect to a completely different NM in another area.

**Comment by Fiddler-Cerberus** [comment]
I'm not sure if it's also in the fix, but SAM Empy. legs + seals aren't working either. 
http://homepointxi.com/db/items/12079/unkai_haidate
http://homepointxi.com/db/items/3181/unkai_seal_legs

**Comment by Jessland86** [comment]
Yes it is. I noticed that was typos as well when I was fixing the other one.

**Comment by Jessland86** [comment]
Fixed in today's maintenance.
