### ISSUE TITLE
No Whisper of Tremors after Trial-Size Trial by Earth

### ISSUE THREAD

**Issue by nskip** [HomepointXI/Issues#333]
**Date & Time**: 
2018-DEC-17 0117

**Client Version (use `/ver` in game):**
30181205_0

**Character Name:**
Zied

**Discord Name (if different from in game):**
blackbird

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
Summoner(99)/RDM(99)

**NPC or Monster or item Name:**
Titan Prime

**Zone name:** 
Northern San d'Oria

**Coordinates (use `!where`):**
X:70 Y:0 Z:11

**Item tool link (for items issues only):**
Key Item unavailable in database.
https://ffxiclopedia.fandom.com/wiki/Whisper_of_Tremors

**Multi-boxing? (multiple clients on same connection):**
N/A

**Steps to reproduce:**
Quest Log shows Trial-Size Trial by Earth is Completed
Opened Key Items
No Whisper of Tremors

**Any additional information:**
Recently logged into Zied after Legion became HomepointXI (2018-DEC-18)
Attempted quest https://ffxiclopedia.fandom.com/wiki/The_Moonlit_Path
Realized there was no Whisper of Tremors, despite Trial-Size Trial by Earth being complete in quest log.

At first glance, it seems this error is database related, and could be due to numerous updates since last login. It has been several months since last login, and happy to be back. 

![quest_completed](https://user-images.githubusercontent.com/46020261/50276579-22f81580-03f7-11e9-86d9-e18ab36e424d.png)
![no_whisper](https://user-images.githubusercontent.com/46020261/50276582-255a6f80-03f7-11e9-9dd4-e2ffcbc20696.png)

**Comment by nfaletra** [comment]
If you turned in the whisper for a reward already, you won't have the KI. Do Titan again.
