### ISSUE TITLE
Keep getting kicked out of Abyssea Tahrongi

### ISSUE THREAD

**Issue by neonracer** [HomepointXI/Issues#334]
**Date & Time**: Dec 20th, 2018 @ 630 pm est

**Client Version (use `/ver` in game):**30181205_0

**Character Name:** Neonracer & Dhiana

**Discord Name (if different from in game):** Neonracer

**Nation:** Bastok

**Job(level)/Sub Job(level):** Neo( 99thf/49 Dnc)   Dhiana(99Rdm/49Whm)

**NPC or Monster or item Name:** Abas

**Zone name:** Abyssea Tahrongi

**Coordinates (use `!where`):** around where you spawn Abas

**Item tool link (for items issues only):** 

**Multi-boxing? (multiple clients on same connection):** Dual yes. Same connect.

**Steps to reproduce:**   Abas gets down to about 3% health, game automatically disconnect both my players. Trying to rebuild my KI for Glavoid. Keeps booting me out.  Just recently bough Inundation ( not read yet or used) but bought distract and read before entering abyssea. Unsure if that is causing the issues) I am using Curebot as well.  So not sure what gives.  My curebot program is on, but not active, as I am assisting Neonracer to kill Abas while Nuking with tier 3 spells.   Not sure what else is causing the issue. Everything is fully explained.

**Any additional information:** Just that I keep getting booted out when Abas gets to 3%. That is all.

**Comment by EpicTaru** [comment]
Try loading the game without any addons or plugins.

**Comment by neonracer** [comment]
Do I  have to delete my scripts file? ET?

**Comment by EpicTaru** [comment]
You can just rename it, don't have to delete it

**Comment by neonracer** [comment]
Ok. Gave it a new name. Now do I delete the default?

**Comment by neonracer** [comment]
Kilked Abas at 1% booted both chars. Tested @ 715pm

**Comment by neonracer** [comment]
Need to know, please and thank you what addons and or plugins that need to be unloaded, so as to try fighting this mob with all types of addons and plugins from Ashita.

Thank you.

**Comment by EpicTaru** [comment]
If you loaded the game and it still crashed with no addons/plugins loaded, then it's neither of those

**Comment by neonracer** [comment]
I have not unloaded anything. Unsure by what you mean, unload the game. You
mean, uni stall everything, andcreload it all???

**Comment by neonracer** [comment]
ok ET, I had Aliron join me on 3 occasions, Neo and Dhiana, they both got kicked. ( while in AByssea Tahrongi)  We tried each person by themselves, both got kicked at separate times... Aliron typed this, told me to add this as well...( his 2 cents as we tried to see what was wrong)

The disconnects happen specifically when abyssea NMs are killed, tested on 3 NM with Aliron in Abyssea-Tahrongi. When the NM is killed I all characters get disconnected. Tried a regular NM outside abyssea and no disconnect occured. Might be related to a Key Item check is best guess .
by Aliron.

P.S Yes specify also that we tried with only one character, and no addons/plugins loaded.

Neo

**Comment by neonracer** [comment]
I just noticed and told aliron. I noticed Dhiana had the spell, Distract, that I bought. I bet all problems are stemming from this.  Now I looked on the Ah it was there but was not yellow( as in one can read it to learn it, to use it) it was blue, but I did not have it.  Now I went and bought it, she learned it, but is still in my inventory. I traded it to neo, went on Rdm, went to read it, b.c he doesnt have it, went to read it, nd FROZE UP.   Now Neo has learned the spell, and now still have the scroll in inventory. ( its like its dupeing or something.....( weird)  Im not going to sell the scroll, I will leave it in Neo;s invnetory, and let you guys deal with it. Im guessing tat is where the problem may lie.... . Might be the culprit.

**Comment by EpicTaru** [comment]
This is outside of my level of expertise at this point, you'll have to wait until one of the higher ups can assist you.

**Comment by neonracer** [comment]
Np. Just told you all what we've done on our end, to test and see what
could be fixed. Wonder if a mini roll back and dont touch that scroll, b.c
everything worked b4 that scroll. Distract.

**Comment by neonracer** [comment]
I just wanted to add, that distract works, but freezes a character once used..( then kicks you out) but like I said, the scroll I had, never disappeared ( appears to dupe maybe?) Then traded ftom Dihana( after she learned it, to Neonracer, he frozed, then dc'd. Then leant the spell, then still had the scroll in inventory. Something has to do with this spell, either having bought it, learning it.on both characters, all off 1 scroll, and not disappezring from inventory off the 1 spell. ( after thinking of it after 1 game day.) Hoping this helps narrowing what the problem may be. Could a rollback be done, 2 both characters upon the request of me, the owner of these 2 chars, to the day before or say of tuesday 18th of december 2018, pls and ty. All gaming before distract, everything was fine.

**Comment by nfaletra** [comment]
I was told you reinstalled. Is this still happening?

**Comment by neonracer** [comment]
You can close this now. I will be montoring anything that will come up. I'm not going to say its fixed yet, but I am not getting d'cd either( but that does not mean it might happen again) but I did do a clean install, and so far, no issues. Like I said, I'll continue to be vigilant, unkess another issue arises. You may close this up. Ty
