### ISSUE TITLE
Nanti Knife isnt working for DNC and some more jobs

### ISSUE THREAD

**Issue by tifya** [HomepointXI/Issues#338]
**Date & Time**: 

**Client Version (use `/ver` in game):**
/30181103_0

**Character Name:**
Nashasha

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
Isnt working cant equip for some jobs working for thf but isnt working to DNC

**Comment by neonracer** [comment]
So is this fixed? As he traded this to me, and I will agree, as I could not equip this. Did trd back to this person.

**Comment by nfaletra** [comment]
Read the labels on the ticket.

**Comment by Jessland86** [comment]
Fixed in today's maintenance.
