### ISSUE TITLE
SAM AF1+1 items missing from bonusLimbusDrop

### ISSUE THREAD

**Issue by neuromancerxi** [HomepointXI/Issues#34]
**Date & Time**: 

Wolf! Right here and now!

**Client Version (use `/ver` in game):** 

N/A

**Character Name:** 

N/A

**Discord Name (if different from in game):** 

tarumancer

**Nation:** 

N/A

**Job(level)/Sub Job(level):** 

N/A

**NPC or Monster or item Name:**

1952/1953

**Zone name:** 

All Limbus Zones

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

SAM AF1+1 items id 1952/1953

**Multi-boxing? (multiple clients on same connection):**

N/A

**Steps to reproduce:**

N/A

**Any additional information:**

Validating against LegionReloaded code base. Check globals/mobs.lua:94 bonusLimbusDrop(player). itemList is missing entries for 1952/1953. Table needs to grow to 40 entries and the corresponding math entries need to be updated.

This may already be fixed, found it while trying to help a Discord User track down Limbus drops.

**Comment by Heepster03** [comment]
Pretty sure that I've gotten both items before when I did runs but it'll get looked into

**Comment by Heepster03** [comment]
The Scarlet Odoshi is in the Item drop list. Look it up, it'll tell you what mobs drop it. The kurogane comes from the chest, like retail.
