### ISSUE TITLE
Juggler Hecatomb

### ISSUE THREAD

**Issue by merkaga** [HomepointXI/Issues#340]
Juggler Hecatomb is suppose to be 46-48 ,I'm at lvl 84 and he almost killed me.
**Date & Time**: 

12/28/18 2330 Hrs

**Client Version (use `/ver` in game):**

Version:30181103_0

**Character Name:**
Merkaga

**Discord Name (if different from in game):**

**Nation:**

Windurst

**Job(level)/Sub Job(level):**

84 Blm/42 Whm

**NPC or Monster or item Name:**

Juggler Hecatomb

**Zone name:** 

Gusgen Mine

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

**Comment by merkaga** [comment]
Is there a list of NM's on this server that are buffed?


-----Original Message-----

**Comment by Jessland86** [comment]
http://wiki.homepointxi.com/Category:Boosted_Notorious_Monsters
http://wiki.homepointxi.com/Category:Wonder_Notorious_Monsters

**Comment by Jessland86** [comment]
Ironically Juggler Hecatomb doesn't have a listing on there >.>

**Comment by Jessland86** [comment]
@EpicTaru Can you please add the current buffed NM's to the wiki on the appropriate pages? It appears none of the buffed conquest NM's are on the page. Juggler, Alkyoneus, Biast, etc...

**Comment by EpicTaru** [comment]
The HP wiki has been updated with all of the currently known Boosted NMs.
