### ISSUE TITLE
CoP Mission - When Angels Fall

### ISSUE THREAD

**Issue by Watashi428** [HomepointXI/Issues#341]
**Date & Time**: 
1/1/19 7:30PM PST

**Client Version (use `/ver` in game):**
30181103_0

**Character Name:**
Bokura
Bokurai
Bokurawa
Watashii
Watashiwa

**Discord Name (if different from in game):**
Watashi

**Nation:**
Bastok

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 
The Garden of Ru'Hmet

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**

**Any additional information:**
1 of 6 of my characters completed the mission the other 5 didn't. Character that completed name is Watashi. After completing "When Angels Fall" CoP Mission 8-3 it put me outside the battlefield entrance. i could not check the "Luminous Convergence" So i cannot completed the 8-3 Mission for 5 of the characters.

**Comment by EpicTaru** [comment]
Just curious, which of the 6 is the 1 that completed it? Was it the main account (the first account you logged in, basically)?

**Comment by Watashi428** [comment]
Yes, Watashi (main), my alternates are Bokura, Bokurawa, Bokurai, Watashii, and Watashiwa.

**Comment by EpicTaru** [comment]
@Heepster03 or @Jessland86; for the above 5 characters (**Bokura, Bokurai, Bokurawa, Watashii, Watashiwa**), please !bring them to the following coords: **420.000, -2.650, 520.000**.  Verification (thru checking of variables) of these characters having completed the BCNM necessary has been completed.  I am assuming that multibox issues occuring with the correct placement of these characters after the successful completion of the BCNM.

**Comment by Watashi428** [comment]
Hi. So what would i need to do? Do i need to keep my guys logged off? Do we schedule a date for this issue? i'm just curious because there's some upgrades i would like to do and it requires that i complete this mission. thanks.

**Comment by EpicTaru** [comment]
@Watashi428, Heep or Immo will be responding to you soon. Apologies for the delay.

**Comment by Heepster03** [comment]
@Watashi428 , I'm online now, I sent you a tell to get your other peeps online :)

**Comment by Watashi428** [comment]
@Heepster03 Hey Sorry. i forgot to log myself off earlier. i just got home. Are you online now?

**Comment by Watashi428** [comment]
@Heepster03 .Sorry, i was stuck in traffic going home. Are you online now?

**Comment by EpicTaru** [comment]
@Watashi428 please respond here with times during the day/week when you'll be available/able to have all of the necessary characters online for Heep or Immo to pull them to where they need to be in order to interact with the Luminous Convergence.

**Comment by Watashi428** [comment]
@EpicTaru @Heepster03 @Jessland86 . I actually got home early today. so i'm available right now. If we cannot do it today, I can be available tomorrow Friday at 6:00PM-7:30PM PST (Hopefully traffic won't be too bad).

**Comment by Heepster03** [comment]
Taken care of~
