### ISSUE TITLE
i lost my password

### ISSUE THREAD

**Issue by qiganggang** [HomepointXI/Issues#342]
**Date & Time**: 
1/3

**Client Version (use `/ver` in game):**
30181103_0

**Character Name:**

qigang
hiya

**Discord Name (if different from in game):**

qigang

**Nation:**
sand

**Job(level)/Sub Job(level):**

99thf/49nin

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

I haven't played for more than a year. I forgot my password. Please help me recover it.

**Any additional information:**

**Comment by qiganggang** [comment]
ID  qigang and qigang1

**Comment by qiganggang** [comment]
Preparing to return all my friends to this game, first of all, I have to get the password back.

**Comment by qiganggang** [comment]
This is my white mage
![13742980](https://user-images.githubusercontent.com/13742980/50734101-4501de00-11d4-11e9-8555-7cf370844ba0.jpg)

**Comment by Heepster03** [comment]
Seems to have been resolved. Closing ticket.
