### ISSUE TITLE
Skillchain doing 0 Damage with relic 

### ISSUE THREAD

**Issue by Sethhp** [HomepointXI/Issues#345]
**Date & Time**: 1-9-2019

**Client Version (use `/ver` in game):**30181205_0

**Character Name:**Seth/Gendo

**Discord Name (if different from in game):**Seth

**Nation:**Sandy

**Job(level)/Sub Job(level):**99NIN/49DNC - 99THF/49DNC

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**yes

**Steps to reproduce:**
Was doing some Darkness skillchain with Mandau(119) "Blade: Hi > Rudra storm" weapon skill damage r fine, but the skillchain additional damage is hitting for 0, vice versa with Nin also, Nin with Kikoku (119) Rudra storm > Hi/Metsu also 0, I tested with Mythic and Empyrean both dagger skillchain r normal with damage, only seem to do zero only when u have relic weapon main hand and closing the skillchain.

**Any additional information:**

**Comment by Heepster03** [comment]
Just verified myself that:

Hi (with Kikoku MH) > Rudras (with Mandau MH) 
AND
Rudras (with Mandau MH) > Hi (with Kikoku MH)

Both created Darkness Skillchains that produced damage. Therefore, closing ticket.
