### ISSUE TITLE
Altepa gate not working

### ISSUE THREAD

**Issue by valkus8712** [HomepointXI/Issues#349]
**Date & Time**: 1/30/2019   2:42am CST

**Client Version (use `/ver` in game):**   30181205_0

**Character Name:**  Kapiku

**Discord Name (if different from in game):** Kapiku

**Nation:** Sandoria

**Job(level)/Sub Job(level):** blu99 dnc 49

**NPC or Monster or item Name:**  altepa gate

**Zone name:**  Western altepa desert

**Coordinates (use `!where`):**  I-6

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** yes

**Steps to reproduce:**

**Any additional information:**  I'm not sure if the coulnms are buged or if altepa gate is buged but all switches have been pressed and gate wont open not recieving cutscene when interacting with coulmns saphire coloumn might be stuck down was not able to use it i triple checked all coulmns waited 45 min  no change  gate remains locked

**Comment by Heepster03** [comment]
Looks like this was updated in DSP when they did some variable changing and such. This would most likely have to wait until we can get a DSP merge put into place. Current timeframe on that is unknown.

**Comment by stabster** [comment]
this is more for ellectra she will be stuck there soon for her savage blade nm also

**Comment by EpicTaru** [comment]
@valkus8712 @stabster Are you two still experiencing this issue?

**Comment by billyboy2020** [comment]
I also have this issue

**Comment by EpicTaru** [comment]
@billyboy2020 Npnp, DM me on Discord at your earliest convenience and I'll open the Altepa Gate.

**Comment by EpicTaru** [comment]
Closing issue as this was resolved in the last version update of the server.
