### ISSUE TITLE
Eagle Eye Shot displays as Mercy Stroke in chatlog

### ISSUE THREAD

**Issue by TrezThorne** [HomepointXI/Issues#35]
**Date & Time**:  April 25th, 2018 @ 09:00

**Client Version (use `/ver` in game):** 30780329_1

**Character Name:** Trez

**Discord Name (if different from in game):** Trez Thorne

**Nation:** Bastok

**Job(level)/Sub Job(level):** RNG (21) / COR 10

**NPC or Monster or item Name:** Hill Lizard

**Zone name:** Valkurm Dunes

**Coordinates (use `!where`):** K-9

**Item tool link (for items issues only):** N/A

**Multi-boxing? (multiple clients on same connection):** No

**Steps to reproduce:** Use Eagle Eye Shot

**Any additional information:** The animation is the correct animation for EES, as is the damage, but it shows up as using Mercy Stroke in the chatlog.
![eeserror](https://user-images.githubusercontent.com/38732209/39260485-8833ae90-486e-11e8-9dda-e873372cdd13.PNG)

**Comment by EpicTaru** [comment]
@TrezThorne please verify your client version again, please. The version you listed doesn't follow the standard scheme for client version naming formats.

**Comment by TrezThorne** [comment]
Hmmm still the same version.
![vercheck](https://user-images.githubusercontent.com/38732209/39262707-03d0e576-4875-11e8-83a9-e55295c5ffad.PNG)

**Comment by nfaletra** [comment]
This issue exists in core dsp

**Comment by EpicTaru** [comment]
Please elaborate further regarding your remark, @nfaletra

**Comment by nfaletra** [comment]
It's not specific to HomepointXI. The issue exists in stock DSP.

**Comment by EpicTaru** [comment]
How did you determine this?

**Comment by nfaletra** [comment]
Tested it on a stock DSP Test Server.

Basically, the Eagle Eye Shot script uses weaponskill functions to determine its damage. Part of that is overriding the message ID to a weaponskill specific id. Ability ID for Eagle Eye Shot is 26. The client interprets 26 as Mercy Stroke for this particular message ID. Hard setting the message ID back to 110 (instead of 185) or msgBasic.JA_DAMAGE after the damage calculation will fix this.

I (or someone) will submit a fix to DSP shortly. That enough info?

**Comment by EpicTaru** [comment]
Yep, more than sufficient. Thank ye, good sir.

**Comment by nfaletra** [comment]
https://github.com/DarkstarProject/darkstar/pull/4796

**Comment by nfaletra** [comment]
Just need to confirm this is fixed.

**Comment by nfaletra** [comment]
Possibly a new issue after the merge. I'll take a look at it.

**Comment by nfaletra** [comment]
@TrezThorne Did you happen to have nothing equipped in your main hand?

**Comment by TrezThorne** [comment]
I honestly do not recall 100% though it is highly likely, as I simply switched to RNG main and grabbed a xbow and bolt from nearby merchants. I will retry in a shortwhile, this time making sure to have a mainhand weapon equipped.

**Comment by nfaletra** [comment]
Nah, you're good. I fixed it.

**Comment by nfaletra** [comment]
Confirmed fixed.
