### ISSUE TITLE
Hachiryu sun ate

### ISSUE THREAD

**Issue by valkus8712** [HomepointXI/Issues#351]
**Date & Time**:   2/10/19

**Client Version (use `/ver` in game):**  30181205_0

**Character Name:** Kapiku

**Discord Name (if different from in game):** Kapiku

**Nation:** Sandoria

**Job(level)/Sub Job(level):** 99/49

**NPC or Monster or item Name:** Hachiryu sun ate >retail drop>Tinnin

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):** Hachiryu sun ate "no drop info"

**Multi-boxing? (multiple clients on same connection):** kapiku abarai olgaflow

**Steps to reproduce:** check item database hachiryu sun ate

**Any additional information:** hachiryu sun ate does not appear to have any drop info whilst the rest of the set does

**Comment by EpicTaru** [comment]
@valkus8712 please elaborate more, you aren't saying what the issue is, lol

**Comment by valkus8712** [comment]
updated

**Comment by EpicTaru** [comment]
Confirmed that this drops off Tinnin on DSP Master: 
<code>INSERT INTO `mob_droplist` VALUES (3525,0,0,1000,11364,100);</code>

but that it was then removed from the droplist for this mob on the LD source code 
<code>DELETE FROM `mob_droplist` WHERE dropId=3525 and dropType=0 and itemId=11364 and itemRate=100;</code>

with it then never having been subsequently re-inserted into any other droplist in the mob_droplist.sql (or the custom version this .sql file).

Ball is in your court on this one, @Heepster03 or @Jessland86!

**Comment by Heepster03** [comment]
![image](https://user-images.githubusercontent.com/8421725/127104203-f314316c-d498-41f3-81c2-de8ec7d8a129.png)

This was fixed awhile back.
