### ISSUE TITLE
Raptor mount quest buged

### ISSUE THREAD

**Issue by valkus8712** [HomepointXI/Issues#352]
**Date & Time**:  2/10/19  11:07 pm CST

**Client Version (use `/ver` in game):**    30181205_0

**Character Name:** Kapiku

**Discord Name (if different from in game):** Kapiku

**Nation:** sandoria

**Job(level)/Sub Job(level):** 99/49

**NPC or Monster or item Name:**  syrillia npc 

**Zone name:**   batallia downs

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:** was helping new player with quest couldnt find the npc turns out she was there but shes invisible  was still able to finish quest NPC is just invisible =^-^=

**Comment by EpicTaru** [comment]
What is the name (discord and in game, please) of the new player, @valkus8712?

**Comment by Heepster03** [comment]
![halkuras_2019 02 12_212834](https://user-images.githubusercontent.com/8421725/52684928-7d9c8200-2f0d-11e9-9043-80f6926b086a.png)
I verified it. Will have to look into it.

**Comment by SirYanFFXI** [comment]
Date & Time: August 1st 2011 17:58 EST 

Client Version (use /ver in game): 30191204_1

Character Name: 
Shantatta RDM51/WHM01
Shantitti RDM51/WHM01
Shantuttu RDM50
Karaha WHM51
Baruha WHM50

Discord Name (if different from in game): Siryan

Nation: Bastok

Job(level)/Sub Job(level): 99/49

NPC or Monster or item Name: Syrillia

Zone name: Batallia Downs

Coordinates (use !where): X:-515 Y:-16 Z:195 (248)

Item tool link (for items issues only):

Multi-boxing? (multiple clients on same connection): Yup

Steps to reproduce:

Any additional information: After riding raptor to (E-6), can't find Syrillia and can't target anything if she's invisible.

**Comment by Heepster03** [comment]
I know that it “used” to just auto CS when you got to her location without
her physically being there. I’ll try to work on this quest next.

**Comment by SirYanFFXI** [comment]
Thanks for the info Heep. I went back to Jeuno to take raptor again and I was probably not on "the spot". CS triggered

**Comment by EpicTaru** [comment]
Yeah, even if the npc isn't there, just need to ride the raptor around around that little area that the marker for the npc indicates that are at on /map. Once you enter the little "region" that the npc is normally at, the cs will trigger and you'll automatically be sent back to jeuno at the end of the cs

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/136275054-54ec3f56-7dc5-4c83-b55a-5d722627e8c0.png)
This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.
