### ISSUE TITLE
Miyako/Vira (Account Recovery)

### ISSUE THREAD

**Issue by RosaZhang** [HomepointXI/Issues#354]
**Date & Time**: 
Last online: Sep 24, 2018 2:48:37 PM

**Client Version (use `/ver` in game):**
I just reinstalled the game, should be the lastest.

**Character Name:**
Miyako

**Discord Name (if different from in game):**
Vira

**Nation:**
Windurst (RANK 4)

**Job(level)/Sub Job(level):**
SAM62, NIN60 and WAR, RDM, DNC all 49.

**NPC or Monster or item Name:**

**Zone name:** 
I think was Kuftal Tunnel.

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
I only forgot my account name but if reset info is nessesary i will take it.

**Comment by Heepster03** [comment]
@RosaZhang , Reach out to me on Discord. I'll try to get it done by tomorrow.

**Comment by Heepster03** [comment]
Can you reach out to me on Discord, if you'd like this resolved?

**Comment by Heepster03** [comment]
If you're still interested, you can reach me at: Halkuras#1965 on Discord.
