### ISSUE TITLE
Guild Point Item Issue

### ISSUE THREAD

**Issue by neoffxi** [HomepointXI/Issues#356]
**Date & Time**: 
02/22/2019 8:19PM EDT

**Client Version (use `/ver` in game):**
30181205_0

**Character Name:**
Neomorpheus

**Discord Name (if different from in game):**
Neo

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
BLU 99 / RDM 49

**NPC or Monster or item Name:**
Hemewmew (Alchemy Guild Point NPC)

**Zone name:** 
Bastok Mines

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
1. Talk to Alchemy guild point NPC.
2. The NPC requests SCH AF2 belt as the guild point item for the day.

**Any additional information:**
For some reason the NPC requests an AF2 accessory as the guild point item of the day.

**Comment by neoffxi** [comment]
![neomorpheus_2019 02 22_202439](https://user-images.githubusercontent.com/34224364/53279645-3158fb00-36e0-11e9-9b4e-1f51184613da.png)

**Comment by Heepster03** [comment]
This was carried over from LD and has since been fixed awhile back. Closing ticket.
