### ISSUE TITLE
Recovering characters Wargasmic and Unisei

### ISSUE THREAD

**Issue by DeianYM** [HomepointXI/Issues#358]
**Date & Time**: 
11:21 PM EST 3/3/2019

**Client Version (use `/ver` in game):**
Don't know what version the game client is now.

**Character Name:**
Wargasmic
Unisei

**Discord Name (if different from in game):**
Chakrazee

**Nation:**
Both are Sandy nation.

**Job(level)/Sub Job(level):**
Unisei DRK THF
Wargasmic WHM BRD

**NPC or Monster or item Name:**
NA

**Zone name:** 
NA

**Coordinates (use `!where`):**
NA

**Item tool link (for items issues only):**
NA

**Multi-boxing? (multiple clients on same connection):**
NA

**Steps to reproduce:**
NA

**Any additional information:**
Can DM in discord Chakrazee#3094 for additional info I will reply. Not too sure what will be needed but I will try and remember, have not logged in, in a very long time. Since other server management group pretty much during Legiondark.

**Comment by DeianYM** [comment]
Hello?

**Comment by Heepster03** [comment]
I'll try to get to it later tonight when I am free. Sorry for the delay.

**Comment by Heepster03** [comment]
Issue was self-resolved. Closing ticket.
