### ISSUE TITLE
Buggy autoattack behavior

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#359]
**Date & Time**: 

3/3/19

**Client Version (use `/ver` in game):**
30181205_0

**Character Name:**

Maggot

**Discord Name (if different from in game):**

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
99thf/war

**NPC or Monster or item Name:**

I've noticed it camping conquest hnm but likely any mob/zone

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**
autoattack/engage with melee and alt-tab to a different character. Alt-tab back, original character still deals damage but stands idley and the menu reflects a disengaged status so you can't activate weaponskills or actually disengage from mob. Observing from other multi-boxed characters there's no attack animation either. I don't know if this correct place to mention it but I've neither seen nor heard anything about it and I first noticed it ~2 weeks ago. Using borderless windowed mode in Ashita.

![slothgif](https://user-images.githubusercontent.com/26309049/53703253-d315d180-3ddd-11e9-9bbe-f57fb72b5511.gif)

**Any additional information:**

**Comment by Jessland86** [comment]
This is a DSP bug and I think it should be fixed next time we pull DSP.

**Comment by EpicTaru** [comment]
Closing as this should have been fixed a while ago, please comment on ticket again if issue re-presents itself.
