### ISSUE TITLE
Shield Bash not working on Aegis

### ISSUE THREAD

**Issue by CaptSparklez** [HomepointXI/Issues#36]
**Date & Time**: -

**Client Version (use `/ver` in game):** 30180203_1

**Character Name:** Hakubai

**Discord Name (if different from in game):** Haku

**Nation:** San D'Oria

**Job(level)/Sub Job(level):** PLD99/WAR49

**NPC or Monster or item Name:** - 

**Zone name:** -

**Coordinates (use `!where`):** -

**Item tool link (for items issues only):** - 

**Multi-boxing? (multiple clients on same connection):** yes

**Steps to reproduce:**

Using Job Ability "Shield Bash" results in no stun effect when using Aegis. Using it on a different shield (tested with Ochain) seems to work just fine, though. 

**Any additional information:** Both shields are the lvl 99 non-afterglow version

**Comment by nfaletra** [comment]
ItemID: 11927 (For my own reference)
