### ISSUE TITLE
Mizuharu Recovery

### ISSUE THREAD

**Issue by Mizuharu** [HomepointXI/Issues#360]
**Date & Time**: 

3/3/2019

**Client Version (use `/ver` in game):**

ver.30190202_0

**Character Name:**

Zixum

**Discord Name (if different from in game):**

Mizu

**Nation:**

Forgot

**Job(level)/Sub Job(level):**

Ninja??

**NPC or Monster or item Name:**

n/a

**Zone name:** 

n/a

**Coordinates (use `!where`):**

n/a

**Item tool link (for items issues only):**

n/a

**Multi-boxing? (multiple clients on same connection):**

n/a

**Steps to reproduce:**

n/a

**Any additional information:**
Trying to recover old account log in info back from before this was HomePointXI. Account name would have been Mizuharu and character name would be Zixum.

**Comment by Mizuharu** [comment]
In no rush and I know the info provided isn't much, but all I could remember. Sorry. :c

**Comment by Heepster03** [comment]
@Mizuharu , Get in contact with me through Discord. Thanks.

**Comment by Heepster03** [comment]
Resolved.
