### ISSUE TITLE
Ranger Quest: The Fanged One - Old Sabretooth not spawning

### ISSUE THREAD

**Issue by honeycubbinz** [HomepointXI/Issues#361]
**Date & Time**: 
3/5/2019
8:00PM EST

**Client Version (use `/ver` in game):**
30181205_0

**Character Name:**
Brandoh then Brando

**Discord Name (if different from in game):**

**Nation:**
Sandoria

**Job(level)/Sub Job(level):**
Brandon - Thf(99)/Dnc(49)

Brando - Rdm(99)/Whm(49

**NPC or Monster or item Name:**
Old Sabretooth

**Zone name:** 
Sauromugue Champaign

**Coordinates (use `!where`):**
x 665
y -8
z 380 
(129)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No, then yes

**Steps to reproduce:**

Talk to Perih Vashai to flag ranger quest
Walk to Sauromugue Champaign
Click ???
"Nothing happens..."

**Any additional information:**

Thought it might just be Brandoh having an issue, like maybe I killed it by accident before and it wouldn't respawn but also tried it on Brando and got the same result.

I saw there's another issue with this problem out there but didn't see any fix that could be done without coding.

Lemme know what you guys think and thanks.

**Comment by EpicTaru** [comment]
Value of variable **TheFangedOne_Event** is showing as **0**.  Please try logging off one of the charas, talking to Perih Vashai again and see what occurs.  Having both characters online at the same time may be causing the value of this variable to not update correctly.

**Comment by honeycubbinz** [comment]
Tried to talk to Perih Vashai again with just Brandoh with same results.
Logged in Brando to give it another shot and still same results.

She says "My child, if you desire to submit yourself to the laws of naturrre, then go, meet with the fanged king of the beasts and bring back one of his grrreat teeth. Listn to the voice of nature and wait for nature to run herrr course. If nature accepts us, then even we who lack fangs will be perrrmitted to hunt as her rangers."

**Comment by EpicTaru** [comment]
Checked variable's value, did not change on either character.

**Comment by EpicTaru** [comment]
@honeycubbinz Are you still experiencing this issue?

**Comment by honeycubbinz** [comment]
hey man!
Im not sure i haven't played in forever. You can go ahead and close that
case though if no one else is having the problem. sorry about not closing
it.

**Comment by EpicTaru** [comment]
![pol_2019-09-30_10-40-00](https://user-images.githubusercontent.com/26195580/65894410-5cd74e80-e36f-11e9-9d2d-8d7da8f3e27d.png)

Confirmed that NM is spawnable thru normal quest process.

@honeycubbinz Ticket will be closed.  If you discover that you are still unable to spawn the NM, please comment on this ticket for assistance. :)

**Comment by honeycubbinz** [comment]
Thanks for the email :)
