### ISSUE TITLE
To Cure a Cough

### ISSUE THREAD

**Issue by TheToasterbox** [HomepointXI/Issues#363]
**Date & Time**: 
3/6/2019

**Client Version (use `/ver` in game):**

30190202_0

**Character Name:**
Crosander

**Discord Name (if different from in game):**

The Toasterbox

**Nation:**

Currently Sandy

**Job(level)/Sub Job(level):**

Currently Ranger (14)/Thief (7)

**NPC or Monster or item Name:**

Nenne

**Zone name:** 

Sandy South

**Coordinates (use `!where`):**

F-6

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

no

**Steps to reproduce:**

Talk to Nenne after completing The Medicine Women

**Any additional information:**

**Comment by EpicTaru** [comment]
@TheToasterbox please provide more details regarding the issue you are experiencing with this quest.

**Comment by TheToasterbox** [comment]
I talk to nenne, the cutscene begins but then it doesn't continue because the son doesn't appear

**Comment by benfolka** [comment]
when cutscene freezes usually fastcs addon is the problem
disable addon and relogin game
if problem persists disable config plugin too and relogin.

**Comment by EpicTaru** [comment]
Just checked this quest on current version of DSP Master (30191102_1):
![image](https://user-images.githubusercontent.com/26195580/69286110-012f8180-0bb8-11ea-8da2-24329cce946a.png)

Once HomepointXI updates to version **30191102_1 (or newer)**, you should be able to continue on with this quest.

**Comment by EpicTaru** [comment]
No idea why this wasn't closed when the server did its version update, closing now.
