### ISSUE TITLE
Flurry II crashes bootloader

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#364]
**Date & Time**: 
3/7/19

**Client Version (use `/ver` in game):**

30181205_0

**Character Name:**

Agnes

**Discord Name (if different from in game):**

**Nation:**

windurst

**Job(level)/Sub Job(level):**
99rdm

**NPC or Monster or item Name:**

scroll of flurry ii

**Zone name:** 

port windurst

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
attempt to use/learn flurry2 scroll and bootloader immediately crashes. tried 4 times on 2 different machines

**Any additional information:**

**Comment by Heepster03** [comment]
I just tried it on Halk and it seems to be working as intended. Are you sure that you haven't already learned it?

**Comment by Heepster03** [comment]
![Halkuras_2019 03 17_004419](https://user-images.githubusercontent.com/8421725/54486066-d20a8880-4850-11e9-8f20-82cac80747d4.png)

**Comment by stevomatic** [comment]
![Capture1](https://user-images.githubusercontent.com/26309049/54785361-6e8bac80-4bfc-11e9-844e-5d19d577163b.PNG)
Snipping tool wasn't cooperating, but this image should give you the idea. Just tried again with Agnes and Gunt and it crashed, so I looked at my spell list and it appears I know Flurry2 like you suggested, although I'm fairly certain I didn't when this started. Also, I bought a copy of flurry1, which I already know, and it also crashed bootloader when attempting to use it. At any rate  I guess my problem is solved. Thanks!

**Comment by stevomatic** [comment]
accidently closed the issue somehow, sorry lol, {mistake}

**Comment by Heepster03** [comment]
![image](https://user-images.githubusercontent.com/8421725/129226023-329369ae-fd57-407e-ab04-5301cde6db6a.png)

No longer an issue. Working as intended.
