### ISSUE TITLE
Can't use Rudra's storm

### ISSUE THREAD

**Issue by salazer** [HomepointXI/Issues#365]
**Date & Time**: 3/8/2019 8:07 PM Est

**Client Version (use `/ver` in game):**yes

**Character Name:**China

**Discord Name (if different from in game):**

**Nation:**Bastok

**Job(level)/Sub Job(level):**99Thf/49Dnc

**NPC or Monster or item Name:**
https://www.bg-wiki.com/bg/Rudra%27s_Storm

**Zone name:** Cape Teriggan

**Coordinates (use `!where`):**G-6

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**yes

**Steps to reproduce:**
At 1k -3k tp tried to use ws multi time's

**Any additional information:**when i got ws tp and used Rudra's Storm my tp would drop to 0.
I  tried with and without Twashtar same thing tp drain's to 0 but no ws, i can use other ws's it just  Rudra's Storm.

**Comment by Jessland86** [comment]
Sounds like an issue with your Ashitacast or your gear swaps doing something with main/sub/range in it. even if you swap to the exact same things it'll still reduce your tp to 0.

**Comment by Jessland86** [comment]
Tested in game and could not reproduce with twash in main hand vs unlocked via the moogle.

**Comment by salazer** [comment]
Yeah, it was the ac xml fixed it thanks
