### ISSUE TITLE
Game Character Password Forgotten, Need Help

### ISSUE THREAD

**Issue by ymchotmail** [HomepointXI/Issues#366]
**Date & Time**: 

2018, probably March

**Client Version (use `/ver` in game):**

**Character Name:**

Free

**Discord Name (if different from in game):**

**Nation:**

bastok 

**Job(level)/Sub Job(level):**

WAR PLD NIN SMN SAM BLU 99 / SUB JOB RDM 59 BST 28 COR 73 DNC 57 MNK 21 THF 75 BLM 18 

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

Because our servers were shut down for a short time, I unloaded the game, our servers came back to life, but my account password was forgotten. Now I can submit the exact mailbox and the names of game characters, and provide some vague game accounts.

The role name is Free Xiaolaodi Miaomiao Kulang Freeritoice

**Comment by Heepster03** [comment]
@ymchotmail , Please contact me through Discord to handle this issue. Thanks. Removing your personal information for your benefit.

**Comment by Heepster03** [comment]
Resolved.
