### ISSUE TITLE
Bastok 5-1 mission

### ISSUE THREAD

**Issue by eliturk89** [HomepointXI/Issues#367]
**Date & Time**: 03/17/19

**Client Version (use `/ver` in game):**

**Character Name:**Argdos

**Discord Name (if different from in game):**OvalOffice

**Nation:**
bastok

**Job(level)/Sub Job(level):**74rdm/37blm

**NPC or Monster or item Name:**

**Zone name:** 
Fei'yen

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
Finished 5-1 fight but then Black screen no shortcut so I did not get quest.

**Any additional information:**

**Comment by EpicTaru** [comment]
Player's variables indicated that he hadn't completed the battlefield fight.  

Re-did battlefield fight with player.  

Checked player's variables after fight, MissionStatus variable updated correctly (was 11, is now 12) and player also obtained KI 73 (Burnt Seal) as well as no long possesses KI 72 (New Fei'Yin Seal).
