### ISSUE TITLE
Luck of the Draw: Talacca Cove ???

### ISSUE THREAD

**Issue by Refuge001** [HomepointXI/Issues#368]
**Date & Time**: 

03/19/2018, 7:54PM

**Client Version (use `/ver` in game):**

30190305_0

**Character Name:**

Supporting

**Discord Name (if different from in game):**

Refuge

**Nation:**

San d'Oria

**Job(level)/Sub Job(level):**

Bard (99)/Red Mage (33)

**NPC or Monster or item Name:**

Key Item: Forgotten Hexgun

**Zone name:** 

Talacca Cove

**Coordinates (use `!where`):**

X:-62 Y:-7 Z: -137

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

Yes

**Steps to reproduce:**

Click ??? - Nothing happens.

**Any additional information:**

**Comment by Refuge001** [comment]
Not an issue. It was my mistake, I forgot to grab the CS in Ilrusi Atoll, totally forgot about it.

**Comment by EpicTaru** [comment]
Thanks for the update, @Refuge001. Closing this ticket.
