### ISSUE TITLE
No DNC weapons

### ISSUE THREAD

**Issue by SychaeusAcerbas** [HomepointXI/Issues#369]
**Date & Time**: 
all

**Client Version (use `/ver` in game):**
30181205_0

**Character Name:**
Sychaeus

**Discord Name (if different from in game):**

**Nation:**
Sandoria

**Job(level)/Sub Job(level):**
Dnc1/war1

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
no weapons have DNC on them. stuck using an ALL JOBS club

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
Buy a dagger, not be able to use it.

**Any additional information:**

**Comment by EpicTaru** [comment]
H2H until you get dual wield at lvl20, where you should switch to daggers.

**Comment by Jessland86** [comment]
What's the actual dagger you're not able to equip?

**Comment by SychaeusAcerbas** [comment]
nvm, thinking even though everythings lit up that the expansion for wotg didnt take.
cant see sch either.

**Comment by SychaeusAcerbas** [comment]
almost 10 hrs later - 16000 repaired files, an hour to go

**Comment by SychaeusAcerbas** [comment]
issue resolved (and now im apparently ahead of the server version)

**Comment by EpicTaru** [comment]
Being ahead of the server is fine, server will catch up soon
