### ISSUE TITLE
Niddhog's aoe moves don't affect anyone outside the party

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#37]
**Date & Time**: 4/28/2018

**Client Version (use `/ver` in game):** 30180203_1

**Character Name:** Spectre

**Discord Name (if different from in game):**Spectre

**Nation:**Windurst

**Job(level)/Sub Job(level):**pld99/whm49

**NPC or Monster or item Name:**Nidhogg

**Zone name:** DragonAery

**Coordinates (use `!where`):** X: 78, Y: 6, Z: 34 

**Item tool link (for items issues only):** na

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:** Nidhogg's true aoe attacks only affect people in the party who are fighting.  All characters outside party(possibly alliance) are unaffected.

**Any additional information:**

**Comment by nfaletra** [comment]
Need versions of Dragon Breath and Hurricane Wing added to mob_skills table that hit outside of alliance. Then swap them out in Nidhogg's skill list.
