### ISSUE TITLE
purchasing already purchased KI (sheeting, chainwork)

### ISSUE THREAD

**Issue by ediww** [HomepointXI/Issues#370]
**Date & Time**: 
22 march 2019

**Client Version (use `/ver` in game):**
30181222_1

**Character Name:**
Tate

**Discord Name (if different from in game):**

**Nation:**
Sandoria

**Job(level)/Sub Job(level):**
Thief/WHM

**NPC or Monster or item Name:**
Lorena

**Zone name:** 
Blacksmith guild/Bastok Metalworks

**Coordinates (use `!where`):**
x:-106,y:2,z:29 (215)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
try to purchase with guild points?

**Any additional information:**
It appears that already purchased KI related to smiting are purchasable again, repeatedly, causing throwing away guild points for nothing.
I don't have screenshot, but i was offered once Metal ensorsellment and Metal purification, but did not get screenshot and now I am not so sure if it happen (it happened!)
![Tate_2019 03 22_220514](https://user-images.githubusercontent.com/30444503/54943532-2640f700-4f3a-11e9-807b-b73abf0592aa.png)
![Tate_2019 03 22_220418](https://user-images.githubusercontent.com/30444503/54943530-250fca00-4f3a-11e9-8488-b02d5eba31bf.png)

**Comment by Heepster03** [comment]
this was apparently fixed in some update since then. however, you have to back out of the menu after purchasing the KI and then talk again and the KI will no longer be re-obtainable due to owning it.
