### ISSUE TITLE
Horutoto Ruins Cracked Mana Orb Glitch

### ISSUE THREAD

**Issue by Benji-Ninja** [HomepointXI/Issues#371]
**Date & Time**: 
25/3/19

**Client Version (use `/ver` in game):**
Most recent version

**Character Name:**
Affected Toto and previously in another instance Yvris. 
Bien was in the party at the time. 

**Discord Name (if different from in game):**
Benji-Ninja

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
Warrior

**NPC or Monster or item Name:**
Cracked Mana Orb

**Zone name:** 
Horutoto Ruins

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
Cracked Mana Orb

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
Twice now during the first Windurst Mission, after talking to all the NPC and travelling to the ruins in a party. If one person in the party completes the cutscene after interacting with the weird gizmo door, and then searches for the cracked mana orbs. Only one player can activate it. The other members of the party are unable to search the weird magical gizmos to search for the cracked mana orbs. No search scene will show and no mana orb will be added.

We some how solved this one time by one player trying again later by themselves. But even quitting the party does not resolve the new player being unable to search the magical gizmos for the cracked mana orb. 

The new player has spoken to all necessary NPCs. 

**Any additional information:**

**Comment by Heepster03** [comment]
Sounds like a multibox issue. Closing ticket.
