### ISSUE TITLE
Mob TP move Saline Coat has wrong text displayed

### ISSUE THREAD

**Issue by EpicTaru** [HomepointXI/Issues#372]
**Date & Time**: 
04/06/2019 @ 1729:57 CST

**Client Version (use `/ver` in game):**
30181205_0 (matches server version)

**Character Name:**
Epictaru

**Discord Name (if different from in game):**

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
BLU99/RDM49

**NPC or Monster or item Name:**
Ul'xzomit (or any mob in the Xzomit family, really)

**Zone name:** 
Al'Taieu

**Coordinates (use `!where`):**
Anywhere in the zone mobs of this family are found

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Fight any mob in the Xzomit family until it uses TP move Saline Coat.
Text given after TP move is used is incorrect.
Note: It does not give the player the actual mod.  I am unable to confirm if the TP move gave the mob the mod.

**Any additional information:**
![image](https://user-images.githubusercontent.com/26195580/55676087-16f36f00-5893-11e9-8a31-5e90b0cff1f5.png)

**Comment by Heepster03** [comment]
Issue has been resolved for next update!

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/136274415-fc727745-77d8-4fce-9e55-96fc9eddf65a.png)

This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.
