### ISSUE TITLE
Blu spell learned but not on magic list

### ISSUE THREAD

**Issue by SquallerSnake** [HomepointXI/Issues#373]
**Date & Time**: 
04/11/2019 

**Client Version (use `/ver` in game):**
30181222_1

**Character Name:**
Squaller

**Discord Name (if different from in game):**

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
Blu99/Rdm49

**NPC or Monster or item Name:**
Tinnin

**Zone name:** 
Wajaom Woodlands

**Coordinates (use `!where`):**
X: 278, Y: 0.1, Z: -703

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**
After killing Tinnin I learned a blue spell that should be Pyrik Bulwark, but does not appear on the spell list.

**Any additional information:**
![img_20190410_224908](https://user-images.githubusercontent.com/13245127/55934286-638ecf80-5c30-11e9-9b85-4137116c8462.png)

**Comment by EpicTaru** [comment]
@SquallerSnake Try using the Job Ability **Unbridled Learning**.  The spell should then appear in the list of those able for you to cast.

https://www.bg-wiki.com/bg/Pyric_Bulwark

**Comment by SquallerSnake** [comment]
Hello,
if I use Unbridled Learning i can cast other spell like Gates of Hades, those spell are greyed when Unbridled Learning is not active. Pyric bulwark is just not in list.
![img_20190412_085434](https://user-images.githubusercontent.com/13245127/56017938-f5660d80-5d00-11e9-977c-c359b86d8672.png)

**Comment by EpicTaru** [comment]
Is that the very bottom of the list? Make sure it isn't further down. Regardless, I'll check your variables at next chance. Also, looking at it very closely, where in the screenshot, that you originally submitted with the ticket, does it show you learning that spell?

**Comment by SquallerSnake** [comment]
Checked and the spell is 100% not in the list. U can see in the first screenshot Squaller learn a new spell, the only one i can lear from Tinnin is Pyrik Bulwark so...

**Comment by EpicTaru** [comment]
Kk, just checking, I'll check your variables when next able

**Comment by SquallerSnake** [comment]
Learned from Mired Hydra.
