### ISSUE TITLE
Relic Shield Final Stage

### ISSUE THREAD

**Issue by TonyHollows** [HomepointXI/Issues#376]
**Date & Time**:   4/28   9AM-ish

**Client Version (use `/ver` in game):**  30181205_0

**Character Name:**   TonyHollows

**Discord Name (if different from in game):**

**Nation:**  Bastok

**Job(level)/Sub Job(level):**  99Thf/49Dnc

**NPC or Monster or item Name:**  Switchstix

**Zone name:** Castle Zvahl Baileys

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**  Traded 10k piece, shield, necropsyche, and fragment to Switchstix.   He returned the items, but kept the 10k piece.  Now, he is asking if I want to cancel the transaction.

**Comment by EpicTaru** [comment]
@TonyHollows were you multiboxing when the issue occurred?

**Comment by TonyHollows** [comment]
I don't remember, but I don't think so

**Comment by Jessland86** [comment]
I'll see about fixing things when I get back from the movies.

**Comment by Genesis-Nova** [comment]
You're not supposed to trade the 10,000 piece currency to the goblin, you're supposed to trade the stage 4 relic, Necropsyche, and fragment to a ??? in carpenter's landing @ H-10

**Comment by EpicTaru** [comment]
Good comment @Genesis-Nova, but there still remains the issue as to why gobbie boy eats the currency instead of spitting it back at the player. That's a dsp issue that'll be looked into to figure out why.

**Comment by TonyHollows** [comment]
Any headway?

**Comment by Jessland86** [comment]
Taken care of by GM in game.
