### ISSUE TITLE
??? for Detonator ws notorious monster is bugged

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#378]
**Date & Time**: 
5/13

**Client Version (use `/ver` in game):**
30181205_0

**Character Name:**

Agnes

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 
The tree

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

no

**Steps to reproduce:**
Instead of a ??? to spawn the nm, the doohickie thing says "treasure casket" and clicking it doesn't trigger anything

**Any additional information:**

**Comment by EpicTaru** [comment]
Resolved in maintenance prior to last.
