### ISSUE TITLE
Nome - account recovery

### ISSUE THREAD

**Issue by d279020** [HomepointXI/Issues#379]
**Date & Time**: 
2019/05/16

**Client Version (use `/ver` in game):**
current

**Character Name:**
Nome

**Discord Name (if different from in game):**
Alannor

**Nation:**
Sandoria

**Job(level)/Sub Job(level):**
99 WHM RDM BLM

**NPC or Monster or item Name:**
N/A

**Zone name:** 
N/A

**Coordinates (use `!where`):**
N/A

**Item tool link (for items issues only):**
N/A

**Multi-boxing? (multiple clients on same connection):**
N/A

**Steps to reproduce:**
N/A

**Any additional information:**
Sending on behalf of friend:
Current in game chars: Namers/Namera/Namerz/Namerw
Login username was 32378820
But he forgot the password....

**Comment by Heepster03** [comment]
PM sent to Player in question.
