### ISSUE TITLE
Learning Haste 2 crashes game

### ISSUE THREAD

**Issue by wapozzi** [HomepointXI/Issues#380]
**Date & Time**: 5/18/19 2:13PM was last time i tried

**Client Version (use `/ver` in game): 30190430_0

**Character Name: Bthreepio

**Discord Name (if different from in game): Bigbadbill

**Nation: Bostok

**Job(level)/Sub Job(level): 77RDM/38WHM

**NPC or Monster or item Name: Haste II spell

**Zone name:** All

**Coordinates (use `!where`):** All

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** Yes and no, tried both

**Steps to reproduce:** Tried to use learn haste 2 and then the game crashes as it starts the animation 

**Any additional information:** I tried disabling all plugins, etc. reinstalled game and new copy of ashita with no luck.  here is the dump from windows event log

Log Name:      Application
Source:        Application Error
Date:          5/18/2019 2:13:49 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      BILLY-DESKTOP
Description:
Faulting application name: pol.exe, version: 1.0.0.4, time stamp: 0x590830c8
Faulting module name: FFXiMain.dll, version: 3.0.0.0, time stamp: 0x5cc7a730
Exception code: 0xc0000005
Fault offset: 0x000c0c4f
Faulting process id: 0x1124
Faulting application start time: 0x01d50dbc0c131067
Faulting application path: C:\Users\user\Desktop\Ashita\ffxi-bootmod\pol.exe
Faulting module path: E:\Program Files (x86)\PlayOnline\SquareEnix\FINAL FANTASY XI\FFXiMain.dll
Report Id: 077c87af-b4ee-4ff2-b1b7-56b1d76abe4b
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-05-18T21:13:49.278854200Z" />
    <EventRecordID>15858</EventRecordID>
    <Channel>Application</Channel>
    <Computer>BILLY-DESKTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>pol.exe</Data>
    <Data>1.0.0.4</Data>
    <Data>590830c8</Data>
    <Data>FFXiMain.dll</Data>
    <Data>3.0.0.0</Data>
    <Data>5cc7a730</Data>
    <Data>c0000005</Data>
    <Data>000c0c4f</Data>
    <Data>1124</Data>
    <Data>01d50dbc0c131067</Data>
    <Data>C:\Users\user\Desktop\Ashita\ffxi-bootmod\pol.exe</Data>
    <Data>E:\Program Files (x86)\PlayOnline\SquareEnix\FINAL FANTASY XI\FFXiMain.dll</Data>
    <Data>077c87af-b4ee-4ff2-b1b7-56b1d76abe4b</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by wapozzi** [comment]
Learning other spells works fine as tested with protect 4

**Comment by Heepster03** [comment]
This was either an isolated incident or it was previously resolved. No longer an issue.
