### ISSUE TITLE
Jeuno Voidwatch T2 NM Item Drop Error

### ISSUE THREAD

**Issue by Skett** [HomepointXI/Issues#381]
**Date & Time**: 20/05/2019 18:44:33 GMT

**Client Version (use `/ver` in game):** 30190328_2 (Yes I know its too new)

**Character Name:** Skett/Chrystina/Pray

**Discord Name (if different from in game):** Skett

**Nation:** Sandy

**Job(level)/Sub Job(level):** BLU99/RDM49

**NPC or Monster or item Name:** Kalos Eunomia

**Zone name:** Crawlers Nest [S]

**Coordinates (use `!where`):** Planar Rift (unsure of pos)

**Item tool link (for items issues only):** 
This is the first monster of a 2 phase fight, neither drop the listed Rusted Coin
http://homepointxi.com/db/monsters/17478057/Nympha_Eunomia

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:**
Engage Phase one, defeat phase one, engage phase 2, defeat phase 2, review drops. 

**Any additional information:**
![Skett_2019 05 20_184557](https://user-images.githubusercontent.com/12629708/58042643-27a23080-7b33-11e9-8bad-3b2f2a2ce706.png)

**Comment by EpicTaru** [comment]
Please go ahead and provide the screenshot, @Skett.

**Comment by Jessland86** [comment]
Bug: Drops are backwards on this mob. Drops happen after killing phase 1 and not phase 2.
![image](https://user-images.githubusercontent.com/28382433/58044386-9ec4ce00-7b0d-11e9-9832-0dc9a50e1eca.png)
![image](https://user-images.githubusercontent.com/28382433/58044460-cae04f00-7b0d-11e9-9b17-b8a0e7a7d507.png)
![image](https://user-images.githubusercontent.com/28382433/58044533-ffeca180-7b0d-11e9-807b-63c392933efe.png)
![image](https://user-images.githubusercontent.com/28382433/58044550-0aa73680-7b0e-11e9-9f94-88361bf8e28a.png)
