### ISSUE TITLE
BLU JA : Unbridled Learning triggering Curing Waltz II CD

### ISSUE THREAD

**Issue by munkee128** [HomepointXI/Issues#382]
**Date & Time**: 
May 28, 2019 // 09:59 AM PST

**Client Version (use `/ver` in game):**
Tested on 2 systems (different versions)
30181222_1
30190430_0

**Character Name:**
Musubi

**Discord Name (if different from in game):**
Munkee128

**Nation:**
NA

**Job(level)/Sub Job(level):**
BLU/(dnc & nin so far)

**NPC or Monster or item Name:**
NA

**Zone name:** 
NA

**Coordinates (use `!where`):**
NA (but tested on bats in Zeruhn Mines)

**Item tool link (for items issues only):**
NA

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Use the Job Ability, Unbridled Learning for BLU and Curing Waltz II will go on cool down.

**Any additional information:**
Recast addon for Ashita shows Curing Waltz II going on a 5 min cooldown even when my SJ was set to NIN.
If my SJ was DNC and I use Unbridled Learning, Curing Waltz II will go on cooldown on my menu list of Job Abilities. This will make it unable to use Curing Waltz II from menu list, but it will still trigger when used as a macro (/ja "Curing Waltz II" <me>)

**Comment by Heepster03** [comment]
resolved in next update!

**Comment by Heepster03** [comment]
yay, had to redo the fix due to unfucking the first september update. it'll be pulled in when I do it again.

**Comment by EpicTaru** [comment]
This issue was resolved in the maintenance completed the night of 10/16. Please open a new ticket should this issue re-occur.
