### ISSUE TITLE
Sheer animosity/Ix'drk seems broken

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#383]
**Date & Time**: 
5/29

**Client Version (use `/ver` in game):**

30181205_0

**Character Name:**

agnes

**Discord Name (if different from in game):**

**Nation:**

windurst

**Job(level)/Sub Job(level):**
pld/war

**NPC or Monster or item Name:**

Ix'aern drk

**Zone name:** 
the garden of ru'hmet

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

yes

**Steps to reproduce:**
killing aerns in room with ??? isn't resulting in sheer animosity after multiple tries over the past 2 days. I've gotten all the rest of the drops I need inside except Ix'drk.  Last week~ish I made AV sets and was pleasantly surprised that every time I killed the aerns in the ??? room I immediately received sheer animosity, now it seems to be not working at all.

**Any additional information:**

**Comment by stevomatic** [comment]
Update: been trying every day for sheer animosity and finally got it this evening, after killing Ix'drk I waited and tried for animosity again and after about 4 hours of killing the mobs haven't gotten it again
![sloth_3](https://user-images.githubusercontent.com/26309049/58845071-c5bfeb80-8647-11e9-99a2-a29e6ee7f4e7.gif)

**Comment by Jessland86** [comment]
I'll double check our code, but I don't think we changed anything in regards to popping it from stock DSP, which is a "1 in 8" chance from the 3 aerns in each of the 4 rooms.

**Comment by stevomatic** [comment]
Seems to be working normally, I just farmed two Ix'Drk. It seemed so remarkable before because I had gotten about 7 or 8 animosity procs in succession, then a week~ish later, when running around the Garden I never got any procs when I came across the ??? After finishing up all other items for the set I focused on Ix'Drk and still wasn't getting anything. It was so polarized I thought, perhaps, it was broken but now seems like some random coincidence. 
![djcat](https://user-images.githubusercontent.com/26309049/58923268-f28a0680-870c-11e9-9f74-647740bea3bc.gif)

**Comment by EpicTaru** [comment]
Welcome to a fairly low chance, lol. ¯\_(ツ)_/¯彡︵ ┻━┻

**Comment by EpicTaru** [comment]
@stevomatic Are you still experiencing this issue?

**Comment by EpicTaru** [comment]
Closing this issue due to non-response from ticket submitter.  If this issue still exists, @stevomatic, please comment here and the ticket will be re-opened.
