### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by khodge86** [HomepointXI/Issues#386]
**Date & Time**: 
06/07/2019 9:30pm

**Client Version (use `/ver` in game):**
30181205_0

**Character Name:**
Scanlan

**Discord Name (if different from in game):**
None

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
Blm41/whm20

**NPC or Monster or item Name:**

**Zone name:** 
Ghelsba Outpost

**Coordinates (use `!where`):**
X:-188 Y:-10 Z:50 (159)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
Character stuck in DRG fight zone.

**Comment by Jessland86** [comment]
Log out and then log in on the website and use the unstuck tool.

**Comment by EpicTaru** [comment]
@khodge86 Are you still experiencing this issue?

**Comment by Heepster03** [comment]
Checked the DB and this character shows to be in Port Jeuno. You can comment back if any issues further.
