### ISSUE TITLE
Mob Abyssic Cluster wandered off map and is stuck in a mountain?

### ISSUE THREAD

**Issue by EpicTaru** [HomepointXI/Issues#387]
**Date & Time**: 
06/26/2019

**Client Version (use `/ver` in game):**
30181205_0

**Character Name:**
EpicTaru

**Discord Name (if different from in game):**
Rocketpants

**Nation:**
Sandoria

**Job(level)/Sub Job(level):**
THF99/DNC49

**NPC or Monster or item Name:**
http://homepointxi.com/db/monsters/17662494/Abyssic_Cluster

**Zone name:** 
Abyssea - Misareaux

**Coordinates (use `!where`):**
Mob should be spawning/hanging out around Flux #06 at X: -268, Y: -31, Z: 188 but somehow wandered off and got stuck off map to the east of Flux#06

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Wait forever for the mob to never spawn at listed coordinates, then use Watchdog to discovered that it's stuck off map.

**Any additional information:**
![Cluster off map1](https://user-images.githubusercontent.com/26195580/60209158-acadf300-981f-11e9-87f5-b493e733aec1.png)
![Cluster off map2](https://user-images.githubusercontent.com/26195580/60209165-af104d00-981f-11e9-9385-8f7b3e8f86f5.png)

**Comment by Jessland86** [comment]
Despawned/respawned.
