### ISSUE TITLE
Bastok 2-3 Mission (Freeze)

### ISSUE THREAD

**Issue by Aldia270** [HomepointXI/Issues#388]
**Date & Time**: 
6/28/2019, 6:32 P.M EST

**Client Version (use `/ver` in game):**
30190605_0

**Character Name:**
Aldia

**Discord Name (if different from in game):**
N/A

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
75RDM/37WHM

**NPC or Monster or item Name:**

**Zone name:** 
Balga's Dais

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes, however i have a friend with me whom is not and experience same issue.

**Steps to reproduce:**
Attempt to enter the Bastok 2-3 Rank mission fight from Burning Circle in Balga's Dais.

**Any additional information:**
Upon further review with EpicTaru he stated that this issue is most likely a mismatch of ID's due to a newer client version. He requested that i create the ticket more for awareness purposes with the DEV team. I hope we see a version match-up in the future! This is currently preventing ZM progression which has a trickle effect throughout many quest lines in the game as a pre-requisite. 

Please note that this issue is identical to ticket 210 which i will leave the link to below. This issue was resolved and discusses "Jova Compability Dats" which EpicTaru described as .DAT files from other private servers that may have got mixed up with Homepoint's install. 

https://github.com/HomepointXI/Issues/issues/210

**Comment by EpicTaru** [comment]
@Aldia270, until the server gets updated to the latest DSP version and rid us of the version mismatch issue, the rank and mission requirements for reforging armor and entering Dynamis have been reduced so everyone can now do so regardless of progression. 

Once the version mismatch has been resolved the requirements will be reinstated.

**Comment by EpicTaru** [comment]
Resolved in latest version update.  Please open a new issue if this issue is experienced again.
