### ISSUE TITLE
jailed

### ISSUE THREAD

**Issue by jenovaslayer** [HomepointXI/Issues#389]
**Date & Time**: 
idk a year ago

**Client Version (use `/ver` in game):**

dunno

**Character Name:**
caitibrie

**Discord Name (if different from in game):**

amy

**Nation:**

windurst?
**Job(level)/Sub Job(level):**

paladin?
**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
fuck if i know man, i just came back to the game, i've been in jail for pissing off other people with my language.

**Comment by atom0s** [comment]
Nothing has changed, user is still banned.
