### ISSUE TITLE
Account Recovery

### ISSUE THREAD

**Issue by munkee128** [HomepointXI/Issues#390]
**Date & Time**: 

July 15, 2019

**Client Version (use `/ver` in game):**

30181222_1

**Character Name:**

Upgrayedd

**Discord Name (if different from in game):**

Munkee128

**Nation:**

San D'oria

**Job(level)/Sub Job(level):**

1Thf

**NPC or Monster or item Name:**

N/A

**Zone name:** 

N/A

**Coordinates (use `!where`):**

N/A

**Item tool link (for items issues only):**

N/A

**Multi-boxing? (multiple clients on same connection):**

N/A

**Steps to reproduce:**

N/A

**Any additional information:**

I created it yesterday, and I must've incorrectly typed the username. I normally try to keep the username and character name the same, but I must not have because as a test, I created another account with Upgrayedd and it went through. That's when I knew I had typed it in wrong. Delete "Upgrayedd" username if you like, it has no characters attached to it atm.

I have no way of identifying it's my character because I did not put an email to the account yet (since it was just created yesterday). But if I can just get the correct login username for it, I definitely know the password.

Only thing I have/recall, is who purchased the things yesterday that I had up on bazaar.

**Comment by Heepster03** [comment]
Player was PM'd information on Discord.
