### ISSUE TITLE
Puppet master problems (Ghatsad won't accept items to make Valoredge frame)

### ISSUE THREAD

**Issue by Kazatar** [HomepointXI/Issues#391]
**Date & Time**: 939 mst  july 16 2019

**Client Version (use `/ver` in game):**
30181205_0

**Character Name:** Kazatar

**Discord Name (if different from in game):**

**Nation:**
windurst

**Job(level)/Sub Job(level):**
pup 22/dnc 11

**NPC or Monster or item Name:**
ghatsad

**Zone name:** 
whitegate

**Coordinates (use `!where`):**
x 34 y-7 z53 (190)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
quest wont continue he wont accept my trade

**Any additional information:**
for puppet master frame quest

**Comment by EpicTaru** [comment]
Your **PUP_AttachmentStatus** returns a value of 4, which means that you chose the Stormwaker frame (not the Valoredge frame like you stated in DM conversation).  Please attempt to trade the following items to Ghatsad:

**1x Gold Thread
1x Velvet Cloth
1x Wamoura Cloth
1x Brass Ring**

Please then update this ticket with your findings.

**Comment by Kazatar** [comment]
it worked stupid galkan told me the items for valor edge.. inbreeding galkans dont work!!!!
