### ISSUE TITLE
jailed

### ISSUE THREAD

**Issue by Sumthingwo** [HomepointXI/Issues#392]
**Date & Time**: 

07/19/2019

**Client Version (use `/ver` in game):**

**Character Name:**

Sumthingwong
Logie

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

Sorry, i used EasyFarm Bot. Lesson learned wont happen again.

**Comment by EpicTaru** [comment]
@Sumthingwo: Your characters are jailed for a minimum of 3 days starting at midnight tonight, unless otherwise decided upon by Halkuras or Immorality.

**Comment by spectre99** [comment]
User freed along with his alts.
