### ISSUE TITLE
Star Ring desynth recipe 

### ISSUE THREAD

**Issue by salazer** [HomepointXI/Issues#393]
**Date & Time**: 7/27/19 1:00 am est 

**Client Version (use `/ver` in game):**current

**Character Name:**Emel

**Discord Name (if different from in game):**

**Nation:**Bastok

**Job(level)/Sub Job(level):**Blu99/Rdm49

**NPC or Monster or item Name:**star-ring

**Zone name:** Port Jeuno

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**https://www.ffxiah.com/item/15805/star-ring

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**I tried to desynth a Star Ring the recipe not on server

**Comment by Heepster03** [comment]
![image](https://user-images.githubusercontent.com/8421725/132012502-cb76c70f-770c-4f76-8b15-e0b185d62ae6.png)
Issue resolved for next update!

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/136272505-7c7dde0e-e737-49e7-a4d0-b4cd37c77659.png)
This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.
