### ISSUE TITLE
Dancer post 75

### ISSUE THREAD

**Issue by SychaeusAcerbas** [HomepointXI/Issues#394]
Feather step *nonfunctional*
Presto *nonfunctional*

Flourishes III:
Climactic Flourish: activates but doesnt consume finishing moves, has no effect on ws
Striking Flourish : Ditto
Ternary Flourish : Ditto

Dancer empy gear augments nonfunctional abils.

**Date & Time**: 

**Client Version (use `/ver` in game):**

**Character Name:**

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
These abilities are not currently coded here, no timeline as to when they will be implemented.

**Comment by Heepster03** [comment]
The aforementioned abilities have been added to the next upcoming update.

**Comment by EpicTaru** [comment]
This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.
