### ISSUE TITLE
Account recovery

### ISSUE THREAD

**Issue by BigCIAman** [HomepointXI/Issues#395]
**Date & Time**: 
september 4

**Client Version (use `/ver` in game):**
30190605_0

**Character Name:**
Francis

**Discord Name (if different from in game):**
Pacobell#7066

**Nation:**
San D'oria

**Job(level)/Sub Job(level):**

N/A

**NPC or Monster or item Name:**

N/A

**Zone name:** 

don't remember the name but it was a cave

**Coordinates (use `!where`):**
N/A

**Item tool link (for items issues only):**
N/A

**Multi-boxing? (multiple clients on same connection):**

N/A

**Steps to reproduce:**

N/A

**Any additional information:**
i created the account a while ago and i don't know the password if someone can help me recover it would be nice thanks!

**Comment by Heepster03** [comment]
Sent you a PM in Discord.

**Comment by Heepster03** [comment]
Resolved!
