### ISSUE TITLE
Mache earring +1

### ISSUE THREAD

**Issue by SychaeusAcerbas** [HomepointXI/Issues#396]
Mache earring has all the crafting ingredients except 
http://homepointxi.com/db/items/8721/
which should be in the drop table for
cop mission The Warrior's Path .

**Date & Time**: 
Today, Now

**Client Version (use `/ver` in game):**

all versions

**Character Name:**

Sychaeus

**Discord Name (if different from in game):**

SychaeusAcerbas

**Nation:**

USA USA USA

**Job(level)/Sub Job(level):**

Dance/BLU

**NPC or Monster or item Name:**

None

**Zone name:** 

Crawlers nest

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
That actually drops from the higher level version of the battle. Whoever at bg-wiki.com listed it as dropping from the cop mission version didn't double-check where the entry item comes from (and the page for the entry item).
