### ISSUE TITLE
Twashtar Aftermath appears nonfunctional

### ISSUE THREAD

**Issue by SychaeusAcerbas** [HomepointXI/Issues#397]
Aftermath: Occ. deals double damage

The buff appears, but testing in multiple abyssea zones has yet to show a single instance of doubled damage on any mob.  

i monitored using crits which varied between 720-922 on same species mobs in a 3 level range of each other using lvl 3 aftermath (twashtar in offhand), after WS rudra's

**Date & Time**: 
Today

**Client Version (use `/ver` in game):**

30190731_2

**Character Name:**

Sychaeus

**Discord Name (if different from in game):**

SychaeusAcerbas

**Nation:**

Sandy

**Job(level)/Sub Job(level):**
Dnc99/thf49

**NPC or Monster or item Name:**

100's of tigers in abyssea ule, sheep in la thiene

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

Just curebot

**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
Twashtar in offhand? What is in the main hand? @SychaeusAcerbas

**Comment by SychaeusAcerbas** [comment]
derpsichore so i can pyrrhic kleos.

**Comment by EpicTaru** [comment]
Aftermath only applies to the weapon in your main hand slot.  If you have the iLvl119-II version of an Empyrean weapon and unlocked the usage of that weaponskill (normally restricted for usage with the specific weapon) with all weapons of that type (here on HomepointXI), that doesn't mean that you'll receive the Aftermath effects normally associated with that Empyrean weapon if it is not equipped in the main hand slot for the weaponskill usage.

In your case, having the Terpsichore in the main hand doesn't generate the Empyrean Aftermath effect during a weaponskill usage. Only weaponskill that you should be able to generate an Aftermath effect with, with that specific weapon, is Pyrrhic Kleos.
