### ISSUE TITLE
Returning Player, lost login

### ISSUE THREAD

**Issue by captainmyth** [HomepointXI/Issues#398]
**Date & Time**: 
October 9th, 2019
10:10 P.M.

**Client Version (use `/ver` in game):**
30190904_3

**Character Name:**
Draek

**Discord Name (if different from in game):**
captainmyth
or
Dazzda

**Nation:**

Sandy

**Job(level)/Sub Job(level):**

BLU99/WHM49

**NPC or Monster or item Name:**

NA

**Zone name:** 

NA

**Coordinates (use `!where`):**

NA

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

I forgot the initial login to the account containing Draek. I have access to my alt account, with Draekinne, Draekinni, and Drae.

**Comment by Jessland86** [comment]
Per discord: 

> captainmythToday at 3:25 AM
Remembered the pass to my old account!
