### ISSUE TITLE
Missing ???s for An Empty Vessel

### ISSUE THREAD

**Issue by BlueRath** [HomepointXI/Issues#4]
**Date & Time**: 
~23:00 GMT+1

**Client Version (use `/ver` in game):** 
30180203_1

**Character Name:**
Rathian

**Nation:**
San D'Oria

**Job(level)/Sub Job(level):**
THF34/BLM17

**NPC or Monster or item Name:**
Various ???

**Zone name:** 
Valkurm Dunes
Dangruf Wadi

**Coordinates (use `!where`):**
-

**Item tool link (for items issues only):**
-

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**
Tried to do the BLU unlock quest and Waoud asks me to deliver an item. Tried to get the Valkurm Sand from the ??? on the boat that only appears during sandstorms, but it doesn't seem to pop. 

Same applies to the ??? in Dangruf Wadi for the Dangruf Stone. ??? doesn't pop even under clear/sunny weather. 

**Any additional information:**
Might be a version mismatch issue, but was told to open the ticket anyway. Thanks!

**Comment by Willthefluteboy** [comment]
Quest sent me to obtain the Siren's Tear in North Gust. Made sure to have both weapon and shield unequiped. The spot was indicated by an unnamed target location. First loot gave me gil second loot said I already had the tear. Looked in my inventory and it was there.

**Comment by Jessland86** [comment]
When it tells you you obtain x amount of gil from an npc when you should be getting an item, that's a version mismatch. The amount of gil it's "giving" you is the item ID.

I'll look into the other locations and make sure they are spawning.

**Comment by Jessland86** [comment]
Dagruf is fine, it spawned during the correct weather conditions. Valkurm did not.

**Comment by EpicTaru** [comment]
Can also confirm that the Sunsand item in Valkurm Dunes isn't appearing when the weather for the zone is as needed for the Sunsand item to appear.

My client version is 30180306_2.

**Comment by Heepster03** [comment]
![halkuras_2018 04 17_100015](https://user-images.githubusercontent.com/8421725/38878256-2575782c-4226-11e8-891f-6b69cf843f34.png)

Was fixed with the recent maintenance.
