### ISSUE TITLE
Summon Skillchains

### ISSUE THREAD

**Issue by Willthefluteboy** [HomepointXI/Issues#40]
**Date & Time**: Monday, April 30, 2018

**Client Version (use `/ver` in game):** 30180203_1

**Character Name:** Reon

**Discord Name (if different from in game):** Will/Reon

**Nation:** Sandy

**Job(level)/Sub Job(level):** SMN 46 / RDM 23

**NPC or Monster or item Name:** Any combat mob

**Zone name:** Any zone with combat

**Coordinates (use `!where`):** tested in different zones to repeat effect. Worked in all combat zones. Currently at X:162 Y:-32 Z:-20 (116)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** Tried with multi-boxing and without. Same result. 

**Steps to reproduce:** While in combat when you preform the summon's blood pact rage, it is suppose to be able to be followed by a weaponskill to produce a skillchain. This does not happen. 

**Any additional information:** Tested in different locations, different subjobs, and with and without multi-boxing. Same result every time.

**Comment by simthra** [comment]
As a side note neither master-automaton SCs work, nor viceversa. Do I need to open a new ticket about this PUP issue?

**Comment by Willthefluteboy** [comment]
I would as each is their own problem. ^_^ Though now I wonder if you can do so with bst pets either(or if you ever could, I cannot remember) Or DRG for that matter...

**Comment by EpicTaru** [comment]
Yes, please open a separate ticket, @simthra

**Comment by nfaletra** [comment]
None of the skills have skillchain properties set up. :(

**Comment by nfaletra** [comment]
Found the issue on DSP tracker https://github.com/DarkstarProject/darkstar/issues/2495

I will probably fix it here first and then submit to DSP.

**Comment by Jessland86** [comment]
Fixed in today's maintenance.

**Comment by davismj** [comment]
<3
