### ISSUE TITLE
signet

### ISSUE THREAD

**Issue by kingkongchris** [HomepointXI/Issues#400]
hello i need a signet staff and cant surpass rank missions to acquire one please help

**Date & Time**: 

10/11/2019 7:31 pm CST

**Client Version (use `/ver` in game):**

**Character Name:**

kingkongchris

**Discord Name (if different from in game):**

**Nation:**

bastok

**Job(level)/Sub Job(level):**

57thf/25dnc

**NPC or Monster or item Name:**

signet staff

**Zone name:** 

kazham

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
Give me a minute

**Comment by Jessland86** [comment]
Check your dbox.
