### ISSUE TITLE
rank missions

### ISSUE THREAD

**Issue by kingkongchris** [HomepointXI/Issues#401]
hello so i am currently bastokian nation and cannot complete mission 1-1 it goes to black screen each time i try to turn in the required item/items

**Date & Time**: 

10/16/2019 3:36 pm CT

**Client Version (use `/ver` in game):**

**Character Name:**

kingkongchris

**Discord Name (if different from in game):**

**Nation:**

bastok

**Job(level)/Sub Job(level):**
75thf/37dnc

**NPC or Monster or item Name:**

**Zone name:** 

bastok mines

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
Are you sure you have accepted that mission?  I'm not showing a Bastok Mission assigned to you at all:

![image](https://user-images.githubusercontent.com/26195580/66957601-287cb700-f02c-11e9-8dc3-402eec22fe02.png)

**Comment by kingkongchris** [comment]
thank you i have figured it out now

**Comment by EpicTaru** [comment]
Good deal, glad to hear.
