### ISSUE TITLE
Stuck in limbo

### ISSUE THREAD

**Issue by benfolka** [HomepointXI/Issues#402]
**Date & Time**: 15.18

**Client Version (use `/ver` in game):**30190605_0

**Character Name:**Sabutay

**Discord Name (if different from in game):**Sabutay

**Nation:**Sandy

**Job(level)/Sub Job(level):**99war/49sam

**NPC or Monster or item Name:**

**Zone name:** west ronfeure

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**yes

**Steps to reproduce:**
my character camkum was stuck on limbo (it seemed online constantly) then i deleted character camkum now my other chars cant log in please reset me

**Any additional information:**

**Comment by EpicTaru** [comment]
What error message(s) do you receive when you attempt to log your other accounts on?

Please attach screenshots if possible.

**Comment by EpicTaru** [comment]
Also, please attempt to log in character Cankum one more time, please.

Please screenshot and provide here the screenshot of any error message(s) you receive from attempting to log Cankum in.

**Comment by benfolka** [comment]
I deleted Camkum and others cant log on now

i am receiving ffxi-3305 unable to connect world server

could not take screenshot.
i am guessing my problem will be solved next time server resets

**Comment by EpicTaru** [comment]
Did you have other characters logged in when you attempted to delete Cankum?

**Comment by benfolka** [comment]
i guess so

**Comment by EpicTaru** [comment]
Heep or Immo will have to look into this, I've done everything in my power to attempt to resolve it.  Please be patient while this is being researched.

**Comment by benfolka** [comment]
thank you

**Comment by benfolka** [comment]
can i request a server reboot please, it does not have to be imminent, it can be early in the morning when noone is on.

**Comment by benfolka** [comment]
player id of camkum is 34585 does this help ? may be a posfix command for that

**Comment by EpicTaru** [comment]
That's already been attempted. If you are unable to log in, then you need to wait for heep or immo to look into this issue further.

**Comment by benfolka** [comment]
i found the querry database for fixing my char
assuming your db name is dspdb

UPDATE `dspdb`.`chars` SET `pos_zone`='108' WHERE  `charid`=34585;
will send me directly to south gustaberg which will save my other chars

**Comment by benfolka** [comment]
is there any work going on about this.
i am sure this happened to other people 
please solve my problem just like you did to other people
i will check a few times more then move to another server.

**Comment by benfolka** [comment]
i setup myself a dsp server
followed same steps and stuck my char
then i rebooted game server
poof my char was unstuck
hopefully you can restart server when noone is on
thank you.

**Comment by Heepster03** [comment]
Locking and closing.
