### ISSUE TITLE
Cop 5-3 stuck

### ISSUE THREAD

**Issue by billyboy2020** [HomepointXI/Issues#404]
**Date & Time**: 

10/25/2019 --10:25 pm est

**Client Version (use `/ver` in game):**

30190731

**Character Name:**

Billygirl and Lilbilly

**Discord Name (if different from in game):**

**Nation:**

Sandoria

**Job(level)/Sub Job(level):**

99thf and 99rdm

**NPC or Monster or item Name:**

Pherimociel

**Zone name:** 

Rulude gardens

**Coordinates (use `!where`):**

G6

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

Dual box 

**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
Please close the other ticket if this is a duplicate, @billyboy2020
