### ISSUE TITLE
Account Recovery

### ISSUE THREAD

**Issue by gori123** [HomepointXI/Issues#406]
**Date & Time**: 01/11/2019

**Client Version (use `/ver` in game):**---

**Character Name:**Oggy

**Discord Name (if different from in game):**Oggy

**Nation:**Sandy

**Job(level)/Sub Job(level):**99sam/49dnc

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

cant remember login details of my character please restore me.

**Any additional information:**

**Comment by gori123** [comment]
please help me

**Comment by Heepster03** [comment]
Sent you a PM in Discord.

**Comment by gori123** [comment]
hello please send again i just registered my account on discord,
My usernames are oyunsever1 and Oggy on homeffxi server. Character names are Clay and Oggy
dont remember passwords.
Thanks alot for the help.

**Comment by Heepster03** [comment]
Oggy = Sabutay. He's been threatening me in Discord PMs. Locking and Closing the ticket.
