### ISSUE TITLE
Can't start Zilart missions.

### ISSUE THREAD

**Issue by Sinnersslayer** [HomepointXI/Issues#407]
**Date & Time**: 
Anytime

**Client Version (use `/ver` in game):**
301090904_3

**Character Name:**
Assassino

**Discord Name (if different from in game):**
Sinnersslayer

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
THF99/DNC49

**NPC or Monster or item Name:**
---

**Zone name:** 
Norg

**Coordinates (use `!where`):**
everywhere

**Item tool link (for items issues only):**
---

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**
I suppose to get first CS while entering Norg, but it never happen.

**Any additional information:**

**Comment by EpicTaru** [comment]
This is an item caught up in the version mismatch issues.  Server admins are already aware of this and are determining how to deal with it.  Thank you for your patience!

**Comment by Sinnersslayer** [comment]
Any ETA on that?

**Comment by EpicTaru** [comment]
@Sinnersslayer, If you are still interested in this, please send me a DM.  I'll close this ticket in a week if I hear no response from you.
