### ISSUE TITLE
Voidwatch Reqs (Rank 3 ~ Adventurer's Certificate)

### ISSUE THREAD

**Issue by Niobiritzu** [HomepointXI/Issues#411]
**Date & Time**: 12/02/2019 10:00 p.m.

**Client Version (use `/ver` in game)**: 30191102_1

**Character Name:**
(Brother's Characters)
Kazaku
Clara

**Discord Name (if different from in game):**
Niobiritzu

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
Kazaku THF 99/DNC 49
Clara RDM 99/SCH 49

**NPC or Monster or item Name:**
Voidwatch Officer
Concerning the issue of ranking up to 3 and obtaining Adventurer's Certificate.
The other reqs, according to the wiki, are fulfilled.

**Zone name:** 
Southern San d'Oria
(Or BCNM in Giddeus)

**Coordinates (use `!where`):**
N/A

**Item tool link (for items issues only):**
N/A

**Multi-boxing? (multiple clients on same connection):**
Multi and Solo same connection

**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
This issue has since been resolved with the server having updated to 30191204_1.  Please create a new ticket should you experience this issue again.
