### ISSUE TITLE
Trading/Lost Wrong Item to the Gobbie 

### ISSUE THREAD

**Issue by Niobiritzu** [HomepointXI/Issues#413]
**Date & Time**: 
01/04/2020 - 01/05/2020

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Kazaku

**Discord Name (if different from in game):**
Niobiritzu

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
THF99/DNC49

**NPC or Monster or item Name:**
Switchstix

Traded 10,000 Byne Bill and lost it

**Zone name:** 
Castle ZXvahl Baileys

**Coordinates (use `!where`):**
At entrance

**Item tool link (for items issues only):**
Ten Thousand Byne Bill (Item Id: 1457)
http://homepointxi.com/db/items/1457/ten_thousand_byne_bill

**Multi-boxing? (multiple clients on same connection):**
No (Was farming Dynamis so no mutli-box)

**Steps to reproduce:**
Trade to gob after obtaining 4th stage relic weapon.

**Any additional information:**
This is my brother's (Kazaku) character. I'm filling out the report for him. We farmed Dyanmis and then got the items, then he went to the place in Sanctuary of Zi'Tah but it would take the items (found out that he forgot to trade the Necrospyche as well as the other items). So he went back to the gob and he seduced him into trading the 10,000 Byne bill. Send me a message on Discord (Niobiritzu) if you need any additional information. Thank you.

**Comment by EpicTaru** [comment]
So the blank spot in Zi'Tah didn't accept the trade because he forgot to also trade the Necropsyche, but then why did he return to Switchstix and trade the currency to the the gobbie instead of attempting to trade all of the items back to the blank spot? @Niobiritzu

**Comment by Niobiritzu** [comment]
@EpicTaru 
I was watching him do it on a live stream through Discord. When he initially did it, I did not notice that he was not trading the Necrospyche. We thought that perhaps he needed to speak to the goblin. So he went back and the goblin spoke with a different prompt asking for the 10k currency. This ultimately caused the issue. Then when he went back, frustrated, and I asked him to do everything again so I could see (of course not having the currency this time). I saw that he didn't trade the Necrospyche and this is how I know that that is what he was missing the first time.

**Comment by EpicTaru** [comment]
Kk, thanks for clarifying. Heep or Immo will contact him asap.

**Comment by Niobiritzu** [comment]
Thanks!

**Comment by Jessland86** [comment]
Player should now have replacement item.

**Comment by Niobiritzu** [comment]
Confirmed that Player does have the item! Thank you so much for your help!
