### ISSUE TITLE
Dybbuk enemy force closes game

### ISSUE THREAD

**Issue by warlord1352** [HomepointXI/Issues#415]
**Date & Time**:  19:20 1/30/20

**Client Version (use `/ver` in game):**30191204_1

**Character Name:** Bumblebeeman and Cureslave and Erinyes

**Discord Name (if different from in game):** warlord1352

**Nation:** bastok

**Job(level)/Sub Job(level):** blu99/dnc49; rdm91/whm45; war99/dnc49

**NPC or Monster or item Name:**Dybbuk

**Zone name:** abyssea konschtat

**Coordinates (use `!where`):** X: 301, Y: 23, Z: 388 

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** yes

**Steps to reproduce:** fought same enemy....then tried fighting anything else nothing else would force close

**Any additional information:**

**Comment by EpicTaru** [comment]
I am unable to re-create this issue.  Please open a new issue regarding this if the issue presents itself again.
