### ISSUE TITLE
CoP 3-3 Final CS issue

### ISSUE THREAD

**Issue by boxghost7** [HomepointXI/Issues#417]
**Date & Time**: 
February 9, 2020 22:29

**Client Version (use `/ver` in game):**
Version 30191204_1

**Character Name:**
Pakwan

**Discord Name (if different from in game):**
N/A

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
Ranger(99)/Ninja(49)

**NPC or Monster or item Name:**
Cid

**Zone name:** 
Metalworks

**Coordinates (use `!where`):**
X: -13, Y: -10, Z: 1 (205)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Not sure what this means.

**Any additional information:**
Final Cutscene to finish CoP 3-3 The Road Forks

**Comment by EpicTaru** [comment]
Value of **EMERALD_WATERS_Status** variable didn't update after player had defeated the Overgrown Ivy NM in Carpenters' Landing, even though they indicated that they did talk to the NPC Guilloud after having defeated the NM.

Had player talk to NPC Guilloud again, after which the value of the variable did update correctly and player was able to proceed onward with the mission.
