### ISSUE TITLE
Limbus failure

### ISSUE THREAD

**Issue by boxghost7** [HomepointXI/Issues#418]
**Date & Time**: 
02/13/2020 11:49 EST

**Client Version (use `/ver` in game):**
Version 30191204_1

**Character Name:**
Jestr

**Discord Name (if different from in game):**
Jestr

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
Ninja(99)/Dancer(49)

**NPC or Monster or item Name:**

**Zone name:** 
NE Apollyon

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**

**Any additional information:**
Was on the first floor of limbus, when an issue occurred with my account and the server and i got kicked out the game. When i logged back, all the monsters were gone and my key items as well.

**Comment by EpicTaru** [comment]
@boxghost7 closing this ticket due to length of time since the ticket was opened.  I can sponsor a Limbus run for you or refund your gil spent on the Cosmo Cleanse if you so wish, just /tell me in game.
