### ISSUE TITLE
Evisceration quest vanished from log

### ISSUE THREAD

**Issue by simthra** [HomepointXI/Issues#419]
**Date & Time**: 15/03/2020 17.00 GMT+1

**Client Version (use `/ver` in game):** 30191204_1

**Character Name:** Rinoar

**Discord Name (if different from in game):** Thranduil

**Nation:** Sandoria

**Job(level)/Sub Job(level):** brd99/dnc49

**NPC or Monster or item Name:** Jakoh Wahcondalo

**Zone name:** Kazham

**Coordinates (use `!where`):**  100,-15, -113

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:** Went on and broke the latent on the trial dagger, then while trading said dagger to Jakoh wakondalo nothing happens. 
I've noticed the the quest "Cloak and dagger" doesn't show up on any quest log anymore.
TY 

**Any additional information:**

**Comment by EpicTaru** [comment]
Did anything at all appear in your chat log after trading the dagger? @simthra

**Comment by simthra** [comment]
Nope, NPC doesn't react

**Comment by EpicTaru** [comment]
I'll check your variables in a few minutes

**Comment by EpicTaru** [comment]
I still show that you have the Dagger of Trials on your chara, @simthra.

![image](https://user-images.githubusercontent.com/26195580/76706901-ff368480-66b8-11ea-93ad-4a9a4e5c372e.png)

**Comment by simthra** [comment]
Yes, the NPC isn't accepting it

**Comment by EpicTaru** [comment]
As directed in game, please provide the two screenshots requested so that I can examine them.

**Comment by simthra** [comment]
![Rinoar_2020 03 15_184331](https://user-images.githubusercontent.com/12772770/76707121-fbbcf080-66ec-11ea-8396-1f9944e27db6.png)
![Rinoar_2020 03 15_184322](https://user-images.githubusercontent.com/12772770/76707123-04152b80-66ed-11ea-8cf1-4b03297e6552.png)
![Uploading Rinoar_2020.03.15_184322.png…](
![Uploading Rinoar_2020.03.15_184331.png…]()

**Comment by simthra** [comment]
![Rinoar_2020 03 15_184837](https://user-images.githubusercontent.com/12772770/76707212-a0d7c900-66ed-11ea-86dc-4ecebf46528e.png)

**Comment by EpicTaru** [comment]
OK, give me a couple minutes, I'll push you on thru the quest.

**Comment by EpicTaru** [comment]
Player forced thru remainder of quest after verifying player had broken trial weapon (per above screenshots).

Things pushed:

Added KI **MAP_TO_THE_ANNALS_OF_TRUTH**  (KI ID **344**) to Rinoar.

Had to force spawn the WSNM (thru usage of **!spawnmob 17645809**) (nothing occurred when player interacted with the ??? to spawn the WSNM).  Player successfully killed the WSNM.

![image](https://user-images.githubusercontent.com/26195580/76708802-b20ddf00-66c7-11ea-8698-24c1965e9e2a.png)

Added KI **ANNALS_OF_TRUTH** (KI ID **345**) to Rinoar. (Player interacted with the ??? once NM had died but did not receive the KI).

Player then attempted to interact with NPC Jakoh Wahcondalo for completion of quest, NPC only gave standard chat line not related to the WS quest.

At this point, I re-added the WS unlock quest to the character (via **!addquest 5 13**).

Had player interact with NPC Jakoh Wahcondalo again, at which point the player received the correct interaction and WS was unlocked for the character.

Had player drop the Dagger of Trials at this point as it was not necessary any longer for them to retain it with its the broken trial weapon status.

![image](https://user-images.githubusercontent.com/26195580/76709426-9a852500-66cc-11ea-87ea-dec7944d51ee.png)
