### ISSUE TITLE
DRK GS buggy while lvl sync'd in Korroloka Tunnel

### ISSUE THREAD

**Issue by Devolnu** [HomepointXI/Issues#42]
**Date & Time**: Monday, 4/30/2018 

**Client Version (use `/ver` in game):** 30180306_2

**Character Name:** Devolnu

**Discord Name (if different from in game):** Devolnu-Ace

**Nation:**Sandy

**Job(level)/Sub Job(level):** 99DRK/49SAM

**NPC or Monster or item Name:** crabs and leeches

**Zone name:** Korroloka Tunnel

**Coordinates (use `!where`):** x:-336 y:-5 z: 146 (97)

**Item tool link (for items issues only):**N/A

**Multi-boxing? (multiple clients on same connection):** No

**Steps to reproduce:** 
While level synced in Korroloka tunnel at lvl 82 - 89 Great Sword hitting for low damage. at 82 i was hitting for 0s 1s and 2s yet im lvl 99 with a 119 Weapon on. Great Sword skill is capped at lvl 99. all other weapons on Drk are working fine but GS is buggy.

**Any additional information:**

**Comment by nfaletra** [comment]
Which Great Sword?

**Comment by Devolnu** [comment]
Macbain 119

**Comment by nfaletra** [comment]
Hot damn. Basically DSP never thought about Level Syncing 119 weapons. tl;dr The damage scaling was coming out to 0 for weapons with high base damage while level synced at higher levels (like 80+). Fix coming in the next maintenance.
