### ISSUE TITLE
BST flag quest bugged me out

### ISSUE THREAD

**Issue by simthra** [HomepointXI/Issues#420]
**Date & Time**: 15/03/2020 17.00 GMT+1

**Client Version (use `/ver` in game):** 30191204_1

**Character Name:** Duncanidaho

**Discord Name (if different from in game):** Thranduil

**Nation:** Sandoria

**Job(level)/Sub Job(level):** blu99/rdm49

**NPC or Monster or item Name:** Dietmund

**Zone name:** Lower jeuno

**Coordinates (use `!where`):** -84, -6, -167

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:** I've finished the quest and  got the reward, but I am unable to change job to BST (it doesn't even show up on job list in MH).
Ty

**Any additional information:**

**Comment by EpicTaru** [comment]
Issue is resolved.  Player didn't speak with Brutus enough times after completion of the Save My Son quest (the quest that gives the Beast Whistle reward).
