### ISSUE TITLE
NPC names incorrect or in wrong place seems to be conflicting with San D Mission 2-1

### ISSUE THREAD

**Issue by Nerov333** [HomepointXI/Issues#421]
**Date & Time**: 
3/18/2020
5:35pm MST

**Client Version (use `/ver` in game):**
30200304_3

**Character Name:**
Nerov

**Discord Name (if different from in game):**
Nerov333

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
Mnk(18)

**NPC or Monster or item Name:**
Galaihaurat and others going towards Ordelle's Caves for Mission 2-1
NPC's in wrong spots or with wrong names

**Zone name:** 
La Theine Plateau / Ordelle's Caves

**Coordinates (use `!where`):**
E-6, F-6, F-7

**Item tool link (for items issues only):**
N/A

**Multi-boxing? (multiple clients on same connection):**
N/A

**Steps to reproduce:**
Just zoning into La Theine and going towards the canyon and into the canyon for Ordelle's Caves

**Any additional information:**
When talking to the NPCs they do not have the correct names as one of the NPCs is showing a name of rainbow at the top of the path leading down to get to Ordelle's Caves. Attempting to do mission 2-1 for San D. Also talking to the NPC leading up the hill right prior to Ordelles shows a name of Tayula, but that isn't correct and when talking to this NPC it locks out all controls to where you can only rotate your camera as for some reason it disables the controller and keyboard.
Any help would be appreciated.

**Comment by EpicTaru** [comment]
This is caused by the version mismatch between the version of your FFXI client and the version of the server itself.  Will be resolved when the server itself does its version update.

**Comment by Nerov333** [comment]
Thanks for the quick response, any chance of a time frame for when the server will update?
