### ISSUE TITLE
Username/pw recover

### ISSUE THREAD

**Issue by ScorchSter** [HomepointXI/Issues#422]
**Date & Time**: 3/24/2020

**Client Version (use `/ver` in game):**
Current (december download)

**Character Name:**  Heyo and Heyocure

**Discord Name (if different from in game):** Jonathan

**Nation:**  Bastok

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**  I wiped my harddrive due to a pc issue and lost my login information

**Comment by Heepster03** [comment]
If you're still interested, you can reach me at: Halkuras#1965 on Discord.
