### ISSUE TITLE
Exalted bow

### ISSUE THREAD

**Issue by boxghost7** [HomepointXI/Issues#424]
**Date & Time**: 
03/29/2020 11:53 a.m.

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Pakwan

**Discord Name (if different from in game):**

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
Ranger(99)/Dancer(49)

**NPC or Monster or item Name:**
Exalted bow

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
When equipping the exalted bow, arrows won't equip in the ammo box.

**Any additional information:**
Weapon skills doesn't show when the exalted bow is equipped

**Comment by Heepster03** [comment]
This was previously resolved at some point and no longer an issue. I verified, myself, that I can equip the Exalted Bow and also arrows.

**Comment by Heepster03** [comment]
and it also shows me the bow WSs when equipped.
