### ISSUE TITLE
Atonement damage

### ISSUE THREAD

**Issue by xendral** [HomepointXI/Issues#425]
**Date & Time**: 

3/29/2020 11:30am pst

**Client Version (use `/ver` in game):**

30190328_2

**Character Name:**

bozidar

**Discord Name (if different from in game):**

ceriissquishy

**Nation:**

bastok

**Job(level)/Sub Job(level):**

99pld/49war

**NPC or Monster or item Name:**

na

**Zone name:** 

halvung

**Coordinates (use `!where`):**

everywhere

**Item tool link (for items issues only):**

na

**Multi-boxing? (multiple clients on same connection):**

yes

**Steps to reproduce:**

Use Atonement as pld

**Any additional information:**

damage seems to cap at 1287 even with max hate and 100% tp.

**Comment by EpicTaru** [comment]
This is not an issue, the damage output of Atonement was never supposed to be as much as it originally was here before it was corrected.  Per BG-wiki:
![image](https://user-images.githubusercontent.com/26195580/126912737-4080fd46-2a31-4e7a-9d0e-cbc115e229a1.png)
