### ISSUE TITLE
Account Recovery 

### ISSUE THREAD

**Issue by jalestas84** [HomepointXI/Issues#426]
**Date & Time**: 3/31/2020 1321 hours

**Client Version (use `/ver` in game):** 30200304_3

**Character Name:**Sickheals

**Discord Name (if different from in game):**Sick

**Nation:**Sandoria

**Job(level)/Sub Job(level):**10 whitemade

**NPC or Monster or item Name:**

**Zone name:** northern sandoria

**Coordinates (use `!where`):** x:70 y:0 z:22 )213)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**yes

**Steps to reproduce:**

**Any additional information:** I have my main account login name as Sick and made an alt account for a curebot, but i cannot for the life of me remember the account login name I used.  It is only a level 10 whitemage named sickheals

**Comment by Heepster03** [comment]
If you're still interested, you can reach me at: Halkuras#1965 on Discord.
