### ISSUE TITLE
Happo Shuriken unequips any item in Sub slot

### ISSUE THREAD

**Issue by boxghost7** [HomepointXI/Issues#428]
**Date & Time**: 
April 20th, 2020 12:16

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Jestr

**Discord Name (if different from in game):**
Jestr/Boxghost

**Nation:**
Bastok *wookie noise*

**Job(level)/Sub Job(level):**
Ninja(99)/Dancer(49)

**NPC or Monster or item Name:**
Happo Shuriken (ItemID 21353)
Happo Shuriken (ItemID 21354)

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/21353
http://homepointxi.com/db/items/21354

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
When trying to equip happo shurikens, it unequips the sub hand weapon and trying to equip the sub hand back on, unequips the happo shurikens.

**Any additional information:**

**Comment by neoffxi** [comment]
![Untitled](https://user-images.githubusercontent.com/34224364/79776324-9075c800-8303-11ea-8d41-09e8b85877fb.jpg)

**Comment by EpicTaru** [comment]
@Heepster03, @Jessland86 for both these items, in item_armor_custom.sql, their rows need changed.

Currently they are:
```
REPLACE INTO `item_armor` VALUES (21353,'happo_shuriken',99,117,4096,22,0,0,8,2);
REPLACE INTO `item_armor` VALUES (21354,'happo_shuriken_+1',99,118,4096,22,0,0,8,2);
```

Needs to be updates to:
```
REPLACE INTO `item_armor` VALUES (21353,'happo_shuriken',99,117,4096,22,0,0,8,0);
REPLACE INTO `item_armor` VALUES (21354,'happo_shuriken_+1',99,118,4096,22,0,0,8,0);
```

**Comment by EpicTaru** [comment]
This issue was fixed in a previous maintenance.  Closing ticket.
