### ISSUE TITLE
Latent: Regain on Goblin Cest and Krousis Ring

### ISSUE THREAD

**Issue by neoffxi** [HomepointXI/Issues#429]
**Date & Time**: 
04/20/2020

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Neomorpheus

**Discord Name (if different from in game):**
NeoArmy

**Nation:**
Bastok

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**
Goblin Cest and Krousis Ring

**Zone name:** 
n/a

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/15931/goblin_cest
http://homepointxi.com/db/items/15849/krousis_ring

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**

**Any additional information:**
The Maat augments for each item varies depending on what job receives the reward. If an RDM receives the belt, then it comes with latent: +10 regain (with weapon drawn). Similarly, when a BLU receives the ring, then it comes with latent: +10 regain (with weapon drawn).

Here is the code snippet from Augments.sql and Maat.lua

[[  SQL\Augments.sql  ]]
`INSERT INTO `augments` VALUES (59, 0, 0, 0, 0, 0); -- Latent effect: Regain+1 (Do via Script: triggered with your current weapon drawn for 1 TP/tick.)`

[[  Goblin Cest  ]]
`elseif (mJob == 5) then -- RDM`
               ` aug_1 = 554; val_1 = 1; aug_2 = 512; val_2 = 0; aug_3 = 59; val_3 = 0; -- INT+2 MND+2, STR+1 Latent effect: Regain+1`

[[  Krousis Ring  ]]
`elseif (mJob == 16) then -- BLU`
               ` aug_1 = 57; val_1 = 3; aug_2 = 59; val_2 = 0; -- Magic crit. hit rate+4, Latent effect: Regain+1`

Since augment values are +1, then the actual values for +10 regain should be 9 and not 0.
The code was not adjusted when SE transitioned TP from base 10^2 to 10^3.

**Comment by Heepster03** [comment]
In the next update... Due to the fuckery with trying to make this work. These two items will now inherit REGAIN+9, which will display as Latent Regain+10; however you will get 9TP/tick. Every time I bump it up to 10/tick, the description changes on the item to Latent Regain+20 and I'm just not going to deal with over assuming like that for the time being. At least it will work now regardless of being engaged or not and will be more that 1TP/tick as was originally designed.

**Comment by EpicTaru** [comment]
This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.
