### ISSUE TITLE
Pygmytois hitbox too large

### ISSUE THREAD

**Issue by Willthefluteboy** [HomepointXI/Issues#43]
**Date & Time**: April 30th, 2018

**Client Version (use `/ver` in game):** 30180203_1

**Character Name:** Reon

**Discord Name (if different from in game):** Will/Reon

**Nation:** Sandy

**Job(level)/Sub Job(level):** THF 99 /DNC 49

**NPC or Monster or item Name:** Pygmytoise

**Zone name:** Gustav Tunnel

**Coordinates (use `!where`):** x:64 y: 0 z: 198 (78)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** Both yes and no. happens in both types. 

**Steps to reproduce:** Fight a Pygmytois. Move to the maximum distance of 7.8 away from mob and still attacking. It can also attack you at that distance. 

**Any additional information:**

**Comment by TeoTwawki** [comment]
@nfaletra wouldn't it be great if the field that controls this in mob_family_system.sql was actually a) properly labeled and b) related to in game yalms measurements? `#dreams`
sadly neither is true. But I'd bet its set identically to regular (larger) sized adamantoise's

**Comment by nfaletra** [comment]
Mob size for this family was set larger than Aspid >.>
