### ISSUE TITLE
Sahagin Key quest

### ISSUE THREAD

**Issue by Amhio** [HomepointXI/Issues#430]
**Date & Time**:   4-26-2020

**Client Version (use `/ver` in game):** 30200304_3

**Character Name:** Amhio

**Discord Name (if different from in game):**

**Nation:** Windurst

**Job(level)/Sub Job(level):** THF99/DNC49

**NPC or Monster or item Name:** Norg Shell

**Zone name:** Sea Serpent's Grotto 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:** Unable to obtain Norg Shell for Sahagin Key quest.

**Comment by EpicTaru** [comment]
Please /tell me in game when you are on the outside edge of the door, @Amhio.

**Comment by EpicTaru** [comment]
Player pulled to inside edge of door.  Player had been attempting to fish up the item.  Player needed access past the Ornamented Door in order to battle the Polearm WSNM

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/80320084-e9e56780-87d9-11ea-8963-05e69c8a3e98.png)
