### ISSUE TITLE
PUP Relic Body Aptant Reforge

### ISSUE THREAD

**Issue by Uzi904** [HomepointXI/Issues#431]
**Date & Time**:  may,9,2020 9:00am

**Client Version (use `/ver` in game):** 
30191204_1

**Character Name:** Uzi

**Discord Name (if different from in game):**
Uzi

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
99Pup

**NPC or Monster or item Name:**

Relic Moogle/npc

**Zone name:** 

tavnazian safehold

**Coordinates (use `!where`):**

H-8

**Item tool link (for items issues only):**

http://homepointxi.com/db/items/10687/pantin_tobe_+2

**Multi-boxing? (multiple clients on same connection):**
Yea

**Steps to reproduce:**

Trading Pantin Tobe+2 & 25 aptant of pera to moogle per wiki relic reforge page, not upgrading.
**Any additional information:**

**Comment by EpicTaru** [comment]
Verified that that is the correct Aptant needed per the wiki but cannot see anything at all in the LD code for PUP to confirm.  This is all yours, @Heepster03 and @Jessland86!

**Comment by Jessland86** [comment]
Hotfixed.
