### ISSUE TITLE
Account Recovery

### ISSUE THREAD

**Issue by skye2388** [HomepointXI/Issues#432]
**Date & Time**: 
5/9/20, 11:40 AM

**Client Version (use `/ver` in game):**

**Character Name:**
Benji (WHM99/RDM49)
Bailey (THF99/DNC49)

**Discord Name (if different from in game):**
Kevo #9064

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
WHM99/RDM49
THF99/DNC49

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**

**Any additional information:**

**Comment by Heepster03** [comment]
If you're still interested, you can reach me at: Halkuras#1965 on Discord.
