### ISSUE TITLE
No EXP from Greater Manticore in Cape Teriggan while Level-Synced

### ISSUE THREAD

**Issue by FluXed314** [HomepointXI/Issues#433]
**Date & Time**: 
5/25/2020 Around 9:00 CST

**Client Version (use `/ver` in game):**
30200327_2

**Character Name:**
Amethra

**Discord Name (if different from in game):**
FluXed314 #4104

**Nation:**
Windhurst

**Job(level)/Sub Job(level):**
BLM 73 / WHM 36

**NPC or Monster or item Name:**
Greater Manticore

**Zone name:** 
Cape Teriggan

**Coordinates (use `!where`):**
I-8

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
3 man party, level-synced to 73, killed a Greater Manticore(Tough) and received no experience points, checked if anyone called for help, no one did. Tried killing a second one, once again received no experience.

**Any additional information:**
Party Members were Lander on WAR99/DNC49 and Shanked BLM73/WHM36 as well as myself on BLM73/WHM36. We were synced to level 73 at the time of both kills.

![Amethra_2020 05 25_211008](https://user-images.githubusercontent.com/37763973/82853880-7dd74b80-9ecc-11ea-8826-75c4779d8148.png)
![Amethra_2020 05 25_211120](https://user-images.githubusercontent.com/37763973/82853884-8039a580-9ecc-11ea-84ca-2806d7487eb6.png)

**Comment by EpicTaru** [comment]
Closing this issue, please create a new ticket if this issue presents itself again.
