### ISSUE TITLE
BCNM "Creeping doom" Working

### ISSUE THREAD

**Issue by boxghost7** [HomepointXI/Issues#434]
**Date & Time**: 
05/31/2020 7:04pm EDT

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Jestr

**Discord Name (if different from in game):**
Jestr

**Nation:**
Murica!!!!! (Bastok)

**Job(level)/Sub Job(level):**
NIN(99)/THF(49)

**NPC or Monster or item Name:**
Bitoso

**Zone name:** 
Balga's Dais

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**
-Traded the sky orb to the burning circle.
-Entered fight with no issues.
-Began casting buffs and used !regen
-Walked to Bitoso and engaged fight.
-Defeated Bitoso and had chest pop.
-Told Bitoso, "my fo-fo, make sho none of yo kids grow"
-Open chest and got a various of drops.
-Was zoned out after chest was opened.

**Any additional information:**
I LOVE YOU!!!......STILL lol

**Comment by EpicTaru** [comment]
Confirmed that this BCNM works as well as some others. Refer to the HP wiki page for BCNM/KSNM Status (http://wiki.homepointxi.com/BCNM/KSNM_Status) for more information.  Closing ticket.
