### ISSUE TITLE
Account Recovery 

### ISSUE THREAD

**Issue by RealMefit** [HomepointXI/Issues#435]
**Date & Time**: 
I think in 2016

**Client Version (use `/ver` in game):**
Ashita can’t remember the version

**Character Name:**
Mefit 

**Discord Name (if different from in game):**

Mefit

**Nation:**

Can’t remember

**Job(level)/Sub Job(level):**

Wanna believe Rdm 

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

**Comment by Heepster03** [comment]
If you're still interested, you can reach me at: Halkuras#1965 on Discord.
