### ISSUE TITLE
~ Abyssean VNM ~ Cannot upgrade demilune abyssite colorful -> indigo 

### ISSUE THREAD

**Issue by simthra** [HomepointXI/Issues#437]
**Date & Time**:  11/06/20 12.40 GMT+1

**Client Version (use `/ver` in game):** 30191204_1

**Character Name:** Thranduil

**Discord Name (if different from in game):**

**Nation:** Bastok

**Job(level)/Sub Job(level):** MNK99/WAR49

**NPC or Monster or item Name:** Gamayun (MobID 17818071)

**Zone name:** Abyssea Grauberg

**Coordinates (use `!where`):** X: 512, Y: 7, Z: 393

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** yes

**Steps to reproduce:** I've been trying for 3 hours to upgrade the demilune abyssite (clear->indigo) in order to spawn the T3 mob, but no deal so far. I've never had such bad streak with others AVNM. Is this W.A.I.? Ty

**Any additional information:**

**Comment by EpicTaru** [comment]
So I have no direct viewability into the code behind the Voidwalker NM System, only @Heepster03 and @Jessland86 can see what the percentages are for the upgrading of the abyssites.  From what I've seen on retail wikis though, the upgrade isn't a 100% thing.

**Comment by simthra** [comment]
Yea, i'm aware that the upgrade is % chance, but now 6 hrs and counting ...

**Comment by EpicTaru** [comment]
I know, my statement about that was for all, not for just those in this issue.

**Comment by EpicTaru** [comment]
@simthra I'm gonna go (force)spawn and kill that VNM about 100ish times with my GM and see if the abyssite upgrades or not, I'll report back with my findings.

**Comment by EpicTaru** [comment]
Exhausted 100 kill spree completed, abyssite didn't upgrade a single time.

**Comment by EpicTaru** [comment]
![VNM test1](https://user-images.githubusercontent.com/26195580/89589656-a99b7980-d80b-11ea-9273-2ba8b4a6c1ad.png)
![VNM test2](https://user-images.githubusercontent.com/26195580/89589660-aacca680-d80b-11ea-9ff5-07d23f0b8f1f.png)

**Comment by Heepster03** [comment]
![image](https://user-images.githubusercontent.com/8421725/132079462-f942caf5-d888-4713-b2ce-ceb96e3e4ba1.png)

It is now working and will be in next update!

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/136267784-1ed40b97-bf83-4e20-a533-a0813a5c96c3.png)

This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.
