### ISSUE TITLE
Missing Mod: Nirvana

### ISSUE THREAD

**Issue by neoffxi** [HomepointXI/Issues#438]
**Date & Time**: 
06/16/2020 12:38 PM EDT

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Neomorpheus

**Discord Name (if different from in game):**
NeoArmy

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
99 SMN / 49 RDM

**NPC or Monster or item Name:**
Nirvana (119 Afterglow) (Item ID 21142)

**Zone name:** 
n/a

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/21142/nirvana

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
The mentioned item is missing one of its best mods, +2 avatar level.

**Any additional information:**
The additional 2 extra levels for the avatar is HUGE. It offers more HP, stats (str, int, etc.), and plays a huge role in the resist / level difference calculations.

If anything, the 119 Nirvana can be implemented similar to how Sancus Sachet  sets the avatar's level to 119. In Nirvana's case, it will be 119 + 2 = 121.

**Comment by Heepster03** [comment]
moved to #559
