### ISSUE TITLE
Account Recovery

### ISSUE THREAD

**Issue by LimitGlove** [HomepointXI/Issues#439]
**Date & Time**: 7/23/2020

**Client Version (use `/ver` in game):**

**Character Name:** Limit

**Discord Name (if different from in game):** Limit

**Nation:** Bastok

**Job(level)/Sub Job(level):** RDM18/WAR9

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

I forgot my username and password, I know the email I used though.

**Any additional information:**

**Comment by Heepster03** [comment]
If you're still interested, you can reach me at: Halkuras#1965 on Discord.
