### ISSUE TITLE
Tunga not respawning

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#44]
**Date & Time**: 

851pm est 5/1/18

**Client Version (use `/ver` in game):**
30180203_1

**Character Name:**

agnes

**Discord Name (if different from in game):**

**Nation:**

bastok

**Job(level)/Sub Job(level):**

blm/rdm

**NPC or Monster or item Name:**
tunga

**Zone name:** 

abyssea attohwa

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**
pulled tunga south of spawn point where it deaggro'd (presumably,) despawned and hasn't respawned after like an hour and counting

**Any additional information:**

**Comment by Jessland86** [comment]
Mob was in a wall or something from deagroing. When I tried to pop it it did not spawn(already spawned), I pulled it back to it's starting position, and is able to be pulled now.
