### ISSUE TITLE
2-3 workaround

### ISSUE THREAD

**Issue by Sorablades** [HomepointXI/Issues#440]
**Date & Time**: 7/27/20 11:44 a.m. EST

**Client Version (use `/ver` in game):** 30200217_0

**Character Name:** Sorablades

**Discord Name (if different from in game):** Sora

**Nation:** Sandy

**Job(level)/Sub Job(level):** 99BLU/49DNC

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

**Comment by Sorablades** [comment]
![IMG_20200727_115054](https://user-images.githubusercontent.com/68862972/88563391-ef806280-cfff-11ea-877e-2afdfe8140f0.jpg)

**Comment by EpicTaru** [comment]
@Sorablades please type `/ver` in game and it'll tell you what client version you are using.  Please add that number to the relevant section of the above form.

I'll be online in a few minutes. to verify your variables

**Comment by Sorablades** [comment]
Ver 30200217_0

**Comment by EpicTaru** [comment]
Verified deletion/addition of any KIs that needed to be deleted and adjustment of the MissionStatus/any other variables necessary according to the code for completion of the battle.  Congrats, @Sorablades!
