### ISSUE TITLE
Rank 5-2 Frozen after battle cutscene

### ISSUE THREAD

**Issue by PunchdrunkXI** [HomepointXI/Issues#443]
**Date & Time**: 7.30PM Tuesday, 28th of July 2020

**Client Version (use `/ver` in game):**30200604_0

**Character Name:**Punchdrunk, Curedrunk and Swipedrunk

**Discord Name (if different from in game):**Punchdrunk

**Nation:**Bastok

**Job(level)/Sub Job(level):**99MNK/49WAR

**NPC or Monster or item Name:**5-2 Cutscene

**Zone name:** The Throne room

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**Yes

**Steps to reproduce:**

**Any additional information:**Attaching image of kill/battle completion time
![Punchdrunk_2020 07 28_191103](https://user-images.githubusercontent.com/68868049/88707507-3c506000-d10a-11ea-871c-7cbc46c6527f.png)

**Comment by EpicTaru** [comment]
Thanks for the screenshot!

Verified deletion/addition of any KIs that needed to be done and adjustment of the MissionStatus/any other variables necessary according to the code for completion of the battle. You should be good to continue the rest of the storyline for the mission.  Congrats!
