### ISSUE TITLE
5-2 Bastok Mission Workaround

### ISSUE THREAD

**Issue by Skimmyson** [HomepointXI/Issues#444]
**Date & Time**: 07/28/2020

**Client Version (use `/ver` in game):**30200702-1

**Character Name:**Skimmy

**Discord Name (if different from in game):**Skimmyson71

**Nation:**Bastok

**Job(level)/Sub Job(level):**70 Mnk/35Dnc

**NPC or Monster or item Name:**Shadowlord

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**No

**Steps to reproduce:**

**Any additional information:**frozen in cs at door.

**Comment by PunchdrunkXI** [comment]
![Punchdrunk_2020 07 28_191103](https://user-images.githubusercontent.com/68868049/88708254-49ba1a00-d10b-11ea-9dc8-b28b9e6fc560.png)

**Comment by EpicTaru** [comment]
Thanks for the screenshot!

Verified deletion/addition of any KIs that needed to be done and adjustment of the MissionStatus/any other variables necessary according to the code for completion of the battle. You should be good to continue the rest of the storyline for the mission.  Congrats!
