### ISSUE TITLE
Legion floor 5 issue

### ISSUE THREAD

**Issue by Sorablades** [HomepointXI/Issues#446]
**Date & Time**: 8/14/2020 6:58 p.m. EDT

**Client Version (use `/ver` in game):** 30181205_0

**Character Name:** Sorablades

**Discord Name (if different from in game):** Sora

**Nation:** Sandy

**Job(level)/Sub Job(level):** 99/49 BLU/DNC

**NPC or Monster or item Name:** N/A

**Zone name:** Legion Floor 5

**Coordinates (use `!where`):** not sure

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** yes

**Steps to reproduce:** Entering Floor 5

**Any additional information:** Both sets of monsters spawn simultaneously
 after entering the floor

**Comment by Jessland86** [comment]
Tested, could not reproduce. Mobs do not despawn on a players death/wipe in Legion. If someone wiped on the second wave, mobs will still be up when entering. spawning a new first wave while the second wave is still up from a previous run/failure.
