### ISSUE TITLE
Shadow Lord Battle

### ISSUE THREAD

**Issue by boxghost7** [HomepointXI/Issues#447]
**Date & Time**: 
08/19/2020 10:01

**Client Version (use `/ver` in game):**
The newest version...im stuck at cs atm

**Character Name:**
Jestr & Myblueballs

**Discord Name (if different from in game):**
Boxghost

**Nation:**
Bastok & Windurst

**Job(level)/Sub Job(level):**
Nin(99)/Dnc(49)
Rdm(99)/whm(49)

**NPC or Monster or item Name:**
The door called Lion

**Zone name:** 
Castle Zvahl Keep

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**
After talking to NPC for the shadow lord fight (Mission 5-2), zoned to Castle Zvahl Keep and went through Ore Door. Walk down the path, clicked on the door for the cutscene to trigger and my characters are walking into a closed door.

**Any additional information:**

**Comment by EpicTaru** [comment]
Used !**release** command to force characters thru the stuck CS, but then had to use the **!bring** command to force a zone of the characters as they were unable to target the Ore Door, probably due to the frozen camera issue caused by the !release command usage.

**Comment by boxghost7** [comment]
![20200819_102424](https://user-images.githubusercontent.com/60934733/90647472-57445a80-e206-11ea-94d0-5ebaccb211d7.jpg)

**Comment by EpicTaru** [comment]
Verified deletion/addition of any KIs that needed to be done and adjustment of the MissionStatus/any other variables necessary according to the code for completion of the battle. Congrats!
