### ISSUE TITLE
Guatambu Log

### ISSUE THREAD

**Issue by boxghost7** [HomepointXI/Issues#448]
**Date & Time**: 
08/19/2020 16:04

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Jestr

**Discord Name (if different from in game):**
Boxghost

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
Nin(99)/dnc(49)

**NPC or Monster or item Name:**
Guatambu Log

**Zone name:** 
Somewhere in Vana'diel

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/4018/guatambu_log

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
Trying to make arasy bow and one of the items needed is guatambu lumber, which comes from guatambu log and that is no where to be found on hp wiki.

**Any additional information:**

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/90684647-2b3ccf80-e22e-11ea-960a-eb5eabfde681.png)

**Comment by Jessland86** [comment]
AH bot sells these now. 10k each 120k a stack
