### ISSUE TITLE
Unable to equip any bullet w/ Arasy Gun

### ISSUE THREAD

**Issue by TrezThorne** [HomepointXI/Issues#45]
**Date & Time**:  May 4th, 2018 @ 02:02

**Client Version (use `/ver` in game):** 30180329_1

**Character Name:** Trez

**Discord Name (if different from in game):** Trez Thorne

**Nation:** Bastok

**Job(level)/Sub Job(level):** COR(99)/RNG(32) 

**NPC or Monster or item Name:** Arasy Gun 

**Zone name:** Bastok Markets; S. Gustaberg

**Coordinates (use `!where`):** X: -351 Y: -10 Z: -172 (223)

**Item tool link (for items issues only):** ? Uncertain how to find this info. 

**Multi-boxing? (multiple clients on same connection):** No

**Steps to reproduce:** Equip Arasy Gun, then equip any bullet

**Any additional information:** Devolnu crafted the ilvl 119 gun for me, but upon equipping the weapon, it immediately unequips my ammunition. Tried with different level bullets with the same outcome. When attempting to equip any bullet, it will unequip the gun, back and forth, ad nauseam.

**Comment by nfaletra** [comment]
http://homepointxi.com/db/items/22135/arasy_gun

**Comment by nfaletra** [comment]
Confirmed fixed after update.
