### ISSUE TITLE
quest for rank 3 glitch

### ISSUE THREAD

**Issue by krissykat1994** [HomepointXI/Issues#451]
**Date & Time**: 
I dual boxed two chars doing the rank quests and i was allowed to trade in to onz of mythril sand to npc on tsuki character but it will not take it from my Annabella character. 8-29-2020 8:46PM

**Client Version (use `/ver` in game):**

30190202_0

**Character Name:**

Annabella

**Discord Name (if different from in game):**

krissykat

**Nation:**

Sandoria
**Job(level)/Sub Job(level):**
99RDM/49BLM

**NPC or Monster or item Name:**

Onz of Mythril sand

**Zone name:** 

Metal works

**Coordinates (use `!where`):**

Savae E Paleade Metal works

**Item tool link (for items issues only):**

Onz of mythril sand
**Multi-boxing? (multiple clients on same connection):**

Yes Tsuki and Annabella
**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
@krissykat1994 you need to complete all of the fields on the ticket before I can start investigating this issue.

**Comment by EpicTaru** [comment]
Only NPC in the mission line that can set the MissionStatus variable to 0 is Halver and he only does that setting for Sandoria 9-2, which this character isn't yet on.  

In the flow of the code, when the character is assigned Sandoria mission 6 (Journey to Bastok) the setting of the MissionStatus variable should have been set to the **3**.  Then talking to Pius sets it to a value of **4**.  Then talking to Ghrom sets it to a value of **5**.  

Given that both characters were able to receive the cutscene from Ghrom this mean that the setting of the variable for Annabella wasn't correctly set to 5 and the multibox glitch instead cleared the variable value entirely for Annabella, preventing the character from being able to receive the subsequent cutscene from Savae when attempting to trade the mythril sand.

Annabella's MissionStatus variable has now been set to the correct value of **5**. Please attempt trading the mythril sand to Savae again, @krissykat1994.  Please respond here if you are able to correctly do so or not.

**Comment by krissykat1994** [comment]
ty ET!!! :D it worked!!!!

**Comment by EpicTaru** [comment]
Awesome, wonderful to hear! Closing this ticket now.
