### ISSUE TITLE
~ Discarded item unintentionally ~

### ISSUE THREAD

**Issue by simthra** [HomepointXI/Issues#452]
**Date & Time**: sep 07 2020

**Client Version (use `/ver` in game):** 30191204_1

**Character Name:** squaller

**Discord Name (if different from in game):** thranduil

**Nation:** bastok

**Job(level)/Sub Job(level):** thf 99/dnc 49

**NPC or Monster or item Name:** Plunderer'vest

**Zone name:** bastok mines

**Coordinates (use `!where`):** MH

**Item tool link (for items issues only):** 
http://homepointxi.com/db/items/26810

https://www.ffxiah.com/item/26810/plunderers-vest

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:** Unintentionally discarded the item from inventory. May I have it restored (first time)?
![Squaller_2020 09 07_103827](https://user-images.githubusercontent.com/12772770/92367652-fa4a0f00-f0f6-11ea-942e-721342c19c63.png)

**Any additional information:**

**Comment by EpicTaru** [comment]
Item restoration is a one time deal. Item restoration of any other item will be denied. Do you still wish to have this item restored, @simthra?

**Comment by simthra** [comment]
yes pls

**Comment by Jessland86** [comment]
Resolved.
