### ISSUE TITLE
Raaz tusk

### ISSUE THREAD

**Issue by boxghost7** [HomepointXI/Issues#453]
**Date & Time**: 
09/07/2020 18:45 EDT

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Jestr

**Discord Name (if different from in game):**

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
Thf(99)/Dnc(49)

**NPC or Monster or item Name:**
Raaz tusk

**Zone name:** 
Unknown

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
Homepointxi.com/db/items/8709/

**Multi-boxing? (multiple clients on same connection):**
Nyet

**Steps to reproduce:**
Can't find on the wiki page which mob drops this item, which is needed to make an Arasy staff.

**Any additional information:**

**Comment by EpicTaru** [comment]
Added in maintenance prior to most recent:
![image](https://user-images.githubusercontent.com/26195580/126913212-0dd52835-dc22-4dab-926a-ef1dfc210f79.png)
