### ISSUE TITLE
Rank 2-3 workaround

### ISSUE THREAD

**Issue by Oyasumimuzaki** [HomepointXI/Issues#454]
**Date & Time**: 

**Client Version (use `/ver` in game):**

**Character Name:**

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
@Oyasumimuzaki Please complete as many fields of the ticket as you can, especially ones that pertain to the issue.
