### ISSUE TITLE
Voidwatch armour drops with missing defense

### ISSUE THREAD

**Issue by PunchdrunkXI** [HomepointXI/Issues#459]
**Date & Time**: 25th of September 2020. 10.10pm

**Client Version (use `/ver` in game):**30200604_0

**Character Name:**Punchdrunk

**Discord Name (if different from in game):**

**Nation:**Bastok

**Job(level)/Sub Job(level):**99PLD/49RDM

**NPC or Monster or item Name:**Outrider Mask, Outrider Mittens, Espial Cap, Espial Hose, Wayfarer Robe, Wayfarer Slops and Wayfarer Cuffs

**Zone name:** Bastok Mines

**Coordinates (use `!where`):**

**Item tool link (for items issues only):** http://homepointxi.com/db/items/28169/espial_hose
http://homepointxi.com/db/items/27741/espial_cap
http://homepointxi.com/db/items/27740/outrider_mask
http://homepointxi.com/db/items/28029/outrider_mittens
http://homepointxi.com/db/items/27883/wayfarer_robe
http://homepointxi.com/db/items/28031/wayfarer_cuffs
http://homepointxi.com/db/items/28170/wayfarer_slops

**Multi-boxing? (multiple clients on same connection):**Yes

**Steps to reproduce:**

**Any additional information:** Doesn't give any defense but does give the + to stats, i.e Str Dex and so on. Not sure about the set bonuses either.

**Comment by EpicTaru** [comment]
Pull request resolving all this was submitted to Topaz today, in final stages of review but will most likely be merged so whenever we update the server, these should be corrected by that.

https://github.com/project-topaz/topaz/pull/1195

**Comment by EpicTaru** [comment]
This ticket is resolved, all issues mentioned in the ticket are non-issues now. 👍🏼
