### ISSUE TITLE
~ PUP ~ master<->automaton Skillchains aren't working

### ISSUE THREAD

**Issue by simthra** [HomepointXI/Issues#46]
**Date & Time**: May 4th 2018

**Client Version (use `/ver` in game):** 30180306_2

**Character Name:** Thranduil

**Discord Name (if different from in game):**

**Nation:** Bastok 10

**Job(level)/Sub Job(level):** Pup 73/ dnc 36

**NPC or Monster or item Name:** any

**Zone name:** any

**Coordinates (use `!where`):** anywhere

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:** While levelling the job tried several times to execute a SC with puppet first or second, but nothing ever happened.

**Any additional information:**

**Comment by Heepster03** [comment]
moved to #558
