### ISSUE TITLE
The problemchild of vanadiel

### ISSUE THREAD

**Issue by MonikaToki7** [HomepointXI/Issues#460]
**Date & Time**: 10:59

**Client Version (use `/ver` in game):** 030200731_2

**Character Name:** Monika

**Discord Name (if different from in game):** MonikaTokisaki

**Nation:** Sandy

**Job(level)/Sub Job(level):** 99sam/49war

**NPC or Monster or item Name:**

**Zone name:**  Jeuno

**Coordinates (use `!where`):**x 2 y -4 z 55

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**3

**Steps to reproduce:**Zoning

**Any additional information:**

**Comment by MonikaToki7** [comment]
30200731_2 ver

**Comment by EpicTaru** [comment]
thanks, updated ticket contents with that info.
