### ISSUE TITLE
Frozen in Rank 2-3 closing CS

### ISSUE THREAD

**Issue by MonikaToki7** [HomepointXI/Issues#461]
[

**Date & Time**: 

**Client Version (use `/ver` in game):**

**Character Name:** Annabelle / Beana

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:**  rank 2-3 BCNM

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
What's the actual issue? @MonikaToki7

**Comment by MonikaToki7** [comment]
same as before glitched CS after you beat the the dragon / ahriman

**Comment by EpicTaru** [comment]
Please make sure both charas are online and then send me a /tell in game.

**Comment by MonikaToki7** [comment]
ok ill let them know

**Comment by EpicTaru** [comment]
Verified deletion/addition of any KIs that needed to be done and adjustment of the MissionStatus/any other variables necessary according to the code for completion of the battle. Congrats!
