### ISSUE TITLE
Shadow lord for Peekabooie Beana and Monika

### ISSUE THREAD

**Issue by MonikaToki7** [HomepointXI/Issues#463]
**Date & Time**: 3:20

**Client Version (use `/ver` in game):**030200731_2

**Character Name:**Monika, Beana, Peekabooie , liger

**Discord Name (if different from in game):**
MonikaTokisaki

**Nation:**
Sandy

**Job(level)/Sub Job(level):**

99sam/49dnc

**NPC or Monster or item Name:**

**Zone name:** Throne Room

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

![IMAG0363-](https://user-images.githubusercontent.com/71977642/94605801-99ca6f80-0267-11eb-9555-09f8e4fadaee.jpg)

**Any additional information:**

**Comment by EpicTaru** [comment]
Did you all crash or something?  This ticket doesn't say at all what the issue is.  Please advise.

**Comment by MonikaToki7** [comment]
Went through the cutscene at end of fight then the entirety of the  Client crashed RiP

**Comment by EpicTaru** [comment]
KK, keep all the listed characters online, please. I'll check/adjust their KIs/variables as needed.

**Comment by EpicTaru** [comment]
Verified deletion/addition of any KIs that needed to be done and adjustment of the variables necessary according to the code for completion of the battle. Congrats!
