### ISSUE TITLE
COP 5-3 issue - Cid removes all traces of Three Paths when attempting to have him complete it

### ISSUE THREAD

**Issue by beanashino** [HomepointXI/Issues#465]
**Date & Time**: 
Oct 14 2020

**Client Version (use `/ver` in game):**
30200731_2

**Character Name:**
Shino.   Excellence. Peeka 

**Discord Name (if different from in game):**

**Nation:**
All San d

**Job(level)/Sub Job(level):**

Shino 99 rdm whm.   Peeka. 99 whm blm.  Excellence 99 pld war

**NPC or Monster or item Name:**
Cid 

**Zone name:** 

Metalworks

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
Went and did cop mission 5-3 the 3 paths after all finished went to cid for cutscenes he gave us one but not second one tried a few more times and when I checked my mission log it literally showed us on cop 1-1 when the others checked theirs was same issue. We triple checked everything 

**Any additional information:**

**Comment by EpicTaru** [comment]
@beanashino are all the impacted charas online? If not, please log them all on and send Epictaru a /tell in game.

**Comment by EpicTaru** [comment]
@beanashino were all of these charas multiboxing when this occured?

**Comment by beanashino** [comment]
Peek and excellence we’re mine is different

**Comment by Warleaf** [comment]
Date & Time:
Oct. 16th 2020.
Like 5pm EST.

Client Version (use /ver in game):
30191227_0

Character Name:
Warleaf

Discord Name (if different from in game):
Warleaf

Nation:
Windurst, Rank 7

Job(level)/Sub Job(level):
82BLU/41DNC

NPC or Monster or item Name:
Cid.

Zone name:
Bastok Metalworks.

Coordinates (use !where):
X:-23 Y:-10 Z:-1 (122)

Item tool link (for items issues only):

Multi-boxing? (multiple clients on same connection):
No.

Steps to reproduce:
Talked to Cid after completing the Louverance section of CoP Mission 5-3. It was the last section of the mission and would normally start into mission 6-1.

Any additional information:

**Comment by EpicTaru** [comment]
@Jessland86 @Heepster03 For the above characters, verification of their variables was completed to make sure they were showing the correct values indicating that they had completed all 3 paths.  After this verification, their PromathiaStatus variable was verified to be set at 0 or changed to reflect that.  This doesn't appear to be a multiboxing issue, appears to be an issue in Cid's code.  Issue started presenting itself after the server updated to the Dec. 2019 version.

Promathia Mission 60 (FOR_WHOM_THE_VERSE_IS_SUNG) was then added to their mission log.

Keeping this issue open for any other players that may also encounter this issue.

**Comment by MVM1787** [comment]
Happened to me as well, Ligerzero
Version: 30191204_1

**Comment by EpicTaru** [comment]
For the above character(s), verification of their variables was completed to make sure they were showing the correct values indicating that they had completed all 3 paths. After this verification, their **PromathiaStatus** variable was verified to be set at 0 or changed to reflect that. This doesn't appear to be a multiboxing issue, appears to be an issue in Cid's code. Issue started presenting itself after the server updated to the Dec. 2019 version.

Promathia Mission FOR_WHOM_THE_VERSE_IS_SUNG) was then added to their mission log for current mission.

Keeping this issue open for any other players that may also encounter this issue.

**Comment by Heepster03** [comment]
Currently looking into it. I think I found the possibly resolution. I'll let you know when it's fixed.

**Comment by Draxxus82** [comment]
Draxxus and Voltage now have this issue as well

**Comment by EpicTaru** [comment]
One minute and I'll adjust your characters' variables, @Draxxus82.

**Comment by EpicTaru** [comment]
For the above character(s), verification of their variables was completed to make sure they were showing the correct values indicating that they had completed all 3 paths. After this verification, their **PromathiaStatus** variable was verified to be set at 0 or changed to reflect that. This doesn't appear to be a multiboxing issue, appears to be an issue in Cid's code. Issue started presenting itself after the server updated to the Dec. 2019 version.

Promathia Mission FOR_WHOM_THE_VERSE_IS_SUNG was then added to their mission log for current mission.

Keeping this issue open for any other players that may also encounter this issue.

**Comment by Draxxus82** [comment]
Lander is now having the same issue

**Comment by EpicTaru** [comment]
For the above character(s), verification of their variables was completed to make sure they were showing the correct values indicating that they had completed all 3 paths. After this verification, their **PromathiaStatus** variable was verified to be set at 0 or changed to reflect that. This doesn't appear to be a multiboxing issue, appears to be an issue in Cid's code. Issue started presenting itself after the server updated to the Dec. 2019 version.

Promathia Mission FOR_WHOM_THE_VERSE_IS_SUNG was then added to their mission log for current mission.

Keeping this issue open for any other players that may also encounter this issue.

**Comment by EpicTaru** [comment]
Pasted below on behalf of Vixxen (having same issue posting to Github that Albian has):

Date & Time:

12/1/2020 @ 2:00pm EST

Client Version (use /ver in game):

30200327_2

Character Name:

Vixxen
Heytherelilguy

Discord Name (if different from in game):
Sevvghetto


Nation:

Vixxen - Bastok

Job(level)/Sub Job(level):

60NIN/30DNC

NPC or Monster or item Name:

Any

Zone name:

Any

Coordinates (use !where):



Item tool link (for items issues only):



Multi-boxing? (multiple clients on same connection):

No

**Comment by EpicTaru** [comment]
For the above character(s), verification of their variables was completed to make sure they were showing the correct values indicating that they had completed all 3 paths. After this verification, their **PromathiaStatus** variable was verified to be set at 0 or changed to reflect that. This doesn't appear to be a multiboxing issue, appears to be an issue in Cid's code. Issue started presenting itself after the server updated to the Dec. 2019 version.

Promathia Mission FOR_WHOM_THE_VERSE_IS_SUNG was then added to their mission log for current mission.

Keeping this issue open for any other players that may also encounter this issue.

**Comment by EpicTaru** [comment]
https://github.com/HomepointXI/Issues/issues/485

**Comment by EpicTaru** [comment]
Pasting this here on behalf of Albian who continues to have issues getting his Github account unflagged.  This was posted by him in the #looking-for-help channel:

Date & Time:
2021 Feb. 10 7:02:44

Client Version (use /ver in game):
30191204_1

Character Name:
Albian
Nyaan
Onlan
Lonelytortoise
Ogopogo
Popey

Nation:
San d'Oria

Job(level)/Sub Job(level):
BLU99/RDM49 x6

NPC or Monster or item Name:
Cid.

Zone name:
Bastok Metalworks.

Coordinates (use !where):
X:-23 Y:-10 Z:-1 (122)

Multi-boxing? (multiple clients on same connection):
Yes

Steps to reproduce:
Finished CoP 5-3

**Comment by EpicTaru** [comment]
Verified that all affected characters had the correct variable values that indicated they had completed the quests involved in Three Paths.

Added Promathia Mission FOR_WHOM_THE_VERSE_IS_SUNG (Mission ID 60) to all affected characters.

Verified/adjusted value of PromathiaStatus variable to correct value so that progression with next COP mission can occur.

@Albian Please attempt to proceed forward in COP and report back here with your findings.

Please also attempt to unflag your github account as directed in the Pinned Messages in this channel.

**Comment by EpicTaru** [comment]
Albian Today at 8:58 AM
It appears to be working on all characters now.

**Comment by EpicTaru** [comment]
Epic🚀👖Taru/Gathin/Ancillam Today at 8:58 AM
Very nice, good to hear. :slight_smile:

Keeping this issue open for any other players that may also encounter this issue.

**Comment by SirYanFFXI** [comment]
Date & Time:
Feb 14 2021

Client Version (use /ver in game):
30200731_2

Character Name:
Siryan, Swarovski, Angelvoice, Petitepeste

Discord Name (if different from in game):
Siryan

Nation:
Bastok/Bastok/Bastok/San d'Oria

Job(level)/Sub Job(level):

Siryan : PLD99/WAR49
Swarovski : THF99/DNC49
Angelvoice : BRD99/WHM49
Petitepeste : WHM99/SCH49

NPC or Monster or item Name:
Cid

Zone name:

Metalworks

Coordinates (use !where):

Item tool link (for items issues only):

Multi-boxing? (multiple clients on same connection):
Yes but not related apparently

Steps to reproduce:
Went and did cop mission 5-3 the 3 paths after all finished went to cid for cutscenes he gave us one but not second one tried a few more times and when I checked my mission log it literally showed us on cop 1-1. Same issue on all 4 characters, went to Cid again, zoned, log off / log on, nothing.

Any additional information:

**Comment by EpicTaru** [comment]
For the above character(s), verification of their variables was completed to make sure they were showing the correct values indicating that they had completed all 3 paths. After this verification, their **PromathiaStatus** variable was verified to be set at 0 or changed to reflect that. This doesn't appear to be a multiboxing issue, appears to be an issue in Cid's code. Issue started presenting itself after the server updated to the Dec. 2019 version.

Promathia Mission FOR_WHOM_THE_VERSE_IS_SUNG was then added to their mission log for current mission.

Keeping this issue open for any other players that may also encounter this issue.

**Comment by BiggX048** [comment]
**Date & Time**: 16.02.2021



**Client Version (use `/ver` in game):** 30191204_1



**Character Name:** Danzo



**Discord Name (if different from in game):** BiggX#4519



**Nation:** San d'Oria



**Job(level)/Sub Job(level):** BLU99/RDM49



**NPC or Monster or item Name:** Cid



**Zone name:** Bastok - Metalworks



**Coordinates (use `!where`):**



**Item tool link (for items issues only):**



**Multi-boxing? (multiple clients on same connection):** Yes



**Steps to reproduce:** Finished CoP Mission 5-3



**Any additional information:** Finished CoP 5-3 (Three Paths) but cant get 6-1 (For Whom the Verse is Sung).

**Comment by EpicTaru** [comment]
For the above character(s), verification of their variables was completed to make sure they were showing the correct values indicating that they had completed all 3 paths. After this verification, their **PromathiaStatus** variable was verified to be set at 0 or changed to reflect that. This doesn't appear to be a multiboxing issue, appears to be an issue in Cid's code. Issue started presenting itself after the server updated to the Dec. 2019 version.

Promathia Mission FOR_WHOM_THE_VERSE_IS_SUNG was then added to their mission log for current mission.

Keeping this issue open for any other players that may also encounter this issue.

**Comment by Draxxus82** [comment]
Happened again for 
99RDM Proto
99THF Eclipsed

**Comment by EpicTaru** [comment]
For the above character(s), verification of their variables was completed to make sure they were showing the correct values indicating that they had completed all 3 paths. After this verification, their PromathiaStatus variable was verified to be set at 0 or changed to reflect that. This doesn't appear to be a multiboxing issue, appears to be an issue in Cid's code. Issue started presenting itself after the server updated to the Dec. 2019 version.

Promathia Mission FOR_WHOM_THE_VERSE_IS_SUNG was then added to their mission log for current mission.

Keeping this issue open for any other players that may also encounter this issue.

**Comment by kpinoy** [comment]
Character Nix, single box on version 30191204_1 is experiencing this issue as well.

**Comment by EpicTaru** [comment]
For the above character(s),  to make sure they were showing the correct values indicating that they had completed all 3 paths, verification of the following variables was completed:

Variable **COP_Tenzen_s_Path** has a value of **11**.

Variable **COP_Ulmia_s_Path** has a value of **8**.

Variable **COP_Louverance_s_Path** has a value of **10**.

After the above verifications, the value of the **PromathiaStatus** variable was verified to be set at **0** or updated to reflect that. 

Promathia Mission **FOR_WHOM_THE_VERSE_IS_SUNG** was then added to their mission log **(!addmission 6 60**) as the current mission.

This doesn't appear to be a multiboxing issue, appears to be an issue in Cid's code. Issue started presenting itself after the server updated to the Dec. 2019 version.

Keeping this issue open for any other players that may also encounter this issue.

**Comment by Thotless** [comment]
Happened to me,  
Characters:   Thotless    Clairdeluna     Lunaless
Version:  30191204_1
Multiboxing:  Yes

**Comment by EpicTaru** [comment]
For the above character(s),  to make sure they were showing the correct values indicating that they had completed all 3 paths, verification of the following variables was completed:

Variable **COP_Tenzen_s_Path** has a value of **11**.

Variable **COP_Ulmia_s_Path** has a value of **8**.

Variable **COP_Louverance_s_Path** has a value of **10**.

After the above verifications, the value of the **PromathiaStatus** variable was verified to be set at **0** or updated to reflect that. 

Promathia Mission **FOR_WHOM_THE_VERSE_IS_SUNG** was then added to their mission log (**!addmission 6 60**) as the current mission.

This doesn't appear to be a multiboxing issue, appears to be an issue in Cid's code. Issue started presenting itself after the server updated to the Dec. 2019 version.

Keeping this issue open for any other players that may also encounter this issue.

**Comment by Shoruto** [comment]
Date & Time:
2021 April 6th @ 9:22 am

Client Version (use /ver in game):
30191204_1

Character Name:
Sporky

Nation:
Windurst

Job(level)/Sub Job(level):
WHM99/BLM49

NPC or Monster or item Name:
Cid.

Zone name:
Bastok Metalworks.

Coordinates (use !where):
X:-23 Y:-10 Z:-1 (122)

Multi-boxing? (multiple clients on same connection):
No

Steps to reproduce:
Completed all 3 paths of the CoP mission and spoke to Cid.  Received final CS then the mission log emptied out.  Tried starting Mission 6-1 but no CS.

**Comment by EpicTaru** [comment]
@Shoruto I'll help you out as soon as I'm finished with breakfast. Thanks for your patience.

**Comment by Shoruto** [comment]
Take your time don't rush

**Comment by EpicTaru** [comment]
@Shoruto Please let me know, on this ticket or via /tell in game or via @ing me on discord, that your chara is online so that I can look into/resolve your issue.

**Comment by Shoruto** [comment]
I will I am eating lunch and taking care of a home project but after lunch I'll log in and leave it logged in I may not be there at the computer though.  When I log in I'll let you know.

**Comment by EpicTaru** [comment]
@Shoruto No worries, no rush, just lemme know.  Enjoy your lunch.

**Comment by EpicTaru** [comment]
For the above character(s),  to make sure they were showing the correct values indicating that they had completed all 3 paths, verification of the following variables was completed:

Variable **COP_Tenzen_s_Path** has a value of **11**.

Variable **COP_Ulmia_s_Path** has a value of **8**.

Variable **COP_Louverance_s_Path** has a value of **10**.

After the above verifications, the value of the **PromathiaStatus** variable was verified to be set at **0** or updated to reflect that. 

Promathia Mission **FOR_WHOM_THE_VERSE_IS_SUNG** was then added to their mission log (**!addmission 6 60**) as the current mission.

This doesn't appear to be a multiboxing issue, appears to be an issue in Cid's code. Issue started presenting itself after the server updated to the Dec. 2019 version.

Keeping this issue open for any other players that may also encounter this issue.

**Comment by tuing** [comment]
Date & Time:
2021 April 14th @ 1:22 am

Client Version (use /ver in game):
30191204_1

Character Name:
Minimey
Higuchi

Nation:
Sandoria
Sandoria

Job(level)/Sub Job(level):
WHM99/RDM49
BRD99/WHM39

NPC or Monster or item Name:
Pherimociel

Zone name:
Ru'Lude Gardens

Coordinates (use !where):
X:-31 Y:2 Z:67 (168)

Multi-boxing? (multiple clients on same connection):
Yes

Steps to reproduce:
Completed all three paths of the CoP mission and Cid already saying to go to Jeuno where the appropriate next step is to talk to Pherimociel yet the mentioned NPC doesnt give any cutscene. As side note when checked mission log on both char it still said Ancient Flames Beckon.

**Comment by EpicTaru** [comment]
@tuing Please let me know, either on this ticket or in game, that you have both affected charas online, so I can look into and resolve this for you.

**Comment by EpicTaru** [comment]
For the above character(s),  to make sure they were showing the correct values indicating that they had completed all 3 paths, verification of the following variables was completed:

Variable **COP_Tenzen_s_Path** has a value of **11**.

Variable **COP_Ulmia_s_Path** has a value of **8**.

Variable **COP_Louverance_s_Path** has a value of **10**.

After the above verifications, the value of the **PromathiaStatus** variable was verified to be set at **0** or updated to reflect that. 

Promathia Mission **FOR_WHOM_THE_VERSE_IS_SUNG** was then added to their mission log (**!addmission 6 60**) as the current mission.

This doesn't appear to be a multiboxing issue, appears to be an issue in Cid's code. Issue started presenting itself after the server updated to the Dec. 2019 version.

Keeping this issue open for any other players that may also encounter this issue.

**Comment by Heepster03** [comment]
Issue may by resolved in upcoming update, Cid was sick and hopefully I cured him.

**Comment by djsnowfang** [comment]
Date & Time:
4/22/21

Client Version (use /ver in game):
30200731_2

Character Name:
Djsnowfang

Discord Name (if different from in game):

Nation:
windurst

Job(level)/Sub Job(level):
DRG99/SAM49

NPC or Monster or item Name:
Cid

Zone name:
Metalworks

Multi-boxing? (multiple clients on same connection):
No

**Comment by EpicTaru** [comment]
@djsnowfang Please let me know, either on this ticket or in game, that your chara is online so we can address this issue.

**Comment by EpicTaru** [comment]
For the above character(s),  to make sure they were showing the correct values indicating that they had completed all 3 paths, verification of the following variables was completed:

Variable **COP_Tenzen_s_Path** has a value of **11**.

Variable **COP_Ulmia_s_Path** has a value of **8**.

Variable **COP_Louverance_s_Path** has a value of **10**.

After the above verifications, the value of the **PromathiaStatus** variable was verified to be set at **0** or updated to reflect that. 

Promathia Mission **FOR_WHOM_THE_VERSE_IS_SUNG** was then added to their mission log (**!addmission 6 60**) as the current mission.

This doesn't appear to be a multiboxing issue, appears to be an issue in Cid's code. Issue started presenting itself after the server updated to the Dec. 2019 version.

Keeping this issue open for any other players that may also encounter this issue.

**Comment by EpicTaru** [comment]
After yet **ANOTHER** exhaustive climb up COP (this time on the test server), I can confirm that this issue is resolved!
![image](https://user-images.githubusercontent.com/26195580/129260530-76c16aeb-67fa-456d-aee1-eae685e5283e.png)
