### ISSUE TITLE
Dynamis Issue: No KI from trail markings.

### ISSUE THREAD

**Issue by Warleaf** [HomepointXI/Issues#466]
**Date & Time**: 
Oct. 17th 2020

**Client Version (use `/ver` in game):**
30191227_0

**Character Name:**
Warleaf

**Discord Name (if different from in game):**
Warleaf

**Nation:**
Windurst, rank 7

**Job(level)/Sub Job(level):**
85Blu/41DNC

**NPC or Monster or item Name:**
Key Item Vial of Shrouded Sands

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No.

**Steps to reproduce:**
Interacting with trail markings does not give the key item Vial of Shrouded Sands.

**Any additional information:**
I think I received the CS in Xarcabard for Dynamis a while ago when I first enter the zone as any form of entrance afterward has not prompted the CS to play. After reaching rank 7 in Windurst I attempted to get the key item by inspecting the trail markings in Windurst. After that I attempted to examine the other 3 trail markings and did not receive the item from those either. When talking to the Goblins in the beastmen areas which would normally sell the Prismatic Hour glass they give the response that they do not want to talk to me.

**Comment by EpicTaru** [comment]
So you have never done any dynamis on the affected chara, @Warleaf?

**Comment by Warleaf** [comment]
It was my first attempt at getting the KI. I did also interact with the Hieroglyphics in Buburimu for that Dynamis and got a CS with Diabolos, but can not enter their either. Not sure if it is related to not being able to get the KI now.

**Comment by EpicTaru** [comment]
Most likely unrelated to this issue as dreamland dyna access needs you to beat diabolos in cop first

**Comment by Warleaf** [comment]
Which I have also done, and before I tried interacting with those in Buburimu, just offering it as more info incase some weird things are going on under the hood.

**Comment by EpicTaru** [comment]
Just checked the code for the hieroglyphics, those also require the ki shrouded sand (besides defeating diabolos in cop)

**Comment by EpicTaru** [comment]
@Warleaf Let me know (via a response here) when you are next online, I need to double-check the value of a variable on your chara before we can proceed.

**Comment by Warleaf** [comment]
Character is online now.

**Comment by EpicTaru** [comment]
Value of character's **Dynamis_Status** variable was displaying as **256** for some reason.  Set the value of that variable to 0.  Had player then zone the character into Xarcabard after which the character received the cutscene there and the **Dynamis_Status** variable successfully updated correctly.  Character then examined the Trail Markings in Windurst Walls and successfully received the KI Shrouded Sand.
