### ISSUE TITLE
CoP 6-4: Airship Fight

### ISSUE THREAD

**Issue by Warleaf** [HomepointXI/Issues#467]
**Date & Time**: 
Oct, 16th 2020

**Client Version (use `/ver` in game):**
30191227_0

**Character Name:**
Warleaf

**Discord Name (if different from in game):**
Warleaf

**Nation:**
Windurst, rank 7

**Job(level)/Sub Job(level):**
86BLU/41DNC

**NPC or Monster or item Name:**
Ultima

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No.

**Steps to reproduce:**
During the airship fight the first two parts worked correctly, first the mammets and then Omega. When interaction with the door to move to the final fight against Ultima the CS plays but does not spawn the boss afterwards. Subsequent attempts to move to the fight replay the CS but do not load the boss.

**Any additional information:**

**Comment by EpicTaru** [comment]
It's the return of the "wandering" Ultima (or a code error putting the player on the wrong ship after the intermediate cutscene finishes)!!!!

Ultima (ModID **16908295**) successfully spawned after defeat of Omega, but player wasn't placed on correct ship at the end of the intermediate CS.  I !brought the player to the ship that Ultima was on and player was then able to successfully defeat the NM.  Player then confirmed they received the Ducal Ring reward and was able to proceed on with COP missions.

**Comment by MVM1787** [comment]
Currently in Airship Battle, Ultima doesnt show up for me, clearly its the coding. nothing to do with versions of whichever your on.

Character: Ligerzero
Help when you can Epictaru, No Rush.

**Comment by EpicTaru** [comment]
@MVM1787 need you to provide affected charas, your client version, and if you are multiboxing.

**Comment by MVM1787** [comment]
Character: Ligerzero
Version: 30191204_1
Multiboxing: No

**Comment by EpicTaru** [comment]
I'm already done for the day and getting ready to sleep. I'll find you tomorrow, @MVM1787.

**Comment by MVM1787** [comment]
Guess ill start on Whitegate Missions then

**Comment by EpicTaru** [comment]
Ligerzero experienced same issue as Warleaf.  Player is placed on incorrect airship at the end of the intermediate cs between Omega and Ultima.  This time, I used **!mobhere 16908295** to pull Ultima from the ship it spawned on to the ship that Ligerzero was placed on. Player was able to successfully defeat the NM. Player then confirmed they received the Ducal Ring reward and was able to proceed on with COP missions.

Keeping this ticket open for any other players that have this issue.

**Comment by beanashino** [comment]
Finally fixed was able to get through the fight

**Comment by EpicTaru** [comment]
No, it's not finally fixed, lol, I brought Ultima to the ship you (Shino) were placed on after the CS. Player was able to successfully defeat the NM. Player then confirmed they received the Ducal Ring reward and was able to proceed on with COP missions.

Keeping this ticket open for any other players that have this issue.

**Comment by EpicTaru** [comment]
Player Sevvghetto (discord name), w/ chara names Vixxen and Heytherelilguy also experienced the above issue whle doing the Airship fight on both charas.  I ended up !bringing the charas to the ship that Ultima spawned on in order for them to defeat the mob and then complete the remainder of the mission.

Keeping this issue open for any other players that may also encounter this issue.

**Comment by PunchdrunkXI** [comment]
Having the same issue.
Character: Healdrunk
Version: 30201204_0
Multiboxing: Yes, but not during the fight
![Healdrunk_2020 12 22_232552](https://user-images.githubusercontent.com/68868049/102942812-47879c00-44ae-11eb-99f1-0bdb52008fdc.png)

**Comment by PunchdrunkXI** [comment]
Character: Azuredrunk
Version: 30201204_0
Multiboxing: Yes, but not during fight
![Azuredrunk_2020 12 22_234824](https://user-images.githubusercontent.com/68868049/102943776-ec0add80-44b0-11eb-8909-13f03ddb1eaf.png)

**Comment by EpicTaru** [comment]
For the above two charas (Healdrunk and Azuredrunk), the same issues listed in the ticket were also experienced. I ended up !bringing the characters to the ship that Ultima spawned on in order for them to defeat the mob and then complete the remainder of the mission.  Adjustment of the **PromathiaStatus** variable value to reflect successfully defeating the mission was also done if necessary.  Congrats!

Keeping this issue open for any other players that may also encounter this issue.

**Comment by PunchdrunkXI** [comment]
successfully rescued by a red glowy hume, mission was completed and progress continues. Thnx again ET /salute

**Comment by djsnowfang** [comment]
Date & Time:
4/23/2021

Client Version (use /ver in game):
30191227_0

Character Name:
djsnowfang

Discord Name (if different from in game):

Nation:
Windurst

Job(level)/Sub Job(level):
99drg/49sam

NPC or Monster or item Name:
mammits

Zone name:
airship fight

Multi-boxing? (multiple clients on same connection):
No.

Placed on wrong airship after mamait fight. unable to click on door.

**Comment by EpicTaru** [comment]
@djsnowfang Let me know, either here on this ticket or in game, when you are next available to do this fight and I'll monitor you with my GM and provide assistance if needed.  Please be ready to take screenshots of death messages of the mobs if requested.

**Comment by djsnowfang** [comment]
> @djsnowfang Let me know, either here on this ticket or in game, when you are next available to do this fight and I'll monitor you with my GM and provide assistance if needed. Please be ready to take screenshots of death messages of the mobs if requested.

![Djsnowfang_2021 04 24_104825](https://user-images.githubusercontent.com/80540590/115965146-419dd800-a4ed-11eb-9429-03609f8e02f0.png)
![Djsnowfang_2021 04 24_105350](https://user-images.githubusercontent.com/80540590/115965147-42366e80-a4ed-11eb-8926-b86b95b531ca.png)
![Djsnowfang_2021 04 24_105400](https://user-images.githubusercontent.com/80540590/115965148-42366e80-a4ed-11eb-81d1-87ba0f1653b0.png)
![Djsnowfang_2021 04 24_105413](https://user-images.githubusercontent.com/80540590/115965149-42cf0500-a4ed-11eb-8fff-6052034e2ee9.png)
![Djsnowfang_2021 04 24_105724](https://user-images.githubusercontent.com/80540590/115965151-43679b80-a4ed-11eb-8a24-2a2fa719473d.png)
![Djsnowfang_2021 04 24_110122](https://user-images.githubusercontent.com/80540590/115965152-43679b80-a4ed-11eb-816e-8ece017d7187.png)

**Comment by EpicTaru** [comment]
Neither Omega nor Ultima spawned automatically so I ended up having to force-spawn those two mobs.  Both were successfully defeated per the above screenshots.  After the death of Ultima, ending CS correctly triggered so no adjustment of character's variables was necessary.  Congrats on the wins, @djsnowfang.

Leaving this ticket closed as it is a duplicate of https://github.com/HomepointXI/Issues/issues/472
