### ISSUE TITLE
Survival Guide Teleport to Ro'Maeve Places You Mid Air in somewhat middle of the zone.

### ISSUE THREAD

**Issue by MVM1787** [HomepointXI/Issues#468]
**Date & Time**:  Monday, October 19th 2020, Time: 5:59 PM PST

**Client Version (use `/ver` in game):** 30191204_1

**Character Name:** Ligerzero

**Discord Name (if different from in game):** Ligerzero

**Nation:** Sandy

**Job(level)/Sub Job(level):** 99 THF/ 49 DNC

**NPC or Monster or item Name:** None

**Zone name:**  Ro'Maeve

**Coordinates (use `!where`):** X:51 Y:-28 Z:53 (64)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**No

**Steps to reproduce:**Use any Survival Guide to teleport to Ro'Maeve, it will place you here in this same spot in air, to get out your able to rest and use !tele function to get out.

![Ligerzero_2020 10 19_180327](https://user-images.githubusercontent.com/12943935/96527643-70cd4700-1235-11eb-92a4-625ad4bb53ac.png)

**Any additional information:**

**Comment by EpicTaru** [comment]
Just submitted a fix for this to Topaz. When its merged, it'll be pulled down to here.

**Comment by EpicTaru** [comment]
The above fix also addresses a similar issue with the Survival Guide in Pashhow Marshlands putting you off map

**Comment by EpicTaru** [comment]
Fixed in update on 04/29/2021.  Closing ticket.
