### ISSUE TITLE
Fenrir - Key Lost

### ISSUE THREAD

**Issue by Draxxus82** [HomepointXI/Issues#469]
[

**Date & Time**: 
11/9 - 6:07 PM

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Voltage

**Discord Name (if different from in game):**
Hauteclaire

**Nation:**
Windy

**Job(level)/Sub Job(level):**
66 SMN 

**NPC or Monster or item Name:**
Leepe -Hoppe

**Zone name:** 
Windy Waters South

**Coordinates (use `!where`):**
X:14 Y: -9 Z: -195 (220)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Draxxus and Voltage

**Steps to reproduce:**
Full inventory, npc said come back, then it tried to make me start the quest over

**Any additional information:** 
![Proof](https://user-images.githubusercontent.com/74222907/98620971-4d496980-22d4-11eb-8798-6e650923c902.PNG)

**Comment by EpicTaru** [comment]
Gave @Draxxus82 the Whisper Of The Moon KI again, advised to talk to Leepe again (after making sure had free inv. space).

**Comment by Draxxus82** [comment]
Item recieved

**Comment by EpicTaru** [comment]
Resolved in maintenance prior to most recent.
