### ISSUE TITLE
Mission Magicite (San d'Oria), Baudin, Crest of Davoi

### ISSUE THREAD

**Issue by Albian-HomepointXI** [HomepointXI/Issues#470]
**Date & Time**: 
Nov. 10 11:08:31

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Albian
Nyaan
Onlan
Lonelytortoise
Ogopogo
Popey

**Discord Name (if different from in game):**

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
Albian RDM75/THF37
Nyaan RDM73/WHM36
Onlan RDM70/THF35
Lonelytortoise THF63/WAR31
Ogopogo RDM70/THF35
Popey RDM70/THF35
**NPC or Monster or item Name:**
Baudin

**Zone name:** 
Upper Jeuno

**Coordinates (use `!where`):**
X:-73 Y:0 Z:81

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/4377/slice_of_coeurl_meat

**Multi-boxing? (multiple clients on same connection):**
Yes, 6 total.

**Steps to reproduce:**
Undertake the mission Magicite
Get to the point where you need to acquire the Crest of Davoi
Speak with him and trade him Coeurl Meat, he does not give you the Crest of Davoi

**Any additional information:**
Occurred on all six of my characters.

**Comment by EpicTaru** [comment]
Duplicate issue, please comment on https://github.com/HomepointXI/Issues/issues/471 if you are still having this issue, @Albian-HomepointXI
