### ISSUE TITLE
CoP 7-4 - Cid Final CS Issue

### ISSUE THREAD

**Issue by Draxxus82** [HomepointXI/Issues#473]
**Date & Time**: 
11/12/2020 - 7:40AM 

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Draxxus and Voltage

**Discord Name (if different from in game):**
Hauteclaire

**Nation:**
Windy

**Job(level)/Sub Job(level):**
99PLD 99 BLU

**NPC or Monster or item Name:**
CID

**Zone name:** 
Metalworks

**Coordinates (use `!where`):**
X:-13 Y:-10 Z:0 (201)
 (201

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**
Killed the NMs in the following order, Taz, Carp, Biki

**Any additional information:**
Cid is saying  you remember what I asked you to do right? Verified that I have the keyitem from the first fight, I have added snips from my log showing the 3 nms and dialogue from the cs
![light](https://user-images.githubusercontent.com/74222907/98941678-e89c3380-24ba-11eb-8e12-ca839ef4b844.PNG)
![manta](https://user-images.githubusercontent.com/74222907/98941679-e934ca00-24ba-11eb-82a0-de6070b543d5.PNG)
![toll](https://user-images.githubusercontent.com/74222907/98941680-e934ca00-24ba-11eb-8554-1b6f0dfcd1af.PNG)

**Comment by EpicTaru** [comment]
From your variables, I show you didn't click on the ??? after killing Dalham.  Try redoing that fight and I can check if your variables updated correctly, @Draxxus82.

**Comment by EpicTaru** [comment]
Verified that variables now correctly reflect the right values after death of Dalham NM.  Should be good to proceed further.
