### ISSUE TITLE
Mission The Shadow Lord (San d'Oria)

### ISSUE THREAD

**Issue by Albian-HomepointXI** [HomepointXI/Issues#474]
**Date & Time**: 
Nov 12 18:55:54

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Albian
Nyaan
Onlan
Lonelytortoise
Ogopogo
Popey
**Discord Name (if different from in game):**

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
Albian RDM82/THF41
Nyaan RDM80/WHM40
Onlan RDM78/THF39
Lonelytortoise THF78/WAR39
Ogopogo RDM78/THF39
Popey RDM78/THF39

**NPC or Monster or item Name:**
The Shadow Lord

**Zone name:** 
Throne Room

**Coordinates (use `!where`):**
X: -1076 Y: -647 Z:-718

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes, 6.

**Steps to reproduce:**
Enter the battle with the Shadow Lord while multiboxing.
I activated the battle first on Albian and then one at a time did so on the other 5.

**Any additional information:**
Albian teleported into the arena with the Shadow Lord, the other five were grouped together in a duplicate room sans Albian and the Shadow Lord. I beat the first phase of the Shadow Lord on Albian following the cutscene the Shadow Lord walked away from Albian and then through the wall towards the other five in the duplicate room where they defeated him. When the battle was over only Albian got the cutscene to play.

![pol_2020_11_12_18_48_58_880](https://user-images.githubusercontent.com/74258270/99011566-5f1c4e00-251a-11eb-8ecc-3b6d45a64467.jpg)

**Comment by EpicTaru** [comment]
Duplicate issue, please comment on https://github.com/HomepointXI/Issues/issues/502 if this hasn't already been resolved, @Albian-HomepointXI
