### ISSUE TITLE
Windy mission 7-2

### ISSUE THREAD

**Issue by Lander-23** [HomepointXI/Issues#475]
**Date & Time**: 
11/13/20  6:00pm

**Client Version (use `/ver` in game):**
30200327_2

**Character Name:**
Lander

**Discord Name (if different from in game):**
Lander

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
99war/49dnc

**NPC or Monster or item Name:**
Granit Door

**Zone name:** 
Temple of Uggalepih

**Coordinates (use `!where`):**
X:340 Y:0 Z:334  (192)

**Item tool link (for items issues only):**
Cursed Key

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
Trade Cursed Key to Granite Door

**Any additional information:**
No Cutseen

**Comment by EpicTaru** [comment]
Check of player's **MissionStatus** variable reported a value of 3.  Advised player to talk to Vanono to be sure that the variable updates to the needed value of 4 in order for the interaction with the Granite Door to perform as expected.

Please spoke with Vanono again, variable updated correctly to 4.  Player then repeated the trading of the key to the Granite Door and the expected CS was received, after which time the player's **MissionStatus** variable correctly updated to 5 and the necessary adjustments to the **Blank Book of the Gods** KI and the **Book of the Gods** KI also correctly occurred.

**Comment by BasslineTRT** [comment]
Meashon traded the Cursed Key with the Granite Door and the expected CS was received. Unfortunately the Book of the Gods KI didn't drop after the CS. Mission is still in limbo.

**Comment by Heepster03** [comment]
I verified that the player has a MissionStatus of 4 and still has the Blank Book of the Gods. Informed player that they would have to try trading to the door again. I gave them the cursed key back so they can try it again. I also verified on the server itself that there are no console errors or anything.
