### ISSUE TITLE
Genkai quests not being marked as completed after successful completion

### ISSUE THREAD

**Issue by HitoSeven** [HomepointXI/Issues#479]
**Date & Time**:  
11/26/2020 @ 2:00pm EST

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Hito

**Discord Name (if different from in game):**

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
74THF/37DNC

**NPC or Monster or item Name:**

Maat

**Zone name:** 

Ru'ludeGardens

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

No

**Steps to reproduce:**

Talk to Maat

**Any additional information:**

EpicTaru had to help me with Maat as after I handed in Limit Break 1 items he asked for them again instead of furthering the quest line. Now I am stuck with the same error but after doing Limit Break 2 and getting KI's from Xarcabard he asks for them again.

**Comment by EpicTaru** [comment]
Using **!checkquest 3 128**, the quest **In Defiant Challenge** showed _accepted_ status.  After verifying that the player had the Fiend Torque in their inventory (**!hasitem 28390**), I then used **!completequest 3 128** to force **In Defiant Challenge** to be _completed_.  Player then confirmed that he was able to flag the subsequent Genkai quest (**Atop the Highest Mountains**).

Performed the above process to verify that the quest player had the **Goblin Cest** (Item ID 15931) in their inventory and to then force-completed **Atop the Highest Mountains** (Quest ID 129) to be completed.

Leaving this issue open for issues with any of the subsequent Genkai quests that this player or any other player may have.

**Comment by HitoSeven** [comment]
Same deal with the next quest. He is asking for 3 KI's again instead of triggering (**Riding on the Clouds**)

**Comment by EpicTaru** [comment]
I'm online now, @HitoSeven. Send me a /tell in game and we'll get this sorted out.

**Comment by EpicTaru** [comment]
Performed the above process to verify that the quest player had the **Krousis Ring** (Item ID 15849) in their inventory and then force-completed **Atop the Highest Mountains** (Quest ID 129).

Leaving this issue open for issues with any of the subsequent Genkai quests that this player or any other player may have.

**Comment by EpicTaru** [comment]
Performed the above processes to verify that player **Harmony** had the award item(s) in their inventory and then force-completed the relevant Genkai quest(s) related to that award item.

Leaving this issue open for issues with any of the subsequent Genkai quests that this player or any other player may have.

**Comment by EpicTaru** [comment]
Pasting the contents of Albian's comment to this ticket as he's having the issue of Github flagging his account for no known reason:

AlbianToday at 3:48 PM
Genkai quests not being marked as completed after successful completion

Date & Time:
2021, Jan. 8 14:02:33

Client Version (use /ver in game):
30191204_1

Character Name:
Albian
Nyaan
Onlan
Ogopogo
Lonelytortoise
Popey

Nation:
San d'Oria

Job(level)/Sub Job(level):
99RDM/49DNC

NPC or Monster or item Name:
Maat

Zone name:
Ru'ludeGardens

Coordinates (use !where):
X:8 Y:3 Z:119

Item tool link (for items issues only):

Multi-boxing? (multiple clients on same connection):

Yes

Steps to reproduce:
Complete Shattering Stars
Speak to Maat
Deliver Exoray Mold, Bomb Coal, and Ancient Papyrus

Any additional information:
My github account is flagged and as such my posts default as hidden.

**Comment by EpicTaru** [comment]
Performed the above processes to verify that characters Albian, Nyaan, Onlan, Ogopogo, Lonelytortoise, Popey had the award item(s) in their inventory and then force-completed the relevant Genkai quest(s) related to that award item.

Leaving this issue open for issues with any of the subsequent Genkai quests that this player or any other player may have.

**Comment by EpicTaru** [comment]
Confirmed this was resolved in previous maintenance.  Closing.
