### ISSUE TITLE
Morta add spawning at wrong rift

### ISSUE THREAD

**Issue by CaptSparklez** [HomepointXI/Issues#48]
**Date & Time**: 06/05/2018

**Client Version (use `/ver` in game):** 30180203_1

**Character Name:** Hakubai

**Discord Name (if different from in game):** Haku

**Nation:** San D'Oria

**Job(level)/Sub Job(level):** PLD99/WAR49

**NPC or Monster or item Name:** Morta/Ravishing Rafflesia

**Zone name:** Aydeewa Subterrane

**Coordinates (use `!where`):** X:273 Y: 1 Z: 392 (236)

**Item tool link (for items issues only):** -

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** Popping Morta at the G-8 rift. Everything pops there except one single add. That one seems to pop at I-8 and then walk all the way to the correct rift. 

**Any additional information:**

**Comment by nfaletra** [comment]
Reworked all voidwatch mobs with adds. They should spawn near their master now.

**Comment by Jessland86** [comment]
Fixed in today's maintenance.
