### ISSUE TITLE
0 Delay Ammo

### ISSUE THREAD

**Issue by HitoSeven** [HomepointXI/Issues#480]
**Date & Time**: 

11/26/2020 @ 2:00pm EST

**Client Version (use `/ver` in game):**

30191204_1

**Character Name:**

Hito

**Discord Name (if different from in game):**

**Nation:**

Bastok

**Job(level)/Sub Job(level):**

60NIN/30DNC

**NPC or Monster or item Name:**

Any

**Zone name:** 

Any

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

No

**Steps to reproduce:**

Throw any ranged ammo

**Any additional information:**

I noticed throwing shurikens seem to have 0delay. I informed EpicTaru of this and he watched me throw them to confirm. Worked with Shurikens, Juji Shurikens & Manji Shurikens as that is all I can equip so far, I suspect most ammo is bugged with no delay.

**Comment by EpicTaru** [comment]
https://github.com/DarkstarProject/darkstar/issues/5885

**Comment by Heepster03** [comment]
closing due to new updated ticket # 560 created.
