### ISSUE TITLE
Cannot See Menus in Game

### ISSUE THREAD

**Issue by Shadowzero73** [HomepointXI/Issues#481]
**Date & Time**: 
Dec 2, 2020

**Client Version (use `/ver` in game):**
Version 30191204_!

**Character Name:**
Sonata

**Discord Name (if different from in game):**
Kairi Daybreak

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
Red Mage (11)

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
Cannot say various menus in game, I can move and hear the menus, but cannot see what I am purchase or what command I'm choosing in battle.

**Comment by EpicTaru** [comment]
This is usually due to incorrect resolution settings. If you are still having this issue, I'll look for you tomorrow and assist.

**Comment by Shadowzero73** [comment]
I'm running the game on laptop, what resolution should be used here?

**Comment by EpicTaru** [comment]
That's dependant on the capabilities of your video card. We can talk about this issue on discord. I'm closing this issue as it isn't an issue related to the server.

**Comment by EpicTaru** [comment]
I also can't @ you on discord, @Shadowzero73. You need to join the HP discord.

https://discord.gg/BahyXQj
