### ISSUE TITLE
Missing ??? pop location to trade Juju items used to spawn Dreamworld Dynamis bosses

### ISSUE THREAD

**Issue by xendral** [HomepointXI/Issues#483]
**Date & Time**:  12/15/2020 11:36 am PST

**Client Version (use `/ver` in game):**30191204_1

**Character Name:**Bozidar

**Discord Name (if different from in game):**CerisSquishy

**Nation:**Bastok

**Job(level)/Sub Job(level):**99th/49dnc

**NPC or Monster or item Name:**Apocalyptic Beast

**Zone name:** Dyna-Buburimu

**Coordinates (use `!where`):**-412 -31 0 (164)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**no

**Steps to reproduce:**Trying to pop monster.

**Any additional information:**
Cannot pop Monster for Harmony, Sitting at the spawn location for the ??? and it does not exist.

**Comment by EpicTaru** [comment]
Verified that at least one member of the above party has the necessary item needed to spawn the megaboss (Revelatory Juju, ItemID 3457).

Force-spawned megaboss of Dynamis-Buburimu (Apocalyptic Beast, mob ID 16941057) so that players are able to obtain zone win.

Leaving this issue open for issues with any of the other dynamis megaboss spawn issues that this player or any other player may have.

**Comment by Warleaf** [comment]
Having the same issue. No ??? to trade at in Dynamis - Vulkrum, Dynamis - Buburimu, and Dynamis - Quifim.

**Comment by EpicTaru** [comment]
@Warleaf Which chara will be used to kill the boss(es).  Need the name(s) please.

**Comment by Warleaf** [comment]
Warleaf has the Juju items.

**Comment by EpicTaru** [comment]
Verified that at least one member of the above party has the relevant necessary pop item needed to spawn the relevant megaboss (thru use of the **!hasitem** command):

Creeper's Juju (Item ID **3456**) for Dynamis Valk boss Cirrate Christelle (Mob ID **16936961**)

Revelatory Juju (Item ID **3457**) for Dynamis Bubu boss Apocalyptic Beast (Mob ID **16941057**)

Undying Juju (Item ID **3458**) for Dynamis Qufim boss Antaeus (Mob ID **16945153**)

The relevant pop item was then deleted from the inventory of the relevant player.

The relevant boss of the relevant Dreamland Dynamis zone was force-popped (thru use of the **!spawnmob** command) after verification that a member of the party had the relevant pop item for the relevant boss.

Leaving this issue open for issues with any of the other dynamis boss spawn issues that this player or any other player may have.

**Comment by Dankykong** [comment]
Hoping to unlock Tavnazia for an alt
![Omobolasire_2021 04 16_123307](https://user-images.githubusercontent.com/77759083/115069400-bdc26b00-9eb0-11eb-8961-222d8e19c7a9.png)

**Comment by EpicTaru** [comment]
@Dankykong Please get the character in the Dynamis and let me know on this ticket or in game when they are ready.

**Comment by EpicTaru** [comment]
Deleted Creeper's Juju (Item ID 3456) and spawned Dynamis Valk boss Cirrate Christelle (Mob ID 16936961).

**Comment by EpicTaru** [comment]
Deleted Undying Juju (Item ID 3458) and spawned Dynamis Qufim boss Antaeus (Mob ID 16945153).

**Comment by EpicTaru** [comment]
Deleted Revelatory Juju (Item ID 3457) and spawned Dynamis Bubu boss Apocalyptic Beast (Mob ID 16941057)

Congrats on access to Dynamis Tav, @Dankykong!

Leaving this issue open for issues with any of the other dynamis boss spawn issues that this player or any other player may have.

**Comment by EpicTaru** [comment]
Fixed in update on 04/29/2021.  Closing ticket.
