### ISSUE TITLE
CoP 5-3 (3 Paths) moving on to CoP 6-1

### ISSUE THREAD

**Issue by PunchdrunkXI** [HomepointXI/Issues#485]
**Date & Time**: 12.57PM 22nd December 2020

**Client Version (use `/ver` in game):** 30200604_0

**Character Name:**Buffdrunk, Azuredrunk and Healdrunk

**Discord Name (if different from in game):**Punchdrunk

**Nation:**Bastok

**Job(level)/Sub Job(level):**COR99/DNC49, BLU99/DNC49 and WHM99/RDM49

**NPC or Monster or item Name:**Cid and/or Pherimociel

**Zone name:** Metalworks and/or Ru'Lude Gardens

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**Yes

**Steps to reproduce:**

**Any additional information:**Having completed CoP 5-3, all 3 paths, and gotten the final cutscene from Cid about Prishe going to Jeuno the current mission resets to Ancient flames beckon. Current mission should be For whom the verse is sung, CoP 6-1.

**Comment by PunchdrunkXI** [comment]
![Buffdrunk_2020 12 22_124338](https://user-images.githubusercontent.com/68868049/102892366-aa017d80-4457-11eb-920c-a3aa5f2fa230.png)
A screenshot of the dialogue from the final cutscene of CoP 5-3, just incase

**Comment by EpicTaru** [comment]
Just woke up. Need to have my breakfast then I'll find you in game to fix your issue, @PunchdrunkXI

**Comment by PunchdrunkXI** [comment]
Issue has been resolved and march to Raja's ring has been restarted. Thanks again ET /myhero

**Comment by EpicTaru** [comment]
Npnp, let the endlesss COP cutscene march resume!

For the above character(s), verification of their variables was completed to make sure they were showing the correct values indicating that they had completed all 3 paths. After this verification, their **PromathiaStatus** variable was verified to be set at 0 or changed to reflect that. This doesn't appear to be a multiboxing issue, appears to be an issue in Cid's code. Issue started presenting itself after the server updated to the Dec. 2019 version.

Promathia Mission FOR_WHOM_THE_VERSE_IS_SUNG was then added to their mission log for current mission.
