### ISSUE TITLE
Stinger helm +1 missing Unity boost

### ISSUE THREAD

**Issue by PunchdrunkXI** [HomepointXI/Issues#486]
**Date & Time**: 3rd of January 2021. 9.15pm

**Client Version (use `/ver` in game):**30191204_1

**Character Name:**Punchdrunk

**Discord Name (if different from in game):**

**Nation:**Bastok

**Job(level)/Sub Job(level):**Drk99/Sam49

**NPC or Monster or item Name:**Stinger helm +1

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**http://homepointxi.com/db/items/26732/stinger_helm_+1

**Multi-boxing? (multiple clients on same connection):**Yes

**Steps to reproduce:**

**Any additional information:** Unity Ranking states STR +3~8 but isn't working

**Comment by EpicTaru** [comment]
Historically, for any other items that are available here that have Unity Ranking values, until the Unity Concord system is coded on the Topaz codebase, the items are given the maximum value of the Unity Ranking. In this case, this item needs to have a Fast Cast mod value of +6% added to it.

Heep/Immo, in item_mods.sql, just need to adjust the following line:

`INSERT INTO `item_mods` VALUES (26732,8,25);`
needs adjusted to:
`INSERT INTO `item_mods` VALUES (26732,8,33);    -- Item STR+25 plus Unity Concord - STR+8`

**Comment by EpicTaru** [comment]
Fixed in maintenance prior to most recent.
