### ISSUE TITLE
Aegis Upgrade

### ISSUE THREAD

**Issue by Draxxus82** [HomepointXI/Issues#487]
**Date & Time**: 
1/7/2021

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Draxxus

**Discord Name (if different from in game):**
Hauteclaire

**Nation:**
Windy

**Job(level)/Sub Job(level):**
99pld/49rdm

**NPC or Monster or item Name:**
Switchstix

**Zone name:** 
CZB

**Coordinates (use `!where`):**
X385 y-12 z-20 (130)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Jard, Proto, Ecplised, and Voltage

**Steps to reproduce:**

**Any additional information:**
Did the first upgrade over 24 hours ago, got the shield back in 2 hours, after the upgrade started, 24 later I cannot start the next level.

**Comment by EpicTaru** [comment]
Character's RELIC_CONQUEST_WAIT variable was set for the next Conquest Tally date of the server.  Updated value of the variable to be current time (set the variable value to 1610067587, which equates to Thursday, January 7, 2021 6:59:47 PM CST.

Had player then attempt to trade the Stage 2 relic shield and the items to the NPC, then the currency (two separate transactions).  Player reported that the NPC accepted all.

Checked value of character's RELIC_DUE_AT variable, which was set correctly for the 2hr wait as defined on the HomepointXI wiki.

Leaving this issue open for issues with any of the other relic building quest that this player or any other player may have.

**Comment by EpicTaru** [comment]
Resolved in maintenance prior to most recent.
