### ISSUE TITLE
Dynamis - Jeuno NMs and Megaboss not able to be spawned

### ISSUE THREAD

**Issue by Draxxus82** [HomepointXI/Issues#488]
**Date & Time**: 
1/18/2021 2:15PM et

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Draxxus

**Discord Name (if different from in game):**
hauteclair

**Nation:**
Windy

**Job(level)/Sub Job(level):**
99pld/49dnc

**NPC or Monster or item Name:**
Dynamis - Jeuno Nms

**Zone name:** 
Jeuno

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Enter Dynamis Jeuno

**Any additional information:**
I have gone in several times to get dynamis jeuno for the win, the nms for the boss drop do not spawn.  The statues for the nms are not able to be located either. The ??? near upper jueno is missing as well.

**Comment by EpicTaru** [comment]
All of the NMs in Jeuno are set to be lottery spawns in the mob_groups.sql file.  There are no mobs that are coded to spawn the NMs as a lottery spawn instead of a respawn of the placeholder mob or to even spawn the NM when a certain mob is aggroed (like how it used to be in old school dyna).  Also, the mobs that would spawn the NMs are also coded to not be spawned into the zone upon chara entry. 

This basically equates the NMs not existing in the basecode as it currently is (hence their absence and the absence of the mobs that would have spawned them under the old school dyna).  Also, the pop item (Roving Bijou) for the megaboss isn't coded to drop from any of the 33 NMs that have the pop item listed as a drop according to FFXIDB.  

Lastly, the ??? that the pop item would be traded to currently has a value of 4 for Status in the npc_list.sql file.  This value equates out to a status type of DISAPPEAR (aka hidden). This is why the ??? itself also isn't where it should be.

**Comment by EpicTaru** [comment]
Until the above issues are resolved, to allow players to progress thru all of the city dynamis zones (including Jeuno), I will force spawn the following 11 Jeuno NMs, which a chara must kill in order for me to then force spawn the megaboss (**Goblin Golem**, Mob ID **17547265**) of Dynamis - Jeuno.  These 11 mobs are as follows:

**Bandrix Rockjaw** (MobID **17547356**)
**Buffrix Eargone** (MobID **17547377**)
**Cloktix Longnail** (MobID **17547294**)
**Lurklox Dhalmelneck** (MobID **17547395**)
**Sparkspox Sweatbrow** (MobID **17547324**)
**Wyrmwix Snakespecs** (MobID **17547312**)
**Karashix Swollenskull** (MobID **17547424**)
**Kikklix Longlegs** (MobID **17547402**)
**Rutrix Hamgams** (MobID **17547454**)
**Snypestix Eaglebeak** (MobID **17547468**)
**Mobpix Mucousmouth** (MobID **17547474**)

The death messages of each of these NMs need to be screenshotted and the screenshots need to be pasted onto this ticket before I will then force spawn the megaboss.

Leaving this issue open for any other player that also encounters this.

**Comment by Draxxus82** [comment]
![Jeuno](https://user-images.githubusercontent.com/74222907/104961587-9e489e80-59a4-11eb-91e2-723bf5d336b2.png)

**Comment by EpicTaru** [comment]
Good work! Spawned the megaboss, good luck!

**Comment by EpicTaru** [comment]
@Draxxus82 In your opinion, how did it go with those 11 NMs?  Was it enough of a challenge?  How spread out were they in the zone?

**Comment by Draxxus82** [comment]
The NMs were spread out fairly decent minus 2 sets, the 2 at the top of the stairs and the 2 coming up from the fountain.  From a challenge standpoint, I think it will depend on job and numbers, if it's only 1 person on say a non-aoe/non-high offence, I could see where they could struggle, Even with help (total 2 people) In several cases 1 or both of us came close to dying due to links and random 2 hours. I think the links are the hardest part, fight an nm and also fight the 10+ mobs depending on where it is being pulled from.  Normally you could clear the trash and pop the nm so you are just fighting him. I think everyone will struggle minus 99 blue or really geared out people. I would have expected about 6 deaths based on the damage I was taking.

**Comment by EpicTaru** [comment]
Thanks for the information! I'll look into maybe eliminating some of the NMs from the requirement, especially in heavily congested areas.

**Comment by Draxxus82** [comment]
Need NM spawns for dynamis Jeuno

**Comment by EpicTaru** [comment]
Enter and I'll spawn them.

**Comment by EpicTaru** [comment]
9 NMs listed in ticket are spawned now, good luck! Do the death screenshots and paste them here and I'll then forcespawn the boss

**Comment by Draxxus82** [comment]
![image](https://user-images.githubusercontent.com/74222907/108118345-3a30fd00-706c-11eb-98d0-d05692aedff7.png)
![image](https://user-images.githubusercontent.com/74222907/108118992-1f12bd00-706d-11eb-97fd-aaefc60dafde.png)
![image](https://user-images.githubusercontent.com/74222907/108119606-09ea5e00-706e-11eb-887b-ad9ed6c60530.png)
![image](https://user-images.githubusercontent.com/74222907/108119941-82e9b580-706e-11eb-864d-928a6805861a.png)
![image](https://user-images.githubusercontent.com/74222907/108120609-8b8ebb80-706f-11eb-9177-8860eaa57792.png)

**Comment by EpicTaru** [comment]
4 more needed!

**Comment by Draxxus82** [comment]
Accidentally hit the comment button when I went to paste the screenshot.

**Comment by Draxxus82** [comment]
![image](https://user-images.githubusercontent.com/74222907/108121344-ad3c7280-7070-11eb-8477-9ce2935fa960.png)
![image](https://user-images.githubusercontent.com/74222907/108121533-eecd1d80-7070-11eb-9fab-10dd1d3ab7f1.png)
![image](https://user-images.githubusercontent.com/74222907/108121716-3fdd1180-7071-11eb-996b-a189b57f9582.png)
![image](https://user-images.githubusercontent.com/74222907/108122387-330ced80-7072-11eb-8a4e-fc4b57114554.png)

**Comment by EpicTaru** [comment]
Good job! I'll spawn it when you are near the spawn point.

**Comment by EpicTaru** [comment]
Pasting on behalf of Albian and his charas:

![image](https://user-images.githubusercontent.com/26195580/110030178-02c48080-7cfb-11eb-9ae1-b897c25c1ef9.png)
![image](https://user-images.githubusercontent.com/26195580/110030263-1bcd3180-7cfb-11eb-9936-a28a63e7b03c.png)
![unknown (1)](https://user-images.githubusercontent.com/26195580/110030310-2a1b4d80-7cfb-11eb-90f4-2a2753a9f77f.png)
![unknown (2)](https://user-images.githubusercontent.com/26195580/110030313-2ab3e400-7cfb-11eb-8f06-ed55de45ec44.png)
![unknown](https://user-images.githubusercontent.com/26195580/110030314-2ab3e400-7cfb-11eb-8419-a0feaaeee02e.png)

Forced spawned the megaboss and KI was obtained on all characters.

Leaving this issue open for any other player that also encounters this.

**Comment by Warleaf** [comment]
Looking to get my KI from Jeuno and would need the NMs force spawned, please.

**Comment by EpicTaru** [comment]
@Warleaf, I'm currently around an hour or so away from home, I can force spawn the NMs for you when I get back. After you've killed all of them and pasted the death messages on this ticket, I'll force spawn the zone boss for you.

**Comment by Warleaf** [comment]
![Jeuno Proof](https://user-images.githubusercontent.com/73000862/112407003-a77b2200-8ceb-11eb-9add-65872c6b0151.png)
Think this covers it.

**Comment by EpicTaru** [comment]
Congrats on the Dyna Jeuno clear, Warleaf!

Leaving this issue open for any other player that also encounters this.

**Comment by kpinoy** [comment]
Need to have NMs spawned in Dynamis - Jeuno for Nix.

**Comment by EpicTaru** [comment]
@kpinoy KK, enter the zone and I'll spawn the above 9 NMs for you.  Please screenshot the death messages of the 9 and paste them here.  I'll then force-spawn the boss for you to defeat.

**Comment by kpinoy** [comment]
Screen shots of defeated NMs below:

![IMG_8917](https://user-images.githubusercontent.com/80176429/112772242-8fa1e780-8fe4-11eb-91de-ea2a0e5f23bd.jpg)
![IMG_8918](https://user-images.githubusercontent.com/80176429/112772248-96305f00-8fe4-11eb-9a66-e7a0daffaae9.jpg)
![IMG_8919](https://user-images.githubusercontent.com/80176429/112772252-99c3e600-8fe4-11eb-910e-107179f72597.jpg)
![IMG_8921](https://user-images.githubusercontent.com/80176429/112772254-9a5c7c80-8fe4-11eb-8f93-f56591393a7c.jpg)
![IMG_8924](https://user-images.githubusercontent.com/80176429/112772256-9df00380-8fe4-11eb-9ea0-1fa4d32895e2.jpg)
![IMG_8925](https://user-images.githubusercontent.com/80176429/112772258-9e889a00-8fe4-11eb-9327-8311d25c7a33.jpg)
![IMG_8926](https://user-images.githubusercontent.com/80176429/112772262-a21c2100-8fe4-11eb-9df1-8155ec70c8c9.jpg)
![IMG_8927](https://user-images.githubusercontent.com/80176429/112772266-a6483e80-8fe4-11eb-92b3-68472f87e162.jpg)
![IMG_8928](https://user-images.githubusercontent.com/80176429/112772274-aa745c00-8fe4-11eb-93e9-19085e628875.jpg)

**Comment by EpicTaru** [comment]
Good job, @kpinoy! I'll force-spawn the boss for you tomorrow whenever you are ready.

**Comment by tuing** [comment]
need KI of Dyna Jeuno for Minimey and Higuchi which require to kill several NM which not spawning normally

**Comment by EpicTaru** [comment]
@tuing Let me know when you are doing to enter Dynamis - Jeuno and I'll force-spawn the NMs.

**Comment by tuing** [comment]
![Meyrink_2021 04 12_023354](https://user-images.githubusercontent.com/26522986/114319448-d55dc480-9b3b-11eb-830e-5488a5337443.png)
![Meyrink_2021 04 12_023716](https://user-images.githubusercontent.com/26522986/114319451-d68ef180-9b3b-11eb-8e7f-3e6dfae7a459.png)
![Meyrink_2021 04 12_023953](https://user-images.githubusercontent.com/26522986/114319453-d68ef180-9b3b-11eb-87cb-dbe65afe2ce0.png)
![Meyrink_2021 04 12_024151](https://user-images.githubusercontent.com/26522986/114319456-d7278800-9b3b-11eb-8003-c0ce4bc27d17.png)
![Meyrink_2021 04 12_024434](https://user-images.githubusercontent.com/26522986/114319459-d7c01e80-9b3b-11eb-927a-a6d0c6896a75.png)
![Meyrink_2021 04 12_024820](https://user-images.githubusercontent.com/26522986/114319460-d7c01e80-9b3b-11eb-9e70-d107b85a9be1.png)
![Meyrink_2021 04 12_025230](https://user-images.githubusercontent.com/26522986/114319461-d858b500-9b3b-11eb-9ac7-b79801c5ab43.png)
![Meyrink_2021 04 12_025732](https://user-images.githubusercontent.com/26522986/114319464-d8f14b80-9b3b-11eb-900b-0a60b8c2ba62.png)
![Meyrink_2021 04 12_030155](https://user-images.githubusercontent.com/26522986/114319466-d8f14b80-9b3b-11eb-898e-2a67496e43a9.png)

**Comment by EpicTaru** [comment]
Force-spawned boss for player and character (Higuchi) obtained KI for dyna clear upon death of boss.

**Comment by tuing** [comment]
![Meyrink_2021 04 12_031055](https://user-images.githubusercontent.com/26522986/114320420-19eb5f00-9b40-11eb-9178-eaf5732c63e6.png)
![Meyrink_2021 04 12_031238](https://user-images.githubusercontent.com/26522986/114320421-1b1c8c00-9b40-11eb-83a9-8efeaa45de7b.png)
![Meyrink_2021 04 12_031647](https://user-images.githubusercontent.com/26522986/114320422-1bb52280-9b40-11eb-98c7-0cad4d7efca2.png)
![Meyrink_2021 04 12_031719](https://user-images.githubusercontent.com/26522986/114320423-1c4db900-9b40-11eb-9ab0-39f1043b0504.png)
![Meyrink_2021 04 12_032305](https://user-images.githubusercontent.com/26522986/114320425-1ce64f80-9b40-11eb-8f98-109cc30deced.png)
![Meyrink_2021 04 12_032513](https://user-images.githubusercontent.com/26522986/114320426-1ce64f80-9b40-11eb-8214-1714a02dd9a0.png)
![Meyrink_2021 04 12_032633](https://user-images.githubusercontent.com/26522986/114320427-1d7ee600-9b40-11eb-8a2f-cf50a7afa3bc.png)
![Meyrink_2021 04 12_032859](https://user-images.githubusercontent.com/26522986/114320429-1e177c80-9b40-11eb-9203-d261d59c254d.png)
![Meyrink_2021 04 12_033135](https://user-images.githubusercontent.com/26522986/114320432-1eb01300-9b40-11eb-9bb7-39e9b40ba5e6.png)

**Comment by EpicTaru** [comment]
Force-spawned boss for player and character (Mimimey) obtained KI for dyna clear upon death of boss. Grats on your Dynamis - Jeuno clears, @tuing!

Leaving this issue open for any other player that also encounters this.

**Comment by Shoruto** [comment]
Ready for NM spawns.  Characters Sporky and Nyaan.

**Comment by EpicTaru** [comment]
NMs have been spanwed, please screenshot the death messages and paste them here.  I'll force-spawn the boss ones they are pasted. @Shoruto

**Comment by Shoruto** [comment]
All 9 NM's have been defeated.

![Karashix](https://user-images.githubusercontent.com/46944745/115075371-fbcb8900-9ec8-11eb-8679-916bd09d751a.png)
![Kikklix](https://user-images.githubusercontent.com/46944745/115075377-fc641f80-9ec8-11eb-815d-34c90f38e661.png)
![Lurklox](https://user-images.githubusercontent.com/46944745/115075378-fc641f80-9ec8-11eb-8c6a-650a4fd5e40c.png)
![Rutrix](https://user-images.githubusercontent.com/46944745/115075380-fcfcb600-9ec8-11eb-9924-d89c80a58dac.png)
![Sporky_2021 03 26_125123](https://user-images.githubusercontent.com/46944745/115075384-fcfcb600-9ec8-11eb-8383-35199e9ff876.png)
![Wyrmrix](https://user-images.githubusercontent.com/46944745/115075386-fcfcb600-9ec8-11eb-86b5-0055520833d1.png)
![Bandrix](https://user-images.githubusercontent.com/46944745/115075388-fd954c80-9ec8-11eb-8376-7f343df4989c.png)
![Buffrix](https://user-images.githubusercontent.com/46944745/115075390-fd954c80-9ec8-11eb-83f7-f52dc62f2404.png)
![Cloktix](https://user-images.githubusercontent.com/46944745/115075391-fe2de300-9ec8-11eb-8d37-ba99e4506b1b.png)

**Comment by Shoruto** [comment]
Forgot to post the 9th lol just did,

**Comment by EpicTaru** [comment]
Good job, @Shoruto! Spawning boss when you indicate you are ready.

**Comment by EpicTaru** [comment]
Boss force-spawned and successfully defeated.  Congrats on clearing Dynamis Jeuno, @Shoruto!!!

Leaving this issue open for any other player that also encounters this.

**Comment by KaizerZitro** [comment]
Need Dyna-Jeuno clearance for myself (Kaizer) and Louise

**Comment by EpicTaru** [comment]
Sec, I'll force-spawn the required NMs in a moment.

**Comment by EpicTaru** [comment]
NMs force-spawned. Please paste the death messages of them to this ticket. I will force-spawn the boss once they are.

**Comment by KaizerZitro** [comment]
![IMG_20210428_155445402](https://user-images.githubusercontent.com/82779126/116474369-062d4180-a83e-11eb-9f2d-771f773fb34b.jpg)
![IMG_20210428_155614393](https://user-images.githubusercontent.com/82779126/116474372-06c5d800-a83e-11eb-91ce-ddc841dc993f.jpg)
![IMG_20210428_160007788](https://user-images.githubusercontent.com/82779126/116474373-06c5d800-a83e-11eb-8342-feb4ad04643b.jpg)
![IMG_20210428_160020456](https://user-images.githubusercontent.com/82779126/116474374-075e6e80-a83e-11eb-939f-7f4be7b3c8bb.jpg)
![IMG_20210428_160308725](https://user-images.githubusercontent.com/82779126/116474375-075e6e80-a83e-11eb-8a1a-65994b01978e.jpg)
![IMG_20210428_160647345](https://user-images.githubusercontent.com/82779126/116474378-075e6e80-a83e-11eb-9462-96996da7c9a7.jpg)
![IMG_20210428_161222783](https://user-images.githubusercontent.com/82779126/116474381-07f70500-a83e-11eb-97e2-4e8717ddaff4.jpg)
![IMG_20210428_161301496](https://user-images.githubusercontent.com/82779126/116474385-07f70500-a83e-11eb-97b9-0c1e291e0aa3.jpg)

**Comment by tuing** [comment]
![Meyrink_2021 04 29_044728 - Copy](https://user-images.githubusercontent.com/26522986/116477017-3b6d7a00-a8a6-11eb-85fd-6f9d41d151b8.png)

**Comment by EpicTaru** [comment]
Good job!  I'll force-spawn the boss at your ready.

**Comment by EpicTaru** [comment]
Force-spawned boss which was subsequently defeated.  All characters that needed the KI indicating that they cleared the zone received it automatically upon death of the boss.  Congrats and welcome to Dynamis - Beaucedine~~

Leaving this issue open for any other player that also encounters this.

**Comment by EpicTaru** [comment]
Fixed in update on 04/29/2021.  Closing ticket.
