### ISSUE TITLE
Dynamis - Beaucedine attestation fomor NM and zone boss pop items

### ISSUE THREAD

**Issue by Draxxus82** [HomepointXI/Issues#489]
Date & Time:
1/19/2021 10AM

Client Version (use /ver in game):
30191204_1

Character Name:
Draxxus

Discord Name (if different from in game):
hauteclair

Nation:
Windy

Job(level)/Sub Job(level):
99pld/49dnc

**NPC or Monster or item Name:**

**Zone name:** 
Dynamis - Beaucedine

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
Despot's fortune parchment

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Dynamis - Beaucedine - Fomor NMs

**Any additional information:**
upon killing the mobs that drop the item needed to pop the attest nms, the normal mobs are not dropping the pop item.

**Comment by EpicTaru** [comment]
@Draxxus82 What attestation item are you hoping to obtain off of Goublefaupe?

**Comment by Draxxus82** [comment]
Attestation of invulnerability

**Comment by EpicTaru** [comment]
Unfortunately, none of the mobs that would normally drop that pop items (the misc. ...fortune parchment items) are currently coded to actually drop these items.  The fortune parchment items are then used to force-spawn the different fomor NMs that may then the attestations that you/other players are seeking.

Until the above issue is resolved, please follow these requirements:

Since you are seeking to kill Goublefaupe (Mob ID **17326086**) in hopes of a drop of the Attestation of Invulnerability, you need to kill 12 of the Hydra NMs that would normally drop the fortune parchment item. In your case, these are Hydra Paladin, Hydra Warrior, and Hydra Red Mage.  It can be 12 of one of the three NMs or a mix, just a total of 12 kills of them.  These mobs are scattered all around the zone.  

If you are seeking to kill Angra Mainyu (Mob ID **17326081**), unfortunately, the drop list of all the NMs that would drop the pop item (**Leering Bijou**, Item Id **3357**) used to force spawn Angra Mainyu) is incomplete as well as the drop percentage of the drop being horrendously low on the Item Tool compared to FFXIDB (Item Tool shows a 1% drop rate, FFXIDB has drop rate percentages between 33% all the way up to 100%...the 33% and 100% drops are likely in error due to low sample sizes).  For the purposes of time (each of the placeholder mobs are 10 minute respawns and the chances are low of the NM spawning instead of the placeholder,  you must kill either **one of the these four NMs** (should it spawn) or a total of **12 of these placeholder mobs**.  This means if you kill all 4 of the placeholders, you need to wait for respawns of each placeholder **twice** in hopes that the NM spawns instead. If the NM never spawns, the 12 placeholder kills are sufficient.  If the NM spawns, kill it and that itself is sufficient.  The NMs and their placeholders are specifically as follows:

Yagudo NM **Knii Hoqo the Bisector** (Mob ID **17326344**), placeholder is **Vanguard Persecutor** (Mob ID **17326343**) at I-8 (north-middle part, north of bottom of the ramp in the map grid square)

Orc NM **Drakefeast Wubmfub (Mob ID **17326273**), placeholder mob is **Vanguard Impaler** (Mob ID **17326271**) at J-7 (southern edge of pond in the NW corner of map grid square)

Quadav NM **Mu'Gha Legionkiller** (Mob ID **17326173**), placeholder mob is **Vanguard Defender ** (Mob ID **17326171**), at J-9 (east-middle part of map grid square)

Goblin NM **Slinkix Trufflesniff** (Mob ID **17326458**), placeholder mob is **Vanguard Ambusher** (Mob ID **17326457**), at 
I-8, west-middle part, at top-south edge of the ramp heading east in the map grid square).

It is advised that you **do not** attempt to obtain both the attestation and the zone clear all in one dynamis run due to the time constraints.  Like old school dynamis used to be where specific runs were done for attestation farming or for zone clears, it's best to do separate runs to allow for sufficient time to farm the above required mobs for the attestation NM or the megaboss.

As always, you need to screenshot the death messages of the above mobs (the Hydra NMs for the attestation NM or the placeholders/NMs for the megaboss) and paste the screenshots on this ticket in order for me to force-spawn the relevant fomor/megaboss NM.

Please respond here when you have read and understand the above requirements and are ready to let the fun begin!!!

**Comment by EpicTaru** [comment]
![Vanguard Ambusher PH for Slinkix Trufflesniff at I-8](https://user-images.githubusercontent.com/26195580/105079641-52a1fd80-5a55-11eb-8d9a-1b8edc4e1a32.png)
Vanguard Ambusher PH for Slinkix Trufflesniff at I-8
![Vanguard Defender PH for Mu'Gha Legionkiller at J-9](https://user-images.githubusercontent.com/26195580/105079643-533a9400-5a55-11eb-8f56-d204bd6e2855.png)
Vanguard Defender PH for Mu'Gha Legionkiller at J-9
![Vanguard Impaler PH for Drakefeast Wubmfub at J-7](https://user-images.githubusercontent.com/26195580/105079645-533a9400-5a55-11eb-85ba-432a16fd2888.png)
Vanguard Impaler PH for Drakefeast Wubmfub at J-7
![Vanguard Persecutor PH for Knii Hoqo the Bisector at I-8](https://user-images.githubusercontent.com/26195580/105079647-533a9400-5a55-11eb-84ab-0cd282bb5ffe.png)
Vanguard Persecutor PH for Knii Hoqo the Bisector at I-8

**Comment by Draxxus82** [comment]
![Proof2](https://user-images.githubusercontent.com/74222907/105084877-f8a93400-5a64-11eb-837d-daab8ced86be.PNG)

**Comment by EpicTaru** [comment]
Good work! I'm waiting at the pop tower of  the fomor NM, I'll spawn it when you are in the tower.

**Comment by Draxxus82** [comment]
![2](https://user-images.githubusercontent.com/74222907/105089581-504a9e00-5a6b-11eb-8d1a-c1f2279e3b98.PNG)
![3](https://user-images.githubusercontent.com/74222907/105089582-50e33480-5a6b-11eb-8e6c-27c10d881d4e.PNG)
![4](https://user-images.githubusercontent.com/74222907/105089583-50e33480-5a6b-11eb-8504-ae8cf75edb83.PNG)
![5](https://user-images.githubusercontent.com/74222907/105089584-50e33480-5a6b-11eb-81f6-7912fd31e15c.PNG)
![6](https://user-images.githubusercontent.com/74222907/105089585-50e33480-5a6b-11eb-8db7-0fe308dfe291.PNG)
![7](https://user-images.githubusercontent.com/74222907/105089587-50e33480-5a6b-11eb-88d3-6ba6428cb13c.PNG)
![8](https://user-images.githubusercontent.com/74222907/105089588-517bcb00-5a6b-11eb-8dac-6f387aa41cf3.PNG)
![9](https://user-images.githubusercontent.com/74222907/105089589-517bcb00-5a6b-11eb-9977-b9b883564afe.PNG)
![pld1](https://user-images.githubusercontent.com/74222907/105089591-517bcb00-5a6b-11eb-9bdd-32eb942db4bd.PNG)

**Comment by EpicTaru** [comment]
Good work! I'm waiting at the pop tower of the fomor NM, I'll spawn it when you are in the tower.

If you obtain the desired attestation, please comment that you did and also please give your thoughts on the req. number of hydra kills.

**Comment by Draxxus82** [comment]
Item achieved. I think 9 is a good number, the 12 left me with only 5 minutes, and to be honest, without o club and spamming weapon skills I don't think that I would have made it through in time. I had to switch jobs the second time around to try and make it faster, in general, I don't know how many people would have several different 99s to change into, easy enough for a whm to do in time.

**Comment by EpicTaru** [comment]
Good to know, thanks and congrats!

**Comment by Draxxus82** [comment]
![nm](https://user-images.githubusercontent.com/74222907/105096156-b0920d80-5a74-11eb-93a7-7e47700f5030.PNG)

**Comment by EpicTaru** [comment]
Yep, that's one of the other NMs that have the Leering Bijou as a drop, good work!!!  I'm waiting at the pop spot of the megaboss (by where the zone into Fei'yin would be), I'll spawn it when you are there.

**Comment by Draxxus82** [comment]
After the boss was spawned all 4 dragons poped as expected the boss cast meotor II on me once he got around 50% doing over 2500 dmg.  In a weakened state, I tried again, this time I planned to stun kill the boss on meotor then ws him to death. I did not stun and died again. I got help and was able to then kill the boss and get the KI.

**Comment by EpicTaru** [comment]
Hmmm, the boss isn't coded to use Meteor II at a specific point in its HP or at a certain time in battle so the fact that it did it twice is just pure RNGesus unluckiness, sorry that it happened but glad you were able to eventually defeat the megaboss.  Congrats!

**Comment by EpicTaru** [comment]
https://github.com/HomepointXI/Issues/issues/492

**Comment by Oderson** [comment]
needing a force attestestion
![Capture](https://user-images.githubusercontent.com/22406564/107666511-378d6c80-6c54-11eb-827f-fd0e640d9726.JPG)
![Capture2](https://user-images.githubusercontent.com/22406564/107666517-39573000-6c54-11eb-917b-3e593b6981cd.JPG)
![Capture3](https://user-images.githubusercontent.com/22406564/107666525-3a885d00-6c54-11eb-9fb9-b96b5108f9bb.JPG)
![Capture4](https://user-images.githubusercontent.com/22406564/107666528-3b20f380-6c54-11eb-9721-fb46446d0b25.JPG)
![Capture5](https://user-images.githubusercontent.com/22406564/107666530-3bb98a00-6c54-11eb-8ded-33f998a919a7.JPG)

**Comment by EpicTaru** [comment]
Good work! I'm waiting at the pop tower of the fomor NM, I'll spawn it when you are in the tower.

I'll force spawn the NM up to 3 times if you are don't get the desired drop.  If you don't get the drop in those 3 times, you need to re-kill another 9 mobs like you did before.

**Comment by Draxxus82** [comment]
![image](https://user-images.githubusercontent.com/74222907/108124102-ca734000-7074-11eb-986f-7d7b0a290d50.png)

**Comment by EpicTaru** [comment]
Good job! I'll spawn the megaboss when you are near the spawn point.

**Comment by EpicTaru** [comment]
Pasting all these on behalf of Albian:
![pol_2021_03_05_18_13_35_802](https://user-images.githubusercontent.com/26195580/110225950-def66b80-7eaf-11eb-969c-58752f24aef1.jpg)
![pol_2021_03_06_15_11_54_415](https://user-images.githubusercontent.com/26195580/110225951-df8f0200-7eaf-11eb-8667-d98f0ca48d0d.jpg)
![pol_2021_03_05_16_59_28_874](https://user-images.githubusercontent.com/26195580/110225952-df8f0200-7eaf-11eb-8c0a-d2d1f7916573.jpg)
![pol_2021_03_06_16_19_29_925](https://user-images.githubusercontent.com/26195580/110225953-e0279880-7eaf-11eb-924a-dfb320c5a6ca.jpg)
![pol_2021_03_06_19_23_29_417](https://user-images.githubusercontent.com/26195580/110225954-e0279880-7eaf-11eb-85b7-61d8624e7890.jpg)

Angra Mainyu was forcespawned for all of the above characters.

**Comment by Warleaf** [comment]
![Beaucedine proof](https://user-images.githubusercontent.com/73000862/112673588-49f5eb00-8e3b-11eb-9142-c8c4f6c582b3.png)

**Comment by EpicTaru** [comment]
Very nice, @Warleaf! I'll spawn the Dyna Beaucidine boss when you are ready.

**Comment by Dankykong** [comment]
Looking to try for attestation of invulnerability for Aegis

![Vixxen_2021 03 27_002030](https://user-images.githubusercontent.com/77759083/112736784-e4792b80-8f1a-11eb-92c2-1f766204e7f1.png)
![Vixxen_2021 03 27_002118](https://user-images.githubusercontent.com/77759083/112736787-e7741c00-8f1a-11eb-8f04-ac28b6aa2e8f.png)
![Vixxen_2021 03 27_002134](https://user-images.githubusercontent.com/77759083/112736789-ea6f0c80-8f1a-11eb-9476-59b2ed7b238b.png)
![Vixxen_2021 03 27_002418](https://user-images.githubusercontent.com/77759083/112736790-ee029380-8f1a-11eb-8bfd-85e96d968733.png)
![Vixxen_2021 03 27_002636](https://user-images.githubusercontent.com/77759083/112736796-f8bd2880-8f1a-11eb-838c-dcfa3211bc7e.png)
![Vixxen_2021 03 27_002648](https://user-images.githubusercontent.com/77759083/112736801-fc50af80-8f1a-11eb-9eec-07f43f6f726f.png)
![Vixxen_2021 03 27_002734](https://user-images.githubusercontent.com/77759083/112736803-05418100-8f1b-11eb-8b4a-e4ce1984ebcf.png)
![Vixxen_2021 03 27_003047](https://user-images.githubusercontent.com/77759083/112736805-07a3db00-8f1b-11eb-85b0-367a6701188a.png)
![Vixxen_2021 03 27_003217](https://user-images.githubusercontent.com/77759083/112736807-0a9ecb80-8f1b-11eb-95c9-419dc0a6d04d.png)

**Comment by EpicTaru** [comment]
@Dankykong, good job!!! Let me know when you are ready to try your luck at the attestation fomor NM and I'll force-pop it up to three times for your needed attestation.

**Comment by Dankykong** [comment]
thanks! heading up now

**Comment by EpicTaru** [comment]
Pasting this here for Albian, Github still being stupid about his Github account.

![pol_2021_03_27_12_20_00_551](https://user-images.githubusercontent.com/26195580/112737140-32dff780-8f26-11eb-9d13-221d6bb6b4fe.jpg)

Albian needed Attestation of Fortitude from fomor NM  Dagourmarche.

 Dagourmarche was force-spawned earlier today around 1200 CST and the needed attestation dropped on the first spawn.

**Comment by EpicTaru** [comment]
Congrats on obtained your attestation, @Dankykong!

**Comment by Dankykong** [comment]
Mission complete. Thanks!

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/113354892-8460fb80-9305-11eb-8057-6c3b03cc3553.png)

Leaving this issue open for any other player that also needs either of these (fomors/zone boss).

**Comment by tuing** [comment]
![Meyrink_2021 04 12_041653](https://user-images.githubusercontent.com/26522986/114322444-853a2e80-9b4a-11eb-8146-e2fa9e5a4a2f.png)
![Meyrink_2021 04 12_041842](https://user-images.githubusercontent.com/26522986/114322445-866b5b80-9b4a-11eb-9616-af7e60076d15.png)
![Meyrink_2021 04 12_041934](https://user-images.githubusercontent.com/26522986/114322446-8703f200-9b4a-11eb-85d7-ebb8b31f7b00.png)
![Meyrink_2021 04 12_041957](https://user-images.githubusercontent.com/26522986/114322447-879c8880-9b4a-11eb-8fc2-d232775da325.png)
![Meyrink_2021 04 12_043330](https://user-images.githubusercontent.com/26522986/114322448-88351f00-9b4a-11eb-9dae-357330158181.png)
![Meyrink_2021 04 12_043524](https://user-images.githubusercontent.com/26522986/114322449-88cdb580-9b4a-11eb-977d-6f128b282120.png)
![Meyrink_2021 04 12_043657](https://user-images.githubusercontent.com/26522986/114322450-89664c00-9b4a-11eb-974f-2c0e4dd0d43b.png)
![Meyrink_2021 04 12_043718](https://user-images.githubusercontent.com/26522986/114322451-89fee280-9b4a-11eb-8620-55538cd363cf.png)
![Uploading Meyrink_2021.04.12_044629.png…]()

**Comment by EpicTaru** [comment]
Force-spawned boss for player and character (Higuchi) obtained KI for dyna clear upon death of boss.

**Comment by tuing** [comment]
![Meyrink_2021 04 12_044231](https://user-images.githubusercontent.com/26522986/114323025-8a4cad00-9b4d-11eb-866e-98fdb7be4357.png)
![Meyrink_2021 04 12_040635](https://user-images.githubusercontent.com/26522986/114323026-8b7dda00-9b4d-11eb-8278-fb99feec1755.png)
![Meyrink_2021 04 12_040747](https://user-images.githubusercontent.com/26522986/114323028-8c167080-9b4d-11eb-8b43-855770502bce.png)
![Meyrink_2021 04 12_040945](https://user-images.githubusercontent.com/26522986/114323030-8caf0700-9b4d-11eb-86d5-902fc93a4710.png)
![Meyrink_2021 04 12_042427](https://user-images.githubusercontent.com/26522986/114323032-8d479d80-9b4d-11eb-9204-7a3e07a0001c.png)
![Meyrink_2021 04 12_042444](https://user-images.githubusercontent.com/26522986/114323033-8de03400-9b4d-11eb-82a1-c030e0008a23.png)
![Meyrink_2021 04 12_042554](https://user-images.githubusercontent.com/26522986/114323034-8de03400-9b4d-11eb-9ba7-3deed66123a5.png)
![Meyrink_2021 04 12_044101](https://user-images.githubusercontent.com/26522986/114323035-8e78ca80-9b4d-11eb-8939-35abbddf9a38.png)
![Meyrink_2021 04 12_044206](https://user-images.githubusercontent.com/26522986/114323037-8f116100-9b4d-11eb-8c9f-6109beafb1fd.png)

**Comment by EpicTaru** [comment]
Force-spawned boss for player and character (Mimimey) obtained KI for dyna clear upon death of boss. Grats on your Dynamis - Beaucedine clears, @tuing!

Leaving this issue open for any other player that also needs either of these (fomors/zone boss).

**Comment by Shoruto** [comment]
Ready to spawn 
![hydra bard 2](https://user-images.githubusercontent.com/46944745/115092817-4fe56600-9ee7-11eb-8f26-908f87643a36.png)
![hydra bard 3](https://user-images.githubusercontent.com/46944745/115092827-507dfc80-9ee7-11eb-8f53-b8af3e227cdf.png)
![hydra bard 4](https://user-images.githubusercontent.com/46944745/115092831-507dfc80-9ee7-11eb-8432-9722c7f3bf2f.png)
![hydra bard](https://user-images.githubusercontent.com/46944745/115092835-51169300-9ee7-11eb-8480-3c669cfd45af.png)
![hydra black mage 2](https://user-images.githubusercontent.com/46944745/115092838-51169300-9ee7-11eb-9a1a-3f41a23967b2.png)
![hydra black mage](https://user-images.githubusercontent.com/46944745/115092843-51169300-9ee7-11eb-86f8-2019563697d0.png)
![hydra white mage 2](https://user-images.githubusercontent.com/46944745/115092847-51af2980-9ee7-11eb-9057-cbbb56530a70.png)
![hydra white mage 3](https://user-images.githubusercontent.com/46944745/115092854-51af2980-9ee7-11eb-8478-2ca73cfdab49.png)
![hydra white mage](https://user-images.githubusercontent.com/46944745/115092857-5247c000-9ee7-11eb-810b-0833d7a932d6.png)








Quiebitiel for try at Attestation of Sacrifice (Club)

**Comment by EpicTaru** [comment]
@Shoruto I'll assist you first thing in the morning. Thanks abundantly for your patience.

**Comment by EpicTaru** [comment]
Force-spawned Quiebitiel (Mob ID 17326087). Player obtained desired attestation.  Congrats @Shoruto!

Leaving this issue open for any other player that also needs either of these (fomors/zone boss).

**Comment by Shoruto** [comment]
![D](https://user-images.githubusercontent.com/46944745/115163405-f57b0f80-a076-11eb-90a5-f187fa66529c.png)
![D2](https://user-images.githubusercontent.com/46944745/115163407-f613a600-a076-11eb-8f04-28b55f59bae2.png)
![D3](https://user-images.githubusercontent.com/46944745/115163409-f613a600-a076-11eb-9e7a-3130867da91a.png)
![I](https://user-images.githubusercontent.com/46944745/115163410-f613a600-a076-11eb-8c50-837b739b6092.png)
![I2](https://user-images.githubusercontent.com/46944745/115163411-f6ac3c80-a076-11eb-95b2-0b9a5adc66df.png)
![I3](https://user-images.githubusercontent.com/46944745/115163412-f6ac3c80-a076-11eb-9cfc-5eb48299e17e.png)
![P](https://user-images.githubusercontent.com/46944745/115163413-f6ac3c80-a076-11eb-8c70-a360dddc9df7.png)
![P2](https://user-images.githubusercontent.com/46944745/115163414-f744d300-a076-11eb-8958-fa906c9d9ae2.png)
![P3](https://user-images.githubusercontent.com/46944745/115163415-f744d300-a076-11eb-8f67-1c133995b013.png)

Ready to fight the Megaboss at your leisure.

Character - Sporky

**Comment by EpicTaru** [comment]
@Shoruto Good job! I'm waiting at the spot where the ??? would be, ready to force-spawn the mob at your ready. Please indicate here on this ticket or let me know in game that you are ready.

**Comment by EpicTaru** [comment]
Boss force-spawned and subsequently defeated, character Sporky obtained the KI for the zone win.  Congrats, @Shoruto!

Leaving this issue open for any other player that also needs either of these (fomors/zone boss).
