### ISSUE TITLE
GM Please Help

### ISSUE THREAD

**Issue by mike55544** [HomepointXI/Issues#49]
**Date & Time**:  May 7, 2018 1:15pm

**Client Version (use `/ver` in game):** 30180329_1

**Character Name:** Bartram

**Discord Name (if different from in game):** none

**Nation:** Bastok

**Job(level)/Sub Job(level):** 87 THF

**NPC or Monster or item Name:**  None

**Zone name:** Mordion Gaol

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:** My 72 hours have passed and I have certainly learned my lesson. I  just need GM to take me out of jail please per Astraea instructions

**Comment by nfaletra** [comment]
Technically, the Zone name is "Mordion Gaol" mmk?

**Comment by EpicTaru** [comment]
@mike55544 hang tight, I'll release you in a few mins

**Comment by EpicTaru** [comment]
Oops, accidental close!

**Comment by mike55544** [comment]
Ok I fixed it.... Thank you
 Mike

**Comment by mike55544** [comment]
Thank you

**Comment by EpicTaru** [comment]
Released 05/07/18 at 1238 CST
