### ISSUE TITLE
Dynamis - Xarcabard - Animated Weapon NMs and Vanguard Dragon pops

### ISSUE THREAD

**Issue by Draxxus82** [HomepointXI/Issues#490]
Date & Time:
1/19/2021 5:30 PM

Client Version (use /ver in game):
30191204_1

Character Name:
Draxxus

Discord Name (if different from in game):
hauteclair

Nation:
Windy

Job(level)/Sub Job(level):
99pld/49dnc

**NPC or Monster or item Name:**

**Zone name:** 
Dynamis - Xarcabard

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
Supernal_Fragment
Shard of necropsyche

**Multi-boxing? (multiple clients on the same connection):**
no

**Steps to reproduce:**

**Any additional information:**
The eyes are not at the towers like normal. the weapons are roaming around, but no sign of animated weapons. The satellight weapons do not show having pop item in drop list.  Need help on how to weapons to spawn for fragment.

**Comment by EpicTaru** [comment]
Ah yes, more messed up Neo Dynamis thanks to being incomplete on the DSP basecode when we did the version update!!!

You are correct that the satellite weapons don't have the pop item coded in their drop lists that are now used to force spawn the animated weapon of the same type.

Since there is so much fun that the workarounds for all of the prior Dynamis zones provided, especially Dynamis - Jeuno and Dynamis - Beaucedine, until the above issue with the satellite weapons is resolved, in order for me to force spawn the relevant Animated Weapon of the same type, the following is the requirement:

Locate and defeat all 6 of the Satellite Weapons of the same type as the Animated Weapon.  Please screenshot the death messages of the Satellite Weapons and paste the screenshots here.  I will then force spawn the relevant Animated Weapon of that type.

The Item Tool shows the Necropsyche correctly dropping from the Vanguard Dragons on the ramps near the zone to where Castle Z is.  Best of luck obtaining the Necropsyche from them!

**Comment by EpicTaru** [comment]
Just force spawned and killed the Animated Shield to ensure that it would drop the relevant fragment (was concerned that the drop is limited like how it used to be with old school dynamis where the Animated Weapons wouldn't drop the fragment unless all 15 of the Kindred NMs are first defeated.

**Comment by Draxxus82** [comment]
![image](https://user-images.githubusercontent.com/74222907/105103326-6f9ef680-5a7e-11eb-8623-a5dab972f3fb.png)
![image](https://user-images.githubusercontent.com/74222907/105103371-82193000-5a7e-11eb-9cb8-f043132096da.png)
![image](https://user-images.githubusercontent.com/74222907/105103456-a07f2b80-5a7e-11eb-8e04-49d6fbb96700.png)
![image](https://user-images.githubusercontent.com/74222907/105103508-b55bbf00-5a7e-11eb-82b0-fc3354866649.png)
![image](https://user-images.githubusercontent.com/74222907/105103555-ca385280-5a7e-11eb-934f-34abb3feb961.png)

**Comment by EpicTaru** [comment]
Good work on defeating all 6, I could barely make out the text for the 5th one hidden behind the text of the 4th one, lol.  I'm waiting at the pop spot of the relevate Animated Weapon, I'll spawn it when you are there.

**Comment by EpicTaru** [comment]
And for whatever reason, the Vanguard Dragons are set in the database to be scripted spawns but there are no other mobs in the zone that are scripted to spawn them.  Because of this, I will force spawn all of the Vanguard Dragons.

**Comment by Draxxus82** [comment]
I was able to get both items. For the first one animated nm I liked the path of killing the shields then getting the nm, with links it was not a bad fight. got a few adds when we popped the nm. On the dragons, they had to be popped, was able to get the item on my 1st or second kill I linked 2

**Comment by EpicTaru** [comment]
All good to know, thanks for being patient and helpful in all these!

**Comment by EpicTaru** [comment]
Leaving this issue open for any other player that also encounters this.

**Comment by EpicTaru** [comment]
Nevion Today at 12:45 PM
can I get some help popping Vanguard Dragon pleeeeeeeeeeeease?

Epic🚀👖Taru/Gathin/Ancillam Today at 12:46 PM
yeah, sec, they aren't set to spawn on zone load atm

Leaving this issue open for any other player that also encounters this.

**Comment by Dankykong** [comment]
Hoping to get the last couple items for relic shield please
![Shield1](https://user-images.githubusercontent.com/77759083/113058251-29939c80-916b-11eb-84e9-35ce09243f0d.png)
![Shield2](https://user-images.githubusercontent.com/77759083/113058273-2c8e8d00-916b-11eb-9e9a-213722f0867c.png)
![Shield3](https://user-images.githubusercontent.com/77759083/113058291-2e585080-916b-11eb-9607-5d339ef34810.png)
![Shield4](https://user-images.githubusercontent.com/77759083/113058299-30baaa80-916b-11eb-929b-d70d7d4664c6.png)
![Shield5](https://user-images.githubusercontent.com/77759083/113058301-31ebd780-916b-11eb-99c7-11b1dd6a0516.png)
![Shield6](https://user-images.githubusercontent.com/77759083/113058310-344e3180-916b-11eb-88ed-2fdfe648192e.png)

**Comment by EpicTaru** [comment]
![Discord_kZEe6lKH0c](https://user-images.githubusercontent.com/26195580/113059752-6d8b9f00-9175-11eb-8c2f-d4642aeded19.png)

Force-spawned the Animated Spears for Albian, congrats on your drop!!!

**Comment by EpicTaru** [comment]
Force spawned Animated Shield for Dankykong (Vixxen IGN), congrats on your drop!

**Comment by Dankykong** [comment]
Thank you! I need to get a necroscythe too please

**Comment by EpicTaru** [comment]
KK, I'll force-spawn those right now as well, they'll be up by the time you get to where they are at normally.

**Comment by Dankykong** [comment]
Mission complete! Thank you!

**Comment by Dankykong** [comment]
Back at it again with the relics!
![sword1](https://user-images.githubusercontent.com/77759083/113353760-642c3f00-92fb-11eb-8a84-f4b96aa08871.png)
![sword2](https://user-images.githubusercontent.com/77759083/113353766-65f60280-92fb-11eb-9939-49f91fdd0417.png)
![sword 6](https://user-images.githubusercontent.com/77759083/113353777-67bfc600-92fb-11eb-9aad-add901b25690.png)
![sword 5](https://user-images.githubusercontent.com/77759083/113353785-6a222000-92fb-11eb-8dbb-8efe41b68eaa.png)
![sword 4](https://user-images.githubusercontent.com/77759083/113353788-6e4e3d80-92fb-11eb-83b8-41c01dd619b2.png)
![sword 3](https://user-images.githubusercontent.com/77759083/113353792-70b09780-92fb-11eb-97bd-e00ebffa393b.png)

**Comment by EpicTaru** [comment]
@Dankykong Good job, I'll force spawn the Animated Longsword whenever you are ready, just lemme know in game.

**Comment by Dankykong** [comment]
Got it, thank you!

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/113354814-58457a80-9305-11eb-9199-56f8d007feee.png)

**Comment by Naibla** [comment]
![pol_2021_04_08_16_30_29_864](https://user-images.githubusercontent.com/82182818/114098334-3745d200-988f-11eb-9d30-f5c6d844bb62.png)

**Comment by EpicTaru** [comment]
@Naibla please let me know when you are ready for me to force-spawn the Animated Shield

**Comment by tuing** [comment]
![01](https://user-images.githubusercontent.com/26522986/114215502-dfdb5b00-998f-11eb-9698-ea7a360198e8.jpg)
![02](https://user-images.githubusercontent.com/26522986/114215509-e10c8800-998f-11eb-8011-78868de0251c.jpg)
![03](https://user-images.githubusercontent.com/26522986/114215512-e10c8800-998f-11eb-82f6-b3eeee3ee220.jpg)
![04](https://user-images.githubusercontent.com/26522986/114215513-e1a51e80-998f-11eb-9a6b-02e3935d006a.jpg)
![05](https://user-images.githubusercontent.com/26522986/114215515-e23db500-998f-11eb-8f66-00fe167d3d2b.jpg)
![06](https://user-images.githubusercontent.com/26522986/114215521-e36ee200-998f-11eb-8538-4db7c5343572.jpg)

**Comment by EpicTaru** [comment]
@tuing Good job!  My GM chara is waiting at the location the Animated Kunai will be force-spawned at.  Please /tell me in game when you are ready for me to spawn it.

**Comment by EpicTaru** [comment]
Force spawned Animated Kunai for Tuing (Meyrink IGN), congrats on your drop!

Leaving this issue open for any other player that also encounters this.

**Comment by tuing** [comment]
![Meyrink_2021 04 13_032411](https://user-images.githubusercontent.com/26522986/114457406-318e1a80-9c08-11eb-860a-250b88225065.png)
![Meyrink_2021 04 13_032124](https://user-images.githubusercontent.com/26522986/114457410-32bf4780-9c08-11eb-8d5c-6e5c6760232d.png)
![Meyrink_2021 04 13_032146](https://user-images.githubusercontent.com/26522986/114457413-3357de00-9c08-11eb-9ea4-0166cc5d564b.png)
![Meyrink_2021 04 13_032220](https://user-images.githubusercontent.com/26522986/114457414-3357de00-9c08-11eb-9539-1cec8ae991a1.png)
![Meyrink_2021 04 13_032321](https://user-images.githubusercontent.com/26522986/114457417-33f07480-9c08-11eb-8107-7803a8f8e85d.png)
![Meyrink_2021 04 13_032343](https://user-images.githubusercontent.com/26522986/114457420-34890b00-9c08-11eb-99af-57709c405b04.png)

**Comment by EpicTaru** [comment]
@tuing Good job! I'll force-spawn the Animated Horn at your ready.

**Comment by EpicTaru** [comment]
Animated Horn force-spawned and character obtained the desired fragment. Grats!

**Comment by Albian-HomepointXI** [comment]
![pol_2021_04_17_09_29_17_735](https://user-images.githubusercontent.com/74258270/115115137-ac389c00-9f60-11eb-8232-5bc5a13a3671.jpg)

**Comment by EpicTaru** [comment]
@Albian-HomepointXI Good job, ready to force-spawn the Animated Horn at your ready.  Let me know here on this ticket or in game.

**Comment by EpicTaru** [comment]
Force-spawned Animated Horn (Mob ID 17330213) and player obtained desired Fragment.  Congrats @Albian-HomepointXI!

Leaving this issue open for any other player that also encounters this.

**Comment by Shoruto** [comment]
Ready for Animated Hammer :)

![Satellite Hammer](https://user-images.githubusercontent.com/46944745/115427374-6a615d00-a1cf-11eb-912d-84c78fb3a893.png)
![Satellite Hammer2](https://user-images.githubusercontent.com/46944745/115427376-6af9f380-a1cf-11eb-84a2-a3b632277df6.png)
![Satellite Hammer3](https://user-images.githubusercontent.com/46944745/115427379-6af9f380-a1cf-11eb-8374-e77d7f79a1d1.png)
![Satellite Hammer4](https://user-images.githubusercontent.com/46944745/115427380-6b928a00-a1cf-11eb-85c8-1e5429394588.png)
![Satellite Hammer5](https://user-images.githubusercontent.com/46944745/115427382-6b928a00-a1cf-11eb-8bb7-dc9c0ebc2080.png)
![Satellite Hammer6](https://user-images.githubusercontent.com/46944745/115427386-6b928a00-a1cf-11eb-8cdf-299ba59e194e.png)

**Comment by EpicTaru** [comment]
@Shoruto Good job **_hammering_** out those kills!!! I'm ready to force-spawn the Animated Hammer mob at your ready.  Please let me know here on this ticket or in game when you are.

**Comment by Shoruto** [comment]
I am taking a break, I'll be back around 5:30pm eastern.

**Comment by EpicTaru** [comment]
Understood, look me up around that time and we'll _put a nail in the coffin_ of this for you.

**Comment by EpicTaru** [comment]
Animated Hammer (Mob ID 17330209) force-spawned and subsequently defeated.  Player obtained the desired fragment.  Congrats on the successful defeat, @Shoruto!!!

Leaving this issue open for any other player that also encounters this.

**Comment by EpicTaru** [comment]
Fixed in update on 04/29/2021.  Closing ticket.
