### ISSUE TITLE
Account Recovery

### ISSUE THREAD

**Issue by BiggX048** [HomepointXI/Issues#491]
**Date & Time**:Last online: Jul 8, 2018 8:30:37 PM

**Client Version (use `/ver` in game):**

**Character Name:Tdogg**

**Discord Name (if different from in game):BiggX**

**Nation:San d'Oria**

**Job(level)/Sub Job(level):BLU84/WAR42**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):Yes**

**Steps to reproduce:**

**Any additional information:Lost Account Information**

**Comment by Heepster03** [comment]
If you're still interested, you can reach me at: Halkuras#1965 on Discord.
