### ISSUE TITLE
Dynamis - Beaucedine NM pop item for relic dagger chain

### ISSUE THREAD

**Issue by Dankykong** [HomepointXI/Issues#492]
**Date & Time**: 
Jan 20, 2021 7PM EST

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Vixxen

**Discord Name (if different from in game):**
Sevvghetto

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
99thf/49dnc

**NPC or Monster or item Name:**
NM - Quiebitiel

**Zone name:** 
Dynamis - Beaucedine

**Coordinates (use `!where`):**
X: -90, Y: -0.478, Z: -367.674

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
@Dankykong I'm going offline in a few minutes, have an online meeting I need to attend and then I'm done for the day. When will you be available tomorrow?

**Comment by EpicTaru** [comment]
Sounds good, in the meantime, please read the following, you can perform this today and then paste the death message screenshots today, we can begin the fun tomorrow with the spawn of the relevant fomor NM if today you complete the following:

Since you are seeking to kill **Quiebitiel** (Mob ID **17326086**) in hopes of a drop of the Attestation of Celerity, you need to kill  9 of the Hydra NMs that would normally drop the fortune parchment item. In your case, these are Hydra Bard, Hydra Black Mage, and Hydra White Mage.  It can be 9 of one of the three NMs or a mix, just a total of 9 kills of them.  These mobs are scattered all around the zone.  The attestations are 33% drops from the respective relevant fomor NMs, if the attestation you are after doesn't drop the first time you kill the fomor, it will be spawned again an additional two more times. 
 If the desired attestation still doesn't drop in any of the 3 spawns, you must kill the required number of Hydra NMs again for another 3 chances.

After you have completed the 9 kills and captured the screenshots of the 9 death messages, paste the death message screenshots here and we'll continue tomorrow.

**Comment by Dankykong** [comment]
![Vixxen Dynamis](https://user-images.githubusercontent.com/77759083/105262035-341f2d80-5b4d-11eb-8191-ca0087e343fe.png)
![2](https://user-images.githubusercontent.com/77759083/105262126-397c7800-5b4d-11eb-9746-7422853e962c.png)
![3](https://user-images.githubusercontent.com/77759083/105262190-3da89580-5b4d-11eb-8edf-1a6a929a2516.png)
![4](https://user-images.githubusercontent.com/77759083/105262233-400aef80-5b4d-11eb-83cf-5cd705bc302a.png)
![5](https://user-images.githubusercontent.com/77759083/105262278-4305e000-5b4d-11eb-80fd-77c2d3710769.png)
![6](https://user-images.githubusercontent.com/77759083/105262293-44370d00-5b4d-11eb-875b-c979492f9386.png)
![7](https://user-images.githubusercontent.com/77759083/105262294-4600d080-5b4d-11eb-868f-bd64ade6085a.png)
![8](https://user-images.githubusercontent.com/77759083/105262297-4731fd80-5b4d-11eb-89de-4eac63587f09.png)
![9](https://user-images.githubusercontent.com/77759083/105262300-48fbc100-5b4d-11eb-85f6-9c9cd7b6f14f.png)

**Comment by EpicTaru** [comment]
I'm waiting at the pop tower of the fomor NM, I'll spawn it when you are in the tower.

**Comment by Dankykong** [comment]
Mission successful. Got the item I needed on the 3rd spawn. The requirements for the force spawn were nice and easy!

**Comment by EpicTaru** [comment]
Excellent, glad to hear!  As said in game, when you are ready to start the fun in Dyna - Xarcabard, please open a new ticket about that.

Leaving this issue open for any other player that also encounters this.

**Comment by Oderson** [comment]
![image](https://user-images.githubusercontent.com/22406564/183704120-88f13053-d551-4577-ad38-bd1ba580118c.png)

**Comment by Oderson** [comment]
![image](https://user-images.githubusercontent.com/22406564/183704845-a620a7cf-58cf-462d-9da3-bf398fdbe2ee.png)

**Comment by EpicTaru** [comment]
@Oderson dyna nms are popped via retail methods. Consult the hp wiki dyna pages for more information.

**Comment by Oderson** [comment]
![image](https://user-images.githubusercontent.com/22406564/233818820-b1b9768e-806f-48fe-a158-141797ef2a3b.png)
![image](https://user-images.githubusercontent.com/22406564/233818848-c19ff90a-6706-4fa5-8c9e-ed43a4194715.png)
![image](https://user-images.githubusercontent.com/22406564/233818911-92a76fbb-11f3-4d35-b97b-953fe8af8cfe.png)
![image](https://user-images.githubusercontent.com/22406564/233818928-274e24f5-d803-4138-921d-44ffd9d81b31.png)
![image](https://user-images.githubusercontent.com/22406564/233818954-3c00feb7-3ba8-4021-aaff-699753406718.png)
![image](https://user-images.githubusercontent.com/22406564/233818963-b36307b5-9d36-4275-be70-9bf950d3a498.png)
![image](https://user-images.githubusercontent.com/22406564/233818973-56fe5996-2ff0-4dda-b528-ed4f1f8653ed.png)
![image](https://user-images.githubusercontent.com/22406564/233819005-7b2424a2-2e2b-4b9c-bca6-cb4d8b73cebf.png)
![image](https://user-images.githubusercontent.com/22406564/233819018-fa6052ad-12da-4f19-967e-de42d8d0323a.png)
![image](https://user-images.githubusercontent.com/22406564/233819042-54c06ed2-1dbd-4817-9438-9d927ae8676d.png)
![image](https://user-images.githubusercontent.com/22406564/233819072-0da5741e-8140-4f29-9d30-fdc8755eada7.png)
![image](https://user-images.githubusercontent.com/22406564/233819090-798bf1f9-7202-4679-ae4e-a430e2ab7997.png)
![image](https://user-images.githubusercontent.com/22406564/233819121-b0095380-aa28-4061-818b-cee2c6961d39.png)
![image](https://user-images.githubusercontent.com/22406564/233819133-c5bfc199-f55f-4dfc-83e3-cefc17519c6e.png)
![image](https://user-images.githubusercontent.com/22406564/233819142-5f447ea7-25a6-4ed9-bd79-e9514742ecd1.png)
![image](https://user-images.githubusercontent.com/22406564/233819168-c4321c69-5888-4898-8410-4320360d97ef.png)
![image](https://user-images.githubusercontent.com/22406564/233819187-43c68dbb-b772-4a16-a787-63d38c6a3e12.png)
![image](https://user-images.githubusercontent.com/22406564/233819213-c107968b-b868-4046-ae93-1b1a5ed5c83b.png)

**Comment by EpicTaru** [comment]
> @Oderson dyna nms are popped via retail methods. Consult the hp wiki dyna pages for more information.

http://wiki.homepointxi.com/Dynamis_-_Beaucedine#Hydra_Corps
