### ISSUE TITLE
Akbaba kill gave no exp or credit of kill for Field Manual page

### ISSUE THREAD

**Issue by Shoruto** [HomepointXI/Issues#496]
**Date & Time**: 
3/18/2021 1:27 pm eastern

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Sporky

**Discord Name (if different from in game):**
Shoruto

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
19 BLM/9 WHM

**NPC or Monster or item Name:**
Akbaba

**Zone name:** 
Tahrongi Canyon

**Coordinates (use `!where`):**
X: 205 Y: 7 Z: 70 (88)

**Item tool link (for items issues only):**
N/A

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
1. Pulled Akbaba with Fire
2. Attacked with Aero
3. Killed with Water

**Any additional information:**
After previous Akbaba kill I showed 7 of 8 killed for my Field Manual Page.  After this kill received no confirmation of kill, no exp and no confirmation of 8 of 8 with rewards.  After killing the next Akbaba I got credit for 8 of 8.  Killed another got experience and 1 of 8 but never got credit for the first of the 3 killed, no exp no field manual credit.  
![Sporky Akbaba Bug](https://user-images.githubusercontent.com/46944745/111670754-8ea3d580-87ee-11eb-95ce-6cdbac2763f7.png)

**Comment by EpicTaru** [comment]
What are the mobs /checking for you as, @Shoruto?

**Comment by Shoruto** [comment]
Easy Prey, now that I leveled a couple levels they are Too Weak.

**Comment by EpicTaru** [comment]
A mob needs to check as Easy Prey for them to count as credit for a page, if you are right on the cusp of them being Too Weak to Be Worthwhile you probably killed one that was TWTBW accidentally thinking it was Easy Prey.

**Comment by Shoruto** [comment]
Could be, probably the case, you can disregard the report :)
