### ISSUE TITLE
ToAH Easterly Winds

### ISSUE THREAD

**Issue by Warleaf** [HomepointXI/Issues#497]
**Date & Time**: 
3/19/2021 2:18 pm EST

**Client Version (use `/ver` in game):**
30191227_0

**Character Name:**
Warleaf

**Discord Name (if different from in game):**

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
99BLU/49DNC

**NPC or Monster or item Name:**
Easterly Winds mission

**Zone name:** 
Ru'lude Gardens

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Got CS for mission when entering palace but mission did not progress after.

**Any additional information:**

**Comment by EpicTaru** [comment]
Character still shows that they are assigned ToAU Mission Easterly Winds but value of the **AhtUrganStatus** variable is showing a 0, which, after looking at the code for that part of that mission, if the mission is Easterly Winds, would only be a 0 after viewing the CS.  The CS would also complete the Easterly Winds mission and then assign the Westerly Winds mission.

@Warleaf, I've changed your AhtUrganStatus variable back to a value of 1.  Please re-approach the palace at your next earliest convenience to see if you get the CS to trigger again.  After the CS, please check to see if your current ToAU mission shows as Westerly Winds.  Please comment here either way with your findings.

**Comment by Warleaf** [comment]
When I entered the palace I got the CS for the meeting and afterwards my mission was updated to Westerly Winds.

**Comment by EpicTaru** [comment]
Wootz! Closing this ticket.
