### ISSUE TITLE
Item disappeared in trade

### ISSUE THREAD

**Issue by Dankykong** [HomepointXI/Issues#498]
**Date & Time**: 
March 22 12:00PM

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Heytherelilguy & Omobolasire

**Discord Name (if different from in game):**
Sevvghetto

**Nation:**
Windurst & Sandy

**Job(level)/Sub Job(level):**
99cor/49rng & 99thf/49dnc

**NPC or Monster or item Name:**
Arasy Knife

**Zone name:** 
Zeruhn Mines

**Coordinates (use `!where`):**
X:-16 Y:0 Z:3 (99)

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/21554/arasy_knife

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**

**Any additional information:**
I traded my Blurred Sword from Heytherelilguy to Omobolasire and traded my Arasy Knife from Heytherelilguy to Omobolasire and the Arasy Knife. I still have the sword but the Arasy Knife disappeared completely.
![Vixxen_2021 03 22_115114](https://user-images.githubusercontent.com/77759083/112037403-514d8980-8b07-11eb-8f96-b37e58cd2a76.png)
![Omobolasire_2021 03 22_120743](https://user-images.githubusercontent.com/77759083/112037429-54e11080-8b07-11eb-8f5b-d3f8b201f3dc.png)

**Comment by EpicTaru** [comment]
Inventory searches of both charas using the **!hasitem** command produced negative results on both charas.

**Comment by EpicTaru** [comment]
@Dankykong Please check the delivery box of character Omobolasire for the item that was lost.
