### ISSUE TITLE
CoP 5-3 Louverance's Path

### ISSUE THREAD

**Issue by Thotless** [HomepointXI/Issues#499]
**Date & Time**: 
3/26/2021  9:10 AM MST

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Thotless

**Discord Name (if different from in game):**
Thoughtless

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
NIN99/WAR49

**NPC or Monster or item Name:**

**Zone name:** 
Oldton Movalpolos

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Thotless, Lunaless, Clairdeluna, Lunarie, Orange, Juice

**Steps to reproduce:**

**Any additional information:**
Did the previous cutscene in Bibiki Bay, then went to Oldton Movalpolos and only got the cutscene for zoning in on 2/3 characters.  Lunaless and Clairdeluna.  Did not get the cutscene on Thotless.

**Comment by EpicTaru** [comment]
@Thotless until I return from lunch, please, on the chara that didn't get the cs, go back to bibiki bay and see if the chara gets that cutscene again then see if it gets the cs in oldton.

**Comment by Thotless** [comment]
haha sure thing, was going to do that before requesting your help, but i was lazy XD

**Comment by EpicTaru** [comment]
No worries, just figured I'd suggest it so that you weren't sitting there twiddling your thumbs waiting for my return, lol

**Comment by Thotless** [comment]
hey it worked! thanks ET

**Comment by EpicTaru** [comment]
Always good to hear, closing this ticket.
