### ISSUE TITLE
Aby Misa NM Nehebkau works like normal mob

### ISSUE THREAD

**Issue by CaptSparklez** [HomepointXI/Issues#5]
**Date & Time**: 00:08 GMT+1

**Client Version (use `/ver` in game):** 20180203_1

**Character Name:** Hakubai

**Nation:** San D'Oria

**Job(level)/Sub Job(level):** PLD99/WAR49

**NPC or Monster or item Name:** Nehebkau

**Zone name:** Abyssea - Misareaux 

**Coordinates (use `!where`):** X:326 Y:22 Z:-348 (65)

**Item tool link (for items issues only):** N/A

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** NM Nehebkau (Conflux #7) walks around freely in vicinity to the ??? it's supposed to be popped from (spawned by trading Hardened Raptor Skin). After kill, it repops as if you killed one of the normal roaming raptors.  

**Any additional information:** Drops are the same as when spawned by trading the item. It is also still possible to pop it with that method.

**Comment by Heepster03** [comment]
Fixed with reboot.
