### ISSUE TITLE
Hyuuga online but not online

### ISSUE THREAD

**Issue by o0Persefone0o** [HomepointXI/Issues#50]
**Date & Time**:  8 May 2018

**Client Version (use `/ver` in game):** 30180306_2

**Character Name:** Hyuuga

**Discord Name (if different from in game):** Persefone

**Nation:** Bastok

**Job(level)/Sub Job(level):** WHM99/RDM49

**NPC or Monster or item Name:** -----

**Zone name:** Promyvion-Holla

**Coordinates (use `!where`):** entrance

**Item tool link (for items issues only):** -----

**Multi-boxing? (multiple clients on same connection):** yes

**Steps to reproduce:** I was doing Promyvion-Holla with 2 chars (Hyuuga and Atropos) and reaching the last floor they get stucked (black screen but chat log still up) after killing the last memory receptacle, i type !tele holla with Hyuuga and run back to promyvion-holla, i touch the cermet gate and procedd onward, then i get a "dowloading black screen" and that was where she get stucked.
i close both chars like 2hrs ago, i relog Atropos (she didnt tele-holla and re-enter) and she is fine she was on 3th promy floor but Hyuuga is still online and cant log her back. 

**Any additional information:**

**Comment by Heepster03** [comment]
I need to be sure that you're not at the character selection screen currently.

**Comment by o0Persefone0o** [comment]
i have no char online or FFXI even open in this moment

**Comment by Heepster03** [comment]
Okay, you should be able to log in now.

**Comment by o0Persefone0o** [comment]
yas i can log now, thank you Heep, thank you ET.

**Comment by Heepster03** [comment]
No problem, enjoy~
