### ISSUE TITLE
My items are disappearing

### ISSUE THREAD

**Issue by Dankykong** [HomepointXI/Issues#501]
**Date & Time**: 
March 27 2021 12:30PM

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Vixxen

**Discord Name (if different from in game):**
Sevvghetto

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
99THF/49DNC

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**

**Any additional information:**
I was looking through my MH and every piece of gear from Wardrobe 3 has disappeared. It was nearly full yesterday
![Vixxen_2021 03 27_124745](https://user-images.githubusercontent.com/77759083/112731061-b08e0e00-8efa-11eb-91dd-1fd8c6b549be.png)

**Comment by EpicTaru** [comment]
@Dankykong Are you still experiencing this issue?

**Comment by EpicTaru** [comment]
@Dankykong Are you still experiencing this issue? This issue will be closed in a week if a response to this ticket isn't received.

**Comment by EpicTaru** [comment]
Closing ticket.  Please open a new ticket if this issue still exists.
