### ISSUE TITLE
Switchstix not giving proper response for starting relic weapon

### ISSUE THREAD

**Issue by tuing** [HomepointXI/Issues#503]
Date & Time:
04/09/2021 @ 21:15 PM

Client Version (use /ver in game):
30191204_1

Character Name:
Meyrink

Discord Name (if different from in game):
Meyrink

Nation:
Sandoria

Job(level)/Sub Job(level):
99 NIN/49 DNC

NPC or Monster or item Name:
Switchstix

Zone name:
Castle Zvahl Baileys

Coordinates (use !where):
X:387 Y:-12 Z: -19 (168)

Item tool link (for items issues only):
Ihintanto

Multi-boxing? (multiple clients on same connection):
No

Steps to reproduce:
Trying to start the very first step for relic katana and the npc not mentioning the item even though its in inventory, instead just saying whats on the screenshot.
![Meyrink_2021 04 09_211956](https://user-images.githubusercontent.com/26522986/114194173-6afd2680-9979-11eb-83db-b5288baff118.png)

**Comment by EpicTaru** [comment]
Issue will be resolved in upcoming maintenance, @tuing.

In the meantime, cleared the value of the character's **RELIC_CONQUEST_WAIT** variable.

Character should be able to start another relic, @tuing.  Please comment here with your results of them attempting to.

**Comment by tuing** [comment]
![Meyrink_2021 04 09_213223](https://user-images.githubusercontent.com/26522986/114196061-37230080-997b-11eb-8b26-ba6e538b36a7.png)

**Comment by EpicTaru** [comment]
Leaving this issue open for anyone else that encounter this issue.

**Comment by EpicTaru** [comment]
Should have been resolved in maintenance before most recent one, please open another ticket if this issue is still encountered.
