### ISSUE TITLE
Items missing after trade.

### ISSUE THREAD

**Issue by Albian-HomepointXI** [HomepointXI/Issues#505]
**Date & Time**: 
15/Apr/2021 at 5:30-9:30am EST

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Albian
Nyaan

**Discord Name (if different from in game):**

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
PLD99/DNC49
THF99/DNC49

**NPC or Monster or item Name:**

**Zone name:** 
Behemoth's Domain

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**
I traded 8ish stacks of Mythril Ingots from Albian to Nyaan while in Behemoth's Domain and now they're missing.

**Any additional information:**
Upon referring to the log on my alt the time window was corrected.

**Comment by EpicTaru** [comment]
@Albian-HomepointXI Please check your delivery box on character Albian for the 7 stacks of ingots that were lost.
