### ISSUE TITLE
Account Recovery

### ISSUE THREAD

**Issue by KaizerZitro** [HomepointXI/Issues#509]
**Date & Time**: 
4/18/2021

**Client Version (use `/ver` in game):**
I think its the 30191204_1

**Character Name:**
Don't remember char name, but I usually use either Kaizer or Zitro

**Discord Name (if different from in game):**

Zitro

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
My account is kaizer0645, but I dont remember the pass so I can access my account, I used to play a few years back, and I would like to recover my previous chars, thanks!

**Comment by Heepster03** [comment]
If you're still interested, you can reach me at: Halkuras#1965 on Discord.
