### ISSUE TITLE
Kingdom Signit Staff

### ISSUE THREAD

**Issue by Willthefluteboy** [HomepointXI/Issues#51]
Date & Time: May 8th, 2018

Client Version (use /ver in game): 30180203_1

Character Name: Reon

Discord Name (if different from in game): Will/Reon

Nation: Sandy

Job(level)/Sub Job(level): THF 99/DNC 49

NPC or Monster or item Name: Kingdom Signet Staff

Zone name: Abysse-Vunkerl

Coordinates (use !where): X:-184 Y:-39 Z:-249 (131)

Item tool link (for items issues only): http://homepointxi.com/db/items/17583/kgd._signet_staff

Multi-boxing? (multiple clients on same connection): Yes

Steps to reproduce: Equip staff. Wait for cool-down and try and use it.

Any additional information: Character is Rank 10 in Sandy.

**Comment by nfaletra** [comment]
Signet staffs do not work in non-conquest regions. This includes Abyssea zones.
