### ISSUE TITLE
Maighdean Uaine invisible

### ISSUE THREAD

**Issue by Shoruto** [HomepointXI/Issues#512]
**Date & Time**: 
4/22/2021 @ 9:00 am eastern

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Sporky

**Discord Name (if different from in game):**
Shoruto

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
17 SAM/ 8 WAR

**NPC or Monster or item Name:**
Maighdean Uaine (NM)

**Zone name:** 
North Gustaberg

**Coordinates (use `!where`):**
X:339 Y:-23 Z:978 (121)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Spawned this NM after killing multiple Walking Saplings.  Went to fight and got killed, Raised and aggroed it, ran to Pal Mines zone.  Came out it was gone, leveled up to 17 and went to find it.  Found it on Widescan, set target and went to target but no NM, I searched the entire zone and it wasn't there.

**Any additional information:**
![Sapling NM Opital Earring](https://user-images.githubusercontent.com/46944745/115719507-26469780-a34a-11eb-971d-533c580dba6f.png)

**Comment by EpicTaru** [comment]
Probably burrowed underground after you zoned. I'll check when I'm online in a few minutes, @Shoruto

**Comment by Shoruto** [comment]
No rush :)

**Comment by EpicTaru** [comment]
Yeap, it burrowed underground to lick its wounds, I'll pull it back to its spawn point for you.
![image](https://user-images.githubusercontent.com/26195580/115725569-956ebc80-a347-11eb-8dac-7866eeb3acd3.png)

**Comment by EpicTaru** [comment]
Use **!mobhere** to pull mob (Mob ID **17211702**) back to spawn point (272, -0.324, 797.8).
