### ISSUE TITLE
Cid Final talk Promathia Mission 3-3 The Road Forks problem

### ISSUE THREAD

**Issue by Vorpall** [HomepointXI/Issues#513]
**Date & Time**: 
3:50 PM

**Client Version (use `/ver` in game):**

30191204_1

**Character Name:**
Vorpal

**Discord Name (if different from in game):**

Vorpal

**Nation:**

San d'Oria

**Job(level)/Sub Job(level):**

Blu/rdm

**NPC or Monster or item Name:**

Cid

**Zone name:** 

metalworks

**Coordinates (use `!where`):**

X:- 15 Y:- 10 Z:-1 (172)

**Item tool link (for items issues only):**

n/a

**Multi-boxing? (multiple clients on same connection):**

No

**Steps to reproduce:**

doing Promathia Mission 3-3 and the final step try to talk to cid to complete the mission but i get nothing 

**Any additional information:**

**Comment by EpicTaru** [comment]
@Vorpall Please let me know, either on this ticket or in game, when you are online so this issue can be researched further.

**Comment by Vorpall** [comment]
i am online

**Comment by EpicTaru** [comment]
@Vorpall, the value of variable **EMERALD_WATERS_Status** shows **6**, it needs to be **7** in order for the CS with Cid to trigger.  That variable is updated to the value of **7** after the CS with Hinaree in Southern Sandy.  Please visit her again and see if she gives you the CS again then try and talk to Cid again and see if he gives you the CS.  Please report back your findings on this ticket.

**Comment by Vorpall** [comment]
its work problem solved  thank you so much sir

**Comment by EpicTaru** [comment]
Glad to hear it's resolved.  Closing this ticket.
