### ISSUE TITLE
Mamool Ja Sophist Inaccurate Drops

### ISSUE THREAD

**Issue by Shoruto** [HomepointXI/Issues#516]
**Date & Time**: 
4/26/2021 @ 9:17am

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Sporky and was with Team Albian

**Discord Name (if different from in game):**
Shoruto

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
99 WHM / 49 SMN

**NPC or Monster or item Name:**
Mamool Ja Sophist

**Zone name:** 
Wajaom Woodlands

**Coordinates (use `!where`):**
X-694 Y: -7 Z: -129 (233)

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/10637/tenryu_sune-ate_+1
http://homepointxi.com/db/items/10572/khepri_kecks
homepointxi.com/db/items/19174/borealis
http://homepointxi.com/db/items/10493/iaso_bliaut
http://homepointxi.com/db/items/28327/gorney_sollerets
http://homepointxi.com/db/items/10539/huginn_gauntlets
http://homepointxi.com/db/items/10408/spurrina_coif
http://homepointxi.com/db/items/21242/bocluamni

**Multi-boxing? (multiple clients on same connection):**
I was not

**Steps to reproduce:**
Me and Team Albian gathered at the ??? to fight the ZNM Vulpangue.  We killed the surrounding mobs to build TP which included the above Mamool.  These drops came off of 2 of them we killed, not the same group off each one, it varied by 2 items on the second one.  I listed all the drops from both kills.

**Any additional information:**
The ZNM worked as intended so I thank you for that and all the other awesome fixes you and your team accomplished.  Keep up the GREAT work!

**Comment by EpicTaru** [comment]
Resolved in last update.
