### ISSUE TITLE
ZNM Vulpangue didn't drop Trophy after Kill

### ISSUE THREAD

**Issue by Shoruto** [HomepointXI/Issues#517]
**Date & Time**: 
4/26/2021

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Sporky

**Discord Name (if different from in game):**
Shoruto

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
99 WHM / 49 SMN

**NPC or Monster or item Name:**
http://wiki.homepointxi.com/Vulpangue
Tier I ZNM

**Zone name:** 
Wajaom Woodlands

**Coordinates (use `!where`):**
X-694 Y: -7 Z: -129 (233)

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/2616/vulpangues_wing

**Multi-boxing? (multiple clients on same connection):**
None

**Steps to reproduce:**
Purchased Zeni
Received Hellcage Butterfly Pop Item
Popped ZNM and Killed
No Trophy Item in drop list and none in Inventory

**Any additional information:**

**Comment by EpicTaru** [comment]
Resolved in last update.
