### ISSUE TITLE
Bune Inaccurate Drops

### ISSUE THREAD

**Issue by Albian-HomepointXI** [HomepointXI/Issues#518]
**Date & Time**: 
626/Apr/2021 6:58:12

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Nyaan

**Discord Name (if different from in game):**

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
THF99/DNC49

**NPC or Monster or item Name:**
Bune

**Zone name:** 
Gustav Tunnel

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**
Kill Bune

**Any additional information:**

**Comment by Albian-HomepointXI** [comment]
![Nyaan_2021 04 26_065903](https://user-images.githubusercontent.com/74258270/116099546-13013800-a67a-11eb-9a27-601bc0a1ad48.png)

**Comment by EpicTaru** [comment]
Resolved in last update.
