### ISSUE TITLE
Abyssea loot pools

### ISSUE THREAD

**Issue by Dankykong** [HomepointXI/Issues#519]
**Date & Time**: 
April 26 9:30AM

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Vixxen

**Discord Name (if different from in game):**
Sevvghetto

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
THF99/DNC49

**NPC or Monster or item Name:**
Gruesome Gargouille and others

**Zone name:** 
Abyssea-Vunkerl

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**

**Any additional information:**
monsters here don't have the right loot pools. I'll post more when I find them

**Comment by Heepster03** [comment]
Abyssea drops are fixed and will be uploaded to the server when I get to finish the other custom files.

**Comment by Heepster03** [comment]
Will be fixed in next update.

**Comment by EpicTaru** [comment]
Resolved in last update.
