### ISSUE TITLE
Bukhis Animations are FUBAR.

### ISSUE THREAD

**Issue by Heepster03** [HomepointXI/Issues#52]
**Date & Time**: N/A

**Client Version (use `/ver` in game):** N/A

**Character Name:** [GM] Halkuras

**Discord Name (if different from in game):** N/A

**Nation:** N/A

**Job(level)/Sub Job(level):** N/A

**NPC or Monster or item Name:** Bukhis

**Zone name:** Abyssea-Vunkerl

**Coordinates (use `!where`):** N/A

**Item tool link (for items issues only):** N/A

**Multi-boxing? (multiple clients on same connection):** N/A

**Steps to reproduce:** N/A

**Any additional information:**
Animations for TP moves are all jacked.

**Comment by nfaletra** [comment]
Easiest way to fix this is cap the animation packets on retail. I'm compiling a list of mobs to check.

**Comment by nfaletra** [comment]
Capped Bukhis animations on retail and fixed them in the DB. 
Fixed apocalyptic ray incorrectly saying "Player is KO'd."
No more baby Bukhis. He's a big boy again.

**Comment by Jessland86** [comment]
Fixed in today's maintenance.
