### ISSUE TITLE
Wrong loot from Goblin Gamblers in Valkurm Dunes

### ISSUE THREAD

**Issue by KaizerZitro** [HomepointXI/Issues#520]
**Date & Time**: 
26/4/2021
19:20

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Kaizer
Yueri
Manaward

**Discord Name (if different from in game):**
KaizerZitro

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
PLD99/WAR49
THF25
RDM 24

**NPC or Monster or item Name:**
Goblin Gambler

**Zone name:** 
Valkurm Dunes

**Coordinates (use `!where`):**
X:-449 Y: -15 Z:279 (76)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes, Yueri and Manaward are my alts

**Steps to reproduce:**
Goblin Gamblers consistently dropped Aoidos, Tantra, Raider and Caller seals: body, ranging from 1 to 4 of each in Valkurm Dunes

**Any additional information:**

**Comment by Heepster03** [comment]
Will be fixed in next update.

**Comment by EpicTaru** [comment]
Resolved in last update.
