### ISSUE TITLE
Windurst Mission 2-1 Problem (Nanaa not giving correct dialogue)

### ISSUE THREAD

**Issue by BasslineTRT** [HomepointXI/Issues#521]
**Date & Time**: 
Saturday, May 1st, 2021 10:51 PM

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Meashon

**Discord Name (if different from in game):**
TenoTheTiger

**Nation:**
USA

**Job(level)/Sub Job(level):**
THF (Lvl 50)/ WHM (Lvl 25)

**NPC or Monster or item Name:**
NaNaa Mihgo

**Zone name:** 
Windurst

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**

**Any additional information:** 
Windurst Mission 2-1 Lost for Words
NaNaa Mihgo is not giving me the correct dialogue for the mission. While going through "Lost for Words" NaNaa Mihgo  is giving dialogue for another mission. so basically Dialogue is being given for two or three different missions at the same time. THF AF1 Tenshodo Showdown has now started. NaNaa Mihgo is not giving me the Lapis Monocle.

**Comment by EpicTaru** [comment]
@BasslineTRT Please respond here with when you will be online tomorrow/this week so that I can look at your variables and see what may be causing your issue.

**Comment by BasslineTRT** [comment]
Tomorrow around Noon but I'll be on for a good 3 or 4 hours.

**Comment by EpicTaru** [comment]
Verified that character was on the correct mission using **!checkmission 2**.

Character's **MissionStatus** variable reported a value of **5** (most likely from the code of a previous mission not clearing the value correctly) where it needed to report a value greater than 1 but less than 5 in order for the correct CS/dialogue with Nanaa Mihgo to trigger.

I reset the character's MissionStatus variable to a value of 0 and had the character interact with NPC Tosuka-Porika in the Optistery at Windurst Waters, which is the NPC that would correctly increment the value of that variable in order for the CS with Nanaa to trigger.

Checked that the value of the variable incremented to **1** correctly after the interaction with Tosuka-Porika.  Had player then interact with Nanaa again.  The correct CS triggered with Nanaa, after which the variable incremented correctly to the expected value of **2**.  I also verified that the player had also obtained the Key Item **LAPIS_MONOCLE** using **!haskeyitem 88**.

@BasslineTRT, please comment here if the remainder of the mission works correctly without issues.  Please also comment here if you encounter any other issues with the remainder of the mission.  Keeping this ticket open until the response from you is received here.

**Comment by BasslineTRT** [comment]
Got the Cut Scene for the Mahogany Door in the Inner Horutoto Ruins. Although Cut Scene for House of Hero will not trigger.

**Comment by EpicTaru** [comment]
@BasslineTRT Looks like the MissionStatus variable didn't update correctly when you clicked on the Mahogany Door, try clicking it again.  Let me know in game once you have and I can verify if it did update correctly or not.

**Comment by BasslineTRT** [comment]
Started the Cut Scene now

**Comment by EpicTaru** [comment]
Character's **MissionStatus** variable refused to update to needed value of **5**, even after player interacted with (and watched the CS) multiple times.  Manually set the value of the **MissionStatus** variable to the needed value of **5** using **!setplayervar MissionStatus 5**.

@BasslineTRT Please proceed on with the next step in the mission and report back here on this ticket with your findings.

**Comment by EpicTaru** [comment]
Player reported that remainder of mission progressed without any more issues and was able to complete mission.  Closing this ticket now.

**Comment by BasslineTRT** [comment]
CS at Mahogany Door progressed as needed. Went to House of Hero. CS at House of Hero progressed without any problems. All problems have been resolved.
