### ISSUE TITLE
Custom Absolute Virtue and pop items

### ISSUE THREAD

**Issue by drezack** [HomepointXI/Issues#525]
Jailer of justice did not drop a fourth virtue. In addition, none of the custom AV drops (the SOA rings like Gorney Ring) are shown in the item lookup tool as dropping from a monster. It seems likely that the custom AV that the server previously had is not working.

**Date & Time**: 
5/12/2021

**Client Version (use `/ver` in game):**

**Character Name:**
Dace

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**
Jailer of Justice

**Zone name:** 
Al'Taieu

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
Attempt to pop AV, can you get pop items? Is AV boosted and behaves as he used to? Does he drop SOA rings?

**Any additional information:**

**Comment by Heepster03** [comment]
I've already gotten to this in the custom sql. It is fixed but not pushed yet until all of the file is completed which is a work in progress. Hopefully not much longer.

**Comment by EpicTaru** [comment]
Resolved in last update.
