### ISSUE TITLE
Account Recovery

### ISSUE THREAD

**Issue by Roamin64** [HomepointXI/Issues#526]
**Date & Time**: May 15 2021

**Client Version (use `/ver` in game):** 30191204_1

**Character Name:**Thievan

**Discord Name (if different from in game):**Roamin

**Nation:**Windurst

**Job(level)/Sub Job(level):**99 Thf/49BRD

**NPC or Monster or item Name:**N/A

**Zone name:** N/A

**Coordinates (use `!where`):**N/A

**Item tool link (for items issues only):**N/A

**Multi-boxing? (multiple clients on same connection):**N/A

**Steps to reproduce:**N/A

**Any additional information:**I haven't logged in this character since the Legiondark days.  I cannot remember the account name at all.

**Comment by Heepster03** [comment]
If you're still interested, you can reach me at: Halkuras#1965 on Discord.
