### ISSUE TITLE
Account Recovery

### ISSUE THREAD

**Issue by MVM1787** [HomepointXI/Issues#528]
**Date & Time**: 5/18/2021 8:02 PM

**Client Version (use `/ver` in game):** 30191204_1

**Character Name:** Mirra

**Discord Name (if different from in game):** Ligerzero #4172

**Nation:** Bastok

**Job(level)/Sub Job(level):** 99RDM/49WHM

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

**Comment by Heepster03** [comment]
If you're still interested, you can reach me at: Halkuras#1965 on Discord.
