### ISSUE TITLE
Graphics Glitch With Puppets on Puppetmaster Job Class

### ISSUE THREAD

**Issue by MVM1787** [HomepointXI/Issues#529]
**Date & Time**: 5/21/2021 4:42 PM PST

**Client Version (use `/ver` in game):**30191204_1

**Character Name:**Ligerzero, Hyoga, Pseiya, Shun, Dshiryu, Ikki 

**Discord Name (if different from in game):**Ligerzero #4172

**Nation:** Sandy

**Job(level)/Sub Job(level):** Hyoga, Pseiya, Dshiryu, Shun, Ikki PUP:68/MNK:34 Ligerzero: PUP:99/DNC:49

**NPC or Monster or item Name:**None

**Zone name:** Crawlers Nest and others ETC

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**Yes and No

**Steps to reproduce:**Can be reproduced by going to crawlers nest or other places with Range Puppet or other Frames Activated and summoned, moving around they will seem fine till after a few battles then they start going wacky in graphics, look like there floating at some points, or parts of them are being turn flat into the ground while attacking, they tend to get cought up for no reason making it so they have to run to enemys to attack , instead of staying in range position to attack.

**Any additional information:**
![Screenshot (83)](https://user-images.githubusercontent.com/12943935/119207775-46a26880-ba54-11eb-8005-3b913133cb87.png)
![Hyoga_2021 05 21_162647](https://user-images.githubusercontent.com/12943935/119207796-57eb7500-ba54-11eb-9cf5-c9ec98df3792.png)
![Hyoga_2021 05 21_162742](https://user-images.githubusercontent.com/12943935/119207805-5c179280-ba54-11eb-86da-a353797dd648.png)
![Hyoga_2021 05 21_162747](https://user-images.githubusercontent.com/12943935/119207809-60dc4680-ba54-11eb-90d1-3ce0d74e574c.png)

**Comment by EpicTaru** [comment]
Common issue even on current day private servers based on the lasted codebase.  Current workaround is to dismiss and re-summon the automaton.

**Comment by Heepster03** [comment]
moved top #558
