### ISSUE TITLE
Boulder Worms in Gustav Tunnels don't give EXP if item level animator is equipped when automaton is summoned

### ISSUE THREAD

**Issue by MVM1787** [HomepointXI/Issues#530]
**Date & Time**: 5/22/2021 11:16 PM

**Client Version (use `/ver` in game):**30191204_1

**Character Name:**Ligerzero, Hyoga, Ikki, Shun, Pseiya, Dshiryu

**Discord Name (if different from in game):**Ligerzero #4172

**Nation:**Sandy

**Job(level)/Sub Job(level):**Ligerzero: 99PUP/49DNC,  Shun:92PUP/46MNK, Dshiryu:92PUP/46MNK, Pseiya:91PUP/45MNK,
Ikki:92PUP/46MNK, Hyoga:92PUP:46MNK

**NPC or Monster or item Name:**Boulder Eater and Pygmytoise

**Zone name:** Gustav Tunnels

**Coordinates (use `!where`):**X:18 Y:-2 Z:143 (236)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**yes

**Steps to reproduce:**out of no where the game forced closed on Pseiya, and then after that all monsters at least for the Boulder Eater stopped giving exp to Ligerzero and the rest of the party
![Ligerzero_2021 05 22_231341](https://user-images.githubusercontent.com/12943935/119250383-9ec09400-bb54-11eb-8028-5e2360eeb6ab.png)

**Any additional information:**
![Ligerzero_2021 05 22_232517](https://user-images.githubusercontent.com/12943935/119250447-fd860d80-bb54-11eb-804e-c46fc80c6d93.png)

**Comment by EpicTaru** [comment]
@MVM1787, is the issue still occurring? Did you try logging all characters out then back in and reforming the party?

**Comment by MVM1787** [comment]
The issue still occurred when logging out and logging back in, even tried zoning and it was still happening

**Comment by EpicTaru** [comment]
You broke the party and reformed and it still occurred after that?

**Comment by MVM1787** [comment]
Broke the party and tried on just Ligerzero himself, and it still was happening

**Comment by EpicTaru** [comment]
Tried that with just Liger or also on any other character by themselves?

**Comment by MVM1787** [comment]
> Tried that with just Liger or also on any other character by themselves?

With just liger himself, want me to try with the others as well.

**Comment by EpicTaru** [comment]
Yes please.  Try with each of them by themselves

**Comment by MVM1787** [comment]
> Yes please.  Try with each of them by themselves

Lol they can't solo the worms or turtles yet.

**Comment by EpicTaru** [comment]
Try with the mobs in zeruhn mines, they should still give some exp to players in the 90s

**Comment by MVM1787** [comment]
> Try with the mobs in zeruhn mines, they should still give some exp to players in the 90s

Confirmed, Shun, Hyoga, Ikki, Dshiryu, and Pseiya all got exp from the bats in the Zeruhn Mines.

**Comment by EpicTaru** [comment]
This is with them all in a party or solo? If they were all in a party, was Liger also in same party?

**Comment by MVM1787** [comment]
> This is with them all in a party or solo? If they were all in a party, was Liger also in same party?

Solo, I'll try with party next with liger, just need to log him back in and walk him to survival guide in the tunnels.

**Comment by EpicTaru** [comment]
ok, thanks for trying all this to isolate possible causes.

**Comment by MVM1787** [comment]
> ok, thanks for trying all this to isolate possible causes.

So with and without level sync no one in party gets exp from the bats in the mines.

**Comment by EpicTaru** [comment]
> > This is with them all in a party or solo? If they were all in a party, was Liger also in same party?
> 
> Solo, I'll try with party next with liger, just need to log him back in and walk him to survival guide in the tunnels.

You just said that they were getting exp, but without Liger in the party, correct?

**Comment by MVM1787** [comment]
> > > This is with them all in a party or solo? If they were all in a party, was Liger also in same party?
> 
> > 
> 
> > Solo, I'll try with party next with liger, just need to log him back in and walk him to survival guide in the tunnels.
> 
> 
> 
> You just said that they were getting exp, but without Liger in the party, correct?

Yes while they where soloing, I'll kick liger out to see what happens then.

**Comment by EpicTaru** [comment]
Please also clarify which instances you were using level sync and who the party was syncing to/the level of the person they were syncing to

**Comment by MVM1787** [comment]
> Please also clarify which instances you were using level sync and who the party was syncing to/the level of the person they were syncing to

Confirmed party gets exp off bats in Zeruhn Mines while synced with Pseiya, everyone Shun, Ikki, Dshiryu, Pseiya, and Hyoga all got exp.

**Comment by MVM1787** [comment]
> > Please also clarify which instances you were using level sync and who the party was syncing to/the level of the person they were syncing to
> 
> Confirmed party gets exp off bats in Zeruhn Mines while synced with Pseiya, everyone Shun, Ikki, Dshiryu, Pseiya, and Hyoga all got exp.

Level was 91PUP/35MNK which is Pseiya

**Comment by EpicTaru** [comment]
And with Liger added in, but also still having Pseiya as the sync target?

**Comment by MVM1787** [comment]
> And with Liger added in, but also still having Pseiya as the sync target?

Doesn't give exp, just found out that ligerzero solo he gets limit points, but not while in party.

**Comment by MVM1787** [comment]
> > And with Liger added in, but also still having Pseiya as the sync target?
> 
> Doesn't give exp, just found out that ligerzero solo he gets limit points, but not while in party.

And now he's getting exp/limit points from the bats in Zeruhn Mines while being synced to Pseiya and partying with the others.

**Comment by MVM1787** [comment]
> > > And with Liger added in, but also still having Pseiya as the sync target?
> > 
> > Doesn't give exp, just found out that ligerzero solo he gets limit points, but not while in party.
> 
> And now he's getting exp/limit points from the bats in Zeruhn Mines while being synced to Pseiya and partying with the others.

Only thing different with party is Shun is party leader and not Liger

**Comment by EpicTaru** [comment]
> > > > And with Liger added in, but also still having Pseiya as the sync target?
> > > 
> > > 
> > > Doesn't give exp, just found out that ligerzero solo he gets limit points, but not while in party.
> > 
> > 
> > And now he's getting exp/limit points from the bats in Zeruhn Mines while being synced to Pseiya and partying with the others.
> 
> Only thing different with party is Shun is party leader and not Liger

But even when Liger was the leader and the party was syncing to the level of Pseiya, Liger's level would also sync down?

**Comment by MVM1787** [comment]
> > > > > And with Liger added in, but also still having Pseiya as the sync target?
> 
> > > > 
> 
> > > > 
> 
> > > > Doesn't give exp, just found out that ligerzero solo he gets limit points, but not while in party.
> 
> > > 
> 
> > > 
> 
> > > And now he's getting exp/limit points from the bats in Zeruhn Mines while being synced to Pseiya and partying with the others.
> 
> > 
> 
> > Only thing different with party is Shun is party leader and not Liger
> 
> 
> 
> But even when Liger was the leader and the party was syncing to the level of Pseiya, Liger's level would also sync down?

Yes it would, went back to Gustav Tunnels with shun as party leader, sadly no go, no one got exp/limit points. That was without level sync.

**Comment by EpicTaru** [comment]
This is with automatons for all characters also activated, correct? If so, attempt without any automatons activated.

**Comment by MVM1787** [comment]
> This is with automatons for all characters also activated, correct? If so, attempt without any automatons activated.

Lol I can try without, but mine is a whm that keeps us alive, but just confirmed that while leveled synced to Pseiya in Gustav Tunnels we still didn't get exp.

**Comment by MVM1787** [comment]
> > This is with automatons for all characters also activated, correct? If so, attempt without any automatons activated.
> 
> Lol I can try without, but mine is a whm that keeps us alive, but just confirmed that while leveled synced to Pseiya in Gustav Tunnels we still didn't get exp.

Confirmed we got exp/limit points without the presence of automations.

**Comment by EpicTaru** [comment]
Re-add automatons in, one by one, until you notice the absence of exp/limit points.

**Comment by MVM1787** [comment]
> > > This is with automatons for all characters also activated, correct? If so, attempt without any automatons activated.
> > 
> > Lol I can try without, but mine is a whm that keeps us alive, but just confirmed that while leveled synced to Pseiya in Gustav Tunnels we still didn't get exp.
> 
> Confirmed we got exp/limit points without the presence of automations.

Confirmed root cause of this mess is the Animator P II Ilvl 119 animator for 99 PUP, when I deactivated the puppet and reactivated him with the gimped stats from it, for sure it made the issue happen so that no one gets exp, if I remove the animator and resummon the puppet then exp/limit points work again.

**Comment by EpicTaru** [comment]
Try activating the automaton with a non-item level animator and after it's activated, switch then to the item level animator.

**Comment by MVM1787** [comment]
> Try activating the automaton with a non-item level animator and after it's activated, switch then to the item level animator.

With the automation already out I swapped my turbo animator with the ilvl 119 animator Animator P II and confirmed that we still get exp/limit points, the cause only happens if you deactivate and reactivate the Automation with the ilvl 119 animator p II equipped. So overall I'm just gonna stick to my turbo animator lol.

**Comment by EpicTaru** [comment]
> > Try activating the automaton with a non-item level animator and after it's activated, switch then to the item level animator.
> 
> With the automation already out I swapped my turbo animator with the ilvl 119 animator Animator P II and confirmed that we still get exp/limit points, the cause only happens if you deactivate and reactivate the Automation with the ilvl 119 animator p II equipped. So overall I'm just gonna stick to my turbo animator lol.

This is a similar situation that is present with the item level sancus sachet for SMN where the avatar isn't given item level stats if the sancus sachet is currentlyequipped at the time of summoning.  If the avatar is summoned without the sancus sachet eqiupped but you then switch to the sachet after the avatar is summoned, their item level stats are re-calculated.

So if you activate your automaton with the Turbo Animator and then switch to the Animator P II after the automaton is already activated/summoned, you do not notice the exp/limit point issue, correct?

**Comment by MVM1787** [comment]
> > > Try activating the automaton with a non-item level animator and after it's activated, switch then to the item level animator.
> 
> > 
> 
> > With the automation already out I swapped my turbo animator with the ilvl 119 animator Animator P II and confirmed that we still get exp/limit points, the cause only happens if you deactivate and reactivate the Automation with the ilvl 119 animator p II equipped. So overall I'm just gonna stick to my turbo animator lol.
> 
> 
> 
> This is a similar situation that is present with the item level sancus sachet for SMN where the avatar isn't given item level stats if the sancus sachet is currentlyequipped at the time of summoning.  If the avatar is summoned without the sancus sachet eqiupped but you then switch to the sachet after the avatar is summoned, their item level stats are re-calculated.
> 
> 
> 
> So if you activate your automaton with the Turbo Animator and then switch to the Animator P II after the automaton is already activated/summoned, you do not notice the exp/limit point issue, correct?

Correct the issue doesn't occur when you do that method, it happens if you activate the automation with the ilvl 119 animator equipped.

**Comment by EpicTaru** [comment]
That is a DSP issue then, not one specific to this server.  I am not aware that the issue has been resolved for this and/or with the smn item, so please utilize the stated workaround for the time being.

**Comment by Heepster03** [comment]
moved to #558
