### ISSUE TITLE
Missing key Item

### ISSUE THREAD

**Issue by nxnslite** [HomepointXI/Issues#531]
**Date & Time**: 
04-06-21 : 6:40 pm

**Client Version (use `/ver` in game):**
locked version..

**Character Name:**
nxnpow, nxncure, nxnmage, altanaspouce, khrisitna

**Discord Name (if different from in game):**
NxN_Slite

**Nation:**
Windy

**Job(level)/Sub Job(level):**
99 blu whm thf

**NPC or Monster or item Name:**
Mysterious Amulet

**Zone name:** 
Taz

**Coordinates (use `!where`):**
K7 walnut door

**Item tool link (for items issues only):**
Quest : An Eternal Melody
Key-Item: Mysterious Amulet

**Multi-boxing? (multiple clients on same connection):**
Yes.

**Steps to reproduce:**

**Any additional information:**
Server Crashed durring CS. I didnt get keyitem.. and cant get CS at Dilapidated Gate
Thank you.

**Comment by nxnslite** [comment]
filled

**Comment by nxnslite** [comment]
they are online @EpicTaru

**Comment by EpicTaru** [comment]
Variables of all affected characters report that they should receive the CS at the Dilapidated Gate at (I-11) in Misareaux Coast.  Please ensure that they check the correct gate as there are more than one in that zone.  Please double-check this and report back if they receive the CS at the Gate or not.

**Comment by nxnslite** [comment]
im sorry to have wasted you time... :( its working like a charm.... u may remove some merits point if you like...
or ill over double taru to altana on next festival.
Thanks again and sorry for wasting your time. 👍

**Comment by EpicTaru** [comment]
No apologies necessary or accepted, lol, just glad it was that and not something more complex.
