### ISSUE TITLE
PM 8-1 Crystalline Field Door

### ISSUE THREAD

**Issue by nxnslite** [HomepointXI/Issues#532]
**Date & Time**: 
21-06-10

**Client Version (use `/ver` in game):**
Locked

**Character Name:**
nxncure
nxnmage
altanaspouce
nxnpow
Khrisitna

**Discord Name (if different from in game):**
nxn_slite

**Nation:**
Windy

**Job(level)/Sub Job(level):**
nxncure          WHM
nxnmage        BLU
altanaspouce  BLU
nxnpow           BLU
Khrisitna          PLD

**NPC or Monster or item Name:**
Key Item: Light of Al'Taieu

**Zone name:** 
Al'Taieu

**Coordinates (use `!where`):**
x:-5 y: -10 z-464 (244)
H-11 Crystalline Field

**Item tool link (for items issues only):**
https://ffxiclopedia.fandom.com/wiki/Garden_of_Antiquity

**Multi-boxing? (multiple clients on same connection):**
yes. All of the above

**Steps to reproduce:**
Defeat Tenzen - get CS - Auto Teleport to Al'Taieu - Another CS on spawn

**Any additional information:**
Thank you for the support.... ET is one heck of a good taru.

**Comment by EpicTaru** [comment]
@nxnslite What issue are you having?  Please explain further.

**Comment by EpicTaru** [comment]
Are the ones that are missing the KI able to redo the fight on the airship against Tenzen?

**Comment by EpicTaru** [comment]
See if they can redo the Tenzen fight solo this time, please.  Respond here please if they are unable to.

**Comment by EpicTaru** [comment]
@nxnslite please let me know here on this ticket or in game via /tell when the affected charas are online so I can check variables

**Comment by nxnslite** [comment]
for others that might have the same probleme. I did 2 relog on the server. 1st one.. nothing changed and I was still stuck... logout and went to sleep... came back several hours later... lets say about 16 Hours. Reloged and then BOOM same CS restarted for all my characters. But I did get the Key Item: Light of Al'Taieu. I did follow the path of the quest and got the next CS at H-11.   Thank you.
