### ISSUE TITLE
Aura Statue not dropping Diorite

### ISSUE THREAD

**Issue by tuing** [HomepointXI/Issues#533]
Date & Time:
06/15/2021 @ 04:00 PM

Client Version (use /ver in game):
30191204_1

Character Name:
Meyrink

Discord Name (if different from in game):
Meyrink

Nation:
Sandoria

Job(level)/Sub Job(level):
99 THF/49 DNC

NPC or Monster or item Name:
Aura Statue

Zone name:
The Shrine of Ruavitau

Coordinates (use !where):
didnt check

Item tool link (for items issues only):
n/a

Multi-boxing? (multiple clients on same connection):
Yes

Steps to reproduce:
Aura Statue the mob that can drop pop item namely Diorite for popping Ullikumi, the NM for Autumnstone arent dropping loot properly where i had test killing it and also on item tool Diorite show no mob that can drop it. http://homepointxi.com/db/items/2388/chunk_of_diorite

**Comment by EpicTaru** [comment]
Resolved in last update.
