### ISSUE TITLE
Abyssea Atma Issues

### ISSUE THREAD

**Issue by neoffxi** [HomepointXI/Issues#538]
**Date & Time**: 
07/24/2021 3:01AM ET

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Neo

**Discord Name (if different from in game):**
NeoArmy

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
n/a

**NPC or Monster or item Name:**
All Atma Infufionist

**Zone name:** 
Abyssea zones

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
Atma Infusionist NPCs are unresponsive (e.g. they don't talk to you). 
!atma1, !atma2, and !atma3 commands don't work.

**Any additional information:**

**Comment by Heepster03** [comment]
Issue has been resolved. Verified that the atma commands are working and also the Infusionist is giving out atmas like candy.
