### ISSUE TITLE
Pcmd and Acmd Issues

### ISSUE THREAD

**Issue by neoffxi** [HomepointXI/Issues#539]
**Date & Time**: 
07/24/2021 3:08AM ET

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Neo

**Discord Name (if different from in game):**
NeoArmy

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
n/a

**NPC or Monster or item Name:**
n/a

**Zone name:** 
different zones

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
/pcmd add command does not work if the inviter and invitee are in different zones.
The same can be said for the /acmd add command.

**Any additional information:**

**Comment by EpicTaru** [comment]
Resolved.
