### ISSUE TITLE
Lividroot Amooshah dropping 2 tendrils

### ISSUE THREAD

**Issue by T3RT1UM** [HomepointXI/Issues#54]
**Date & Time**: 
5/11/2018    
3:41 am CST

**Client Version (use `/ver` in game):**
30180427_2

**Character Name:**
Kurare

**Discord Name (if different from in game):**
Kura

**Nation:**
Bastok

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**
Lividroot Amooshah

**Zone name:**
Bhaflau Thickets 

**Coordinates (use `!where`):**
X: 321 Y: -12 Z: 175

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**
traded item "Samariri Corpsehair" at ??? (H-9) to spawn NM Lividroot Amooshah

**Any additional information:**
![image](https://user-images.githubusercontent.com/22230953/39916173-63b095ca-54cf-11e8-9a6d-2a4129c3b58d.png)

**Comment by T3RT1UM** [comment]
made a mistake, item used is "Oily blood" not "samariri corpsehair"

**Comment by EpicTaru** [comment]
@T3RT1UM, per the Monster Tool, this mob is supposed to drop 2 Amooshah's Tendrils 100% of the time.  Please open a new ticket for a different issue not related to this.
