### ISSUE TITLE
Linkshell Issues

### ISSUE THREAD

**Issue by Shoruto** [HomepointXI/Issues#540]
**Date & Time**: 
7/24/2021 @ 8:23 AM EST

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Fatalbeast

**Discord Name (if different from in game):**
Sporky

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
51 DRK/25 SAM

**NPC or Monster or item Name:**
N/A

**Zone name:** 
Bastok Mines, Crawlers Nest and Lower Jeuno (only places I have tested it at)

**Coordinates (use `!where`):**
Mines - X:9 Y:-3 Z:-51 (169)

**Item tool link (for items issues only):**
N/A

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
**Bastok Mines** - Menu > Linkshell > Clicked FKLS Linkshell > Link List and gives message Search Failed with Downloading Data up top and doesn't change.

It does let me unequip and reequip in slot #1 but still same error message.

Same steps repeated for HomePointXI Linkshell in slot #2 and same Search Failed but doesn't give Downloading Data.

**Lower Jeuno** - Repeated first set of steps however the FKLS didn't even open, acted like I didn't do anything.  HomepointXI linkshell did open up with Search Failed.

**Crawlers Nest** - Same as Lower Jeuno

**Any additional information:**
Nothing more to add, feel free to ask me if above is confusing :)

**Comment by EpicTaru** [comment]
Linkshell communications (/l blah blah or /l2 blah blah) aren't affected, only the searching of linkshell.

**Comment by EpicTaru** [comment]
Resolved.
