### ISSUE TITLE
Unable to start VW CH6 (Aht Urhgan)

### ISSUE THREAD

**Issue by tb1** [HomepointXI/Issues#541]
**Date & Time**:  

2021-07-24 1705 GMT

**Client Version (use `/ver` in game):**

30191204_1

**Character Name:**

Tbone The Absolute Most Magnificent

**Discord Name (if different from in game):**

Cornholio The Master Connoisseur Of Tee Pee

**Nation:**

Canada

**Job(level)/Sub Job(level):**

Part Time Building Support Worker (lv1) / International Spy and Man Of Mystery (lv007)

**NPC or Monster or item Name:**

Camille The Ignorant Whore

**Zone name:** 

Wajaom Woodlands

**Coordinates (use `!where`):**

(M-7)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

No

**Steps to reproduce:**

Uncertain

**Any additional information:**

Short Version:  ITS BORKED!

Long Version:

After speaking with Owain (Tavnazian Safehold H-6) to complete VW Op.004: Bibiki Bombardment, I went to Wajaom Woodlands (M-7) to speak with Camille.  This should have started VW Op. 050: Aht Urhgan Assault, however speaking with Camille results in no response.

I've checked that I have completed all prior VW missions.

I have no tried to spawn a Aht Urhgan VWNM.

I do not have Amber Stratum Abyssite.

I suspect Camille is jealous of my hawt Mithra ass, and is angry that I slept with Owain in Tavnazian Safehold.  I tried to tell her that I am into girls too, but she just won't have it.  I am willing to go down on Camille if that is what it takes, but at this point I no longer have any romantic interest in Camille, and Owain has a micro-phallus and can't really hit the stop.

**Comment by EpicTaru** [comment]
Verified that status of VW quest **VW_OP_004_BIBIKI_BOMBARDMENT** did show a status of **COMPLETED** (**!checkquest 4 85**) and that the value of variable **VW_STATUS[Tavnazia]** did show as **0**.  Both of these adjustments would have occurred after interacting with Owain, as @tb1 indicated. Also verified that player didn't have the KI **AMBER_STRATUM_ABYSSITE** (**!haskeyitem 2062**).

**Comment by Heepster03** [comment]
she's hotfixed and is working as intended now.
