### ISSUE TITLE
Reforging AF3 Issue

### ISSUE THREAD

**Issue by neoffxi** [HomepointXI/Issues#542]
**Date & Time**: 
07/25/2021 3:01PM ET

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Neothree

**Discord Name (if different from in game):**
NeoArmy

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
99THF / 49DNC

**NPC or Monster or item Name:**
Prishe 

**Zone name:** 
Abyssea - Empyreal Paradox

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
1. Trade the items to Prishe
2. Prishe gives an error message, "Not so fast... All 10 Titles and All 3 Lunars are required".

Prishe will not upgrade AF3+2 to Reforged AF# 109.
Neothree meets all the requirements to reforge AF3.
I have upgraded multiple pieces already on Neothree.

**Any additional information:**

**Comment by EpicTaru** [comment]
Verified that player does have all 9 titles gained from defeating the 9 abyssea zone bosses:
![image](https://user-images.githubusercontent.com/26195580/126911460-c660c7d8-c37a-4827-9a33-5ad821d718df.png)
as well as all three Lunary Abyssites:
![image](https://user-images.githubusercontent.com/26195580/126911473-d1b6eb0a-be2c-40b3-b412-8e8540f33497.png)
as well as the title gained for defeating Shinryu:
![image](https://user-images.githubusercontent.com/26195580/126911562-8b8f06ea-3598-4a51-bbf1-da9d833e58c0.png)

**Comment by Heepster03** [comment]
This has been hotfixed and is currently working as of now. I had to write a new command in the lua but it is now working as intended. It is also back to telling you what lunars and bosses you are missing should that be why you can't obtain the armor. 

@neoffxi give it a try for me when you get back on and i'll close the ticket if it's working for you. It should be now :)

**Comment by neoffxi** [comment]
That fixed it. Thank you :D
