### ISSUE TITLE
Glory Slash: Weapon skill issue

### ISSUE THREAD

**Issue by neoffxi** [HomepointXI/Issues#543]
**Date & Time**: 
07/25/2021 6:51PM ET

**Client Version (use `/ver` in game):**
3019-1204_1

**Character Name:**
Neommule

**Discord Name (if different from in game):**
NeoArmy

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
99 PLD / 49 WAR

**NPC or Monster or item Name:**
n/a

**Zone name:** 
n/a

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
The weapon skill, Glory Slash, glitches and does no damage.
Prior to the update, the Campaign weapon skills Glory Slash and Uriel Blade, work on normal fights (outside of Campaign).

Uriel Blade still works with no issues. However, Glory Slash just readies / initializes, but the weapon skill just consumes TP and never goes off / does damage.

**Any additional information:**
Prior to

**Comment by neoffxi** [comment]
![Neommule_2021 07 25_185415](https://user-images.githubusercontent.com/34224364/126916005-1a855382-c855-486d-bf84-1ace162374ab.png)

**Comment by neoffxi** [comment]
![Neommule_2021 07 25_185104](https://user-images.githubusercontent.com/34224364/126916008-fa875fa9-07dd-4205-8443-1dadabf8c7b3.png)

**Comment by Heepster03** [comment]
fixed in upcoming update!

**Comment by EpicTaru** [comment]
This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.
