### ISSUE TITLE
~ Gully Clionids not respawning ~

### ISSUE THREAD

**Issue by simthra** [HomepointXI/Issues#548]
**Date & Time**: 
12/8/21 22.13 gmt+1

**Client Version (use `/ver` in game):** 30191204_1

**Character Name:** Thranduil

**Discord Name (if different from in game):** Thranduil

**Nation:**Bastok 10

**Job(level)/Sub Job(level):**MNK99/WAR49

**NPC or Monster or item Name:**Gully Clionid

**Zone name:** Abyssea-Tahrongi

**Coordinates (use `!where`):** -236, 16, -599

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**yes

**Steps to reproduce:**Gully clionids don't respawn; their respawn timer is set to 00:00 per mob tool

**Any additional information:**

**Comment by EpicTaru** [comment]
Heep/Immo, not sure why, but these should have a 60 second respawn (according to the LD code) but they aren't showing this on the Monster Tool, they also aren't showing the boosted level that they should have (LD code shows their level range should be 106-110:

<pre>REPLACE INTO `mob_groups` VALUES (1456,1845,45,60,0,1606,10000,20999,106,110,0); -- Gully Clionid</pre>

**Comment by Heepster03** [comment]
It's because some are set as mob_group 2 and some were set at 52, which doesn't exist. Same thing with the Gulch Limule. Fixed for update!

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/136261467-02d15dac-ae07-4cd3-b38c-53877a3ceb47.png)

This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.
