### ISSUE TITLE
Blurred Staff not working properly

### ISSUE THREAD

**Issue by Cheezdawgy** [HomepointXI/Issues#549]
**Date & Time**: 
8/13/2021 2:04AM MST

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Lexis

**Discord Name (if different from in game):**
Cheezdawg

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
BLM99/RDM49

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**

**Any additional information:**
Did some decent sized sample size comparisons of Blurred Staff vs. Keraunos vs. Ngqoqwanb in Dangruf Wadi with a whole bunch of different tier nukes (used same spell and same type of mob). Also did comparisons of no staff vs. having Blurred Staff equipped. I think the only thing that works on the Blurred Staff is the INT and MND stat. I first noticed the poor magic damage while looking back over my logs against various VNMs in different zones. I saw one of my mages (the only one without a Blurred Staff consistently doing WAY more damage despite the other mages having WAY better gear, stats, etc. (the other mages have Blurred Staffs). On one of the tests I did just a plain old Tier 1 nuke of Blurred Staff vs. Ngqoqwanb. There's no way a Ngqoqwanb does about triple damage than a Blurred Staff. Below are notes I made while performing these tests:

Pellegrino consistently outnukes all my other BLMs despite my other BLMs having a lot more INT and MAB, etc. I assume Blurred Staff isn't working properly.

Pellegrino vs. Fume Lizard with Blurred Staff.
Fire 385 dmg
Blizzard 414 dmg

Pellegrino vs. same Fume Lizard with Ngqoqwanb.
Fire 1173 dmg
Blizzard 1350 dmg
Fire 1173 dmg again

Lexis- Blurred Staff vs. Keraunos vs. Ngqoqwanb

Iceday Keraunos
Fire 1198 dmg
Blizzard 1380 dmg
Aero 1260 dmg
Stone 1154 dmg
Thunder 1269 dmg

Iceday Ngqoqwanb (diff lizard)
Fire 1532 dmg
Blizzard 1751 dmg
Aero 1587 dmg
Stone 1474 dmg

Iceday Blurred staff (diff lizard)
Fire 556 dmg
Blizzard 627 dmg
Aero 485 dmg
Stone 512 dmg
Thunder 605 dmg
Water 526 dmg
etc.

Lightningday Keraunos
Blizzard V 6529 dmg
Fire V 5899 dmg

Lightningday Ngqoqwob
Blizzard V 7944 dmg
Fire V     7694 dmg

Lightningday Blurred Staff
Blizzard V 5483 dmg
Fire V 5256 dmg

Lightningday Keraunos (enemy Natty Gibbon)
Fire V 6363 dmg

Lightningday Ngqoq
Fire V 7798 dmg

Decided on Misshoney to do a (no Blurred Staff and no Benthos Grip vs. Blurred Staff and Benthos Grip

No Staff and no grip (Fume Lizard)
Fire 394 dmg

With Blurred Staff and Benthos Grip
Fire 449 dmg

Tested Blurred Staff vs. Ice Staff on Misswebb. Blurred Staff barely did better than the Ice Staff on T1 nukes and T4 nukes lol.

Final analysis: Blurred staff isn't coded correctly or else there are hidden effects with Keraunos and Ngqoqwob. Ngqoqwob consistently beats out the other staffs. Keraunos comes in a fairly close 2nd.

**Comment by EpicTaru** [comment]
On quick glance, the Blurred Staff and the Keraunos look to have the correct modifiers but the Ngqoqwob looks to have WAY TOO much MAB. I'll look into this further later on my computer and confer with Heep/Immo about it. Thanks for bringing this to our attention, @Cheezdawgy.

**Comment by simthra** [comment]
![staves](https://user-images.githubusercontent.com/12772770/129452625-640a9438-a29a-4377-96c3-e194bc9f3e72.jpg)

I've looked into this issue while I was leveling my blm too. Also Venabulum seems too have too much MAB

**Comment by EpicTaru** [comment]
Venabulum has more custom MAB on purpose because of what it takes to obtain it here.

**Comment by Heepster03** [comment]
Issue has been resolved for future update.

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/136260759-0de206f1-ccab-407f-b6d7-fb990c861d02.png)

 Check the Item Modifications to determine which have.

This issue and several other end-game staves were "resolved" in yesterday's maintenance. Please open a new ticket should this issue re-occur.
