### ISSUE TITLE
Recover Pizza!

### ISSUE THREAD

**Issue by evenger** [HomepointXI/Issues#55]
Trying to recover my healer character and I can't remember the username, the character is named pizzataru, I know the password

**Date & Time**: 
6 AM 5/11

**Client Version (use `/ver` in game):**
most recent

**Character Name:**
Evenger

**Discord Name (if different from in game):**
Evenger

**Nation:**
sandy

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

**Comment by Heepster03** [comment]
>  Pizzataru (Last online: May 29, 2018 3:24:21 AM)

So I'm assuming this is self-resolved?

**Comment by evenger** [comment]
yes, thank you! =D

**Comment by Heepster03** [comment]
Self-Resolved!~
