### ISSUE TITLE
~ Karakul leather ~ Cannot be crafted

### ISSUE THREAD

**Issue by simthra** [HomepointXI/Issues#551]
**Date & Time**: 24/08/21

**Client Version (use `/ver` in game):**30191204_1

**Character Name:**Nanatuttatana

**Discord Name (if different from in game):**Thranduil

**Nation:**Windurst

**Job(level)/Sub Job(level):**WHM99/RDM49

**NPC or Monster or item Name:**

**Zone name:** anywhere

**Coordinates (use `!where`):**anywhere

**Item tool link (for items issues only):**http://homepointxi.com/db/items/879/square_of_karakul_leather

**Multi-boxing? (multiple clients on same connection):**no

**Steps to reproduce:**Synth isn't working. "Synthesis cancelled. The combination of materials cannot be synthesized".

**Any additional information:** Single yield, triple yield recipes aren't working. Craft levels ok, inventory space ok, also trield logging out.

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/130630260-b14049fc-2c77-460a-88cc-66a385502b69.png)

I was able to perform this craft successfully on the test server.  Please ensure that you met all the requirements.  A common cause of you receiving that message is the absence of the necessary KI.

**Comment by Heepster03** [comment]
I just verified on the LIVE server that either of the three methods listed on the DB can be performed perfectly fine.
![image](https://user-images.githubusercontent.com/8421725/130631211-9ac1e33e-fd39-4329-a39c-0c059b9288da.png)
Willing to bet that maybe an ingredient was forgotten to be placed in the box.

**Comment by Heepster03** [comment]
Thanks ET for the quick response!
