### ISSUE TITLE
pup earth maneuver doesn't cast stoneskin

### ISSUE THREAD

**Issue by blademaster-888** [HomepointXI/Issues#552]
**Date & Time**: 
12pm 29/8/21

**Client Version (use `/ver` in game):**
server lock version

**Character Name:**
blademaster

**Discord Name (if different from in game):**
blademaster

**Nation:**
bastok

**Job(level)/Sub Job(level):**
puppetmaster

**NPC or Monster or item Name:**
/pet wind maneuever

**Zone name:** 
any battle map

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**
Shock Absorber attachment

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
Shock Absorber attached to sharpshot head/frame, use eath maneuver, doesn't cast stoneskin as expected.

**Any additional information:**

**Comment by Heepster03** [comment]
moved to #558
