### ISSUE TITLE
Flesh Eater (Worm) in Eastern Altepa Desert /checked as a NM

### ISSUE THREAD

**Issue by ZurmaFFXI** [HomepointXI/Issues#554]
**Date & Time**: 
8/31/2021 @ 6:53 PM

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Zurma

**Discord Name (if different from in game):**

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
58 MNK/29 WAR

**NPC or Monster or item Name:**
Flesh Eater (Worm)

**Zone name:** 
Eastern Altepa Desert

**Coordinates (use `!where`):**
X:58 Y:-14 Z:223 (117)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**

Targeted a Flesh Eater
Hit Ctrl C to /check the worm
Checked Wiki and Homepoint Database and shows it as a normal worm mob with 28 spawn points and is not a NM.

**Any additional information:**
![Zurma Flesh Eater Wrong Wording](https://user-images.githubusercontent.com/89349557/131586109-6617ceaf-ea57-48c9-8282-f56b650ea2b3.png)

**Comment by EpicTaru** [comment]
Group ID is 13 and Pool ID is ~~1368~~1369, Halk.

Curse my fat fingers!

**Comment by Heepster03** [comment]
`INSERT INTO `mob_pools` VALUES (1369,'Flesh_Eater','Flesh_Eater',258,0x0000A80100000000000000000000000000000000,4,5,7,240,100,0,0,0,1,16,0,0,7,131,0,0,9,1,64,258);`

It's 1369, but yeah I found it :P

**Comment by Heepster03** [comment]
Issue resolved for next update. Updated the 16 NM flag to a 0 for Normal mob.

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/136259169-364e1d02-2629-4ace-8a4e-072d845366fb.png)

This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.
