### ISSUE TITLE
Account Recovery: Do not remember account Name or Password

### ISSUE THREAD

**Issue by Sennar1593** [HomepointXI/Issues#555]
**Date & Time**: I do not remember last time i was online, for sure 2018

**Client Version (use `/ver` in game):** 

**Character Name:** Rolevitt

**Discord Name (if different from in game):** Sennar #6517

**Nation:** Windurst

**Job(level)/Sub Job(level):** Do not remember

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):** 

**Multi-boxing? (multiple clients on same connection):** NO

**Steps to reproduce:**

**Any additional information:**
I stopped playing sometime in 2018, decided to give the server a shot once more. I do not remember a lot of stuff about it just the info i did write above. That's all.

**Comment by EpicTaru** [comment]
@Sennar1593 please fill in the complete details of your discord name, including the # and the numbers after it (for example, mine is Epictaru#2948)

**Comment by Heepster03** [comment]
Issue resolved
