### ISSUE TITLE
Unable to make the party go to the same BC for mission cop 6-4

### ISSUE THREAD

**Issue by liugan12** [HomepointXI/Issues#556]
Date & Time:
06/09/2021 @ 05:45 PM

Client Version (use /ver in game):
30191204_1

Character Name:
Nights
Nigo
Nioo
Nices

Discord Name (if different from in game):
Miss#3309

Nation:
Sandoria
Sandoria

Job(level)/Sub Job(level):
99 thf/49 nin
99 nin/ 37 dnc
99 RDM/49 blm
99 blm/49 whm

NPC or Monster or item Name:
Sealion's Den

Zone name:

Coordinates (use !where):

Item tool link (for items issues only):
n/a

Multi-boxing? (multiple clients on same connection):
Yes

Steps to reproduce:
After the BC battle, the team members are not on the same map.

After killing the monster, subsequent battles cannot be carried out.

**Comment by Heepster03** [comment]
This issue will be resolved in our next update which is right around the corner. Maybe I can see if I can do it tomorrow.

**Comment by liugan12** [comment]
> 这个问题将在我们即将到来的下一次更新中得到解决。也许明天我可以看看我能不能做到。

well. If you have time to enter the game and help me solve it, you can contact me in the game.
If you don't have time, I can carry out the cop task after maintenance.

**Comment by EpicTaru** [comment]
This issue was resolved in yesterday's maintenance.  Please open a new ticket should this issue re-occur.
