### ISSUE TITLE
Missing Item Mods: Orsn. Pantaln. +1 & +2

### ISSUE THREAD

**Issue by protocolz2025** [HomepointXI/Issues#563]
**Date & Time**: 
2021/10/10

**Client Version (use `/ver` in game):**

**Character Name:**
Fragile

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

Database shows the following properties.
(1): DEF: 39
(13): MND +5
Unknown Mod (860) 2
Unknown Mod (910) 10

DEF:39 
MND+5 
Healing magic casting time -8% 
Converts 2% of "Cure" amount to MP 
Divine Benison+1

Refer to https://www.bg-wiki.com/ffxi/Orsn._Pantaln._%2B1

The main reason I upgraded to +2 was for "Converts 2% of "Cure" amount to MP " which is completely missing here.

Any additional information:**

**Comment by Heepster03** [comment]
Modifier 860 is Converts % of "Cure" amount to MP. Therefore working as intended.

**Comment by protocolz2025** [comment]
OK. Can you update the database to show the mod 860 as intended rather than "Unknown Mod" ?

**Comment by Heepster03** [comment]
The mod works regardless of what it says. I just verified myself from the
modifier.h file. That’s why I said what I did. As far as it being updated,
that’s a site thing and am currently in progress on working for a solution.
