### ISSUE TITLE
Missing Item Mods: Spaekona's Coat

### ISSUE THREAD

**Issue by protocolz2025** [HomepointXI/Issues#564]
**Date & Time**: 
2021/10/10

**Client Version (use `/ver` in game):**

**Character Name:**
Fragile

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
Database shows the following properties.
(1): DEF: 126
(2): HP +54
(5): MP +59
(8): STR +21
(9): DEX +21
(10): VIT +21
(11): AGI +21
(12): INT +33
(13): MND +33
(14): CHR +29
(28): Magic Attack +10
(29): Magic Defense +6
(30): Magic Accuracy +10
(31): Magic Evasion +80
(68): Evasion +41
(114): Enfeebling Magic Skill +17
(369): Refresh 2
(384): Haste/Slow From Equipment +300

--------------------------------

DEF:89 HP+25 MP+49 STR+13 DEX+13 VIT+13 AGI+13 INT+18 MND+18 CHR+18 Magic Accuracy+10 Evasion+19 Magic Evasion+54 "Magic Def. Bonus"+3 Enfeebling magic skill +15 Enmity-6 Haste+2% Converts 2% of elemental magic damage dealt to MP

Refer to https://www.bg-wiki.com/ffxi/Spaekona%27s_Coat
(369) Refresh +2 is added as a custom feature here. Is it because  "Converts 2% of elemental magic damage dealt to MP" is hard to implement?

**Any additional information:**

**Comment by Heepster03** [comment]
It's just not implemented.

**Comment by Heepster03** [comment]
moved to the stickied #559
