### ISSUE TITLE
Prishe not upgrading Empyrean

### ISSUE THREAD

**Issue by Sethhp** [HomepointXI/Issues#566]
**Date & Time**: 
Oct 11, 2021

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Acisagic
Utena
Miz
Aries
Vicious
Enigma

**Discord Name (if different from in game):**
Seth

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**
Abbysea Zone Bosses
Shinryu

**Zone name:** 
Abyssea - Empyreal Paradox

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**

**Any additional information:**
Killed all 9 zone Abbysea Bosses, got all 3 lunar abyssite, killed Shinryu,
but home girl Prishe says this "Prishes: Not so fast... All 10 Titles and All 3 lunars are required!"
i checked the bard npc in port jeuno all the titles are there, Also i did a few Shinryu run and he's not dropping anything.
can you check these toons see what else is missing..

**Comment by EpicTaru** [comment]
Verified that all players listed had all necessary titles and lunar abyssites:

![image](https://user-images.githubusercontent.com/26195580/136844547-ff2a8f68-5632-4927-9f4c-b80867349c03.png)
![image](https://user-images.githubusercontent.com/26195580/136844575-e72db8ab-d6b2-4633-8596-fa75de6e7e6f.png)
![image](https://user-images.githubusercontent.com/26195580/136844655-63cda0ad-cb08-4aef-870e-cb4177202a91.png)
![image](https://user-images.githubusercontent.com/26195580/136844726-0819ebe3-bf70-4f77-8d8a-3c91f43eaefd.png)
![image](https://user-images.githubusercontent.com/26195580/136844853-94580dd1-aa0f-4a00-a22e-80ea4a4a398e.png)

**Comment by Heepster03** [comment]
i found the issue, i think it broke when I had to roll back the update stuff. But I will pull to the server tonight. It'll be resolved without a reboot.

**Comment by Sethhp** [comment]
ok, thanks ET and Heep

**Comment by EpicTaru** [comment]
This issue was resolved in the maintenance completed the night of 10/16. Please open a new ticket should this issue re-occur.
