### ISSUE TITLE
Missing Item Mods: Haruspex Coat

### ISSUE THREAD

**Issue by protocolz2025** [HomepointXI/Issues#567]
**Date & Time**: 
2021/10/12

**Client Version (use `/ver` in game):**

**Character Name:**

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
http://homepointxi.com/db/items/27893/haruspex_coat
(1): DEF: 107
(2): HP +40
(5): MP +54
(8): STR +15
(9): DEX +15
(10): VIT +15
(11): AGI +15
(12): INT +28
(13): MND +28
(14): CHR +28
(27): Enmity -5
(29): Magic Defense +5
(30): Magic Accuracy +10
(31): Magic Evasion +67
(68): Evasion +30
(384): Haste/Slow From Equipment +200

---------------------------------
See: https://www.bg-wiki.com/ffxi/Haruspex_Coat
DEF:107 HP+40 MP+54 STR+15 DEX+15 VIT+15 AGI+15 INT+28 MND+28 CHR+28 
"Magic Def. Bonus"+5 
Magic Accuracy+10 
Magic Evasion+67 
Evasion+30 
Haste+2% Enmity-5
Magic Damage+13 

Macig Damage+13 is missing.

**Any additional information:**

**Comment by Heepster03** [comment]
ET add it in your project if not already done :)

**Comment by EpicTaru** [comment]
Yep, already fixed in my project, lol

**Comment by Heepster03** [comment]
it'll be in today's update

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/137772405-73f9d364-6ab7-42a4-b1ce-1fc9ee62db33.png)

This issue was resolved in the maintenance completed the night of 10/16. Please open a new ticket should this issue re-occur.
