### ISSUE TITLE
Non Functioning Spells: Boost-INT

### ISSUE THREAD

**Issue by protocolz2025** [HomepointXI/Issues#568]
**Date & Time**: 
2021/10/12

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Fragile

**Discord Name (if different from in game):**

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
WHM99/RDM49

**NPC or Monster or item Name:**
n/a

**Zone name:** 
n/a

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**
1. Cast Boost-INT with/or without a party sync
2. The other party members do not gain extra INT.

**Any additional information:**

**Comment by Heepster03** [comment]
Okay, so the actual issue is that the caster will not get the effect when in a party. But the other party members do. Just tested this myself on HomepointXI. I'm looking into it now.

**Comment by Heepster03** [comment]
fixed issue, next pull it'll work

**Comment by EpicTaru** [comment]
I enlisted the use of my Checkdiscord account for this, he's a level 1 warrior with the displayed value for INT:

![image](https://user-images.githubusercontent.com/26195580/137766134-6a314691-bc27-40fc-b5fe-12d598db9bda.png)

After receiving the effects of the Boost-INT spell casted upon the party by my GM chara:

![image](https://user-images.githubusercontent.com/26195580/137766313-66b719b6-7f4e-4c60-8960-17e68a3bb876.png)

Closing this issue, please open a new ticket should this issue re-occur.
