### ISSUE TITLE
Spaekonas Petasos +1  Missing Magic Atk. Bonus

### ISSUE THREAD

**Issue by Sethhp** [HomepointXI/Issues#569]
**Date & Time**: 

**Client Version (use `/ver` in game):**

**Character Name:**

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
Missing MAB +13 

http://homepointxi.com/db/items/27687

**Comment by Heepster03** [comment]
Fixed in your project?

**Comment by EpicTaru** [comment]
Of course, lol.  If I haven't already gotten to it by the time a ticket is done, I jump to it and add it at that time.  It's not like I'd miss it when I'd eventually get to that part but might as well make sure it's reflected while it's in the focus!

**Comment by Heepster03** [comment]
👍

**Comment by Heepster03** [comment]
it'll be in tonight's update

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/137771813-303a53c7-a3ce-4230-a18e-4667bc677f51.png)

This issue was resolved in the maintenance completed the night of 10/16. Please open a new ticket should this issue re-occur.
