### ISSUE TITLE
atma of the sea daughter and atma of the voracious violet regain

### ISSUE THREAD

**Issue by Oderson** [HomepointXI/Issues#570]
**Date & Time**: 

10/13/21
**Client Version (use `/ver` in game):**

**Character Name:**
Nevion

**Discord Name (if different from in game):**

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
Thf99/dnc49

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
when using both atmas(sea daughter and VV) only the first applied gives regain

**Any additional information:**

**Comment by EpicTaru** [comment]
Confirmed this. Individually, both atmas give their correct amounts of TP gain per tic but when both are applied, only the atma that was first applied is used for TP gain incrementation. The value of the TP gain for the atma applied secondly is completely ignored.

**Comment by EpicTaru** [comment]
This issue appears to affect the stacking of any mod, experiencing it also with attempts to use both Stormbird and Minikin Monstrosity to try to get 15 refresh per tic

**Comment by Heepster03** [comment]
Okay I’m not home atm. But I’ll give it a shot later and see what I can
find out. Thanks for the info.

**Comment by Heepster03** [comment]
okay, jesus fucking christ. I spent quite a bit on this and i found the real issue. It'll be fixed in the next update!

**Comment by EpicTaru** [comment]
To verify this has been resolved, and for sake of simplicity, I went with Atmas that increase the Triple Attack rate:

No armor:
![image](https://user-images.githubusercontent.com/26195580/137762981-862216ea-142a-4af2-813b-7aefebebe108.png)

With only Atma of the Lion applied (+7% Triple Attack rate):
![image](https://user-images.githubusercontent.com/26195580/137763068-e2c78ec8-200e-4fc6-afb1-8aa60a751fec.png)

With only Atma of the Apocalypse applied (15% Triple Attack rate):
![image](https://user-images.githubusercontent.com/26195580/137763300-ef1eba93-6bda-41a1-91f3-33804274f3fc.png)

With both above atmas applied (7% + 15% = 22% Triple Attack rate):
![image](https://user-images.githubusercontent.com/26195580/137763738-744e3d69-afa6-4cf6-baa5-2ea5a503a224.png)

Of course, I also verified that the amount of TP Regain received correctly incremented by 70 TP per tic with both of the atmas in focus in this ticket applied (Atma of the Sea Daughter gives 50 regain per tic and Atma of the Voracious Violet gives 20 regain per tic).

Closing this issue, please open a new ticket should this issue re-occur.  @Oderson, I'll send you a bill for all of the 1 gil transactions that had to be done by both Halk and I to remove all atmas infused during all the testing done to resolve this issue...... :P
