### ISSUE TITLE
FoV page not working

### ISSUE THREAD

**Issue by protocolz2025** [HomepointXI/Issues#571]
**Date & Time**: 
2021/10/15

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
fragile

**Discord Name (if different from in game):**

**Nation:**
sandy

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
1. Choose P1 in The Sanctuary of Zi'Tah or P5 in Tahrongi
2. Open the FoV menu again to verify what's being selected
3. The menu displays as if nothing is selected
4. Kill some mobs and nothing is counted.

These two books used to work properly.
There might be other non-functioning books somewhere.

Priority: Extremely low.  No worry this is not a show stopper.

**Any additional information:**

**Comment by EpicTaru** [comment]
@Fragile2021 please complete all the fields on the ticket.

**Comment by Heepster03** [comment]
fixed the issue regardless, it'll be in the update later tonight.

**Comment by EpicTaru** [comment]
This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.
