### ISSUE TITLE
Wrong mod: Schellenband

### ISSUE THREAD

**Issue by protocolz2025** [HomepointXI/Issues#572]
**Date & Time**: 
2021/11/01

**Client Version (use `/ver` in game):**

**Character Name:**

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
Schellenband  (Item Id: 11885)
(1): DEF: 21
(10): VIT -6
(14): CHR +5
(455): (BRD) Song Spellcasting Time +5%

Refer to http://homepointxi.com/db/items/11885/schellenband

455 should be -5%

You can ignore this. I raised this issue purely for the sake of completeness.

**Any additional information:**

**Comment by EpicTaru** [comment]
That's how the code is set up for that mod, @Fragile2021, you'll notice it's the same way for any item that has that mod. It appears on the tool with a plus sign but code-wise, it's an integer value to reduce the casting time by.
