### ISSUE TITLE
La Theine Liege not dropping KI

### ISSUE THREAD

**Issue by Oderson** [HomepointXI/Issues#573]
**Date & Time**: 
11/4

**Client Version (use `/ver` in game):**

**Character Name:**

Nevion

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

La Theine Liege (MobID 17318440)

**Zone name:** 
Abyssea - La Theine (ZoneID 132)

**Coordinates (use `!where`):**
x: 80 y: 15 z: 199 

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**

repeatedly (12+) killed with a full party, and never received a KI

**Any additional information:**

Baba Yaga, in the same zone, for the same pop set, is dropping KI fine

**Comment by EpicTaru** [comment]
Updated ticket with MobID, ZoneID, and coordinates of mob.

I've also killed this mob multiple times today on my GM and have not yet obtained the KI either.

**Comment by EpicTaru** [comment]
I've killed this mob now fairly constantly for the past half hour and the KI has not dropped at all.

**Comment by Heepster03** [comment]
I'm not sure why, script is there to drop it based on a Random. That hasn't ever been altered.

**Comment by EpicTaru** [comment]
I'm not sure either, the code for the random chance for this KI has the same chance percentage as that of the KI that drops off Baba Yaga (aside from the name of the KI, ofc).

**Comment by protocolz2025** [comment]
Reconfirmed this issue is still present. 
Alternate suggestion: Trade 1G to ??? will give the KI. Or just clicking the ??? will give the KI.
I want to kill Hadhayosh before challenging Shinryu.

**Comment by Jessland86** [comment]
Hotfixed
