### ISSUE TITLE
Missing Item Mods: Mavi Bazubands +2

### ISSUE THREAD

**Issue by protocolz2025** [HomepointXI/Issues#575]
**Date & Time**: 
2021/11/13

**Client Version (use `/ver` in game):**

**Character Name:**
Fragile

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

Item Modifications
(1): DEF: 26
(13): MND +10
(27): Enmity -4
(28): Magic Atk. Bonus +10
http://homepointxi.com/db/items/11119/mavi_bazubands_+2

MISSING
Blue magic recast delay -12%
https://www.ffxiah.com/item/11119/mv-bazubands-2

**Any additional information:**

**Comment by EpicTaru** [comment]
No such mod exists at this point in time. No idea when it will added. Closing ticket but adding mod to list of known missing item mods. Thank you for your submission!
