### ISSUE TITLE
Missing Item Mods: Mavi Mintan +2

### ISSUE THREAD

**Issue by protocolz2025** [HomepointXI/Issues#576]
**Date & Time**: 
2021/11/13

**Client Version (use `/ver` in game):**

**Character Name:**
Fragile

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

Item Modifications
(1): DEF: 60
(25): Accuracy +12
(30): Magic Accuracy +12
(369): Refresh +2
(384): Haste/Slow From Equipment +300
http://homepointxi.com/db/items/11099/mavi_mintan_+2

MISSING
Blue magic spellcasting time -12% 
https://www.ffxiah.com/item/11099/mavi-mintan-2

**Any additional information:**

**Comment by EpicTaru** [comment]
No such mod exists at this point in time. No idea when it will added. Closing ticket but adding mod to list of known missing item mods. Thank you for your submission!

**Comment by protocolz2025** [comment]
Aoidos Calot +2 got "(455): (BRD) Song Spellcasting Time +12%"  
I think this is technically doable for BLU magic, right?

**Comment by EpicTaru** [comment]
Not at this point in time, may be a future project though. Not as easy as just copying one mod to use it for another, lol.

**Comment by protocolz2025** [comment]
OK Understood. Just for you info.  Aoidos Rhingrave +2 got "(833): (BRD) Song Recast Delay +6". Pls consider implementing Recast Delay for BLU for your future project.
