### ISSUE TITLE
steelshells

### ISSUE THREAD

**Issue by cigfa** [HomepointXI/Issues#578]
**Date & Time**: 11/17/21

**Client Version (use `/ver` in game):** v. locked on 3019

**Character Name:**morfran

**Discord Name (if different from in game):**cigfa

**Nation:**bastok

**Job(level)/Sub Job(level):**70/35

**NPC or Monster or item Name:**steelshell

**Zone name:**boyahda tree 

**Coordinates (use `!where`):**no clue

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**yes

**Steps to reproduce:**i killed a few

**Any additional information:**steelshells were linking and no giving credit for page 5

**Comment by EpicTaru** [comment]
May be related to https://github.com/HomepointXI/Issues/issues/562

**Comment by EpicTaru** [comment]
Resolved.  Please open a new ticket if you notice this issue occurring with any other mobs/any other pages.
