### ISSUE TITLE
Khimaira issues with Fulmination

### ISSUE THREAD

**Issue by spectre99** [HomepointXI/Issues#58]
**Date & Time**: 5/14/2018

**Client Version (use `/ver` in game):** 30171205_0

**Character Name:**Spectre

**Discord Name (if different from in game):**

**Nation:**Windurst

**Job(level)/Sub Job(level):**Pld99/whm49

**NPC or Monster or item Name:** Khimaira

**Zone name:** Caedarva Mire

**Coordinates (use `!where`):**  X: 842, Y: -1, Z: 365 

**Item tool link (for items issues only):** na

**Multi-boxing? (multiple clients on same connection):** na

**Steps to reproduce:**Fulmination only affects those within the party when it's supposed to be a true aoe that hits anyone within the.. 35yalm range?  Uzi was fighting it this morning and I was standing right next to Khim and no damage from Fulmination.

**Any additional information:**

**Comment by nfaletra** [comment]
Added True AoE Flag to Fulmination
