### ISSUE TITLE
Web page: double entry of "Crustacean Conundrum"

### ISSUE THREAD

**Issue by protocolz2025** [HomepointXI/Issues#583]
**Date & Time**: 

**Client Version (use `/ver` in game):**

**Character Name:**

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
http://wiki.homepointxi.com/BCNM/KSNM_Status
Crustacean Conundrum appears in Lv99 Working BC and Lv20 Non-Working BC

**Any additional information:**

**Comment by EpicTaru** [comment]
I'll verify this as well as the rest of the battlefields on that webpage tomorrow.

**Comment by EpicTaru** [comment]
Verified the list of working/non-working BCNMs/KSNMs, as it appears on that wiki page should now be correct.
