### ISSUE TITLE
Webpage: Nahn is missing 

### ISSUE THREAD

**Issue by protocolz2025** [HomepointXI/Issues#584]
**Date & Time**: 

**Client Version (use `/ver` in game):**

**Character Name:**

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
http://wiki.homepointxi.com/Category:Abyssea_-_La_Theine_Notorious_Monsters
Nahn is missing in the list.

**Any additional information:**

**Comment by EpicTaru** [comment]
I'll add him tomorrow, thanks for discovering this.

**Comment by EpicTaru** [comment]
Added: http://wiki.homepointxi.com/Nahn

Thanks again for notifying of this.
