### ISSUE TITLE
Cannot start Celaeno

### ISSUE THREAD

**Issue by protocolz2025** [HomepointXI/Issues#587]
**Date & Time**: 
2022/01/11

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Fragile

**Discord Name (if different from in game):**

**Nation:**
sandy

**Job(level)/Sub Job(level):**
WHM/RDM

**NPC or Monster or item Name:**
Celaeno

**Zone name:** 
Dangruf Wadi (J-12) (J-8)

**Coordinates (use `!where`):**
x:-155 y:3 z:-164 (96)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**
1. Click on Planar Ritt
2. Choose start void watch
3. "Indigo Stratum Abyssite IV is responding..."
4. Nothing happens

Clicking on Planar Ritt doesn't even bring up the menu.

**Any additional information:**

**Comment by EpicTaru** [comment]
@Fragile2021 it says that the abyssite IS or ISN'T responding?

**Comment by protocolz2025** [comment]
it says "the abyssite IS responding"

**Comment by EpicTaru** [comment]
And you are at the rift at H-4?

**Comment by protocolz2025** [comment]
I tried J-12 and J-8.

**Comment by EpicTaru** [comment]
Go to the rift at H-4, the VWNM will only spawn at the one specified on the voidwatch page.

http://wiki.homepointxi.com/Category:Voidwatch#Battle_Procedure

**Comment by protocolz2025** [comment]
Can you change the location to J-12? It's too far away.
