### ISSUE TITLE
Bastok Mission 9-2 CS crashing.

### ISSUE THREAD

**Issue by djsnowfang** [HomepointXI/Issues#588]
**Date & Time**: 
1/14/22

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
djsnowfang

**Discord Name (if different from in game):**

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
drg99/sam49

**NPC or Monster or item Name:**
Iron eater

**Zone name:** 
metalwork's

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
Rank 10 ending CS

**Any additional information:**
crashes on specific scene.

**Comment by EpicTaru** [comment]
@djsnowfang What addons/plugins are loaded?  Tried the CS without any addons/plugins loaded?

**Comment by djsnowfang** [comment]
windowerinput, addons, screenshot, distance, FPS, timestamp, tparty. Unloaded addons still crashed.

>

**Comment by EpicTaru** [comment]
Are you running at an FPS other than default (30FPS)?

**Comment by djsnowfang** [comment]
> 

no, FPS is 30

**Comment by EpicTaru** [comment]
Let me know when you are next in-game.

**Comment by EpicTaru** [comment]
Unsure why the Rank 9-2 completion CS is giving issues, CS played correctly for me less than an hour before player reported this issue.

Checked player's MissionStatus variable to verify completion of Rank 9-2 mission then performed the following:

Set value of MissionStatus variable to 0.
Gave player Bastokan Flag (Item ID 182).
Completed Bastok Mission 9-2.
Traded 200,000 gil to player (as I am unable to use the !givegil command).

I am unable to use the !setrank command to set player's rank to 10.  @Heepster03 or @Jessland86, that's for you to do.

Congrats on Rank 10, @djsnowfang!!!

**Comment by EpicTaru** [comment]
Requested that player attempt to complete this mission again since they reinstalled FFXI earlier to resolve a different issue they had.

I had to re-add Bastok Mission 9-2 to their current missions list.
I had to set the value of the MissionStatus variable to 2.

I then asked the player to interact with NPC Iron Eater again and see what happens.

**Comment by djsnowfang** [comment]
A full reinstall of FFXI has fixed the issue with the CS cuting out. I have got rank 10 now.
