### ISSUE TITLE
Seedspray doesn't work with Chain Affinity

### ISSUE THREAD

**Issue by fencedin** [HomepointXI/Issues#60]
**Date & Time**: 
05/17/2018

**Client Version (use `/ver` in game):**
30180329_1

**Character Name:**
Fence

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**
68 BLU/ 34 DNC

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
Use Chain Affinity, 
Then cast Seedspray
Chain Affinity will remain and no TP is taken

**Any additional information:**

**Comment by nfaletra** [comment]
Skillchain properties were not setup for this spell. Fixed in the next update.

**Comment by EpicTaru** [comment]
@fencedin Please attempt this again now that your client version and the server version match.

**Comment by fencedin** [comment]
Fast Blade -> Seedspray made Detonation, so working
