### ISSUE TITLE
Bastok mines door I-7 DC loop.

### ISSUE THREAD

**Issue by djsnowfang** [HomepointXI/Issues#606]
**Date & Time**: 
April 16th, 2022

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Djsnowfang

**Discord Name (if different from in game):**

**Nation:**
WIndurst

**Job(level)/Sub Job(level):**
PUP99/WAR49

**NPC or Monster or item Name:**
Bastok mines door I-7

**Zone name:** 
Bastok

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Walk up to door.

**Any additional information:**
I get into a DC loop if i attempt to go near the door at bastok mines I-7. GM has to repose my PC at that point. Fallen Comrades quest is active for the NPC inside of sead area.

**Comment by EpicTaru** [comment]
@djsnowfang does this issue still occur when you have no addons/plugins loaded?

**Comment by djsnowfang** [comment]
I have fixed the issue by doing a full reinstall of FFXI and than a reboot of the PC.
