### ISSUE TITLE
Treasure Pool Server Wide

### ISSUE THREAD

**Issue by Devolnu** [HomepointXI/Issues#61]
**Date & Time**:  5/18/2018  7pm

**Client Version (use `/ver` in game):** 30180427_2

**Character Name:** Devolnu

**Discord Name (if different from in game):**  Devolnu-Ace

**Nation:**  Bastok

**Job(level)/Sub Job(level):**  Pld99/Whm49

**NPC or Monster or item Name:** Any Mob/NM

**Zone name:** All

**Coordinates (use `!where`):**  N/A

**Item tool link (for items issues only):**  N/A

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:**
Treasure Pool is accessible server wide. We killed KB and items dropped to alts in party that were in bastok mines. 

**Any additional information:**  Tested it further went to other zones and my alt in bastok could lot on any items that were in pool.

**Comment by nfaletra** [comment]
Can people in the party outside the zone lot on it? This seems like a multi boxing issue.

**Comment by Devolnu** [comment]
yeah everyone can lot

**Comment by nfaletra** [comment]
Even people without a mule in the zone the mob was killed in?

**Comment by Devolnu** [comment]
people that are in bastok not even in the zone can lot

**Comment by Devolnu** [comment]
someone in Crawler's Nest just Lotted on a malboro vine that dropped in Dragon's Aery.

**Comment by nfaletra** [comment]
But are your mules in the same zone as them?

**Comment by Devolnu** [comment]
nope

**Comment by EpicTaru** [comment]
Did the vine drop to someone completely out of the zone?

**Comment by Devolnu** [comment]
Yes

**Comment by Devolnu** [comment]
Bozidar is able to do the same thing btw

**Comment by nfaletra** [comment]
Definitely a multi boxing issues. Disbanding the party and reforming fixed the weird treasure pool desync.

**Comment by nfaletra** [comment]
Don’t close it. It’s still an issue and I want it tracked.

**Comment by Heepster03** [comment]
Closing. If someone has an issue it can be addressed.
