### ISSUE TITLE
Taisai PHs not morphing into Taisaijin JM

### ISSUE THREAD

**Issue by EpicTaru** [HomepointXI/Issues#612]
**Date & Time**: 
08/15/22 @ 1426 CST thru 08/25/22 @ 0949 CST

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
EpicTaru

**Discord Name (if different from in game):**

**Nation:**
N/A

**Job(level)/Sub Job(level):**
N/A

**NPC or Monster or item Name:**
* Tasaijin NM (MobID 17457216)
* Taisai PHs (MobIDs 17457213, 17457214, 17457215)

**Zone name:** 
Ranguemont Pass

**Coordinates (use `!where`):**
* Map Co-Ords: (H-9) - (I-9)
  * NM: !pos -15 7 -131 166
    * PH1: !pos -18.325 1.83 -114.932 166
    * PH2: !pos -5.188 11.73 -141.503 166
    * PH3: !pos 59 15 -120 166

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
*  Wait patiently the amount of time listed on the retail wikis for one of the 3 PHs to morph into the NM.
*  As long as none of the PHs are disturbed, one of the 3 will eventually morph into the NM.

**Any additional information:**
*  Waited, from **08/15 at 1426** thru **08/25 at 0949**, in zone, at the middle PH of the 3, monitoring the presence of all 3, ensuring that none of the 3 PHs were disturbed, they all went merrily on their ways, oozing and slooping around their roam paths, casting Blaze Spikes on themselves ad nauseum. None of them eventually morphed (despawned with the NM immediately then spawning in its place) into the NM.

*  From **08/15 at 1426** thru **08/21 at 1853**, the waiting was done in 10-11hr periods (my normal online time). Outside of these periods, the zone (I assume) was empty and would sleep (zone counters would not increment).

*  From **08/21 at 1853** thru **08/25 at 0949** an additional character from a different player (character **Nxnpow** owned by player **Nxnslite**) was always constantly in zone, near the 1st PH. Due to a character always being in zone, the zone never slept and zone counters would increment like usual.

**Comment by Jessland86** [comment]
Tasaijin is custom here, just kill the placeholders one will eventually pop as Tasaijin like normal lottery NMs.
