### ISSUE TITLE
ToAU mission Black Coffin broken

### ISSUE THREAD

**Issue by Suikodenxi** [HomepointXI/Issues#619]
**Date & Time**: 
2/16/2023 3:00pm 

**Client Version (use `/ver` in game):**
30191204_1 

**Character Name:**
Redvulcan, Tarantula, Redscat, Nydaveth, and Madonna

**Discord Name (if different from in game):**
Redheadman

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
99War/49Sam, 99Drg/49Sam, 99Rdm/49Whm, 99Blu/49Dnc, and 99Blm/49Rdm

**NPC or Monster or item Name:**
PIL like NM's "Gesho" and 5 PIL like crewmate NM's 

**Zone name:** 
Arrapago Reef
Cutter

**Coordinates (use `!where`):**
cannot use !where i am not in battlefield

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):*toyes

**Steps to reproduce:**
enter battlefield aboard the cutter "Black Coffin"

**Any additional information:**

**Comment by Suikodenxi** [comment]
Mistake

**Comment by EpicTaru** [comment]
Duplicate of https://github.com/HomepointXI/Issues/issues/618
