### ISSUE TITLE
Journey Abroad Bug? Cutscene Not Initiating 

### ISSUE THREAD

**Issue by EternalLion** [HomepointXI/Issues#62]
**Date & Time**: 
5/22/18 6:04 PM EST

**Client Version (use `/ver` in game):**
version 30180427_2

**Character Name:**

Shadaki

**Discord Name (if different from in game):**

EternalLion
#5414

**Nation:**

San D'Oria

**Job(level)/Sub Job(level):**

WAR23

**NPC or Monster or item Name:**

Pius and Grohm

**Zone name:** 

Metalworks

**Coordinates (use `!where`):**

Pius = J-8, Grohm = G-9

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

No

**Steps to reproduce:**

Speak with Savae E Paleade @ Consulate of San d'Oria (I-9), she tells you to go to Pius. Pius, if I recall, is not giving all the text he is supposed to (I could be wrong) however he still says to go to Grohm. Grohm should be initiating a cutscene when spoken to, but no cutscene is generated. 

**Any additional information:**
This is Mission 2-3, Journey to Bastok specifically (falls under Journey Abroad mission)

**Comment by nfaletra** [comment]
Is this still causing trouble for you? A lot of IDs shifted in the last update. This could just be a version mismatch issue. Next update will have us synced up with retail and this should work again.

**Comment by EpicTaru** [comment]
@EternalLion please leí me know here or on discord when you are next online so I can check your variables with regards to this mission

**Comment by EternalLion** [comment]
Hello,

Just updated to version 30180427_4 and still no luck. Spoke to Grohm, then Pius followed by Grohm. I know he's supposed to give the player some pickaxes, but I think I may try to continue the mission by trying to mine the ore and seeing if I can just skip Grohm. I'm not sure if he's a necessity, but I do see him in the guides I've followed as a step

**Comment by nfaletra** [comment]
Unfortunately, you still have a version mismatch. However, that is not your fault. You are on the version that the server will be updating to soon. In the meantime, hit up a GM next time you're online and they can take a look at your mission status.

**Comment by Heepster03** [comment]
MissionStatus variable was jacked. Was supposed to be a 3 instead of a 0. I fixed it and they are able to continue now.
