### ISSUE TITLE
Attohwa coeurl

### ISSUE THREAD

**Issue by Suterxxx** [HomepointXI/Issues#620]
**Date & Time**: 
19.02.2023
14:40:15 ( GMT)

**Client Version (use `/ver` in game):**

30191204_1

**Character Name:**
Deadshot

**Discord Name (if different from in game):**

**Nation:**

Sandoria 

**Job(level)/Sub Job(level):**

Blu99/rdm49

**NPC or Monster or item Name:**

Attohwa coeurl

**Zone name:** 
Attohwa chasm

**Coordinates (use `!where`):**

X:210 y:20 z:0 (124)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

Yes

**Steps to reproduce:**
Attohwa/master coeurl readies Dragon kick when using charged whisker tp move.

**Any additional information:**
Could be unable to learn blue magic charged whisker from attohwa or master coeurl

**Comment by EpicTaru** [comment]
Currently, the only mob coded to correctly use Charged Whisker on this server is the VWNM mob Cath Palug (http://wiki.homepointxi.com/Cath_Palug). Even if other coeurls may use it, it may not be correct.
