### ISSUE TITLE
Cannot complete CoP 8.4

### ISSUE THREAD

**Issue by simthra** [HomepointXI/Issues#621]
**Date & Time**:  apr 11, 16.41 gmt

**Client Version (use `/ver` in game):** locked

**Character Name:** Rinoar

**Discord Name (if different from in game):** thranduil

**Nation:** Sandoria

**Job(level)/Sub Job(level):** brd 99/dnc 49

**NPC or Monster or item Name:** ??? warmachina

**Zone name:** bibiki bay, purgonorgo isle

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:** I'm trying to complete the cutscenes after the promathia fight. I can,t get the coloured drop after the 3 tarus'one, hence I cannot trigger neither the ru lude stairs one nor the marble bridge door one. 

**Any additional information:**

**Comment by EpicTaru** [comment]
Checked character's variables, all showed correct for being able to trigger the CS with the ??? Warmachine.  Verified that the character didn't already have any of the colored drops and also had at least 1 inventory slot free.

Had character re-examine the ??? Warmachine, CS was triggered, variable **COP_3-taru_story** correctly updated, character was then able to successfully complete the remaining CSes needed and obtained their COP ring of choice.

Not sure at all why the stated issue occurred for the player.
