### ISSUE TITLE
Sagheera won't restore relic armor -1

### ISSUE THREAD

**Issue by simthra** [HomepointXI/Issues#622]
**Date & Time**:  16.04.23, h 19.56 gmt+1

**Client Version (use `/ver` in game):** locked

**Character Name:** Rinoar

**Discord Name (if different from in game):** thranduil

**Nation:** sandoria

**Job(level)/Sub Job(level):** dnc 75/war 37

**NPC or Monster or item Name:** Sagheera

**Zone name:** Port Jeuno

**Coordinates (use `!where`):** -1 0 -8

**Item tool link (for items issues only):** https://www.ffxiah.com/item/16361/etoile-tights-1

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:** Sagheera isn't accepting the items needed to restore the etoile tights -1 to te +1 version

**Any additional information:**

**Comment by EpicTaru** [comment]
Player wasn't trading all required items. Closing ticket.
