### ISSUE TITLE
Unactive Craft

### ISSUE THREAD

**Issue by o0Persefone0o** [HomepointXI/Issues#63]
**Date & Time**: 23 May 2018

**Client Version (use `/ver` in game):** 30180306_2

**Character Name:** Persefone

**Discord Name (if different from in game):** Persefone

**Nation:** Bastok

**Job(level)/Sub Job(level):**  THF99/DNC49

**NPC or Monster or item Name:**   -----

**Zone name:**  ----

**Coordinates (use `!where`):**  -----

**Item tool link (for items issues only):**  http://www.homepointxi.com/db/items/1715/piece_of_vivified_coral

**Multi-boxing? (multiple clients on same connection):**  Yes

**Steps to reproduce:**

I'm trying to do this craft "Piece Of Vivified Coral" i already have the KI needed to do the craft but trying the synth game told me "Syntheis Canceled. That combination of materials cannot be synthetized" 

![image](https://user-images.githubusercontent.com/30010790/40446598-54f0e902-5e95-11e8-936c-cc610b535b27.png)

**Any additional information:**  Thank you

**Comment by nfaletra** [comment]
Are you sure you have the Bone Purification keyitem? A screenshot of it in your key item list would be helpful. Thanks!

**Comment by o0Persefone0o** [comment]
im so stupid, i didnt read its a bonecraft KI not Alchemy .... sorry
