### ISSUE TITLE
Multiple characters did not get closing CS for Dragoon quest in Ghelsba Outpost BCNM (The Holy Crest)

### ISSUE THREAD

**Issue by Azzariah** [HomepointXI/Issues#632]
**Date & Time**: 
9/29/24

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Bobfromqc, Bobfromprnting, Bobfromfinance, Bobfromtesting, Bobfromrevenue, Bobfromgaming

**Discord Name (if different from in game):**
Azzariah

**Nation:**
All San d'Orian

**Job(level)/Sub Job(level):**
99 COR/DNC, THF/DNC, WHM/SCH, BLM/RDM, WAR/SAM, WAR/SAM

**NPC or Monster or item Name:**
Cyranuce M Cutaeleon

**Zone name:** 
Ghelsba Outpost

**Coordinates (use `!where`):**
X:-153 Y:-10 Z72 (48)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes, went in with 2 groups of 6. 12 total. 6 received credit and 6 did not. Mixed groups.
![Bobfromqc](https://github.com/user-attachments/assets/b0e36b49-4996-4790-8d74-73e691e1961f)
![Bobfromrevenue](https://github.com/user-attachments/assets/b2c2bbf4-249b-4031-8762-5dde8219608e)

**Steps to reproduce:**

**Any additional information:**Screenshots of affected members uploaded with their party members in chat. One screenshot per group. Warped out of arena after ticket sent

**Comment by EpicTaru** [comment]
My GM "access" level isn't high enough to allow me to execute a function and unfortunately the only way to unlock the DRG job is via the quest in focus (The Holy Crest) is by the defeating of the NM in the BCNM portion of the quest.  

Characters listed as having the issue were all able to repeat the BCNM and unlock the job.  

Of note, all 12 characters were in the same progress point in the quest.  Even though the two parties were in an alliance, each party of the alliance was able to trigger their own instance of the BCNM and battle the NM in their own individual party instance.  Both parties defeated their respective NM at close to the same time.  Only 6 characters from the 2 parties received the completion CS and the job unlock (for applicable characters in the main party).  The 6 were random across both parties and the only consistency being that both of the leaders of the two parties received the CS and the job unlock but that consistency may not even be that and may just have been luck of the draw/"random consistency".
