### ISSUE TITLE
Achukka TP Moves

### ISSUE THREAD

**Issue by Uzi904** [HomepointXI/Issues#64]
**Date & Time**: 
1:00pm est 5/24/18

**Client Version (use `/ver` in game):**30180427_2

**Character Name:**Uzi

**Discord Name (if different from in game):**

**Nation:**Bastok

**Job(level)/Sub Job(level):**BLU99/RDM49

**NPC or Monster or item Name:**
Achukka

**Zone name:** Attowha Chasm

**Coordinates (use `!where`):**
N/A

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
N/A

**Steps to reproduce:**
While Fighting Achukka he RARELY uses TP moves. Trying to learn BLU spell Blistering Roar, he seems to use the same TP moves only, Searing Something, then one move that only shows animation but shows no move name in Chat Log. Literally Spammed tp for about 30min with Dia/etc. never used BR once. Something seems off, all other wonders use tp moves constantly and “normally”. Kinda discouraging to Try and learns spell one that isn’t a great chance of learning if used. Nvm if it’s never used by the one mob who uses it .

**Any additional information:**

**Comment by nfaletra** [comment]
Achuka's move set is fine. There is an animation bug which is causing him to not attack and TP moves don't show up in the log. Fix't for next update.

**Comment by nfaletra** [comment]
More accurately, the animation bug was preventing TP moves from being flagged as "used" so they would not be considered learnable. Fixing the animation bug will make Blistering Roar learnable again.

**Comment by Jessland86** [comment]
Confirmed fixed.
