### ISSUE TITLE
Missing Voidstones

### ISSUE THREAD

**Issue by fencedin** [HomepointXI/Issues#65]
**Date & Time**: 
5/25/18 17:40 PST

**Client Version (use `/ver` in game):**
30180329_1

**Character Name:**
Fence

**Discord Name (if different from in game):**
fencedin

**Nation:**
San d'Orian

**Job(level)/Sub Job(level):**
99DRK/SAM

**NPC or Monster or item Name:**

**Zone name:** 
South San d'Oria

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes, other char Nail

**Steps to reproduce:**

**Any additional information:**
When I was getting my Void Stones today, I noticed Fence got 0 and my alt Nail got 2.  Nail has had 1 more void stone than Fence since I started playing on HPXI and now Fence has 27 and Nail has 32. I could have swore the last time I went and got void stones it said 0 for Fence and 2 for Nail too, but I am not totally sure. 

It seems like one of my clients is getting both of my characters void stones. I am pretty sure Fence should have 29 and Nail should have 30 at this time. 

I always check them within a minute of each other as I run both of my chars over to the NPC to grab my void stones. This time I had Fence go 1st and got 0, then Nail clicked NPC and got 2.

Also, to be noted, I haven't spent any void stones since being back either.

**Comment by EpicTaru** [comment]
How long are you waiting between interactions with the voidwatch officer? I'm talking about on one character alone.

**Comment by fencedin** [comment]
I have been checking about every 1-2 days or so with both of them

**Comment by nfaletra** [comment]
This is definitely a multibox issue. Not much we can do about it at the moment. I recommend checking the NPC with your characters logged on separately.

**Comment by Heepster03** [comment]
I have been thinking about this. Since our VW is not like retail, where you don't need the voidstones to fight the NMs a long as someone else pops or an issue obtaining loot without stones. And being that this is a multibox issue, we will just leave things as they are.
