### ISSUE TITLE
Melancholic VW NM

### ISSUE THREAD

**Issue by Devolnu** [HomepointXI/Issues#66]
**Date & Time**: 5:14 PM 5/28/2018

**Client Version (use `/ver` in game):** 30180427_2

**Character Name:** Devolnu

**Discord Name (if different from in game):**  Devolnu-Ace

**Nation:** Bastok

**Job(level)/Sub Job(level):** Pld99/War49

**NPC or Monster or item Name:** Melancholic Moira

**Zone name:** Pashow Marshland (S) 

**Coordinates (use `!where`):** X:551 Y:24 Z:488 (195)

**Item tool link (for items issues only):**  N/A

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** Thousand Spears inflicting no damage just death

**Any additional information:**
https://cdn.discordapp.com/attachments/393444070866812943/450785201459560449/not_working.PNG

**Comment by nfaletra** [comment]
The message for the TP move is based on the gaze attack it does. However, you're not surviving the damage so that is the message you see.

**Comment by Devolnu** [comment]
wrong. it isnt working correctly i know this for a fact. its auto death on our server that isnt right. thousand spears is just like 1000 needles

**Comment by Devolnu** [comment]
it is not working as intended at all. that is not a death move nor should ever be now it should show damage like a normal move but not damage being shown and inflicting death is bullshit

**Comment by nfaletra** [comment]
First, do not assume that I did not look at it. It does NOT inflict death. It does damage and causes Amnesia.

Second, how much hp do you have and how many characters were within range when the TP move was used?
