### ISSUE TITLE
Devotion showing as Tachi: Rana

### ISSUE THREAD

**Issue by Devolnu** [HomepointXI/Issues#69]
**Date & Time**:  5/31/2018

**Client Version (use `/ver` in game):** 30180427_2

**Character Name:** Devolnu

**Discord Name (if different from in game):**Devolnu-Ace

**Nation:**Bastok

**Job(level)/Sub Job(level):**pld99/war49

**NPC or Monster or item Name:** Aello

**Zone name:** Ru'Aun Gardens

**Coordinates (use `!where`):** X:78 Y:-40 Z:-459 (127)

**Item tool link (for items issues only):**N/A

**Multi-boxing? (multiple clients on same connection):**Yes

**Steps to reproduce:** Ancillam uses Devotion on Elbavolnu but shows in log Tachi: Rana.

**Any additional information:**

**Comment by nfaletra** [comment]
Got a screenshot of the log?

**Comment by nfaletra** [comment]
Looks like the message is in the dB is wrong. Set to 224 which is mp recover from weaponskills. Should be 451 for job ability mp recover.

**Comment by Jessland86** [comment]
Confirmed fixed.
