### ISSUE TITLE
Dirtyhanded being censored

### ISSUE THREAD

**Issue by Devolnu** [HomepointXI/Issues#71]
**Date & Time**: 11:45pm 5/31/2018

**Client Version (use `/ver` in game):**30180427_2

**Character Name:**Devolnu

**Discord Name (if different from in game):**Devolnu-Ace

**Nation:**Bastok

**Job(level)/Sub Job(level):**Thf99/dnc49

**NPC or Monster or item Name:**Dirtyhanded Gochakzuk

**Zone name:** Davoi

**Coordinates (use `!where`):** X:54 Y:-10 Z:-149 (56)

**Item tool link (for items issues only):** N/A

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** NM readies in japanese.

https://cdn.discordapp.com/attachments/393444070866812943/451969008028090368/wtf.PNG

**Any additional information:**

**Comment by nfaletra** [comment]
This is a bug with the client. It happens in retail, too. Nothing we can do about it.
