### ISSUE TITLE
possibly logging problems in yhoator

### ISSUE THREAD

**Issue by ediww** [HomepointXI/Issues#72]
**Date & Time**:
6/01/2018
**Client Version (use `/ver` in game):**
30180329_1
**Character Name:**
Tate

**Discord Name (if different from in game):**

**Nation:**
Windurst/Tarutaru

**Job(level)/Sub Job(level):**
THF(99)/PLD(99)

**NPC or Monster or item Name:**
Logging point

**Zone name:** 
Yhoator Jungle

**Coordinates (use `!where`):**
https://vignette.wikia.nocookie.net/ffxi/images/4/48/YhoatorJungleLogging.png
the logging points

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
tried single and mutliboxing

**Steps to reproduce:**
go to the points 
https://vignette.wikia.nocookie.net/ffxi/images/4/48/YhoatorJungleLogging.png
and see if you find the right one

**Any additional information:**
It seems that the logging points are not showing up. 
I may be wrong but there is very little chance.
Even tried positioning several chars, also tried running all of the points.

**Comment by nfaletra** [comment]
Should be fixed in the next update. HELM IDs are hardcoded in lua right now and they weren't updated with the last NPC ID Shift.

**Comment by Jessland86** [comment]
Confirmed fixed.
