### ISSUE TITLE
Acamoth Multi-Boxing Crash

### ISSUE THREAD

**Issue by honeycubbinz** [HomepointXI/Issues#73]
**Date & Time**: 
6/2/2018
3:30 pm

**Client Version (use `/ver` in game):**
30180329_1

**Character Name:**
Brandoh

**Discord Name (if different from in game):**

**Nation:**
Sandoria

**Job(level)/Sub Job(level):**
Thf(99)/Dnc(99)

**NPC or Monster or item Name:**
Achamoth

**Zone name:** 
Halvuung

**Coordinates (use `!where`):**
X-15 Y10 Z338(247)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**
Popped Achamoth
About halfway through fight (3 attempts with 2 occurrences) all players crashed. 
 Assuming it's a multi-box issue. Gonna try a few things to see if I can reproduce it again. 

**Any additional information:**
Was able to log back in before de-pop after second crash, but not first.

**Comment by EpicTaru** [comment]
So what was the last few moves that the mob used prior to the crash?

**Comment by honeycubbinz** [comment]
Last few moves were I think Exenterator and Sudden Lunge. Never had issues with Exen so maybe Lunge was doing it.

**Comment by nfaletra** [comment]
The moves the mob used. Not your characters.

**Comment by honeycubbinz** [comment]
Oh ok, my mistake.
I'm pretty sure it was Exuviation.
Kattannah just got d/c'd again after another Exuviation though this time luckily it didn't effect the pop or fight too much.

**Comment by nfaletra** [comment]
Not really sure what's causing the crashes. Could be version mismatch. I cleaned up the mobskill scripts a bit and fought it a bunch. Hopefully we don't see this after we update.
