### ISSUE TITLE
Multi-Box Teleport Crash During Fight

### ISSUE THREAD

**Issue by honeycubbinz** [HomepointXI/Issues#74]
**Date & Time**: 
6/3/2018
4:50 pm

**Client Version (use `/ver` in game):**
30180329_1

**Character Name:**
Kattannah

**Discord Name (if different from in game):**
Brandoh

**Nation:**
Sandoria

**Job(level)/Sub Job(level):**
Blu(99)/Whm(49)

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**
Teleporting during fight. 

**Any additional information:**
I knew about the glitch, but didn't realize that it also crashed when in an alliance. My mistake.
Kat stuck.

**Comment by nfaletra** [comment]
I tried !logoff and it errored as “invalid player.” Needs to be force kicked on the server.

**Comment by honeycubbinz** [comment]
Haha no worries, you are still the man.

**Comment by Heepster03** [comment]
Sorry, been out most of the day. I'll work on this after dinner.

**Comment by Heepster03** [comment]
@honeycubbinz You're good to go. Booted her off for you.

**Comment by honeycubbinz** [comment]
Thanks heep!
