### ISSUE TITLE
Cannot enter limbus after DC

### ISSUE THREAD

**Issue by simthra** [HomepointXI/Issues#76]
**Date & Time**: 7/6/2018, 21.48 gmt

**Client Version (use `/ver` in game):**30180427_2

**Character Name:**Squaller

**Discord Name (if different from in game):**

**Nation:**bastok

**Job(level)/Sub Job(level):** thf99/dnc49

**NPC or Monster or item Name:** 

**Zone name:** any Limbus entrance

**Coordinates (use `!where`):** 601, 0, -599

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:** Got a dc while in limbus, logged back in and all monsters were wiped from the floors, and empty treasure chest spawned; so I've tele'd back to town and waited more than 24 hrs before reentering.
Got the 2 KI, but the instance won't let me in: "You have clearance to enter limbus, but cannot enter while you or a party member is engaged in a battle".
Thanks

**Any additional information:**

**Comment by EpicTaru** [comment]
@simthra is this issue still occurring?

**Comment by simthra** [comment]
Sadly yes, still no limbus admittance.

**Comment by Heepster03** [comment]
Check the variables associated with Limbus entrance. Probably was borked
from the DC.

**Comment by EpicTaru** [comment]
@simthra please let a gm know when your chara is online in game so that a check of your limbus variables can be performed

**Comment by nfaletra** [comment]
SW Apollyon is disabled at the moment because the mobs inside are not fully coded and crash the server.

You're going to the Swirling Vortex on the east side of Al'taieu to enter SE/NE Apollyon, correct?

**Comment by simthra** [comment]
Yessir, east vortex.
