### ISSUE TITLE
BST unlock quest - not getting final cut scene

### ISSUE THREAD

**Issue by spooneyweather** [HomepointXI/Issues#77]
**Date & Time**: 
June, 7 2018

**Client Version (use `/ver` in game):**
30180427_4

**Character Name:**
Astrit

**Discord Name (if different from in game):**

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
57 DRK/28 WAR

**NPC or Monster or item Name:**
Brutus

**Zone name:** 
Upper Jeuno

**Coordinates (use `!where`):**
G-7

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
http://ffxiclopedia.wikia.com/wiki/Save_My_Son

**Any additional information:**
Did the quest, received whistle, but not getting final cut scene or what ever from Brutus. Have tried zoning, logging out, and just plain waiting, but not unlocking Beastmater.

**Comment by EpicTaru** [comment]
@spooneyweather please try again since the version update of the server (please make sure that you also have updated your client version before trying again)

**Comment by nfaletra** [comment]
You have BST at level 60. Thanks for getting back to us. -_-
