### ISSUE TITLE
Rococo Table doesn't give 10 storage spaces

### ISSUE THREAD

**Issue by kyokofu** [HomepointXI/Issues#79]
**Date & Time**: 
3:39 6/9/2018

**Client Version (use `/ver` in game):**
30180427_2

**Character Name:**
Kyokofukada

**Discord Name (if different from in game):**
N/A

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
99THF/49BLM

**NPC or Monster or item Name:**
Rococo Table

**Zone name:** 
N. Sandy (Mog house)

**Coordinates (use `!where`):**
X:0 Y:0 Z:0 (192)

**Item tool link (for items issues only):**
https://www.ffxiah.com/item/427/rococo-table

**Multi-boxing? (multiple clients on same connection):**
Yes.

**Steps to reproduce:**
The Rococo Table is set in layout at different places but still does not provide 10 storage spaces.

**Any additional information:**

**Comment by Jessland86** [comment]
Item was recently added to the furnishing file on DSP, will be in next update.

**Comment by Jessland86** [comment]
Fixed in tonight's maintenance.
