### ISSUE TITLE
Dragoon Mining Excavation points missing?

### ISSUE THREAD

**Issue by Willthefluteboy** [HomepointXI/Issues#8]
**Date & Time**: 03/13/2018

**Client Version (use `/ver` in game):**  30180203_1

**Character Name:** Reon

**Nation:** Sandy

**Job(level)/Sub Job(level):** BLM 33/ WHM 16

**NPC or Monster or item Name:** Excavation Points

**Zone name:** Maze of Shakhrami

**Coordinates (use `!where`):** Entire zone

**Item tool link (for items issues only):**  n/a

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:**  Entering zone and looking around

**Any additional information:** Trying to do the Dragoon quest.

**Comment by Heepster03** [comment]
Need to verify any and all locations that can be located. Annotate what you see or don't see. Thanks.

**Comment by Willthefluteboy** [comment]
The locations on http://ffxiclopedia.wikia.com/wiki/File:MazeofShakhramiExcavation.png map are the locations for the spawn points of excavation in the maze. I can only check the first three on the top left. The points where they should spawn are blank with no markers or anything.

**Comment by Jessland86** [comment]
Excavation point is always at (K-9) on the top floor. You need to go underground and come back up to get it. You'll need sneak/invis.

**Comment by EpicTaru** [comment]
@Willthefluteboy please check where Immo above stated the Excavation Point would be at and update this ticket with your findings.

**Comment by Willthefluteboy** [comment]
Thank you Jessland86. The Excavation point was at that location and I was able to obtain the egg to continue the quest!!!!

**Comment by Heepster03** [comment]
Awesome, glad you were able to continue with the quest.
