### ISSUE TITLE
Vishap Brais +1 doesn't increase wyvern HP at all.

### ISSUE THREAD

**Issue by kyokofu** [HomepointXI/Issues#80]
**Date & Time**: 
4:31 6/9/2018

**Client Version (use `/ver` in game):**
30180427_2

**Character Name:**
Kyokofukada

**Discord Name (if different from in game):**
N/A

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
99DRG/49BLM

**NPC or Monster or item Name:**
Vishap Brais +1

**Zone name:** 
Tahrongi Canyon

**Coordinates (use `!where`):**
X:113 Y:40 Z:359 (233)

**Item tool link (for items issues only):**
https://www.ffxiah.com/item/28124/vishap-brais-1

**Multi-boxing? (multiple clients on same connection):**
Yes, but not when testing item.

**Steps to reproduce:**
Equipped and unequipped vishap brais and wyvern hp remain the same %. Equipped and unequipped drachen brais and drachen brais +1 and hp % resulted in 10-12% loss repectively. This means that the i119 version doesn't work.

**Any additional information:**

**Comment by Jessland86** [comment]
I'll take a look at getting these updated and added to DSP this afternoon or tomorrow.

**Comment by Jessland86** [comment]
Confirmed fixed.
