### ISSUE TITLE
Rainbow Cloth unsynthable with correct mats

### ISSUE THREAD

**Issue by kyokofu** [HomepointXI/Issues#82]
**Date & Time**: 
6:09pm 6/9/18

**Client Version (use `/ver` in game):**
30180427_2

**Character Name:**
Kyokofukada

**Discord Name (if different from in game):**
N/A

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
99THF/49BLM

**NPC or Monster or item Name:**
Rainbow Cloth

**Zone name:** 
Northern Sandy (Mog house)

**Coordinates (use `!where`):**
X:0 Y:0 Z:0

**Item tool link (for items issues only):**
https://www.ffxiah.com/item/830/rainbow-cloth

**Multi-boxing? (multiple clients on same connection):**
Yes, but not at time of craft

**Steps to reproduce:**
Used earth crystal and 3x rainbow thread, which is the correct synth according to homepointxi.com, and message says it is an incorrect synth combination.

**Any additional information:**

**Comment by nfaletra** [comment]
Synth is coded and seems to be working. If you're trying to craft on Kyokofukada, you need to actually level the craft first.
