### ISSUE TITLE
BLM getting quickmagic

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#86]
**Date & Time**: 
6/1/

**Client Version (use `/ver` in game):**

30180427_2

**Character Name:**

agnes

**Discord Name (if different from in game):**
6/11/18

**Nation:**

bastok

**Job(level)/Sub Job(level):**

blm99/rdm49

**NPC or Monster or item Name:**

**Zone name:** 
abyssea-konschtat

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**
blm occasionally popping off instant cast nukes without any  quick magic gear equipped. They didn't have this stuff back then but I don't see it on any wiki as being a native trait. Likely to be a nuisance waking up slept mobs in a manaburn XD. I do have lebeche ring and witful belt in inventories, maybe it's somehow drawing from that? Happening on all 5 of my blm.

**Any additional information:**

**Comment by nfaletra** [comment]
Do you have atma of apocalypse on?

**Comment by stevomatic** [comment]
Negative, currently use baying moon, clawed butterfly and MM.

**Comment by EpicTaru** [comment]
And none of your blms were wearing either of those two items, @stevomatic?

**Comment by stevomatic** [comment]
No, not wearing them, just scattered around different inventories

**Comment by EpicTaru** [comment]
And none of them have AshitaCast or Gearswap switching those items into use for pre-cast/mid-cast?

**Comment by stevomatic** [comment]
Nope

**Comment by EpicTaru** [comment]
And you can personally verify that none of them experienced any lag that would make it seem like they casted instantly?

**Comment by stevomatic** [comment]
Yes, and it happens rather frequently. Hit my nuke macro and 1 blm will instant cast, the rest will cast normally and using nuke macro again immediate the quickmagic user will start casting normally so I've gotten and extra cast in. If it was lag the quick magic user would be on cooldown and couldn't get into the original volley.

**Comment by EpicTaru** [comment]
OK, just eliminating things.

**Comment by EpicTaru** [comment]
were all of the blms subbing rdm?

**Comment by nfaletra** [comment]
Bug is in core. Everyone has a 1% chance for quick magic without gear. I know it might seem higher. Enjoy the bug while it lasts. :P

**Comment by stevomatic** [comment]
This makes farming significantly more difficult if you can't sleep mobs, hopefully this goes away lol.
![agnes](https://user-images.githubusercontent.com/26309049/41316314-03bd057c-6e60-11e8-95ad-ad830c03d053.jpg)
