### ISSUE TITLE
Talking to NPC crashes bootloader

### ISSUE THREAD

**Issue by xendral** [HomepointXI/Issues#87]
**Date & Time**: 
6/12/18 8:40 am pst

**Client Version (use `/ver` in game):**
30180427_4

**Character Name:**
bozidar

**Discord Name (if different from in game):**
bozidar

**Nation:**
bastok

**Job(level)/Sub Job(level):**
99nin/49dnc

**NPC or Monster or item Name:**
Chomo Jinjahl

**Zone name:** 
Windy waters

**Coordinates (use `!where`):**
-101,-1,69

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
Talk to NPC

**Any additional information:**

**Comment by nfaletra** [comment]
Update your client.

**Comment by Devolnu** [comment]
Happens with me also and I'm up to date.

**Comment by EpicTaru** [comment]
@xendral Try unloading all addons and plugins and try then.

**Comment by EpicTaru** [comment]
Also, please list which npcs are causing the crash

**Comment by EpicTaru** [comment]
Nvm previous comment

**Comment by nfaletra** [comment]
Found the issue. It's calling the wrong shop function and passing bad data. I have a fix but gitlab is down right now and we can't push it to the servers, yet. Avoid the npc for now. Sorry for the inconvenience. I'll check the other guild shop NPCs.

**Comment by nfaletra** [comment]
The rest should be safe. Let me know if you come across any others.

**Comment by EpicTaru** [comment]
But still please update your client, @xendral, lol

**Comment by nfaletra** [comment]
Yeah, definitely do that!
