### ISSUE TITLE
fafnir being funny

### ISSUE THREAD

**Issue by Devolnu** [HomepointXI/Issues#89]
**Date & Time**: today

**Client Version (use `/ver` in game):** up to date

**Character Name:** Devolnu

**Discord Name (if different from in game):** same

**Nation:** bastok

**Job(level)/Sub Job(level):** N/A

**NPC or Monster or item Name:** Fafnir

**Zone name:** DA

**Coordinates (use `!where`):** N/A

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** No

**Steps to reproduce:** Fafnir dropped a sea item

https://cdn.discordapp.com/attachments/442025335433723904/456183587365060609/unknown.png

**Any additional information:**

**Comment by nfaletra** [comment]
Fafnir has a fun mix of scripted and loot table drops. Needs to be cleaned up.
