### ISSUE TITLE
Cannot use summons in Elshimo Lowlands

### ISSUE THREAD

**Issue by Karixi** [HomepointXI/Issues#9]
**Date & Time**: 
15th March 2018 
21:00 GMT

**Client Version (use `/ver` in game):**
version 30180203_1
(version mismatch at time of issue)

**Character Name:**
Karixi

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
SMN 40 / WHM 20

**NPC or Monster or item Name:**
n/a

**Zone name:** 
Yuhtunga Jungle

**Coordinates (use `!where`):**
X:-239 Y:0 Z:520 (74)

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
Be in appropriate area and attempt to Summon (seemingly) any summon (can only confirm issue with Carbuncle / Titan / Garuda / Ramuh / Shiva).
Error message should appear informing the player that,
"You cannot use 'summon name' in this area."

**Any additional information:**
[http://prntscr.com/irsatx](url) Yuhtunga Jungle
[http://prntscr.com/irsbi6](url) Yhoator Jungle
[http://prntscr.com/irsf9h](url) Sea Serpent Grotto

**Comment by EpicTaru** [comment]
Checked zone_settings.sql (both on the LD testbed and on DSP) for Yuhtunga Jungle, Yhoator Jungle, and for Sea Serpent Grotto.  MISC flag is correctly including MISC_PETS value (128) in all three zones
Yuhtunga and Yhoator: 156 (128 "pets"+16 "Tractor"+8 "Mazurka"+4 "Chocobo")
Sea Serpent Grotto: 145 (128 "pets"+16 "Tractor"+1 "Escape")

I'll load up my private server later and test this on there to see if the issue still exists on the client version my server is running.

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/37498206-fe7bddb0-288a-11e8-8b85-4750a516841b.png)

![image](https://user-images.githubusercontent.com/26195580/37498269-6436398e-288b-11e8-9f95-25b1fba41898.png)

![image](https://user-images.githubusercontent.com/26195580/37498326-b0eb83ce-288b-11e8-8ea1-2e024aac46ce.png)

Client version: 30171223_0.  Was able to summon avatar in all three areas.

**Comment by Heepster03** [comment]
So I just tested this, I was able to summon in Yhoator Jungle and in Sea Serpent Grotto. 

Was not able to summon in Yuhtunga Jungle, I'm looking into that now.

**Comment by Heepster03** [comment]
![halkuras_2018 04 17_100448](https://user-images.githubusercontent.com/8421725/38878536-c8740228-4226-11e8-88fe-82fe4f30488a.png)

**Comment by Heepster03** [comment]
Summoning in Yuhtunga Jungle will be fixed next server restart.

**Comment by Heepster03** [comment]
![halkuras_2018 04 22_222541](https://user-images.githubusercontent.com/8421725/39105541-2944d164-467c-11e8-8766-4ebdd7bce442.png)
