### ISSUE TITLE
Brandin stuck

### ISSUE THREAD

**Issue by honeycubbinz** [HomepointXI/Issues#90]
**Date & Time**: 
6/16/2018

**Client Version (use `/ver` in game):**
30180329_1

**Character Name:**
Brandin

**Discord Name (if different from in game):**
Brandoh

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
pld99/war49

**NPC or Monster or item Name:**

**Zone name:** 
Dynamis Windurst

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Logged chars about 20 mins prior to entering dynamis

**Steps to reproduce:**

**Any additional information:**
stuck in limbo :P

**Comment by EpicTaru** [comment]
And @honeycubbinz, please please please update your client to current retail!

**Comment by honeycubbinz** [comment]
was able to log back in

**Comment by honeycubbinz** [comment]
also i will update my client epic, hopefully tonight if i remember ha! thx for the reminder
