### ISSUE TITLE
Nonny be stuck

### ISSUE THREAD

**Issue by Kearick** [HomepointXI/Issues#91]
**Date & Time**: 

6/16/18

**Client Version (use `/ver` in game):**

30180604_0

**Character Name:**
Nonash

**Discord Name (if different from in game):**
Nonash

**Nation:**
San D'Oria

**Job(level)/Sub Job(level):**

War99/Sam99

**NPC or Monster or item Name:**

**Zone name:** 

Dynamis Windurst

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

Nope

**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
Player's account is stuck, Was unable to log player off (system returns that the character name is invalid). Connection needs to be killed at the server.
