### ISSUE TITLE
Bismarck Adds

### ISSUE THREAD

**Issue by Uzi904** [HomepointXI/Issues#92]
**Date & Time**: 6/20/18

**Client Version (use `/ver` in game):**N/A

**Character Name:** Uzi

**Discord Name (if different from in game):**

**Nation:**Bastok

**Job(level)/Sub Job(level):**99Pld/49War

**NPC or Monster or item Name:**
Bismarck / Primordial Pugil

**Zone name:** Bibiki Bay

**Coordinates (use `!where`):** Rift F-10

**Item tool link (for items issues only):**N/A

**Multi-boxing? (multiple clients on same connection):**N/A

**Steps to reproduce:**
After Defeating Bismarck His 5-10 Pugil Adds Do not despawn and just sit at rift . Also their Recoil Dive is almost a 1 Shot Move. Making it almost impossible to “hold” while fighting Bismarck 

**Any additional information:**

**Comment by nfaletra** [comment]
I did a lot of testing. Some small nerfs were made to the adds but the difficulty is where we want it for now. Keep in mind that retail strategies for these NMs probably won't work here.
