### ISSUE TITLE
All Arasy Weapons except for scythe/scythe +1

### ISSUE THREAD

**Issue by Devolnu** [HomepointXI/Issues#93]
**Date & Time**: 6/21

**Client Version (use `/ver` in game):**30180604_0

**Character Name:** Devolnu

**Discord Name (if different from in game):**Devolnu-Ace

**Nation:**Bastok

**Job(level)/Sub Job(level):**Pld99/War49

**NPC or Monster or item Name:**N/A

**Zone name:** N/A

**Coordinates (use `!where`):**N/A

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** yes

**Steps to reproduce:**
Arasy weapons have no mods except the scythe / scythe +1

**Any additional information:**

**Comment by nfaletra** [comment]
Got 'em added.
