### ISSUE TITLE
~ Tuskertrap pop item ~

### ISSUE THREAD

**Issue by simthra** [HomepointXI/Issues#94]
**Date & Time**: 21/06/2018

**Client Version (use `/ver` in game):** 30180604_0

**Character Name:** Thranduil 

**Discord Name (if different from in game):**

**Nation:** bastok 10

**Job(level)/Sub Job(level):** drk99/war49

**NPC or Monster or item Name:** Boartrap

**Zone name:** Abyssea-Misareux

**Coordinates (use `!where`):** X: -71.963, Y: -23.925, Z: 677.783

**Item tool link (for items issues only):** https://www.ffxiah.com/item/3096/spotted-flyfrond

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:** Killed boartraps for an hour or so in party with TH10, but the pop item never dropped. The itemtool display "no drops". Is this intentional?
Thank you.

**Any additional information:**

**Comment by Jessland86** [comment]
Not intentional, it's a carryover issue from LD that hasn't gotten fixed so far, Thanks for the ticket.

**Comment by nfaletra** [comment]
Drop ID wasn't set for the mob group. Fixed in the next update.
