### ISSUE TITLE
received 0 voidstones upon checking voidwatch npc

### ISSUE THREAD

**Issue by lonleyhero** [HomepointXI/Issues#95]
![lonehero_2018 06 22_221932](https://user-images.githubusercontent.com/26263080/41804805-c564de86-766a-11e8-9cc3-2fbe4b495b52.png)

**Date & Time**: 
6/22/18 9:06pm EST

**Client Version (use `/ver` in game):**
30180604_0

**Character Name:**
lonehero

**Discord Name (if different from in game):**
lonelyhero

**Nation:**
bastok

**Job(level)/Sub Job(level):**
99thf/49blm

**NPC or Monster or item Name:**
Voidwatch Officer

**Zone name:** 
Basktock markets, Southern Sandoria

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
logged in my main character was already standing right next to the officer in bastok markets so i checked and got the message that i received 0 voidstones checking again he gives the message that they only give out stones once per day as if id actually gotten a stone i checked sandy as suggested by ET but got the same message as if id already gotten a stone

**Any additional information:**

**Comment by lonleyhero** [comment]
waited over 24 hours logged in only my main and once again i received 0 voidstones and still have 76 the same amount ive had for the past few days

**Comment by nfaletra** [comment]
I'm going to have Heep give you the voidstones you missed and reset your timer. When that's done, you will be asked to talk to a Voidwatch Officer again. You should receive 1 stone and your timer should be fixed. There is a small bug with the timer that will be fixed in the next update.

**Comment by nfaletra** [comment]
Pretty sure it's showing 0 stones when 1 is received. Or 1 less than what you should be getting. Your voidstone count is still going up. I got the same thing today. Thanks for the info!

**Comment by nfaletra** [comment]
Put in a fix. Will have to test again tomorrow to make sure it's resolved.

**Comment by nfaletra** [comment]
@lonleyhero Looks fixed for me. Fixed for you? Just quadruple checking before I close the bug.

**Comment by lonleyhero** [comment]
Haven’t been able to check been busy but I’ll log in after work and check tonight

**Comment by nfaletra** [comment]
We did it, fam!
