### ISSUE TITLE
Ironclad Pulverizer dropping Observer loot.

### ISSUE THREAD

**Issue by Heepster03** [HomepointXI/Issues#96]
**Date & Time**: 

**Client Version (use `/ver` in game):**

**Character Name:** [GM] Halkuras

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:** Ironclad Pulverizer

**Zone name:** Abyssea-Misareaux

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**

![i pulverizer](https://user-images.githubusercontent.com/8421725/41915753-18adc770-791c-11e8-932f-5c6603f9deeb.PNG)

**Comment by nfaletra** [comment]
Fixed the drop id.
